PROGRAM:
        "begin" DECLS (STATEMENT (";" STATEMENT)*)? "end"
DECLS:
        "declare" (ID-TYPE ("," ID-TYPE)*)? ";"
ID-TYPE:
        PICO-ID ":" TYPE
TYPE:
        "natural"
        "string"
        "nil-type"
STATEMENT:
        PICO-ID ":=" EXP
        "if" EXP "then" (STATEMENT (";" STATEMENT)*)? "else" (STATEMENT (";" STATEMENT)*)? "fi"
        "while" EXP "do" (STATEMENT (";" STATEMENT)*)? "od"
EXP:
        PICO-ID
        NatCon
        StrCon
        EXP "+" EXP
        EXP "-" EXP
        EXP "||" EXP
        "(" EXP ")"
