reference:
        STR
sample:
        sampleType
runnable:
        runnableType
tail:
        mixedType
document:
        titlePage::titlePage frontMatter::(topSection*) (lists::(frontList+))? (lexicalPart::(lexicalSection+))? (core::structuredSection+ | part::(core::structuredSection+)+) (backMatter::(topSection*))? annex::structuredSection*
titlePage:
        ((body::body number::INT) | author::STR+) topic::STR (version::STR | edition::STR) status::status date::STR
body:
        ansi::EPSILON
        ecma::EPSILON
        ieee::EPSILON
        iso::EPSILON
        iso/iet::EPSILON
        itu::EPSILON
        ietf::EPSILON
        iec::EPSILON
        oasis::EPSILON
        wsa::EPSILON
        w3c::EPSILON
status:
        unknown::EPSILON
        draft::EPSILON
        candidate::EPSILON
        proposed::EPSILON
        approved::EPSILON
        revised::EPSILON
        obsolete::EPSILON
        withdrawn::EPSILON
        collection::EPSILON
        trial::EPSILON
        errata::EPSILON
        report::EPSILON
generated:
        index::EPSILON
        fullgrammar::EPSILON
        listoftables::EPSILON
        listofauthors::EPSILON
        listofcontents::EPSILON
        listofreferences::EPSILON
topSection:
        foreword::simpleSection
        designGoals::simpleSection
        scope::simpleSection
        conformance::simpleSection
        compliance::simpleSection
        compatibility::simpleSection
        notation::simpleSection
        normativeReferences::simpleSection
        documentStructure::simpleSection
        whatsnew::simpleSection
        placeholder::generated
simpleSection:
        (title::STR)? author::STR* content::simpleText (id::STR)?
simpleText:
        simpleTextElement+
simpleTextElement:
        empty::EPSILON
        text::mixedType
        figure::simpleFigure
        table::simpleTable
        list::simpleList
        formula::((math::anyMath | mfenced::anyMath | mtext::anyMath | msub::anyMath | msup::anyMath | mrow::anyMath | mi::anyMath | mo::anyMath | varepsilon::ANY)+)
        sample::((ANY | STR)* src::STR)
        production
simpleFigure:
        caption::STR type::STR file::STR (id::STR)?
simpleTable:
        header::tableRow* row::tableRow+
simpleList:
        item::mixedType+
frontList:
        definitions::listOfTerms
        abbreviations::listOfTerms
        languageOverview::listOfTerms
lexicalSection:
        lineContinuations::simpleSection
        whitespace::simpleSection
        tokens::simpleSection
        preprocessor::simpleSection
        literals::simpleSection
        lexical::simpleSection
structuredSection:
        title::STR author::STR* structuredSectionElement+ (id::STR)?
listOfTerms:
        (title::STR)? author::STR* term::(name::STR definition::simpleText)+ (id::STR)?
tableRow:
        cell::simpleText+
structuredSectionElement:
        placeholder::generated
        normative
        informative
        production
        references::simpleList
        section::simpleSection
        subtopic::structuredSection
        value::(key::STR data::STR)
normative:
        synopsis::simpleSection
        description::simpleSection
        syntax::simpleSection
        constraints::simpleSection
        relationship::simpleSection
        semantics::simpleSection
        default::simpleSection
informative:
        rationale::simpleSection
        example::simpleSection
        update::simpleSection
runnableType:
        context::STR main::STR argument::STR* yields::STR language::STR (version::STR)? (id::STR)?
mixedType:
        (ANY | STR)*
formula:
        ANY+
keyword:
        STR
code:
        STR
link:
        (text::STR)? reference::STR
math:
        anyMath
mfenced:
        anyMath
mtext:
        anyMath
msub:
        anyMath
msup:
        anyMath
mrow:
        anyMath
mi:
        anyMath
mo:
        anyMath
varepsilon:
        EPSILON
anyMath:
        (ANY | STR)*
