CBGFCommand:
        abridge_detour::p::BGFProduction
        abstractize_concretize::p::BGFProduction
        addH_removeH::p::BGFProduction
        addV_removeV::p::BGFProduction
        anonymize_deanonymize::p::BGFProduction
        appear_disapper::p::BGFProduction
        chain_unchain::p::BGFProduction
        clone_equate::(x::STR y::STR w::XBGFScope)
        concatT_splitT::(y::STR xs::(STR*) w::XBGFScope)
        concretize_abstractize::p::BGFProduction
        deanonymize_anonymize::p::BGFProduction
        define_undefine::ps::(BGFProduction*)
        designate_unlabel::p::BGFProduction
        detour_abridge::p::BGFProduction
        deyaccify_yaccify::ps::(BGFProduction*)
        disappear_appear::p::BGFProduction
        downgrade_upgrade::(p1::BGFProduction p2::BGFProduction)
        eliminate_introduce::ps::(BGFProduction*)
        equate_clone::(x::STR y::STR w::XBGFScope)
        extract_inline::(p::BGFProduction w::XBGFScope)
        factor_factor::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        fold_unfold::(x::STR w::XBGFScope)
        horizontal_vertical::w::XBGFScope
        inject_project::p::BGFProduction
        inline_extract::(p::BGFProduction w::XBGFScope)
        introduce_eliminate::ps::(BGFProduction*)
        iterate_assoc::p::BGFProduction
        assoc_iterate::p::BGFProduction
        massage_massage::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        narrow_widen::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        permute_permute::(p1::BGFProduction p2::BGFProduction)
        project_inject::p::BGFProduction
        redefine_redefine::(ps1::(BGFProduction*) ps2::(BGFProduction*))
        removeH_addH::p::BGFProduction
        removeV_addV::p::BGFProduction
        renameL_renameL::(x::STR y::STR)
        renameN_renameN::(x::STR y::STR)
        renameS_renameS::(x::STR y::STR w::XBGFScope)
        renameT_renameT::(x::STR y::STR)
        replace_replace::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        reroot_reroot::(xs1::(STR*) xs2::(STR*))
        splitN_unite::(x::STR ps::(BGFProduction*) w::XBGFScope)
        splitT_concatT::(x::STR ys::(STR*) w::XBGFScope)
        unchain_chain::p::BGFProduction
        undefine_define::ps::(BGFProduction*)
        unfold_fold::(x::STR w::XBGFScope)
        unite_splitN::(x::STR ps::(BGFProduction*) w::XBGFScope)
        unlabel_designate::p::BGFProduction
        upgrade_downgrade::(p1::BGFProduction p2::BGFProduction)
        vertical_horizontal::w::XBGFScope
        widen_narrow::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        yaccify_deyaccify::ps::(BGFProduction*)
CBGFSequence:
        CBGFCommand*
