XBGFSequence:
        XBGFCommand*
XBGFCommand:
        abridge::p::BGFProduction
        abstractize::p::BGFProduction
        addH::p::BGFProduction
        addV::p::BGFProduction
        addC::p::BGFProduction
        anonymize::p::BGFProduction
        appear::p::BGFProduction
        bypass::EPSILON
        chain::p::BGFProduction
        clone::(x::STR y::STR w::XBGFScope)
        concatT::(xs::(STR*) y::STR w::XBGFScope)
        concretize::p::BGFProduction
        deanonymize::p::BGFProduction
        define::ps::(BGFProduction*)
        designate::p::BGFProduction
        detour::p::BGFProduction
        deyaccify::x::STR
        disappear::p::BGFProduction
        distribute::w::XBGFScope
        downgrade::(p1::BGFProduction p2::BGFProduction)
        eliminate::x::STR
        equate::(x::STR y::STR)
        extract::(p::BGFProduction w::XBGFScope)
        factor::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        fold::(x::STR w::XBGFScope)
        horizontal::w::XBGFScope
        importG::ps::(BGFProduction*)
        inject::p::BGFProduction
        inline::x::STR
        introduce::ps::(BGFProduction*)
        iterate::p::BGFProduction
        lassoc::p::BGFProduction
        massage::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        narrow::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        permute::p::BGFProduction
        project::p::BGFProduction
        rassoc::p::BGFProduction
        redefine::ps::(BGFProduction*)
        removeH::p::BGFProduction
        removeV::p::BGFProduction
        renameL::(x::STR y::STR)
        renameN::(x::STR y::STR)
        renameS::(x::STR y::STR w::XBGFScope)
        renameT::(x::STR y::STR)
        replace::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        reroot::xs::(STR*)
        splitN::(x::STR ps::(BGFProduction*) w::XBGFScope)
        splitT::(x::STR ys::(STR*) w::XBGFScope)
        unchain::p::BGFProduction
        undefine::xs::(STR*)
        unfold::(x::STR w::XBGFScope)
        unite::(x::STR y::STR)
        unlabel::x::STR
        upgrade::(p1::BGFProduction p2::BGFProduction)
        vertical::w::XBGFScope
        widen::(e1::BGFExpression e2::BGFExpression w::XBGFScope)
        yaccify::ps::(BGFProduction*)
        atomic::steps::(XBGFCommand*)
        strip::a::STR
XBGFScope:
        globally::EPSILON
        nowhere::EPSILON
        inlabel::l::STR
        notinlabel::l::STR
        innt::x::STR
        notinnt::x::STR
        comboscope::(w1::XBGFScope w2::XBGFScope)
