Thing:
        Event
Thing:
        Role
Thing:
        Person
Thing:
        Document
Thing:
        Detail
Thing:
        Review_expertise
Thing:
        Organizer
Thing:
        Review_preference
Thing:
        Conference
Thing:
        Event
        Role
        Person
        Document
        Detail
        Review_expertise
        Organizer
        Review_preference
Meta-Reviewer:
        assignedByAdministrator::Administrator adjustBid::Bid readPaper::Paper hasBeenAssigned::Paper writeReview::Review assignExternalReviewer::ExternalReviewer invites_co-reviewers::Reviewer invited_by::Reviewer has_a_review_reference_or_expertise::Thing+
Reviewer:
        Meta-Reviewer
Reviewer:
        assignedByAdministrator::Administrator adjustBid::Bid readPaper::Paper hasBeenAssigned::Paper writeReview::Review assignExternalReviewer::ExternalReviewer invites_co-reviewers::Reviewer invited_by::Reviewer has_a_review_reference_or_expertise::Thing+
Decision:
        Acceptance
Decision:
        Rejection
Decision:
        Acceptance
        Rejection
Preference:
        EPSILON
ProgramCommittee:
        hasProgramCommitteeMember::ProgramCommitteeMember
Bid:
        adjustedBy::Reviewer
Conference:
        Conference_volume
Conference:
        hasConferenceMember::ConferenceMember paperAssignmentFinalizedBy::Administrator reviewCriteriaEnteredBy::Administrator paperAssignmentToolsRunBy::Administrator virtualMeetingEnabledBy::Administrator hardcopyMailingManifestsPrintedBy::Administrator detailsEnteredBy::Administrator reviewerBiddingStartedBy::Administrator date::date reviewsPerPaper::Integer logoURL::anyURI acceptsHardcopySubmissions::Boolean siteURL::anyURI
ConferenceChair:
        memberOfConference::Conference
ConferenceMember:
        Reviewer
ConferenceMember:
        ConferenceChair
ConferenceMember:
        AssociatedChair
ConferenceMember:
        Author
ConferenceMember:
        ProgramCommitteeMember
ConferenceMember:
        Chairman
ConferenceMember:
        memberOfConference::Conference
AssociatedChair:
        memberOfConference::Conference
ProgramCommitteeMember:
        ProgramCommitteeChair
ProgramCommitteeMember:
        memberOfProgramCommittee::ProgramCommittee maxPapers::Integer addedBy::Administrator
AuthorNotReviewer:
        submitPaper::Paper writePaper::Paper
SubjectArea:
        EPSILON
ExternalReviewer:
        assignedByReviewer::Reviewer
Chairman:
        ConferenceChair
Chairman:
        AssociatedChair
Chairman:
        ProgramCommitteeChair
Chairman:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String hasConflictOfInterest::Document email::String memberOfConference::Conference
ProgramCommitteeChair:
        endReview::Review
Acceptance:
        EPSILON
Rejection:
        EPSILON
Paper:
        PaperAbstract
Paper:
        PaperFullVersion
Paper:
        Abstract
Paper:
        Invited_Paper
Paper:
        Short_Paper
Paper:
        Full_Paper
Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Author:
        AuthorNotReviewer
Author:
        Co-author
Author:
        Corresponding_Author
Author:
        submitPaper::Paper writePaper::Paper
Co-author:
        co-writePaper::Paper
PaperAbstract:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
PaperFullVersion:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Administrator:
        approve::Event assign::Role finalizePaperAssignment::Conference runPaperAssignmentTools::Conference enableVirtualMeeting::Conference startReviewerBidding::Conference assignReviewer::Reviewer rejectPaper::Paper enterConferenceDetails::Conference printHardcopyMailingManifests::Conference setMaxPapers::ProgramCommitteeMember enterReviewCriteria::Conference acceptPaper::Paper addProgramCommitteeMember::ProgramCommitteeMember
Meta-Review:
        writtenBy::Reviewer reviews::Reviewed_contribution
Event:
        Symposium
Event:
        Conference
Event:
        Workshop
Event:
        conists_of::Event_Tracks confirmed_by::Approval_Email defined_by::Event_Setup approved_by::Administrator
Account:
        registred_by::Person
Inforamtion:
        EPSILON
User:
        Committee
User:
        Administrator
User:
        Author
User:
        recieve::Document create::Thing+ submit::Document
Role:
        Admin_Role
Role:
        Author_Role
Role:
        Committe_Role
Role:
        Head_Role
Role:
        Reviewer_Role
Role:
        assigned_by::Administrator
Help_Request:
        Misc
Help_Request:
        Feature_Request
Help_Request:
        Assistance
Help_Request:
        Misc
        Feature_Request
        Assistance
Person:
        ConferenceMember
Person:
        ExternalReviewer
Person:
        User
Person:
        Conference_participant
Person:
        Conference_contributor
Person:
        Committee_member
Person:
        Conference_applicant
Person:
        Track-workshop_chair
Person:
        ProgramCommitteeMember
Person:
        Chairman
Person:
        Administrator
Person:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String hasConflictOfInterest::Document email::String
Symposium:
        conists_of::Event_Tracks confirmed_by::Approval_Email defined_by::Event_Setup approved_by::Administrator
Abstract:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Abstract:
        is_the_1th_part_of::Thing+
Document:
        Email
Document:
        Submission
Document:
        Template
Document:
        Paper
Document:
        Review
Document:
        recieved_by::User used_by::Person submited__by::User
Invited_Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Admin_Role:
        assigned_by::Administrator
Paper_Typologies:
        define::Event
Event_Setup:
        Paper_Typologies
Event_Setup:
        Review_Form
Event_Setup:
        Submission_Template
Event_Setup:
        Event_Tracks
Event_Setup:
        Research_Topic
Event_Setup:
        Email_Template
Event_Setup:
        define::Event
Event_URL:
        concerned::Event
URL:
        Event_URL
Notification_Email:
        EPSILON
Email:
        Notification_Email
Email:
        Group_Email
Email:
        Approval_Email
Email:
        Rejection_Email
Email:
        Notification_Email
        Group_Email
        Approval_Email
        Rejection_Email
Short_Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Author_Role:
        assigned_by::Administrator
Preview:
        EPSILON
Review_Form:
        Preview
Review_Form:
        Review_Form_Setup
Review_Form:
        Preview
        Review_Form_Setup
Committe_Role:
        assigned_by::Administrator
Group_Email:
        EPSILON
Submission_Template:
        define::Event
Review_Form_Setup:
        EPSILON
Misc:
        EPSILON
Event_Creation:
        has_result::Thing+ sent_by::Person
Approval_Email:
        confirm::Event
Rejection_Email:
        EPSILON
Submission:
        recieved_by::User used_by::Person submited__by::User
Template:
        recieved_by::User used_by::Person submited__by::User
Feature_Request:
        EPSILON
Event_Tracks:
        define::Event
Request:
        Help_Request
Activity:
        Event_Creation
Activity:
        Request
Activity:
        Event_Approval
Activity:
        Registration
Activity:
        has_result::Thing+ sent_by::Person
Head_Role:
        assigned_by::Administrator
Detail:
        EPSILON
Corresponding_Author:
        submitPaper::Paper writePaper::Paper
Reviewer_Role:
        assigned_by::Administrator
Event_Approval:
        has_result::Thing+ sent_by::Person
Registration:
        has_result::Thing+ sent_by::Person
Full_Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Research_Topic:
        define::Event
Description:
        EPSILON
Assistance:
        EPSILON
Email_Template:
        define::Event
Conference_participant:
        Passive_conference_participant
Conference_participant:
        Active_conference_participant
Active_conference_participant:
        gives_presentations::Presentation
Passive_conference_participant:
        EPSILON
Review_expertise:
        has_a_submitted_contribution::Submitted_contribution has_an_expertise::EEnum
Submitted_contribution:
        Reviewed_contribution
Submitted_contribution:
        has_a_review_expertise::Review_expertise
Regular_author:
        Contribution_1th-author
Regular_author:
        Contribution_co-author
Regular_author:
        Contribution_1th-author
        Contribution_co-author
Conference_contributor:
        Regular_author
Conference_contributor:
        Invited_speaker
Conference_contributor:
        Active_conference_participant
Conference_contributor:
        Regular_author
        Invited_speaker
Contribution_1th-author:
        EPSILON
Contribution_co-author:
        EPSILON
Conference_contribution:
        Poster
Conference_contribution:
        Written_contribution
Conference_contribution:
        Presentation
Conference_contribution:
        is_submitted_at::Conference_volume
Co-chair:
        was_a_committe_co-chair_of::Committee
Committee:
        Program_committee
Committee:
        Organizing_committee
Committee:
        Steering_committee
Committee:
        has_members::Committee_member was_a_committee_of::Conference_volume has_a_committee_co-chair::Co-chair has_a_committee_chair::Chair
Committee_member:
        Co-chair
Committee_member:
        Chair
Committee_member:
        was_a_member_of::Committee
Extended_abstract:
        Abstract
Important_dates:
        is_an_abstract_submission_date::date is_a_full_paper_submission_date::date is_an_ending_date::date is_a_date_of_acceptance_announcement::date is_a_date_of_camera_ready_paper_submission::date is_a_starting_date::date belong_to_a_conference_volume::Conference_volume
Invited_speaker:
        EPSILON
Conference_proceedings:
        has_an_ISBN::String has_a_publisher::Publisher has_a_volume::Integer
Information_for_participants:
        has_authors::Person has_a_date_of_issue::date
Conference_document:
        Conference_contribution
Conference_document:
        Information_for_participants
Conference_document:
        Call_for_paper
Conference_document:
        Conference_announcement
Conference_document:
        Call_for_participation
Conference_document:
        Conference_www
Conference_document:
        Review
Conference_document:
        has_authors::Person has_a_date_of_issue::date
Organization:
        EPSILON
Regular_contribution:
        Extended_abstract
Regular_contribution:
        Paper
Poster:
        is_submitted_at::Conference_volume
Written_contribution:
        Submitted_contribution
Written_contribution:
        Regular_contribution
Written_contribution:
        Submitted_contribution
        Regular_contribution
Conference_applicant:
        Registeered_applicant
Camera_ready_contribution:
        EPSILON
Accepted_contribution:
        Camera_ready_contribution
Program_committee:
        was_a_program_committee_of::Conference_volume
Organizing_committee:
        was_an_organizing_committee_of::Conference_volume
Steering_committee:
        was_a_steering_committee_of::Conference_volume
Conference_volume:
        has_parts::Conference_part has_workshops::Workshop has_tracks::Track has_tutorials::Tutorial has_a_commtitee::Committee has_a_steering_committee::Steering_committee has_an_organizing_committee::Organizing_committee has_important_dates::Important_dates has_contributions::Conference_contribution has_a_location::String has_a_program_committee::Program_committee
Call_for_paper:
        has_authors::Person has_a_date_of_issue::date
Conference_announcement:
        has_authors::Person has_a_date_of_issue::date
Invited_talk:
        is_given_by::Active_conference_participant
Conference_part:
        Track
Conference_part:
        Tutorial
Conference_part:
        Workshop
Conference_part:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair
Presentation:
        Invited_talk
Presentation:
        is_given_by::Active_conference_participant
Chair:
        was_a_committee_chair_of::Committee
Track:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair
Workshop:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair conists_of::Event_Tracks confirmed_by::Approval_Email defined_by::Event_Setup approved_by::Administrator
Tutorial:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair
Rejected_contribution:
        has_a_review::Review
Reviewed_contribution:
        Accepted_contribution
Reviewed_contribution:
        Rejected_contribution
Reviewed_contribution:
        has_a_review::Review
Review:
        Meta-Review
Review:
        writtenBy::Reviewer reviews::Reviewed_contribution
Topic:
        belongs_to_a_review_reference::Review_preference is_a_topis_of_conference_parts::Conference_part
Late_paid_applicant:
        EPSILON
Paid_applicant:
        Late_paid_applicant
Paid_applicant:
        Early_paid_applicant
Paid_applicant:
        Late_paid_applicant
        Early_paid_applicant
Early_paid_applicant:
        EPSILON
Organizer:
        EPSILON
Call_for_participation:
        has_authors::Person has_a_date_of_issue::date
Publisher:
        issues::Conference_proceedings
Registeered_applicant:
        Paid_applicant
Track-workshop_chair:
        was_a_track-workshop_chair_of::Conference_part
Conference_www:
        has_a_URL::String
Conference_fees:
        EPSILON
Review_preference:
        has_a_topic_or_a_submission_contribution::Thing+ has_a_degree::Integer
EEnum:
        high::EPSILON
        medium::EPSILON
        low::EPSILON
        very high::EPSILON
        male::EPSILON
        female::EPSILON
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
