RelationshipType:
        rt_related to::EPSILON
        rt_parent of::EPSILON
        rt_child of::EPSILON
        rt_duplicate of::EPSILON
        rt_has duplicate::EPSILON
MantisRoot:
        issues::Issue+
IdentifiedElt:
        ValueWithId
IdentifiedElt:
        Relationship
IdentifiedElt:
        Issue
PrivateElt:
        Issue
PrivateElt:
        Note
Issue:
        i_mantisRoot::MantisRoot project::ValueWithId category::String priority::ValueWithId severity::ValueWithId status::ValueWithId reporter::Person summary::String description::String version::String build::String platform::String os::String osVersion::String reproducibility::ValueWithId stepsToReproduce::String additionalInfo::String dateSubmitted::Integer assignedTo::Person projection::ValueWithId eta::ValueWithId resolution::ValueWithId fixedInVersion::String attachments::Attachment+ relationships::Relationship+ notes::Note+ lastUpdate::Integer
ValueWithId:
        Person
ValueWithId:
        value::String
Person:
        login::String
Relationship:
        type::RelationshipType
TimeStampedElt:
        Attachment
TimeStampedElt:
        Note
Note:
        author::Person text::String
Attachment:
        filename::String size::Integer contentType::String downloadUrl::String
Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
