NamedElement:
        Attribute
NamedElement:
        Project
NamedElement:
        Target
NamedElement:
        TaskElement
CommentableElement:
        TaskElement
Project:
        properties::Property+ targets::Target+ defaultTarget::Target
Property:
        name::String value::String location::String refid::String resource::String file::String url::String environment::String classpath::String classpathref::String prefix::String
Target:
        if::String unless::String tasks::Task+ depends::Target+
TaskElement:
        Task
TaskElement:
        TaskParameter
Attribute:
        value::String
Task:
        attributes::Attribute+ elements::TaskElement+
TaskParameter:
        attributes::Attribute+ elements::TaskElement+
String:
        STR
