JavaElement:
        ClassFeature
JavaElement:
        Package
ClassFeature:
        ClassMember
ClassFeature:
        JavaClass
ClassFeature:
        FeatureParameter
ClassMember:
        Field
ClassMember:
        Method
Field:
        owner::JavaClass type::JavaClass isStatic::Boolean isPublic::Boolean
JavaClass:
        PrimitiveType
JavaClass:
        members::ClassMember+ package::Package typedElements::ClassMember+ parameters::FeatureParameter+ isAbstract::Boolean isStatic::Boolean isPublic::Boolean
Method:
        parameters::FeatureParameter+
Package:
        classes::JavaClass+
PrimitiveType:
        members::ClassMember+ package::Package typedElements::ClassMember+ parameters::FeatureParameter+ isAbstract::Boolean isStatic::Boolean isPublic::Boolean
FeatureParameter:
        type::JavaClass method::Method
String:
        STR
Boolean:
        "true"
        "false"
