PrimitiveTypeDescriptor:
        boolean::EPSILON
        char::EPSILON
        byte::EPSILON
        short::EPSILON
        int::EPSILON
        float::EPSILON
        long::EPSILON
        double::EPSILON
TypeDescriptor:
        primitive::type::PrimitiveTypeDescriptor
        object::internalName::STR
        array::type::TypeDescriptor
MethodDescription:
        methodDescriptor::(arguments::(TypeDescriptor*) returnType::TypeDescriptor)
TypeSignature:
        primitive::type::PrimitiveTypeDescriptor
        fieldType::sig::FieldTypeSignature
FieldTypeSignature:
        classType::class::ClassTypeSignature
        array::type::TypeSignature
        typeVar::name::STR
ClassTypeSignature:
        topLevel::(internalName::STR args::(TypeArg*))
        inner::(class::ClassTypeSignature name::STR args::(TypeArg*))
TypeArg:
        type::fieldType::FieldTypeSignature
        wildcard::EPSILON
        extends::fieldType::FieldTypeSignature
        super::fieldType::FieldTypeSignature
Class:
        class::(version::INT modifiers::(ClassModifier*) name::STR signature::STR superName::STR interfaces::(STR*) sourceFile::STR sourceDebug::STR outerClass::STR outerMethod::STR outerMethodDescription::STR innerClasses::(InnerClass*) fields::(Field*) methods::(Method*))
        class::(version::INT modifiers::(ClassModifier*) name::STR signature::STR superName::STR interfaces::(STR*) innerClasses::(InnerClass*) fields::(Field*) methods::(Method*))
AccessModifier:
        public::EPSILON
        private::EPSILON
        protected::EPSILON
ClassModifier:
        access::access::AccessModifier
        final::EPSILON
        super::EPSILON
        interface::EPSILON
        abstract::EPSILON
        synthetic::EPSILON
        annotation::EPSILON
        enum::EPSILON
        deprecated::EPSILON
InnerClass:
        innerClass::(name::STR outerName::STR innerName::STR modifiers::(ClassModifier*))
        innerClass::(name::STR modifiers::(ClassModifier*))
Field:
        field::(modifiers::(FieldModifier*) name::STR description::STR signature::STR value::ANY)
        field::(modifiers::(FieldModifier*) name::STR description::STR signature::STR)
FieldModifier:
        access::access::AccessModifier
        static::EPSILON
        final::EPSILON
        volatile::EPSILON
        transient::EPSILON
        synthetic::EPSILON
        enum::EPSILON
Method:
        method::(modifiers::(MethodModifier*) name::STR description::STR signature::STR exceptions::(STR*) instructions::(Instruction*) tryCatchBlocks::(TryCatchBlock*) localVariables::(LocalVariable*))
MethodModifier:
        access::access::AccessModifier
        static::EPSILON
        final::EPSILON
        synchronized::EPSILON
        bridge::EPSILON
        varags::EPSILON
        native::EPSILON
        abstract::EPSILON
        strict::EPSILON
        synthetic::EPSILON
Instruction:
        getStatic::(owner::STR name::STR description::STR)
        putStatic::(owner::STR name::STR description::STR)
        getField::(owner::STR name::STR description::STR)
        putField::(owner::STR name::STR description::STR)
        increment::(index::INT amount::INT)
        nop::EPSILON
        aConstNull::EPSILON
        iConstM1::EPSILON
        iConst0::EPSILON
        iConst1::EPSILON
        iConst2::EPSILON
        iConst3::EPSILON
        iConst4::EPSILON
        iConst5::EPSILON
        lConst0::EPSILON
        lConst1::EPSILON
        fConst0::EPSILON
        fConst1::EPSILON
        fConst2::EPSILON
        dConst0::EPSILON
        dConst1::EPSILON
        iaLoad::EPSILON
        laLoad::EPSILON
        faLoad::EPSILON
        daLoad::EPSILON
        aaLoad::EPSILON
        baLoad::EPSILON
        caLoad::EPSILON
        saLoad::EPSILON
        iaStore::EPSILON
        laStore::EPSILON
        faStore::EPSILON
        daStore::EPSILON
        aaStore::EPSILON
        baStore::EPSILON
        caStore::EPSILON
        saStore::EPSILON
        pop::EPSILON
        pop2::EPSILON
        dup::EPSILON
        dupX1::EPSILON
        dupX2::EPSILON
        dup2::EPSILON
        dup2X1::EPSILON
        dup2X2::EPSILON
        swap::EPSILON
        iAdd::EPSILON
        lAdd::EPSILON
        fAdd::EPSILON
        dAdd::EPSILON
        iSub::EPSILON
        lSub::EPSILON
        fSub::EPSILON
        dSub::EPSILON
        iMul::EPSILON
        lMul::EPSILON
        fMul::EPSILON
        dMul::EPSILON
        iDiv::EPSILON
        lDiv::EPSILON
        fDiv::EPSILON
        dDiv::EPSILON
        iRem::EPSILON
        lRem::EPSILON
        fRem::EPSILON
        dRem::EPSILON
        iNeg::EPSILON
        lNeg::EPSILON
        fNeg::EPSILON
        dNeg::EPSILON
        iShl::EPSILON
        lShl::EPSILON
        iShr::EPSILON
        lShr::EPSILON
        iuShr::EPSILON
        luShr::EPSILON
        iAnd::EPSILON
        lAnd::EPSILON
        iOr::EPSILON
        lOr::EPSILON
        iXor::EPSILON
        lXor::EPSILON
        i2l::EPSILON
        i2f::EPSILON
        i2d::EPSILON
        l2i::EPSILON
        l2f::EPSILON
        l2d::EPSILON
        f2i::EPSILON
        f2l::EPSILON
        f2d::EPSILON
        d2i::EPSILON
        d2l::EPSILON
        d2f::EPSILON
        i2b::EPSILON
        i2c::EPSILON
        i2s::EPSILON
        lCmp::EPSILON
        fCmpL::EPSILON
        fCmpG::EPSILON
        dCmpL::EPSILON
        dCmpH::EPSILON
        iReturn::EPSILON
        lReturn::EPSILON
        fReturn::EPSILON
        dReturn::EPSILON
        aReturn::EPSILON
        return::EPSILON
        arrayLength::EPSILON
        aThrow::EPSILON
        monitorEnter::EPSILON
        monitorExit::EPSILON
        biPush::operand::INT
        siPush::operand::INT
        newArray::operand::INT
        ifEq::label::INT
        ifNe::label::INT
        ifLt::label::INT
        ifGe::label::INT
        ifGt::label::INT
        ifLe::label::INT
        ifICmpEq::label::INT
        ifICmpNe::label::INT
        ifICmpLt::label::INT
        ifICmpGe::label::INT
        ifICmpGt::label::INT
        ifICmpLe::label::INT
        ifACmpEq::label::INT
        ifACmpNe::label::INT
        goto::label::INT
        jsr::label::INT
        ifNull::label::INT
        ifNonNull::label::INT
        label::index::INT
        lineNumber::(line::INT labelIndex::INT)
        localVariable::(opcode::INT index::INT)
        iLoad::index::INT
        lLoad::index::INT
        fLoad::index::INT
        dLoad::index::INT
        aLoad::index::INT
        iStore::index::INT
        lStore::index::INT
        fStore::index::INT
        dStore::index::INT
        aStore::index::INT
        ret::index::INT
        ldcString::string::STR
        ldcInt::int::INT
        ldcLong::long::INT
        ldcFloat::float::INT
        ldcDouble::double::INT
        lookupSwitch::(defaultLabel::INT keys::(INT*) cases::(INT*))
        invokeVirtual::(owner::STR name::STR description::STR)
        invokeSpecial::(owner::STR name::STR description::STR)
        invokeStatic::(owner::STR name::STR description::STR)
        invokeInterface::(owner::STR name::STR description::STR)
        invokeDynamic::(owner::STR name::STR description::STR)
        multiANewArray::(description::STR dimensions::INT)
        tableSwitch::(min::INT max::INT defaultLabel::INT cases::(INT*))
        new::internalName::STR
        aNewArray::internalName::STR
        checkCast::internalName::STR
        instanceOf::internalName::STR
TryCatchBlock:
        tryCatchBlock::(startLabelIndex::INT endLabelIndex::INT handlerLabelIndex::INT type::STR)
        finallyBlock::(startLabelIndex::INT endLabelIndex::INT handlerLabelIndex::INT)
LocalVariable:
        localVariable::(name::STR description::STR signature::STR startLabelIndex::INT endLabelIndex::INT index::INT)
