Page:
        xmlns::NameSpace+ title::String graphContainer::GraphicalContainer pageResources::PageResource
NameSpace:
        namespace::String identifier::String
PageResource:
        dictionaries::ResourceDictionary+
GraphicalContainer:
        Grid
WinFXElement:
        Name
PerspectiveElement:
        Workshop3D
PerspectiveElement:
        XyzAxis3D
PerspectiveElement:
        Box3D
PerspectiveElement:
        Square3D
ResourceDictionary:
        source::String
Grid:
        object3D::Object3D+
Object3D:
        Workshop3D
Workshop3D:
        elements3D::Element3D+
Element3D:
        UI3Delement
Element3D:
        XyzAxis3D
Element3D:
        UI3Delement
UI3Delement:
        Box3D
UI3Delement:
        Square3D
UI3Delement:
        transform::String material::String name::Name
XyzAxis3D:
        length::Double
Box3D:
        transform::String material::String name::Name namespace::NameSpace
Square3D:
        transform::String material::String name::Name namespace::NameSpace
Name:
        name::String
String:
        STR
Boolean:
        "true"
        "false"
Integer:
        INT
