BuiltInSort:
        CyclicEnumeration
BuiltInOperator:
        CyclicEnumOperator
CyclicEnumeration:
        cyclicenumeration::FiniteEnumeration.content
CyclicEnumOperator.content:
        BuiltInOperator.content
CyclicEnumOperator:
        Successor
        Predecessor
Successor:
        successor::CyclicEnumOperator.content
Predecessor:
        predecessor::CyclicEnumOperator.content
