CollectionTypes:
        individual::EPSILON
        set::EPSILON
        orderedSet::EPSILON
        bag::EPSILON
        sequence::EPSILON
PredicateCategory:
        closed::EPSILON
        open::EPSILON
        partial::EPSILON
ExternalVocabularyLanguage:
        RDFS::EPSILON
        UML::EPSILON
        OWL::EPSILON
PredicateType:
        ObjectClassificationPredicate::EPSILON
        AttributionPredicate::EPSILON
        AssociationPredicate::EPSILON
        ReferencePropertyPredicate::EPSILON
        EqualityPredicate::EPSILON
        InequalityPredicate::EPSILON
        DatatypePredicate::EPSILON
        DataClassificationPredicate::EPSILON
ReactionRuleSet:
        rules::Rules/ReactionRule+
ProductionRuleSet:
        rules::Rules/ProductionRule+
EventType:
        eventTypeID::String
RuleSet:
        ReactionRuleSet
RuleSet:
        ProductionRuleSet
RuleSet:
        IntegrityRuleSet
RuleSet:
        DerivationRuleSet
RuleBase:
        vocabularies::Vocabulary/VocBasic/Vocabulary externalVocabulaires::Vocabulary/VocBuiltin/ExternalVocabulary+ rules::RuleSet+ ruleBaseID::String
IntegrityRuleSet:
        rules::Rules/IntegrityRule+
DerivationRuleSet:
        rules::Rules/DerivationRule+
Integer:
        INT
Boolean:
        "true"
        "false"
String:
        STR
