BuiltInSort:
        Number
BuiltInOperator:
        IntegerOperator
BuiltInConstant:
        NumberConstant
Number:
        Natural
        Positive
        Integer
Integer:
        integer::EPSILON
Natural:
        natural::EPSILON
Positive:
        positive::EPSILON
IntegerOperator.content:
        BuiltInOperator.content
IntegerOperator:
        Addition
        Subtraction
        Multiplication
        Division
        Modulo
        GreaterThan
        GreaterThanOrEqual
        LessThan
        LessThanOrEqual
NumberConstant:
        numberconstant::(value::INT (BuiltInConstant.content Number))
LessThan:
        lt::IntegerOperator
LessThanOrEqual:
        leq::IntegerOperator
GreaterThan:
        gt::IntegerOperator
GreaterThanOrEqual:
        geq::IntegerOperator
Addition:
        addition::IntegerOperator
Subtraction:
        subtraction::IntegerOperator
Multiplication:
        mult::IntegerOperator
Division:
        div::IntegerOperator
Modulo:
        mod::IntegerOperator
