Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
Activity:
        SubProcess
Activity:
        orderedMessages::MessagingEdge+ incomingMessages::MessagingEdge+ outgoingMessages::MessagingEdge+ groups::Group+ activityType::ActivityType eventHandlerFor::SubProcess lane::Lane looping::Boolean
ActivityType:
        SubProcess::EPSILON
        EventEndMultiple::EPSILON
        EventEndMessage::EPSILON
        EventIntermediateMessage::EPSILON
        EventStartMultiple::EPSILON
        EventIntermediateMultiple::EPSILON
        GatewayParallel::EPSILON
        EventStartTimer::EPSILON
        EventStartEmpty::EPSILON
        EventIntermediateCancel::EPSILON
        EventEndError::EPSILON
        EventStartRule::EPSILON
        EventEndTerminate::EPSILON
        EventStartLink::EPSILON
        EventIntermediateLink::EPSILON
        EventEndCancel::EPSILON
        EventEndLink::EPSILON
        EventIntermediateEmpty::EPSILON
        EventIntermediateCompensation::EPSILON
        Task::EPSILON
        GatewayDataBasedExclusive::EPSILON
        GatewayComplex::EPSILON
        EventEndEmpty::EPSILON
        EventIntermediateError::EPSILON
        EventIntermediateTimer::EPSILON
        EventEndCompensation::EPSILON
        EventStartMessage::EPSILON
        GatewayDataBasedInclusive::EPSILON
        GatewayEventBasedExclusive::EPSILON
        EventIntermediateRule::EPSILON
Artifact:
        DataObject
Artifact:
        Group
Artifact:
        TextAnnotation
Artifact:
        associations::Association+ artifactsContainer::ArtifactsContainer
ArtifactsContainer:
        BpmnDiagram
ArtifactsContainer:
        Graph
ArtifactsContainer:
        artifacts::Artifact+
Association:
        direction::DirectionType source::Artifact target::IdentifiableNode
BpmnDiagram:
        pools::Pool+ messages::MessagingEdge+ author::String title::String
DataObject:
        associations::Association+ artifactsContainer::ArtifactsContainer
DirectionType:
        Both::EPSILON
        From::EPSILON
        To::EPSILON
        None::EPSILON
Graph:
        Pool
Graph:
        SubProcess
Graph:
        vertices::Vertex+ sequenceEdges::SequenceEdge+
Group:
        activities::Activity+
Identifiable:
        IdentifiableNode
Identifiable:
        Artifact
Identifiable:
        BpmnDiagram
Identifiable:
        Lane
Identifiable:
        MessagingEdge
Identifiable:
        SequenceEdge
Identifiable:
        iD::ID
IdentifiableNode:
        Vertex
IdentifiableNode:
        Graph
IdentifiableNode:
        associations::Association+
Lane:
        activities::Activity+ pool::Pool
MessagingEdge:
        bpmnDiagram::BpmnDiagram source::Activity target::Activity
NamedBpmnObject:
        ArtifactsContainer
NamedBpmnObject:
        Activity
NamedBpmnObject:
        Artifact
NamedBpmnObject:
        Lane
NamedBpmnObject:
        MessagingEdge
NamedBpmnObject:
        Pool
NamedBpmnObject:
        SequenceEdge
NamedBpmnObject:
        documentation::String name::String ncname::String
Pool:
        lanes::Lane+ bpmnDiagram::BpmnDiagram
SequenceEdge:
        graph::Graph isDefault::Boolean source::Vertex target::Vertex
SubProcess:
        eventHandlers::Activity+ isTransaction::Boolean
TextAnnotation:
        associations::Association+ artifactsContainer::ArtifactsContainer
Vertex:
        Activity
Vertex:
        outgoingEdges::SequenceEdge+ incomingEdges::SequenceEdge+ graph::Graph
