DateTimeType:
        year::Integer month::Integer day::Integer hour::Integer minute::Integer second::Integer
VersionType:
        n::Integer nn::Integer
ValueType:
        StringValue
ValueType:
        NumberValue
ValueType:
        DateTimeTypeValue
ValueType:
        BooleanValue
ValueType:
        ErrorValue
StringValue:
        value::String
NumberValue:
        value::Double
DateTimeTypeValue:
        value::DateTimeType
BooleanValue:
        value::Boolean
ErrorValue:
        vt_data::Data
DocumentPropertiesCollection:
        dp_workbook::Workbook title::String subject::String keywords::String description::String category::String author::String lastAuthor::String manager::String company::String hyperlinkBase::String revision::Integer presentationFormat::String guid::String appName::String version::VersionType totalTime::Integer lastPrinted::DateTimeType created::DateTimeType lastSaved::DateTimeType pages::Integer words::Integer characters::Integer charactersWithSpaces::Integer bytes::Integer lines::Integer paragraphs::Integer
CustomDocumentPropertiesCollection:
        cdp_workbook::Workbook customDocumentProperties::CustomDocumentProperty+
CustomDocumentProperty:
        customDocumentProperty_cdpe::CustomDocumentPropertiesCollection name::String value::ValueType
SmartTagType:
        smartTagType_ste::SmartTagsCollection namespaceuri::String name::String url::String
SmartTagsCollection:
        st_workbook::Workbook st_cell::Cell smartTagTypes::SmartTagType+
Workbook:
        wb_smartTags::SmartTagsCollection wb_docProperties::DocumentPropertiesCollection wb_customDocProperties::CustomDocumentPropertiesCollection wb_worksheets::Worksheet+
Worksheet:
        ws_workbook::Workbook ws_table::Table name::String
StyledElement:
        Table
StyledElement:
        TableElement
Table:
        t_worksheet::Worksheet t_cols::Column+ t_rows::Row+ defaultColumnWidth::Double defaultRowHeight::Double expandedColumnCount::Integer expandedRowCount::Integer leftCell::Integer topCell::Integer fullColumns::Boolean fullRows::Boolean
TableElement:
        ColOrRowElement
TableElement:
        Cell
ColOrRowElement:
        Column
ColOrRowElement:
        Row
Column:
        c_table::Table autoFitWidth::Boolean width::Double
Row:
        r_table::Table r_cells::Cell+ autoFitHeight::Boolean height::Double
Cell:
        c_row::Row c_smartTags::SmartTagsCollection+ arrayRange::String formula::String hRef::String mergeAcross::Double mergeDown::Double c_data::Data c_comment::Comment
Comment:
        c_cell::Cell com_data::Data author::String showAlways::Boolean
Data:
        d_cell::Cell d_comment::Comment value::ValueType
Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
