Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
StringProperty:
        val::String
StringType:
        StringProperty
StringType:
        Text
StringType:
        DelText
StringType:
        InstrText
StringType:
        DelInstrText
StringType:
        val::String
BreakType:
        bt_page::EPSILON
        bt_column::EPSILON
        bt_text_wrapping::EPSILON
NoteValue:
        ftn_normal::EPSILON
        ftn_separator::EPSILON
        ftn_continuation_separator::EPSILON
        ftn_continuation_notice::EPSILON
OnOffType:
        oot_on::EPSILON
        oot_off::EPSILON
FldCharTypeProperty:
        fctp_begin::EPSILON
        fctp_separate::EPSILON
        fctp_end::EPSILON
WordDocument:
        ignoreSubtree::StringProperty ignoreElements::StringProperty body::BodyElt
BodyElt:
        be_wordDocument::WordDocument blockLevelElts::BlockLevelElt+
BlockLevelElt:
        BlockLevelChunkElt
BlockLevelChunkElt:
        ParaElt
ParaElt:
        pContentElts::ParaContentElt+
ParaContentElt:
        RunElt
RunElt:
        rContentElts::RunContentElt+
RunContentElt:
        BreakElt
RunContentElt:
        NoBreakHyphen
RunContentElt:
        SoftHyphen
RunContentElt:
        AnnotationRef
RunContentElt:
        FootnoteRef
RunContentElt:
        EndnoteRef
RunContentElt:
        Separator
RunContentElt:
        ContinuationSeparator
RunContentElt:
        PgNum
RunContentElt:
        Cr
RunContentElt:
        Picture
RunContentElt:
        Tab
RunContentElt:
        Text
RunContentElt:
        DelText
RunContentElt:
        InstrText
RunContentElt:
        DelInstrText
RunContentElt:
        Footnote
RunContentElt:
        Endnote
RunContentElt:
        Symbol
RunContentElt:
        FldChar
BreakElt:
        type::BreakType
Text:
        rce_rElt::RunElt val::String
DelText:
        rce_rElt::RunElt val::String
InstrText:
        rce_rElt::RunElt val::String
DelInstrText:
        rce_rElt::RunElt val::String
NoBreakHyphen:
        rce_rElt::RunElt
SoftHyphen:
        rce_rElt::RunElt
AnnotationRef:
        rce_rElt::RunElt
FootnoteRef:
        rce_rElt::RunElt
EndnoteRef:
        rce_rElt::RunElt
Separator:
        rce_rElt::RunElt
ContinuationSeparator:
        rce_rElt::RunElt
PgNum:
        rce_rElt::RunElt
Cr:
        rce_rElt::RunElt
Footnote:
        rce_rElt::RunElt n_blockLevelElts::BlockLevelElt+ type::NoteValue suppressRef::OnOffType
Endnote:
        rce_rElt::RunElt n_blockLevelElts::BlockLevelElt+ type::NoteValue suppressRef::OnOffType
NoteElt:
        Footnote
NoteElt:
        Endnote
Picture:
        rce_rElt::RunElt
Symbol:
        rce_rElt::RunElt font::StringType char::StringType
SymElt:
        Symbol
SymElt:
        font::StringType char::StringType
Tab:
        rce_rElt::RunElt
FldChar:
        rce_rElt::RunElt fldData::StringType fldCharType::FldCharTypeProperty fldLock::OnOffType
FldCharElt:
        FldChar
FldCharElt:
        fldData::StringType fldCharType::FldCharTypeProperty fldLock::OnOffType
