Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
LocatedElement:
        Network
LocatedElement:
        Services
Network:
        services::Services+ name::String
Services:
        WebService
Services:
        RSS
WebService:
        linkedServices::Services+
RSS:
        name::String URL::String descriptions::String
