Resource:
        name::String type::String capacity::Integer schedulingPolicy::String description::String acquire::Acquire release::Release
Service:
        name::String formalParams::String speedAttr::String failAttr::String description::String behavior::Behavior+ behaviorUsed::Behavior+ serviceCall::ServiceCall+
Behavior:
        Step
Behavior:
        stepn::Step stepb::Step+ service::Service usedService::Service+ workLoad::WorkLoad
WorkLoad:
        workLoadType::String arrivalProcess::String population::String initialResource::String behavior::Behavior
Step:
        Start
Step:
        End
Step:
        Control
Step:
        InternalActivity
Step:
        ServiceCall
Step:
        name::String repetition::String internalExecTime::String internalFailProb::String completionModel::String serviceCall::ServiceCall+ predecessor::Step+ successor::Step+ behavior::Behavior nestedBehavior::Behavior
Start:
        name::String repetition::String internalExecTime::String internalFailProb::String completionModel::String serviceCall::ServiceCall+ predecessor::Step+ successor::Step+ behavior::Behavior nestedBehavior::Behavior
End:
        name::String repetition::String internalExecTime::String internalFailProb::String completionModel::String serviceCall::ServiceCall+ predecessor::Step+ successor::Step+ behavior::Behavior nestedBehavior::Behavior
Control:
        Branch
Control:
        Fork
Control:
        Join
Control:
        Acquire
Control:
        Release
Control:
        Branch
        Fork
        Join
        Acquire
        Release
InternalActivity:
        name::String repetition::String internalExecTime::String internalFailProb::String completionModel::String serviceCall::ServiceCall+ predecessor::Step+ successor::Step+ behavior::Behavior nestedBehavior::Behavior
ServiceCall:
        resourceType::String serviceName::String isSynch::Boolean actualParam::ActualParam+ step::Step calledService::Service
ActualParam:
        value::String serviceCall::ServiceCall
Branch:
        branchProbs::String
Fork:
        EPSILON
Join:
        EPSILON
Acquire:
        resourceUnits::String resource::Resource
Release:
        resourceUnits::String resource::Resource
String:
        STR
Boolean:
        "true"
        "false"
Integer:
        INT
