LogFile:
        file::String instance::LogFile logger::Logger
Logger:
        instance::Logger expression::Expression logFile::LogFile
Expression:
        Literal
Expression:
        UnaryOperator
Expression:
        BinaryOperator
Expression:
        loggingOn::Boolean logger::Logger
Literal:
        VariableExpression
Literal:
        NumberExpression
Literal:
        value::Integer
VariableExpression:
        name::String
NumberExpression:
        value::Integer
UnaryOperator:
        UnaryPlusOp
UnaryOperator:
        UnaryMinusOp
UnaryOperator:
        operand::Expression
UnaryPlusOp:
        operand::Expression
UnaryMinusOp:
        operand::Expression
BinaryOperator:
        PlusOperator
BinaryOperator:
        MinusOperator
BinaryOperator:
        operand1::Expression operand2::Expression
PlusOperator:
        operand1::Expression operand2::Expression
MinusOperator:
        operand1::Expression operand2::Expression
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
