FIPA-Platform Agent:
        fipa_platform_Task::Solution Domain/FIPA-platform Task+ agent::Agency Domain/Agent
FIPA-platform Task:
        fipa_platform_Agent::Solution Domain/FIPA-Platform Agent task::Agency Domain/Task
Service:
        EPSILON
Agent:
        Name::String Knowledge::Problem Domain/Ontology fipa_platform_AgentA::Solution Domain/FIPA-Platform Agent role::Agency Domain/Role resource::Problem Domain/Ressource+ non_functionnal_Requirement::Problem Domain/Non functionnal Requirement+ requirement::Problem Domain/Requirement+
Role:
        agentR::Agency Domain/Agent service::Solution Domain/Service+ task::Agency Domain/Task+ scenario::Problem Domain/Scenario+ communication::Agency Domain/Communication+
Task:
        Name::String fipa_platform_TaskT::Solution Domain/FIPA-platform Task
Communication:
        Name::String Exchanged Knowledge::Problem Domain/Ontology message::Agency Domain/Message aip::Agency Domain/AIP
Message:
        communication::Agency Domain/Communication Comm_Act::Agency Domain/Performative
AIP:
        Name::String performative::Agency Domain/Performative
Performative:
        aip::Agency Domain/AIP
Ressource:
        Name::String
Non functionnal Requirement:
        EPSILON
Requirement:
        EPSILON
Scenario:
        EPSILON
Ontology:
        EPSILON
Concept:
        EPSILON
Action:
        EPSILON
Predicate:
        EPSILON
String:
        STR
