BoxOperator:
        "HOV" options::(SpaceOption*)
BoxOperator:
        "WD"
BoxOperator:
        "A" alignments::AlignmentOptions options::(SpaceOption*)
BoxOperator:
        "HV" options::(SpaceOption*)
BoxOperator:
        "R"
BoxOperator:
        "H" options::(SpaceOption*)
BoxOperator:
        "I" options::(SpaceOption*)
BoxOperator:
        "V" options::(SpaceOption*)
Context:
        "H"
Context:
        "V"
Boxx:
        "REF" "[" StrCon "," Boxx "]"
Boxx:
        "LBL" "[" StrCon "," Boxx "]"
Boxx:
        operator::BoxOperator "[" list::(Boxx*) "]"
Boxx:
        StrCon
Boxx:
        "CNT" "[" StrCon "," StrCon "]"
Boxx:
        operator::FontOperator "[" list::(Boxx*) "]"
GroupOption:
        "gs" "=" NatCon
GroupOption:
        "op" "=" BoxOperator
FontOperator:
        "VAR"
FontOperator:
        "MATH"
FontOperator:
        "COMM"
FontOperator:
        "KW"
FontOperator:
        "NUM"
FontOperator:
        "ESC"
FontOperator:
        "STRING"
SpaceSymbol:
        "vs"
SpaceSymbol:
        "ts"
SpaceSymbol:
        "hs"
SpaceSymbol:
        "is"
SpaceOption:
        SpaceSymbol "=" NatCon
AlignmentOptions:
        "(" {AlignmentOption ","}* ")"
AlignmentOption:
        "r" options::(SpaceOption*)
AlignmentOption:
        "l" options::(SpaceOption*)
AlignmentOption:
        "c" options::(SpaceOption*)
Main:
        Boxx WhitespaceAndComment*
