VisibilityKind:
        vk_public_vis::EPSILON
        vk_private_vis::EPSILON
        vk_protected_vis::EPSILON
BooleanExpression:
        expresssion::String
ModelElement:
        Dependency
ModelElement:
        Constraint
ModelElement:
        Feature
ModelElement:
        NameSpace
ModelElement:
        name::String visibility::VisibilityKind contraints::Constraint+ clientDependencies::Dependency+ supplierDependencies::Dependency+ namespace::NameSpace importers::Package+
Dependency:
        kind::String clients::ModelElement+ suppliers::ModelElement+
Constraint:
        body::BooleanExpression constrainedElements::ModelElement+
Feature:
        StructuralFeature
Feature:
        owner::Classifier
StructuralFeature:
        Attribute
StructuralFeature:
        type::Classifier
Attribute:
        type::Classifier
NameSpace:
        Classifier
NameSpace:
        Package
NameSpace:
        ownedElements::ModelElement+
Classifier:
        Class
Classifier:
        Datatype
Classifier:
        Subsystem
Classifier:
        features::Feature+
Package:
        Model
Package:
        Subsystem
Package:
        importedElements::ModelElement+
Class:
        features::Feature+
Datatype:
        features::Feature+
Subsystem:
        features::Feature+ importedElements::ModelElement+
Model:
        importedElements::ModelElement+
Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
