BoxOperator:
        "A" alignments::AlignmentOptions options::(SpaceOption*)
BoxOperator:
        "R"
AlignmentOption:
        "l" options::(SpaceOption*)
AlignmentOption:
        "c" options::(SpaceOption*)
AlignmentOption:
        "r" options::(SpaceOption*)
AlignmentOptions:
        "(" (AlignmentOption ("," AlignmentOption)*)? ")"
SpaceSymbol:
        "hs"
SpaceSymbol:
        "vs"
SpaceSymbol:
        "is"
SpaceSymbol:
        "ts"
SpaceOption:
        SpaceSymbol "=" NatCon
Box:
        StrCon
Box:
        operator::BoxOperator "[" list::(Box*) "]"
BoxOperator:
        "H" options::(SpaceOption*)
BoxOperator:
        "V" options::(SpaceOption*)
BoxOperator:
        "HV" options::(SpaceOption*)
BoxOperator:
        "HOV" options::(SpaceOption*)
BoxOperator:
        "I" options::(SpaceOption*)
BoxOperator:
        "WD"
BoxOperator:
        "COMM"
Context:
        "H"
Context:
        "V"
Box:
        "LBL" "[" StrCon "," Box "]"
Box:
        "REF" "[" StrCon "," Box "]"
Box:
        "CNT" "[" StrCon "," StrCon "]"
FontValue:
        NatCon
FontValue:
        FontId
FontOption:
        FontParam "=" FontValue
BoxOperator:
        "F" FontOption*
FontParam:
        "fn"
FontParam:
        "fm"
FontParam:
        "se"
FontParam:
        "sh"
FontParam:
        "sz"
FontParam:
        "cl"
FontOperator:
        "KW"
FontOperator:
        "VAR"
FontOperator:
        "NUM"
FontOperator:
        "MATH"
FontOperator:
        "ESC"
FontOperator:
        "COMM"
FontOperator:
        "STRING"
GroupOption:
        "gs" "=" NatCon
GroupOption:
        "op" "=" BoxOperator
BoxOperator:
        "G" group-options::(GroupOption*)
BoxOperator:
        "SL" group-options::(GroupOption*)
Box:
        "O" SOptions "[" Box BoxString Box "]"
