Actuality:
        Representation
StateOfAffairs:
        Actuality
Thing:
        StateOfAffairs
Thing:
        Meaning
Thing:
        BindableTarget
Thing:
        SemanticFormulation
Thing:
        Namespace
Thing:
        RoleBinding
Thing:
        ReferenceScheme
Thing:
        Set
Thing:
        BodyOfSharedConcepts
Thing:
        BodyOfSharedGuidance
Thing:
        CategorizationScheme
Thing:
        Community
Thing:
        ConceptualSchema
Thing:
        FactModel
Thing:
        Language
Thing:
        LevelOfEnforcement
Thing:
        Res
Thing:
        Situation
Thing:
        SubjectField
Thing:
        TerminologicalDictionary
Thing:
        Viewpoint
Thing:
        name::Name+
Name:
        implicitlyIsUnderstood::Boolean signifier::Expression
Designation:
        Name
Designation:
        Placeholder
Designation:
        FactSymbol
Designation:
        FactTypeRoleDesignation
Designation:
        NonverbalDesignation
Designation:
        PreferredDesignation
Designation:
        ProhibitedDesignation
Designation:
        Term
Designation:
        implicitlyIsUnderstood::Boolean signifier::Expression
Representation:
        Designation
Representation:
        Definition
Representation:
        Statement
Representation:
        FactTypeForm
Representation:
        CommunicationContent
Representation:
        Description
Representation:
        DescriptiveExample
Representation:
        FormalRepresentation
Representation:
        InformalRepresentation
Representation:
        Note
Representation:
        Reference
Representation:
        meaning::Meaning expression::Expression
Meaning:
        Proposition
Meaning:
        Concept
Meaning:
        Question
Meaning:
        representation::Representation+
Expression:
        Text
BindableTarget:
        Expression
BindableTarget:
        Variable
BindableTarget:
        IndividualConcept
BindableTarget:
        Expression
        Variable
AdoptedDefinition:
        EPSILON
Definition:
        AdoptedDefinition
Definition:
        IntensionalDefinition
Definition:
        ExtensionalDefinition
Definition:
        OwnedDefinition
Definition:
        AdoptedDefinition
        IntensionalDefinition
        ExtensionalDefinition
        OwnedDefinition
Advice:
        AdviceOfPossibility
Advice:
        AdviceOfPermission
Advice:
        AdviceOfPossibility
        AdviceOfPermission
ElementOfGuidance:
        Advice
ElementOfGuidance:
        ElementOfGovernance
ElementOfGuidance:
        BusinessRule
ElementOfGuidance:
        isPracticable::Boolean
Proposition:
        ElementOfGuidance
Proposition:
        Rule
Proposition:
        Fact
Proposition:
        isFalse::Boolean isTrue::Boolean statement::Statement+ isPossiblyTrue::Boolean isObligatedToBeTrue::Boolean isPermittedToBeTrue::Boolean isNecessarilyTrue::Boolean
Statement:
        GuidanceStatement
AdviceOfContingency:
        EPSILON
AdviceOfPossibility:
        AdviceOfContingency
AdviceOfOptionality:
        EPSILON
AdviceOfPermission:
        AdviceOfOptionality
AdviceStatement:
        StatementOfAdviceOfPossibility
AdviceStatement:
        StatementOfAdviceOfPermission
AdviceStatement:
        StatementOfAdviceOfPossibility
        StatementOfAdviceOfPermission
GuidanceStatement:
        AdviceStatement
GuidanceStatement:
        BusinessPolicyStatement
GuidanceStatement:
        RuleStatement
GuidanceStatement:
        AdviceStatement
        BusinessPolicyStatement
        RuleStatement
AggregationFormulation:
        projection::Projection
ProjectingFormulation:
        AggregationFormulation
ProjectingFormulation:
        AnswerNominalization
ProjectingFormulation:
        FactTypeNominalization
ProjectingFormulation:
        NounConceptNominalization
ProjectingFormulation:
        QuestionNominalization
ProjectingFormulation:
        projection::Projection
LogicalFormulation:
        ProjectingFormulation
LogicalFormulation:
        Quantification
LogicalFormulation:
        AtomicFormulation
LogicalFormulation:
        LogicalOperation
LogicalFormulation:
        InstantiationFormulation
LogicalFormulation:
        ModalFormulation
LogicalFormulation:
        Objectification
LogicalFormulation:
        PropositionNominalization
LogicalFormulation:
        ClosedLogicalFormulation
LogicalFormulation:
        ProjectingFormulation
        Quantification
        AtomicFormulation
        LogicalOperation
        InstantiationFormulation
        ModalFormulation
        Objectification
        PropositionNominalization
SemanticFormulation:
        LogicalFormulation
SemanticFormulation:
        Projection
SemanticFormulation:
        ClosedSemanticFormulation
SemanticFormulation:
        LogicalFormulation
        Projection
        ClosedSemanticFormulation
Projection:
        BagProjection
Projection:
        ClosedProjection
Projection:
        SetProjection
Projection:
        constrainingFormulation::LogicalFormulation projectionVariable::Variable+ auxiliaryVariable::AuxiliaryVariable+
Variable:
        AuxiliaryVariable
Variable:
        restrictingFormulation::LogicalFormulation projectionPosition::PositiveInteger rangedoverConcept::Concept isUnitary::Boolean
PositiveInteger:
        EPSILON
NonnegativeInteger:
        PositiveInteger
Integer:
        NonnegativeInteger
Integer:
        value::integer
Number:
        Integer
Quantity:
        Number
NounConcept:
        Quantity
NounConcept:
        Role
NounConcept:
        ContextualizedConcept
NounConcept:
        IndividualConcept
NounConcept:
        Quantity
        Role
        ContextualizedConcept
Concept:
        NounConcept
Concept:
        FactType
Concept:
        CategorizationType
Concept:
        ObjectType
Concept:
        ConceptOfThingAsComposite
Concept:
        ConceptOfThingAsContinuant
Concept:
        ConceptOfThingAsDeveloped
Concept:
        ConceptOfThingAsOccurrent
Concept:
        ConceptOfThingAsPrimitive
Concept:
        ConceptOfThingAsUnitary
Concept:
        ConceptOfThingExistingDependently
Concept:
        ConceptOfThingExistingIndependently
Concept:
        DerivableConcept
Concept:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
AttributiveNamespace:
        uri::Uri+
Namespace:
        AttributiveNamespace
Namespace:
        VocabularyNamespace
Namespace:
        uri::Uri+
Uri:
        value::String
Text:
        Uri
Text:
        value::String
Characteristic:
        factTypeForm::FactTypeForm+ role::FactTypeRole+
FactType:
        Characteristic
FactType:
        AssociativeFactType
FactType:
        AssortmentFactType
FactType:
        BinaryFactType
FactType:
        SpecializationFactType
FactType:
        IsroleofFactType
FactType:
        factTypeForm::FactTypeForm+ role::FactTypeRole+
FactTypeForm:
        NounForm
FactTypeForm:
        SententialForm
FactTypeForm:
        placeholder::Placeholder+
Placeholder:
        startingCharacterPosition::PositiveInteger
FactTypeRole:
        roleBinding::RoleBinding+
Role:
        FactTypeRole
Role:
        SituationalRole
RoleBinding:
        name::Name+
ReferenceScheme:
        simplyUsedRole::FactTypeRole+ identifyingCharacteristic::Characteristic+ extensionallyUsedRole::FactTypeRole+
Set:
        BodyOfSharedMeanings
Set:
        Vocabulary
Set:
        Rulebook
Set:
        cardinality::NonnegativeInteger element::Thing+
AuxiliaryVariable:
        restrictingFormulation::LogicalFormulation projectionPosition::PositiveInteger rangedoverConcept::Concept isUnitary::Boolean
AnswerNominalization:
        projection::Projection
AssociativeFactType:
        IspropertyofFactType
AssortmentFactType:
        factTypeForm::FactTypeForm+ role::FactTypeRole+
AtleastnQuantification:
        ExistentialQuantification
AtleastnQuantification:
        minimumCardinality::NonnegativeInteger
Quantification:
        AtleastnQuantification
Quantification:
        AtmostnQuantification
Quantification:
        ExactlynQuantification
Quantification:
        NumericRangeQuantification
Quantification:
        UniversalQuantification
Quantification:
        scopeFormulation::LogicalFormulation
AtmostnQuantification:
        AtmostoneQuantification
AtmostnQuantification:
        maximumCardinality::NonnegativeInteger
AtmostoneQuantification:
        maximumCardinality::NonnegativeInteger
AtomicFormulation:
        roleBinding::RoleBinding+
BagProjection:
        constrainingFormulation::LogicalFormulation projectionVariable::Variable+ auxiliaryVariable::AuxiliaryVariable+
BinaryFactType:
        PartitiveFactType
BinaryLogicalOperation:
        Conjunction
BinaryLogicalOperation:
        Disjunction
BinaryLogicalOperation:
        Equivalence
BinaryLogicalOperation:
        ExclusiveDisjunction
BinaryLogicalOperation:
        Implication
BinaryLogicalOperation:
        NandFormulation
BinaryLogicalOperation:
        NorFormulation
BinaryLogicalOperation:
        WhetherornotFormulation
BinaryLogicalOperation:
        logicalOperand2::LogicalFormulation+ logicalOperand1::LogicalFormulation+
LogicalOperation:
        BinaryLogicalOperation
LogicalOperation:
        LogicalNegation
LogicalOperation:
        logicalOperand::LogicalFormulation
BodyOfSharedConcepts:
        name::Name+
BodyOfSharedGuidance:
        name::Name+
BodyOfSharedMeanings:
        elementaryFactType::FactType+
BusinessPolicy:
        isDirectlyEnforceable::Boolean
ElementOfGovernance:
        BusinessPolicy
ElementOfGovernance:
        OperativeBusinessRule
ElementOfGovernance:
        isDirectlyEnforceable::Boolean
BusinessPolicyStatement:
        EPSILON
BusinessRule:
        StructuralBusinessRule
BusinessRule:
        OperativeBusinessRule
BusinessRule:
        isPracticable::Boolean
Rule:
        StructuralRule
Rule:
        BusinessRule
BusinessVocabulary:
        EPSILON
Vocabulary:
        BusinessVocabulary
CategorizationFactType:
        EPSILON
SpecializationFactType:
        CategorizationFactType
SpecializationFactType:
        ContextualizationFactType
SpecializationFactType:
        CategorizationFactType
        ContextualizationFactType
CategorizationScheme:
        Segmentation
CategorizationScheme:
        ExplicitnessOfRepresentation
CategorizationScheme:
        FactTypeTemplating
CategorizationScheme:
        KindOfGuidanceStatement
CategorizationScheme:
        RealworldNumericalCorrespondence
CategorizationScheme:
        Segmentation
        ExplicitnessOfRepresentation
        FactTypeTemplating
        KindOfGuidanceStatement
        RealworldNumericalCorrespondence
CategorizationType:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
CharacteristicType:
        EPSILON
ConceptType:
        CharacteristicType
ObjectType:
        ConceptType
ObjectType:
        FundamentalConcept
ObjectType:
        LogicalFormulationKind
ObjectType:
        SituationalRole
ObjectType:
        categorizationScheme::CategorizationScheme+ categorizationType::CategorizationType+
ClosedLogicalFormulation:
        EPSILON
ClosedSemanticFormulation:
        ClosedLogicalFormulation
ClosedSemanticFormulation:
        EPSILON
ClosedProjection:
        constrainingFormulation::LogicalFormulation projectionVariable::Variable+ auxiliaryVariable::AuxiliaryVariable+
CommunicationContent:
        meaning::Meaning expression::Expression
Community:
        SemanticCommunity
Community:
        SpeechCommunity
Community:
        uri::Uri+ subcommunity::Community+
ConceptOfThingAsComposite:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptOfThingAsContinuant:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptOfThingAsDeveloped:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptOfThingAsOccurrent:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptOfThingAsPrimitive:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptOfThingAsUnitary:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptOfThingExistingDependently:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptOfThingExistingIndependently:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
ConceptualSchema:
        name::Name+
Conjunction:
        logicalOperand2::LogicalFormulation+ logicalOperand1::LogicalFormulation+
ContextOfThing:
        EPSILON
Segmentation:
        ContextOfThing
Segmentation:
        RepresentationFormality
Segmentation:
        ThingInContext
Segmentation:
        ContextOfThing
        RepresentationFormality
        ThingInContext
ContextualizationFactType:
        IsfacetofFactType
ContextualizedConcept:
        Facet
ContingencyStatement:
        EPSILON
StatementOfAdviceOfPossibility:
        ContingencyStatement
StatementOfAdviceOfPossibility:
        NonnecessityStatement
StatementOfAdviceOfPossibility:
        PossibilityStatement
StatementOfAdviceOfPossibility:
        ContingencyStatement
        NonnecessityStatement
        PossibilityStatement
DefiniteDescription:
        EPSILON
IntensionalDefinition:
        DefiniteDescription
DerivableConcept:
        attributiveNamespace::AttributiveNamespace+ definition::Definition+ moreGeneralConcept::Concept+ category::Concept+ essentialCharacteristic::Characteristic+ instance::Thing+ referenceScheme::ReferenceScheme+ impliedCharacteristic::Characteristic+ necessaryCharacteristic::Characteristic+ designation::Designation+ extension::Set
Description:
        meaning::Meaning expression::Expression
DescriptiveExample:
        meaning::Meaning expression::Expression
Disjunction:
        logicalOperand2::LogicalFormulation+ logicalOperand1::LogicalFormulation+
Equivalence:
        logicalOperand2::LogicalFormulation+ logicalOperand1::LogicalFormulation+
ExactlynQuantification:
        ExactlyoneQuantification
ExactlynQuantification:
        cardinality::NonnegativeInteger
ExactlyoneQuantification:
        cardinality::NonnegativeInteger
ExclusiveDisjunction:
        logicalOperand2::LogicalFormulation+ logicalOperand1::LogicalFormulation+
ExistentialQuantification:
        minimumCardinality::NonnegativeInteger
ExplicitnessOfRepresentation:
        EPSILON
ExtensionalDefinition:
        EPSILON
Facet:
        EPSILON
Fact:
        isFalse::Boolean isTrue::Boolean statement::Statement+ isPossiblyTrue::Boolean isObligatedToBeTrue::Boolean isPermittedToBeTrue::Boolean isNecessarilyTrue::Boolean
FactModel:
        name::Name+
FactSymbol:
        implicitlyIsUnderstood::Boolean signifier::Expression
FactTypeHasFactInFactModel:
        factType::FactType fact::Fact factModel::FactModel
FactTypeNominalization:
        projection::Projection
FactTypeRoleDesignation:
        implicitlyIsUnderstood::Boolean signifier::Expression
FactTypeTemplating:
        EPSILON
FormalRepresentation:
        meaning::Meaning expression::Expression
FundamentalConcept:
        categorizationScheme::CategorizationScheme+ categorizationType::CategorizationType+
Icon:
        EPSILON
NonverbalDesignation:
        Icon
Implication:
        consequent::LogicalFormulation+ antecedent::LogicalFormulation+
ImpossibilityStatement:
        EPSILON
StructuralRuleStatement:
        ImpossibilityStatement
StructuralRuleStatement:
        NecessityStatement
StructuralRuleStatement:
        RestrictedPossibilityStatement
StructuralRuleStatement:
        ImpossibilityStatement
        NecessityStatement
        RestrictedPossibilityStatement
RuleStatement:
        StructuralRuleStatement
RuleStatement:
        OperativeBusinessRuleStatement
RuleStatement:
        StructuralRuleStatement
        OperativeBusinessRuleStatement
IndividualConcept:
        EPSILON
InformalRepresentation:
        meaning::Meaning expression::Expression
InstantiationFormulation:
        EPSILON
IsfacetofFactType:
        EPSILON
IspropertyofFactType:
        EPSILON
IsroleofFactType:
        factTypeForm::FactTypeForm+ role::FactTypeRole+
KindOfGuidanceStatement:
        EPSILON
Language:
        name::Name+
LevelOfEnforcement:
        name::Name+
LogicalFormulationKind:
        categorizationScheme::CategorizationScheme+ categorizationType::CategorizationType+
LogicalNegation:
        logicalOperand::LogicalFormulation
ModalFormulation:
        NecessityFormulation
ModalFormulation:
        ObligationFormulation
ModalFormulation:
        PermissibilityFormulation
ModalFormulation:
        PossibilityFormulation
ModalFormulation:
        NecessityFormulation
        ObligationFormulation
        PermissibilityFormulation
        PossibilityFormulation
NandFormulation:
        logicalOperand2::LogicalFormulation+ logicalOperand1::LogicalFormulation+
NecessityFormulation:
        EPSILON
NecessityStatement:
        EPSILON
NonnecessityStatement:
        EPSILON
NonobligationStatement:
        EPSILON
StatementOfAdviceOfPermission:
        NonobligationStatement
StatementOfAdviceOfPermission:
        OptionalityStatement
StatementOfAdviceOfPermission:
        PermissionStatement
StatementOfAdviceOfPermission:
        NonobligationStatement
        OptionalityStatement
        PermissionStatement
NorFormulation:
        logicalOperand2::LogicalFormulation+ logicalOperand1::LogicalFormulation+
Note:
        meaning::Meaning expression::Expression
NounConceptNominalization:
        projection::Projection
NounForm:
        placeholder::Placeholder+
NumericRangeQuantification:
        maximumCardinality::NonnegativeInteger minimumCardinality::NonnegativeInteger
Objectification:
        EPSILON
ObligationFormulation:
        EPSILON
ObligationStatement:
        EPSILON
OperativeBusinessRuleStatement:
        ObligationStatement
OperativeBusinessRuleStatement:
        ProhibitionStatement
OperativeBusinessRuleStatement:
        RestrictedPermissionStatement
OperativeBusinessRuleStatement:
        ObligationStatement
        ProhibitionStatement
        RestrictedPermissionStatement
OperativeBusinessRule:
        levelOfEnforcement::LevelOfEnforcement+
OptionalityStatement:
        EPSILON
OwnedDefinition:
        EPSILON
PartitiveFactType:
        EPSILON
PermissibilityFormulation:
        EPSILON
PermissionStatement:
        EPSILON
PossibilityFormulation:
        EPSILON
PossibilityStatement:
        EPSILON
PreferredDesignation:
        implicitlyIsUnderstood::Boolean signifier::Expression
ProhibitedDesignation:
        implicitlyIsUnderstood::Boolean signifier::Expression
ProhibitionStatement:
        EPSILON
PropositionNominalization:
        EPSILON
Question:
        representation::Representation+
QuestionNominalization:
        projection::Projection
RealworldNumericalCorrespondence:
        EPSILON
Reference:
        meaning::Meaning expression::Expression
RepresentationFormality:
        EPSILON
Res:
        name::Name+
RestrictedPermissionStatement:
        EPSILON
RestrictedPossibilityStatement:
        EPSILON
Rulebook:
        cardinality::NonnegativeInteger element::Thing+
SemanticCommunity:
        speechCommunity::SpeechCommunity+
SpeechCommunity:
        uri::Uri+ subcommunity::Community+
SententialForm:
        placeholder::Placeholder+
SetProjection:
        constrainingFormulation::LogicalFormulation projectionVariable::Variable+ auxiliaryVariable::AuxiliaryVariable+
Situation:
        name::Name+
SituationalRole:
        categorizationScheme::CategorizationScheme+ categorizationType::CategorizationType+
SpeechCommunityAdoptsAdoptedDefinitionCitingReference:
        speechCommunity::SpeechCommunity adoptedDefinition::AdoptedDefinition reference::Reference
StateOfAffairsInvolvesThingInRole:
        stateOfAffairs::StateOfAffairs thing::Thing role::Role
StructuralBusinessRule:
        EPSILON
StructuralRule:
        StructuralBusinessRule
StructuralRule:
        EPSILON
SubjectField:
        name::Name+
Term:
        implicitlyIsUnderstood::Boolean signifier::Expression
TerminologicalDictionary:
        uri::Uri+
ThingInContext:
        EPSILON
UniversalQuantification:
        scopeFormulation::LogicalFormulation
Viewpoint:
        name::Name+
VocabularyNamespace:
        uri::Uri+
WhetherornotFormulation:
        inconsequent::LogicalFormulation+ consequent::LogicalFormulation+
Boolean:
        "true"
        "false"
String:
        STR
