OperationExp:
        PropertyOperation
OperationExp:
        OclOperation
OperationExp:
        ConstExp
PropertyOperation:
        AttributeExp
PropertyOperation:
        NaviguationExp
PropertyOperation:
        ClassifierOperation
PropertyOperation:
        isMarkedPre::Boolean source::OclExpression
OclOperation:
        arguments::OclExpression
ConstExp:
        IntegerConstExp
ConstExp:
        StringConstExp
ConstExp:
        RealConstExp
ConstExp:
        IntegerConstExp
        StringConstExp
        RealConstExp
IntegerConstExp:
        value::Integer
StringConstExp:
        value::String
RealConstExp:
        value::Double
AttributeExp:
        attr::Attribute
Attribute:
        attrExp::AttributeExp+
NaviguationExp:
        assEnd::AssocationEnd qualifierValues::OclExpression
AssocationEnd:
        navExp::NaviguationExp+
ClassifierOperation:
        op::Operation arguments::OclExpression
Operation:
        classOp::ClassifierOperation+
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
