VisibilityKind:
        vk_public_vis::EPSILON
        vk_private_vis::EPSILON
        vk_protected_vis::EPSILON
ScopeKind:
        sk_instance_level::EPSILON
        sk_classifier_level::EPSILON
MultiplicityType:
        lower::Integer upper::Integer isOrdered::Boolean isUnique::Boolean
ModelElement:
        Feature
ModelElement:
        NameSpace
ModelElement:
        GeneralizableElement
ModelElement:
        name::String
Feature:
        StructuralFeature
Feature:
        BehavioralFeature
Feature:
        ownerScope::ScopeKind visibility::VisibilityKind owner::Classifier
NameSpace:
        Classifier
NameSpace:
        name::String
GeneralizableElement:
        Classifier
GeneralizableElement:
        isRoot::Boolean isLeaf::Boolean isAbstract::Boolean
Classifier:
        Class
Classifier:
        feature::Feature+
Class:
        isActive::Boolean
StructuralFeature:
        Attribute
StructuralFeature:
        multiplicity::MultiplicityType isChangeable::Boolean targetScope::ScopeKind
Attribute:
        initialValue::String
BehavioralFeature:
        Operation
BehavioralFeature:
        isQuery::Boolean
Operation:
        isRoot::Boolean isLeaf::Boolean isAbstract::Boolean specification::String
Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
