Package:
        ownedEltColl::CollaborationPackage ownedEltInt::InteractionPackage+
ProviderClause:
        Package
ProviderClause:
        ownedEltColl::CollaborationPackage ownedEltInt::InteractionPackage+
CollaborationPackage:
        ownedElt::Collaboration
Collaboration:
        interaction::Interaction+ ownedEltAss::AssociationRole ownedEltClass::ClassifierRole
InteractionPackage:
        providerClause::ProviderClause ownedElt::Interaction
Interaction:
        context::Collaboration message::Message+
AssociationRole:
        connection::AssociationEndRole
ClassifierRole:
        associationEndRole::AssociationEndRole+ receiverMess::Message senderMess::Message availableFeature::Operation+ base::Interface
AssociationEndRole:
        associationRole::AssociationRole type::ClassifierRole
Message:
        message::Message+ activator::Message interaction::Interaction+ receiver::ClassifierRole sender::ClassifierRole specification::Request
Request:
        Operation
Request:
        message::Message+
Operation:
        classifierRole::ClassifierRole+ owner::Interface
Interface:
        classifierRole::ClassifierRole+ feature::Operation+
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
