Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
ModelElement:
        TagDefinition
ModelElement:
        referenceTag::TaggedValue+ stereotype::Stereotype+ constraint::Constraint+ taggedValue::TaggedValue+
Constraint:
        constrainedElement::ModelElement+ constrainedStereotype::Stereotype
TaggedValue:
        dataValue::String referenceValue::ModelElement+ type::TagDefinition
TagDefinition:
        tagType::String multiplicity::Multiplicity typedValue::TaggedValue+ owner::Stereotype
Multiplicity:
        value::String
GeneralizableElement:
        Stereotype
Stereotype:
        icon::Geometry baseClass::Name+ definedTag::TagDefinition+ stereotypeConstraint::Constraint+ extendedElement::ModelElement+
Geometry:
        value::String
Name:
        value::String
