Node:
        document::root::Node
        attribute::(namespace::Namespace name::STR text::STR)
        element::(namespace::Namespace name::STR children::(Node*))
        charData::text::STR
        cdata::text::STR
        comment::text::STR
        pi::(target::STR text::STR)
        entityRef::name::STR
        charRef::code::INT
Namespace:
        namespace::(prefix::STR uri::STR)
        none::EPSILON
