[program] Program:
        "begin" decls::Declarations body::{Statement ";"}* "end"
[idtype] IdType:
        id::Id ":" t::Type
[cond] Statement:
        "if" cond::Expression "then" thenPart::{Statement ";"}* "else" elsePart::{Statement ";"}* "fi"
[assign] Statement:
        var::Id ":=" val::Expression
[cond] Statement:
        "if" cond::Expression "then" thenPart::{Statement ";"}* "fi"
[loop] Statement:
        "while" cond::Expression "do" body::{Statement ";"}* "od"
[string] Type:
        "string"
[natural] Type:
        "natural"
[nil] Type:
        "nil-type"
Expression:
        "(" e::Expression ")"
[natcon] Expression:
        natcon::Natural
[id] Expression:
        name::Id
[strcon] Expression:
        string::String
[concat] Expression:
        lhs::Expression "||" rhs::Expression
[add] Expression:
        lhs::Expression "+" rhs::Expression
[min] Expression:
        lhs::Expression "-" rhs::Expression
Declarations:
        "declare" decls::{IdType ","}* ";"
