JavaSource:
        classes::ClassDeclaration+
NamedElement:
        ClassDeclaration
NamedElement:
        MethodDefinition
ClassDeclaration:
        superclass::ClassDeclaration methods::MethodDefinition+
MethodDefinition:
        class::ClassDeclaration invocations::MethodInvocation+
MethodInvocation:
        method::MethodDefinition
