Package:
        EPSILON
ProviderClause:
        ownedEltColl::ANY ownedEltInt::ANY+
CollaborationPackage:
        ownedElt::ANY
Collaboration:
        interaction::ANY+ ownedEltAss::ANY ownedEltClass::ANY
InteractionPackage:
        providerClause::ANY ownedElt::ANY
Interaction:
        context::ANY message::ANY+
AssociationRole:
        connection::ANY
ClassifierRole:
        associationEndRole::ANY+ receiverMess::ANY senderMess::ANY availableFeature::ANY+ base::ANY
AssociationEndRole:
        associationRole::ANY type::ANY
Message:
        message::ANY+ activator::ANY interaction::ANY+ receiver::ANY sender::ANY specification::ANY
Request:
        message::ANY+
Operation:
        classifierRole::ANY+ owner::ANY
Interface:
        classifierRole::ANY+ feature::ANY+
