ModelElement:
        name::ANY
Name:
        EPSILON
AssociationEnd:
        isNavigable::ANY isOrdered::ANY aggregation::ANY multiplicity::ANY changeable::ANY TargetScope::ANY rfIntegrety::ANY rlIntegrety::ANY
AggregationKind:
        EPSILON
Multiplicity:
        EPSILON
ChangeableKind:
        EPSILON
ScopeKind:
        EPSILON
RfIntegretyKind:
        EPSILON
RlIntegretyKind:
        EPSILON
Namespace:
        EPSILON
GeneralizableElement:
        EPSILON
Classifier:
        EPSILON
Class:
        isActive::ANY mutliplicity::ANY key::ANY+
Key:
        EPSILON
Feature:
        EPSILON
StructureFeature:
        EPSILON
Constraint:
        EPSILON
Attribute:
        initialValue::ANY isKey::ANY isUnique::ANY
Expression:
        EPSILON
