Class:
        parent::ANY child::ANY dependency::ANY
Generalization:
        EPSILON
Dependency:
        supplier::ANY client::ANY stereotype::ANY
Stereotype:
        baseClass::ANY extendedElement::ANY
StateMachine:
        context::ANY top::ANY
State:
        stateMachine::ANY internal::ANY
CompositeState:
        subvertex::ANY
SimpleState:
        EPSILON
FinalState:
        EPSILON
StateVertex:
        compositeState::ANY
PseudoState:
        EPSILON
Transition:
        trigger::ANY source::ANY target::ANY
Event:
        EPSILON
