UMLModelElement:
        EPSILON
Attribute:
        owner::ANY type::ANY
Package:
        elements::ANY+
PackageElement:
        EPSILON
Classifier:
        EPSILON
Class:
        attribute::ANY+ general::ANY+ generalOpposite::ANY+ reverse::ANY+ forward::ANY+
PrimitiveDataType:
        typeOpposite::ANY+
Association:
        source::ANY destination::ANY
