ModelElement:
        referenceTag::ANY+ stereotype::ANY+ constraint::ANY+ taggedValue::ANY+
Constraint:
        constrainedElement::ANY+ constrainedStereotype::ANY
TaggedValue:
        dataValue::ANY referenceValue::ANY+ type::ANY
TagDefinition:
        tagType::ANY multiplicity::ANY typedValue::ANY+ owner::ANY
Multiplicity:
        value::ANY
GeneralizableElement:
        EPSILON
Stereotype:
        icon::ANY baseClass::ANY+ definedTag::ANY+ stereotypeConstraint::ANY+ extendedElement::ANY+
Geometry:
        value::ANY
Name:
        value::ANY
