Instance:
        EPSILON
AttributeLink:
        instance::ANY value::ANY linkEnd::ANY attribute::ANY
Link:
        association::ANY connection::ANY
LinkEnd:
        link::ANY qualifiedValue::ANY+ instance::ANY associationEnd::ANY
ComponentInstance:
        resident::ANY+ nodeInstance::ANY
NodeInstance:
        resident::ANY+
UseCase:
        include::ANY+ extend::ANY+ extensionPoint::ANY+
Actor:
        powertypeRange::ANY+ feature::ANY+
UseCaseInstance:
        ownedInstance::ANY+ linkEnd::ANY+ classifier::ANY+ componentInstance::ANY slot::ANY+ ownedLink::ANY+
Extend:
        extensionPoint::ANY+ extension::ANY base::ANY condition::ANY
Include:
        addition::ANY base::ANY
ExtensionPoint:
        useCase::ANY location::ANY
Element:
        EPSILON
ModelElement:
        EPSILON
GeneralizableElement:
        EPSILON
Namespace:
        EPSILON
Classifier:
        EPSILON
Feature:
        EPSILON
StructuralFeature:
        EPSILON
AssociationEnd:
        association::ANY specification::ANY+ participant::ANY qualifier::ANY+ isNavigable::ANY ordering::ANY aggregation::ANY targetScope::ANY multiplicity::ANY changeability::ANY
Relationship:
        EPSILON
Association:
        connection::ANY
Attribute:
        associationEnd::ANY initialValue::ANY
Generalization:
        parent::ANY powertype::ANY child::ANY discriminator::ANY
AggregationKind:
        ak_none::EPSILON
        ak_aggregate::EPSILON
        ak_composite::EPSILON
ChangeableKind:
        ck_changeable::EPSILON
        ck_frozen::EPSILON
        ck_addOnly::EPSILON
OrderingKind:
        ok_unordered::EPSILON
        ok_ordered::EPSILON
ScopeKind:
        sk_instance::EPSILON
        sk_classifier::EPSILON
VisibilityKind:
        vk_public::EPSILON
        vk_protected::EPSILON
        vk_private::EPSILON
        vk_package::EPSILON
Multiplicity:
        range::ANY+
MultiplicityRange:
        multiplicity::ANY lower::ANY upper::ANY
Expression:
        language::ANY body::ANY
BooleanExpression:
        EPSILON
