Element:
        ModelElement
ModelElement:
        GeneralizableElement
ModelElement:
        Namespace
ModelElement:
        Feature
ModelElement:
        Relationship
Relationship:
        Generalization
Generalization:
        parent::GeneralizableElement powertype::Classifier child::GeneralizableElement discriminator::String
Package:
        Model
Package:
        elementImport::ElementImport+
Model:
        EPSILON
Subsystem:
        isInstantiable::Boolean
ElementImport:
        package::Package importedElement::ModelElement visibility::VisibilityKind alias::String isSpecification::Boolean
ScopeKind:
        sk_instance::EPSILON
        sk_classifier::EPSILON
VisibilityKind:
        vk_public::EPSILON
        vk_protected::EPSILON
        vk_private::EPSILON
        vk_package::EPSILON
