LocatedElement:
        EPSILON
ACG:
        metamodel::ANY startsWith::ANY elements::ANY+
ACGElement:
        EPSILON
Function:
        context::ANY name::ANY parameters::ANY+ body::ANY
Attribute:
        context::ANY name::ANY body::ANY
Parameter:
        EPSILON
Node:
        EPSILON
ASMNode:
        name::ANY
CodeNode:
        element::ANY mode::ANY guard::ANY
SimpleNode:
        element::ANY mode::ANY guard::ANY
StatementBlock:
        EPSILON
Statement:
        EPSILON
CompoundStat:
        EPSILON
ForEachStat:
        iterator::ANY collection::ANY
OnceStat:
        
VariableStat:
        definition::ANY name::ANY
OperationStat:
        context::ANY name::ANY
ConditionalStat:
        condition::ANY elseStatements::ANY+
LetStat:
        variable::ANY value::ANY
AnalyzeStat:
        target::ANY mode::ANY
ReportStat:
        severity::ANY message::ANY
Severity:
        critic::EPSILON
        error::EPSILON
        warning::EPSILON
FieldStat:
        name::ANY type::ANY
ParamStat:
        name::ANY type::ANY
EmitStat:
        EPSILON
LabelStat:
        name::ANY id::ANY
NewStat:
        
DupStat:
        
DupX1Stat:
        
PopStat:
        
SwapStat:
        
IterateStat:
        
EndIterateStat:
        
GetAsmStat:
        
FindMEStat:
        
PushTStat:
        
PushFStat:
        
EmitWithOperandStat:
        EPSILON
PushStat:
        operand::ANY
PushIStat:
        operand::ANY
PushDStat:
        operand::ANY
LoadStat:
        operand::ANY
StoreStat:
        operand::ANY
CallStat:
        operand::ANY
PCallStat:
        operand::ANY
SuperCallStat:
        operand::ANY
GetStat:
        operand::ANY
SetStat:
        operand::ANY
EmitWithLabelRefStat:
        EPSILON
IfStat:
        label::ANY
GotoStat:
        label::ANY
VariableDecl:
        name::ANY
Expression:
        EPSILON
VariableExp:
        variable::ANY
SelfExp:
        
LastExp:
        
IfExp:
        condition::ANY thenExp::ANY elseExp::ANY
IsAExp:
        source::ANY type::ANY
LetExp:
        variable::ANY value::ANY in::ANY
PropertyCallExp:
        EPSILON
NavigationExp:
        source::ANY name::ANY
IteratorExp:
        iterator::ANY body::ANY
OperationCallExp:
        arguments::ANY+
OperatorCallExp:
        EPSILON
LiteralExp:
        EPSILON
OclUndefinedExp:
        
CollectionExp:
        EPSILON
SequenceExp:
        elements::ANY+
BooleanExp:
        value::ANY
IntegerExp:
        value::ANY
StringExp:
        value::ANY
