ACMEFile:
        entries::ANY+
ACMEEntry:
        EPSILON
Element:
        EPSILON
Type:
        name::ANY representations::ANY+ property::ANY+
System:
        componentDeclaration::ANY+ connectorDeclaration::ANY+ attachments::ANY+ bindings::ANY+
Representation:
        systems::ANY+
Component:
        EPSILON
ComponentInstance:
        instanceOf::ANY
ComponentType:
        extend::ANY
Port:
        name::ANY representations::ANY+ property::ANY+
Connector:
        roles::ANY+ system::ANY
Role:
        name::ANY representations::ANY+ property::ANY+
Property:
        name::ANY val::ANY
Link:
        EPSILON
Attachment:
        comp::ANY port::ANY con::ANY role::ANY
Binding:
        compSrc::ANY portSrc::ANY compDest::ANY portDest::ANY
