Classifier:
        EPSILON
Environnement:
        element::ANY
Element:
        environnement::ANY action::ANY perception::ANY
CooperativeAgent:
        elementA::ANY elementP::ANY representation::ANY+ skill::ANY+ aptitude::ANY+ characteristic::ANY+ communication::ANY+ observes::ANY+
Representation:
        cooperativeAgentR::ANY element::ANY
Skill:
        cooperativeAgentS::ANY
Aptitude:
        cooperativeAgentA::ANY
Characteristic:
        cooperativeAgentCha::ANY
Communication:
        cooperativeAgentCom::ANY aip::ANY+
AIP:
        EPSILON
CooperationRules:
        detects::ANY+
NCS:
        cooperationRules::ANY
Incomprehension:
        EPSILON
Ambiguity:
        EPSILON
Incompetence:
        EPSILON
Unproductiveness:
        EPSILON
Concurrency:
        EPSILON
Conflict:
        EPSILON
Uselessness:
        EPSILON
