Entity:
        EPSILON
Object:
        EPSILON
AGATEObject:
        EPSILON
Objective:
        type::ANY priority::ANY indicator::ANY traceability::ANY
OperationalContext:
        notice::ANY description::ANY sensitivity::ANY name::ANY comment::ANY isValidIn::ANY isAssociatedWith::ANY
Project:
        moi::ANY moa::ANY director::ANY defines::ANY+ associatedISs::ANY+
Standard:
        caracterizeIC::ANY+ caracterizeTC::ANY+ caracterizeLC::ANY+ caracterizeP::ANY+ caracterizeR::ANY+
GenericStandard:
        EPSILON
Threat:
        nature::ANY DCSSI::ANY clarifies::ANY+
GenericThreat:
        EPSILON
Vulnerability:
        EPSILON
TrafficClass:
        traffic::ANY+
InterfaceCharacteristic:
        EPSILON
ConfidentialityLevel:
        type::ANY
Protocol:
        isoLevel::ANY
Flow:
        unit::ANY
Other:
        type::ANY
ProjectContextElement:
        type::ANY
DataClass:
        notice::ANY description::ANY sensitivity::ANY name::ANY comment::ANY isValidIn::ANY isAssociatedWith::ANY
Event:
        notice::ANY description::ANY sensitivity::ANY name::ANY comment::ANY isValidIn::ANY isAssociatedWith::ANY
Risk:
        disponibilityLevel::ANY integrityLevel::ANY confidencialityLevel::ANY isCoveredByCR::ANY isCoveredByAO::ANY isCoveredByMO::ANY isCoveredByDR::ANY relatesToRO::ANY relatesToCO::ANY isGeneratedBy::ANY
Stake:
        type::ANY relativeDate::ANY unit::ANY date::ANY events::ANY+
Requirement:
        EPSILON
CountermeasureRequirement:
        type::ANY residualVulnerability::ANY
TechnicalRequirement:
        criticality::ANY priority::ANY state::ANY isCoveredBy::ANY+ characterizes::ANY+
PerformanceRequirement:
        criticality::ANY priority::ANY state::ANY isCoveredBy::ANY+ characterizes::ANY+
InteroperabilityRequirement:
        criticality::ANY priority::ANY state::ANY isCoveredBy::ANY+ characterizes::ANY+
OperationalRequirement:
        criticality::ANY priority::ANY state::ANY isCoveredBy::ANY+ characterizes::ANY+
SecurityRequirement:
        criticality::ANY priority::ANY state::ANY isCoveredBy::ANY+ characterizes::ANY+
Means:
        EPSILON
DomainRelation:
        EPSILON
HierarchicalRelation:
        
FunctionalRelation:
        necessaryObjectOF::ANY dependentObjectOF::ANY necessaryObjectOO::ANY dependentObjectOO::ANY necessaryObjectP::ANY dependentObjectP::ANY
Dependence:
        type::ANY necessaryObjectS::ANY dependentObjectS::ANY necessaryObjectLC::ANY dependentObjectLC::ANY necessaryObjectP::ANY dependentObjectP::ANY necessaryObjectC::ANY dependentObjectC::ANY necessaryObjectIS::ANY dependentObjectIS::ANY
ArchitectureObject:
        EPSILON
ReusableObject:
        EPSILON
Site:
        type::ANY localization::ANY deployedObjects::ANY+
GenericSite:
        EPSILON
Package:
        subPackage::ANY+ time::ANY+ groupedObjects::ANY+ isCoveredByLC::ANY isCoveredByTC::ANY composedOf::ANY+
Service:
        Statut::ANY isASpecializationOf::ANY isCoveredBy::ANY
TechnicalComponent:
        type::ANY cots::ANY editor::ANY constructor::ANY version::ANY technology::ANY definedExtension::ANY statut::ANY composedOf::ANY+ isASpecializationOf::ANY interfaces::ANY+
LogicalComponent:
        type::ANY statut::ANY composedOf::ANY+ isASpecializationOf::ANY interfaces::ANY+ isCoveredBy::ANY
OperationalFunction:
        composedOf::ANY+ isCoveredByP::ANY+ isCoveredByS::ANY+
OrganizationObject:
        EPSILON
Center:
        deployedObjects::ANY+
GenericCenter:
        EPSILON
InformationSystem:
        nature::ANY version::ANY membershipCountry::ANY currentLocation::ANY startServiceDate::ANY stopServiceDate::ANY isGeneric::ANY functionalDomain::ANY type::ANY composedOf::ANY+ associatedProjects::ANY+ defines::ANY+ fulfills::ANY+ fixes::ANY+ usedBy::ANY+ interfaces::ANY+
Role:
        type::ANY
GenericRole:
        EPSILON
Actor:
        actors::ANY+
GenericActor:
        EPSILON
TelecomOperator:
        contractType::ANY interfaces::ANY+
CommunicationObject:
        EPSILON
Interface:
        characteristics::ANY+ composedOf::ANY+
Interconnection:
        linkType::ANY between::ANY
InformationFlow:
        priority::ANY frequency::ANY media::ANY continuity::ANY myContainer::ANY time::ANY availabilityRatio::ANY integrity::ANY interoperabilityLevel::ANY mediumFlow::ANY maximumFlow::ANY duration::ANY unitMediumFlow::ANY averageEvent::ANY maximumFlowOverOneDuration::ANY transports::ANY receiverP::ANY transmitterP::ANY receiverOO::ANY transmitterOO::ANY receiverOF::ANY transmitterOF::ANY
Traffic:
        sequence::ANY type::ANY interoperabilityLevel::ANY trafficClass::ANY dataClass::ANY receiverP::ANY transmitterP::ANY receiverIS::ANY transmitterIS::ANY receiverC::ANY transmitterC::ANY receiverTO::ANY transmitterTO::ANY receiverLC::ANY transmitterLC::ANY receiverTC::ANY transmitterTC::ANY
Information:
        format::ANY storageSupport::ANY persistence::ANY DataType::ANY
ReferenceObject:
        EPSILON
ReferenceTechnicalComponent:
        composedOf::ANY+
TechnicalComponentReferenceFrame:
        composedOf::ANY+
ReferenceLogicalComponent:
        composedOf::ANY+
ReferenceService:
        composedOf::ANY+
ServiceReferenceFrame:
        composedOfRS::ANY+ composedOfRLC::ANY+
MADIOSObject:
        EPSILON
Process:
        isCoveredByP::ANY+ isCoveredByS::ANY+
Procedure:
        isCoveredByP::ANY+ isCoveredByS::ANY+
Operation:
        isCoveredByP::ANY+ isCoveredByS::ANY+
Activity:
        isCoveredByP::ANY+ isisCoveredByS::ANY+
