NamedElement:
        EPSILON
DescribableElement:
        EPSILON
CommentableElement:
        EPSILON
Project:
        properties::ANY+ targets::ANY+ defaultTarget::ANY
Property:
        name::ANY value::ANY location::ANY refid::ANY resource::ANY file::ANY url::ANY environment::ANY classpath::ANY classpathref::ANY prefix::ANY
Target:
        if::ANY unless::ANY tasks::ANY+ depends::ANY+
TaskElement:
        EPSILON
Attribute:
        value::ANY
Task:
        attributes::ANY+ elements::ANY+
TaskParameter:
        attributes::ANY+ elements::ANY+
