ModelElement:
        id::ANY name::ANY excludeFromBuild::ANY
VisualModelElement:
        position::ANY label::ANY publicFlag::ANY presentationFlag::ANY showLabel::ANY
Point:
        x::ANY y::ANY
Model:
        engineVersion::ANY javaPackageName::ANY activeObjectClasses::ANY+ experiments::ANY+
ActiveObjectClass:
        clientAreaTopLeft::ANY presentationTopGroupPersistent::ANY iconTopGroupPersistent::ANY generic::ANY genericParameters::ANY agent::ANY environmentDefinesInitialLocation::ANY connectors::ANY+ embeddedObjects::ANY+ shapes::ANY+
Connector:
        sourceEmbeddedObject::ANY sourceConnectableName::ANY targetEmbeddedObject::ANY targetConnectableName::ANY points::ANY+
EmbeddedObject:
        presentation::ANY activeObjectClass::ANY genericParametersSubstitute::ANY parameters::ANY+
ActiveObjectClassRef:
        packageName::ANY className::ANY
Parameter:
        name::ANY value::ANY
Shape:
        asObject::ANY embeddedIcon::ANY rotation::ANY
EmbeddedObjectPresentation:
        EPSILON
Experiment:
        EPSILON
SimulationExperiment:
        activeObjectClass::ANY clientAreaTopLeft::ANY presentationTopGroupPersistent::ANY iconTopGroupPersistent::ANY frame::ANY commandLineArguments::ANY maximumMemory::ANY randomSeed::ANY seedValue::ANY vmArgs::ANY absoluteAccuracy::ANY relativeAccuracy::ANY timeAccuracy::ANY fixedTimeStep::ANY shapes::ANY+ controls::ANY+ parameters::ANY+ enableAdaptiveFrameManagement::ANY enableAntiAliasing::ANY enablePanning::ANY enableZoom::ANY executionMode::ANY cpuRatio::ANY title::ANY framesPerSecond::ANY realTimeScale::ANY uiProperties::ANY+ useCalendar::ANY stopOption::ANY initialDate::ANY initialTime::ANY finalDate::ANY finalTime::ANY modelTimeUnit::ANY
Control:
        width::ANY height::ANY asObject::ANY embeddedIcon::ANY fillColor::ANY textColor::ANY enableExpression::ANY actionCode::ANY labelText::ANY font::ANY
Button:
        EPSILON
Frame:
        x::ANY y::ANY width::ANY height::ANY
Text:
        color::ANY text::ANY font::ANY alignment::ANY
Font:
        name::ANY size::ANY style::ANY
