FiniteAutomaton:
        alphabet::ANY+ transitionSet::ANY+ initialState::ANY finalStateSet::ANY+ StateSet::ANY+
Transition:
        letter::ANY source::ANY target::ANY
State:
        name::ANY combination::ANY
