LocatedElement:
        EPSILON
Bibtex:
        entries::ANY+
Entry:
        EPSILON
Article:
        key::ANY fields::ANY+
Book:
        key::ANY fields::ANY+
Inbook:
        key::ANY fields::ANY+
Booklet:
        key::ANY fields::ANY+
Inproceedings:
        key::ANY fields::ANY+
Proceedings:
        key::ANY fields::ANY+
Incollection:
        key::ANY fields::ANY+
Techreport:
        key::ANY fields::ANY+
PhdThesis:
        key::ANY fields::ANY+
MastersThesis:
        key::ANY fields::ANY+
Manual:
        key::ANY fields::ANY+
Misc:
        key::ANY fields::ANY+
Field:
        EPSILON
Authors:
        value::ANY
AuthorUrls:
        value::ANY
Title:
        value::ANY
Journal:
        value::ANY
BookTitle:
        value::ANY
Institution:
        value::ANY
Organization:
        value::ANY
Type:
        value::ANY
Day:
        value::ANY
Number:
        value::ANY
Chapter:
        value::ANY
Volume:
        value::ANY
Series:
        value::ANY
Pages:
        value::ANY
Publisher:
        value::ANY
Howpublished:
        value::ANY
School:
        value::ANY
Editor:
        value::ANY
Edition:
        value::ANY
Address:
        value::ANY
Year:
        value::ANY
Month:
        value::ANY
Note:
        value::ANY
Text:
        value::ANY
AbstractField:
        value::ANY
Isbn:
        value::ANY
Issn:
        value::ANY
Url:
        value::ANY
Doi:
        value::ANY
