BibTeXFile:
        entries::ANY+
Author:
        author::ANY
BibTeXEntry:
        EPSILON
AuthoredEntry:
        EPSILON
DatedEntry:
        EPSILON
TitledEntry:
        EPSILON
BookTitledEntry:
        EPSILON
Article:
        journal::ANY
TechReport:
        EPSILON
Unpublished:
        note::ANY
Manual:
        title::ANY
Proceedings:
        EPSILON
InProceedings:
        EPSILON
Booklet:
        year::ANY
Book:
        publisher::ANY
InCollection:
        EPSILON
InBook:
        chapter::ANY
Misc:
        id::ANY
ThesisEntry:
        EPSILON
PhDThesis:
        school::ANY
MasterThesis:
        school::ANY
