Assessment:
        motivatedDirective::ANY+ affectedEnd::ANY+ judgedInfluencer::ANY+ assessingOrganizationUnit::ANY affectedMeans::ANY+ identifiedPotentialImpact::ANY+ usedAssessment::ANY+ usingAssessment::ANY+ categorizingAssessmentCategory::ANY+
MotivationElement:
        EPSILON
Directive:
        supportedDesiredResult::ANY+ governedCourseOfAction::ANY+ derivedCourseOfAction::ANY+ governedAsset::ANY+ motivatingPotentialImpact::ANY+ directiveRegulation::ANY+ motivatingAssessment::ANY+
Means:
        establishingOrganizationUnit::ANY+ judgingAssessment::ANY+
OrganizationUnit:
        definedEnd::ANY+ managedBusinessProces::ANY+ managedLiability::ANY+ managedAsset::ANY+ determiningStrategy::ANY+ recognizedInfluencer::ANY+ internalInfluencingOrganization::ANY+ madeAssessment::ANY+ establishedMeans::ANY+
End:
        judgingAssessment::ANY+ definingOrganizationUnit::ANY+
BusinessProcess:
        deliveredOffering::ANY+ realizedCourseOfAction::ANY+ managedAsset::ANY+ governingBusinessPolicy::ANY+ guidingBusinessRule::ANY responsibleOrganizationUnit::ANY+
Offering:
        definingCourseOfAction::ANY+ usedAsset::ANY+ requiredResource::ANY+ deliveringBusinessProcess::ANY+
Asset:
        deployingCourseOfAction::ANY+ governingDirective::ANY+ responsibleOrganizationUnit::ANY+ managingBusinessProcess::ANY+
CourseOfAction:
        enabledCourseOfAction::ANY+ enablingCourseOfAction::ANY+ moreSpecficCourseOfAction::ANY+ broaderCourseOfAction::ANY+ supportedDesiredResult::ANY+ definedOffering::ANY+ dischargedLiability::ANY+ realizingBusinessProcess::ANY governingDirective::ANY+ baseDirective::ANY+ deployedAsset::ANY+
DesiredResult:
        moreSpecificDesiredResult::ANY+ broaderDesiredResult::ANY+ supportingDirective::ANY+ supportingCourseOfAction::ANY+
Liability:
        claimedResource::ANY+ responsibleOrganizationUnit::ANY+ dischargingCourseOfAction::ANY+
Resource:
        providingFixedAsset::ANY+ requiringOffering::ANY+ claimingLiability::ANY+
FixedAsset:
        usingOffering::ANY+ providedResource::ANY+
BusinessPolicy:
        moreSpecificBusinessPolicy::ANY+ broaderBusinessPolicy::ANY+ derivedBusinessRule::ANY+ governedBusinessProcess::ANY+
BusinessRule:
        effectingTactic::ANY+ guidedBusinessProcess::ANY+ baseBusinessPolicy::ANY+
Tactic:
        implementedStrategy::ANY+ enforcedBusinessRule::ANY+
Strategy:
        determinedOrganizationUnit::ANY+ plannedMission::ANY+ implementingTactic::ANY+
Mission:
        operativeVision::ANY componentStrategy::ANY+
Vision:
        amplifyingGoal::ANY+ deliveringMission::ANY+
Goal:
        quantifyingObjective::ANY+ amplifiedVision::ANY
Objective:
        quantifiedGoal::ANY+
Influencer:
        categorizingInfluencerCategory::ANY+ sourceInfluencingOrganization::ANY+ judgingAssessment::ANY+ recognizingOrganizationUnit::ANY+
InfluencerCategory:
        categorizedInfluencer::ANY+
InfluencingOrganization:
        categorizingOrganizationCategory::ANY+ influencingOrganizationUnit::ANY providedInfluencer::ANY+
OrganizationCategory:
        categorizedInfluencingOrganization::ANY+
PotentialImpact:
        identifyingAssessment::ANY+ motivatedDirective::ANY+
Regulation:
        regulatingDirective::ANY
AssessmentCategory:
        categorizedAssessment::ANY+
PotentialReward:
        EPSILON
Risk:
        EPSILON
