Activity:
        orderedMessages::ANY+ incomingMessages::ANY+ outgoingMessages::ANY+ groups::ANY+ activityType::ANY eventHandlerFor::ANY lane::ANY looping::ANY
ActivityType:
        SubProcess::EPSILON
        EventEndMultiple::EPSILON
        EventEndMessage::EPSILON
        EventIntermediateMessage::EPSILON
        EventStartMultiple::EPSILON
        EventIntermediateMultiple::EPSILON
        GatewayParallel::EPSILON
        EventStartTimer::EPSILON
        EventStartEmpty::EPSILON
        EventIntermediateCancel::EPSILON
        EventEndError::EPSILON
        EventStartRule::EPSILON
        EventEndTerminate::EPSILON
        EventStartLink::EPSILON
        EventIntermediateLink::EPSILON
        EventEndCancel::EPSILON
        EventEndLink::EPSILON
        EventIntermediateEmpty::EPSILON
        EventIntermediateCompensation::EPSILON
        Task::EPSILON
        GatewayDataBasedExclusive::EPSILON
        GatewayComplex::EPSILON
        EventEndEmpty::EPSILON
        EventIntermediateError::EPSILON
        EventIntermediateTimer::EPSILON
        EventEndCompensation::EPSILON
        EventStartMessage::EPSILON
        GatewayDataBasedInclusive::EPSILON
        GatewayEventBasedExclusive::EPSILON
        EventIntermediateRule::EPSILON
Artifact:
        associations::ANY+ artifactsContainer::ANY
ArtifactsContainer:
        artifacts::ANY+
Association:
        direction::ANY source::ANY target::ANY
BpmnDiagram:
        pools::ANY+ messages::ANY+ author::ANY title::ANY
DataObject:
        EPSILON
DirectionType:
        Both::EPSILON
        From::EPSILON
        To::EPSILON
        None::EPSILON
Graph:
        vertices::ANY+ sequenceEdges::ANY+
Group:
        activities::ANY+
Identifiable:
        iD::ANY
IdentifiableNode:
        associations::ANY+
Lane:
        activities::ANY+ pool::ANY
MessagingEdge:
        bpmnDiagram::ANY source::ANY target::ANY
NamedBpmnObject:
        documentation::ANY name::ANY ncname::ANY
Pool:
        lanes::ANY+ bpmnDiagram::ANY
SequenceEdge:
        graph::ANY isDefault::ANY source::ANY target::ANY
SubProcess:
        eventHandlers::ANY+ isTransaction::ANY
TextAnnotation:
        EPSILON
Vertex:
        outgoingEdges::ANY+ incomingEdges::ANY+ graph::ANY
