LocatedElement:
        EPSILON
Query:
        entries::ANY+ predicates::ANY+
Entry:
        name::ANY type::ANY allFields::ANY fields::ANY+ predicate::ANY
Field:
        name::ANY entry::ANY
Predicate:
        entry::ANY expression::ANY+
Expression:
        field::ANY value::ANY
