Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
ErrorType:
        et_null::EPSILON
        et_NotFound::EPSILON
        et_NotPermitted::EPSILON
        et_InvalidBugId::EPSILON
SeverityType:
        st_null::EPSILON
        st_blocker::EPSILON
        st_critical::EPSILON
        st_major::EPSILON
        st_normal::EPSILON
        st_minor::EPSILON
        st_trivial::EPSILON
        st_enhancement::EPSILON
StatusType:
        st_null::EPSILON
        st_UNCONFIRMED::EPSILON
        st_NEW::EPSILON
        st_ASSIGNED::EPSILON
        st_REOPENED::EPSILON
        st_RESOLVED::EPSILON
        st_VERIFIED::EPSILON
        st_CLOSED::EPSILON
OperatingSystemType:
        ost_null::EPSILON
        ost_all::EPSILON
        ost_Windows 3.1::EPSILON
        ost_Windows 95::EPSILON
        ost_Windows 98::EPSILON
        ost_Windows ME::EPSILON
        ost_Windows 2000::EPSILON
        ost_Windows NT::EPSILON
        ost_Windows XP::EPSILON
        ost_Windows Vista::EPSILON
        ost_Windows Server 2003::EPSILON
        ost_MacSystem 7::EPSILON
        ost_MacSystem 7.5::EPSILON
        ost_MacSystem 7.6.1::EPSILON
        ost_MacSystem 8.0::EPSILON
        ost_MacSystem 8.5::EPSILON
        ost_MacSystem 8.6::EPSILON
        ost_MacSystem 9.x::EPSILON
        ost_Mac OS X 10.0::EPSILON
        ost_Mac OS X 10.1::EPSILON
        ost_Mac OS X 10.2::EPSILON
        ost_Mac OS X 10.3::EPSILON
        ost_Linux::EPSILON
        ost_BDS/OS::EPSILON
        ost_FreeBSD::EPSILON
        ost_NetBSD::EPSILON
        ost_OpenBSD::EPSILON
        ost_AIX::EPSILON
        ost_BeOS::EPSILON
        ost_HP-UX::EPSILON
        ost_IRIX::EPSILON
        ost_Neutrino::EPSILON
        ost_OpenVMS::EPSILON
        ost_OS/2::EPSILON
        ost_OSF/1::EPSILON
        ost_Solaris::EPSILON
        ost_SunOS::EPSILON
        ost_other::EPSILON
PriorityType:
        pt_null::EPSILON
        pt_P1::EPSILON
        pt_P2::EPSILON
        pt_P3::EPSILON
        pt_P4::EPSILON
        pt_P5::EPSILON
ReportedPlatformType:
        rpt_null::EPSILON
        rpt_all::EPSILON
        rpt_DEC::EPSILON
        rpt_HP::EPSILON
        rpt_Macintosh::EPSILON
        rpt_PC::EPSILON
        rpt_SGI::EPSILON
        rpt_Sun::EPSILON
        rpt_other::EPSILON
ResolutionType:
        rt_null::EPSILON
        rt_FIXED::EPSILON
        rt_INVALID::EPSILON
        rt_WONTFIX::EPSILON
        rt_LATER::EPSILON
        rt_REMIND::EPSILON
        rt_DUPLICATE::EPSILON
        rt_WORKSFORME::EPSILON
        rt_MOVED::EPSILON
BugzillaRoot:
        version::String urlbase::String maintainer::String exporter::String bugs::Bug+
Bug:
        bug_bugzillaRoot::BugzillaRoot error::ErrorType bug_id::String exporter::String urlbase::String bug_status::StatusType resolution::ResolutionType product::String priority::PriorityType version::String rep_platform::ReportedPlatformType assigned_to::String delta_ts::String component::String reporter::String target_milestone::String bug_severity::SeverityType creation_ts::String qa_contact::String status_whiteboard::String op_sys::OperatingSystemType bug_file_loc::String short_desc::String keywords::Keywords+ dependson::Dependson+ blocks::Blocks+ cc::Cc+ long_desc::LongDesc+ attachment::Attachment+
StringElt:
        Keywords
StringElt:
        Dependson
StringElt:
        Blocks
StringElt:
        Cc
Keywords:
        value::String
Dependson:
        value::String
Blocks:
        value::String
Cc:
        value::String
LongDesc:
        isPrivate::Boolean who::String bug_when::String thetext::String
Attachment:
        isObsolete::Boolean isPatch::Boolean isPrivate::Boolean id::String date::String desc::String type::String data::String
