DataType:
        EPSILON
Action:
        EPSILON
Class:
        EPSILON
BusinessEntityPropertySet:
        EPSILON
BusinessRole:
        EPSILON
Task:
        associatedWith::ANY+ needs::ANY+
ArtifactRole:
        characterisedby::ANY typ::ANY task::ANY+ fille::ANY+
PerformerRole:
        perform::ANY
OrganisationalUnit:
        characterisedby::ANY typ::ANY task::ANY+ fille::ANY+
BusinessEntity:
        placehold::ANY+
