Namespace:
        EPSILON
Task:
        EPSILON
DataSet:
        EPSILON
Parameter:
        EPSILON
DataElement:
        EPSILON
ModelElement:
        EPSILON
Flow:
        
DataFlow:
        EPSILON
ControlFlow:
        EPSILON
ControlPoint:
        sink::ANY+
Input:
        sink::ANY source::ANY
Output:
        sink::ANY source::ANY
OutputSet:
        containsOutput::ANY+
InputSet:
        containsInput::ANY+
Exception:
        EPSILON
SimpleTask:
        containsDataSet::ANY containsControlPoint::ANY+ invoker::ANY+ terminator::ANY+
CoumpoundTask:
        containsTask::ANY+ containsFlow::ANY+ realizes::ANY
MutliTask:
        EPSILON
InvokerTask:
        invokes::ANY+
TerminatorTask:
        terminates::ANY+
ApplicationTask:
        EPSILON
Decision:
        EPSILON
Clock:
        EPSILON
SendCommunication:
        EPSILON
ReceiveCommunication:
        EPSILON
BusinessProcess:
        EPSILON
