CDataType:
        CIntegral
CDataType:
        CFloating
CDataType:
        CBitField
CDataType:
        CVoid
CDataType:
        CIntegral
        CFloating
        CBitField
        CVoid
CIntegral:
        CEnumeration
CIntegral:
        CInt
CIntegral:
        CChar
CIntegral:
        CEnumeration
        CInt
        CChar
CFloating:
        CDouble
CFloating:
        CFloat
CFloating:
        CLongDouble
CFloating:
        CDouble
        CFloat
        CLongDouble
CBitField:
        EPSILON
CVoid:
        EPSILON
CEnumeration:
        EPSILON
CInt:
        CUnsignedInt
CInt:
        CLong
CInt:
        CLongLong
CInt:
        CShort
CInt:
        CUnsignedInt
        CLong
        CLongLong
        CShort
CChar:
        CSignedChar
CChar:
        CUnsignedChar
CChar:
        CWChar
CChar:
        CSignedChar
        CUnsignedChar
        CWChar
CDouble:
        EPSILON
CFloat:
        EPSILON
CLongDouble:
        EPSILON
CUnsignedInt:
        UnsignedLong
CUnsignedInt:
        UnsignedLongLong
CUnsignedInt:
        UnsignedShort
CUnsignedInt:
        UnsignedLong
        UnsignedLongLong
        UnsignedShort
CLong:
        EPSILON
CLongLong:
        EPSILON
CShort:
        EPSILON
CSignedChar:
        EPSILON
CUnsignedChar:
        EPSILON
CWChar:
        EPSILON
UnsignedLong:
        EPSILON
UnsignedLongLong:
        EPSILON
UnsignedShort:
        EPSILON
CClassifier:
        CDataType
CClassifier:
        Derived
CClassifier:
        CDataType
        Derived
Derived:
        EPSILON
CStructureContents:
        sc_container::CStructured
CStructured:
        CStruct
CStructured:
        CUnion
CStructured:
        contains::CStructureContents+
CStruct:
        EPSILON
CUnion:
        EPSILON
CSourceText:
        source::String fileName::String
CTypedElement:
        CParameter
CTypedElement:
        type::CClassifier source::CSourceText
CStructuralFeature:
        CField
CStructuralFeature:
        CField
CField:
        EPSILON
CParameter:
        behavioralFeature::BehavioralFeature
BehavioralFeature:
        CFunction
BehavioralFeature:
        parameters::CParameter+
CFunction:
        isVarArg::Boolean
