CDataType:
        EPSILON
CIntegral:
        EPSILON
CFloating:
        EPSILON
CBitField:
        EPSILON
CVoid:
        EPSILON
CEnumeration:
        EPSILON
CInt:
        EPSILON
CChar:
        EPSILON
CDouble:
        EPSILON
CFloat:
        EPSILON
CLongDouble:
        EPSILON
CUnsignedInt:
        EPSILON
CLong:
        EPSILON
CLongLong:
        EPSILON
CShort:
        EPSILON
CSignedChar:
        EPSILON
CUnsignedChar:
        EPSILON
CWChar:
        EPSILON
UnsignedLong:
        EPSILON
UnsignedLongLong:
        EPSILON
UnsignedShort:
        EPSILON
CClassifier:
        EPSILON
Derived:
        EPSILON
CStructureContents:
        sc_container::ANY
CStructured:
        contains::ANY+
CStruct:
        EPSILON
CUnion:
        EPSILON
CSourceText:
        source::ANY fileName::ANY
CTypedElement:
        type::ANY source::ANY
CStructuralFeature:
        EPSILON
CField:
        EPSILON
CParameter:
        behavioralFeature::ANY
BehavioralFeature:
        parameters::ANY+
CFunction:
        isVarArg::ANY
