Element:
        name::ANY content::ANY
Architecture:
        isAssociatedWith::ANY+ missions::ANY+ isFocusOf::ANY+ uses::ANY+
Organization:
        isAssociatedWith::ANY+ softwareItems::ANY+ owns::ANY+ includes::ANY+ performsTo::ANY+ hasRequirement::ANY+ hasMissionArea::ANY+ associatedSystems::ANY+ isProponentOf::ANY+
Guidance:
        isAssocitatedWith::ANY+ isImplementedBy::ANY+ isSpecifiedIn::ANY+ providesAuthorityFor::ANY+ defines::ANY+
Document:
        isAssociatedWith::ANY+ describesArchitecture::ANY describesSystem::ANY+ isSpecifiedUsing::ANY+ cites::ANY+
Action:
        mayBeA::ANY isAssociatedWith::ANY+ involvedIn::ANY+
Agreement:
        isAssociatedWith::ANY+ isCitedBy::ANY+ appliesTo::ANY+ implements::ANY+
Standard:
        EPSILON
Task:
        isAssociatedWith::ANY+ isPerformedBy::ANY+ isPerformedUsing::ANY+ specifies::ANY+
InformationAsset:
        isAssociatedWith::ANY+
ConceptualDataModel:
        EPSILON
ActivityModel:
        EPSILON
Node:
        isAssociatedWith::ANY+ describes::ANY+ hasServicesProvidedBy::ANY+ involvedIn::ANY+ uses::ANY+ involves::ANY+ isParticipedInBy::ANY+ supports::ANY+
Network:
        isAssociatedWith::ANY+ isDescribedIn::ANY+ compliesWith::ANY+ has::ANY+ performsTo::ANY+
Requirement:
        mayBeSatifiedBy::ANY+ isSpecifiedUsing::ANY+ specifiesNeedFor::ANY+ cites::ANY+
InfoExchRequirement:
        isCitedIn::ANY+ isSpecifiedInInfos::ANY+
ExchangeNeedLineReq:
        EPSILON
MissionArea:
        supports::ANY+
System:
        isAssociatedWith::ANY+ citedIn::ANY+ compliesWith::ANY+ isDescribedBy::ANY+ uses::ANY+ operatesUsing::ANY+ performsTo::ANY+ associatedOrganization::ANY+ appliesTo::ANY+
Mission:
        isCitedBy::ANY requires::ANY+ isAssigned::ANY+ mayCite::ANY+
FunctionalArea:
        isPartOf::ANY+ supports::ANY+ cites::ANY+
Capability:
        specifiesRequired::ANY+
MaterielItem:
        establishedAs::ANY+ conformsTo::ANY+ performsTo::ANY+
EquipmentType:
        EPSILON
SoftwareItem:
        uses::ANY+ isSourceFor::ANY
Facility:
        EPSILON
