IUmlType:
        members::ANY+
ICdeComponentSpec:
        EPSILON
IUmlClass:
        EPSILON
IUmlComponent:
        EPSILON
ICdeServer:
        implements::ANY+
ICdeComponent:
        EPSILON
IUmlMember:
        EPSILON
ICdeMember:
        EPSILON
ICdeMemberExe:
        executionPerformance::ANY resourceNeeded::ANY executionDetails::ANY
