IUmlType:
        ICdeComponentSpec
IUmlType:
        IUmlClass
IUmlType:
        members::IUmlMember+
ICdeComponentSpec:
        EPSILON
IUmlClass:
        IUmlComponent
IUmlClass:
        IUmlComponent
IUmlComponent:
        ICdeServer
IUmlComponent:
        ICdeComponent
IUmlComponent:
        ICdeServer
        ICdeComponent
ICdeServer:
        implements::ICdeComponent+
ICdeComponent:
        EPSILON
IUmlMember:
        ICdeMember
IUmlMember:
        ICdeMember
ICdeMember:
        EPSILON
ICdeMemberExe:
        executionPerformance::String resourceNeeded::String executionDetails::String
