LocatedElement:
        EPSILON
OpConstraint:
        eq::EPSILON
        and2::EPSILON
        or2::EPSILON
        gt::EPSILON
        ge::EPSILON
        lt::EPSILON
        le::EPSILON
        plus::EPSILON
Package:
        name::ANY import::ANY+ problem::ANY
Import:
        fqn::ANY
ChocoProblem:
        name::ANY elements::ANY+
Element:
        EPSILON
Expression:
        EPSILON
ConstraintDef:
        op::ANY left::ANY right::ANY
IntVar:
        domain::ANY
Domain:
        lower::ANY upper::ANY
IntConstant:
        val::ANY
SymbolicTerm:
        term::ANY
IntValue:
        val::ANY
IntExp:
        op::ANY left::ANY right::ANY
Constraint:
        op::ANY left::ANY right::ANY
PostConstraint:
        op::ANY constraint::ANY
