AddressInfo:
        Office
AddressInfo:
        Customer
Date:
        year::Integer month::Integer day::Integer
ClassicModels:
        offices::Office+ productLines::ProductLine+ customers::Customer+
ProductLine:
        productLineOwner::ClassicModels products::Product+ name::String textDescription::String htmlDescription::String
Product:
        productLine::ProductLine code::String name::String scale::String vendor::String description::String quantityInStock::Integer buyPrice::Double MSRP::Double
Office:
        officeOwner::ClassicModels code::String employees::Employee+ territory::String
Employee:
        office::Office number::Integer employeeCustomers::Customer+ lastName::String firstName::String extension::String email::String reportsTo::Employee jobTitle::String
Customer:
        customerOwner::ClassicModels number::Integer orders::Order+ payments::Payment+ salesRepEmployee::Employee name::String contactLastName::String contactFirstName::String creditLimit::Double
Payment:
        customer::Customer checkNumber::String date::Date amount::Double
Order:
        customer::Customer orderDetails::OrderDetail+ number::Integer date::Date requiredDate::Date shippedDate::Date status::String comments::String
OrderDetail:
        order::Order product::Product quantityOrdered::Integer priceEach::Double
