Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
NamedElt:
        Classifier
NamedElt:
        Attribute
Classifier:
        DataType
Classifier:
        Class
DataType:
        
Class:
        super::Class+ attr::Attribute+ isAbstract::Boolean
Attribute:
        multiValued::Boolean type::Classifier owner::Class
