AddressInfo:
        EPSILON
Date:
        year::ANY month::ANY day::ANY
ClassicModels:
        offices::ANY+ productLines::ANY+ customers::ANY+
ProductLine:
        productLineOwner::ANY products::ANY+ name::ANY textDescription::ANY htmlDescription::ANY
Product:
        productLine::ANY code::ANY name::ANY scale::ANY vendor::ANY description::ANY quantityInStock::ANY buyPrice::ANY MSRP::ANY
Office:
        officeOwner::ANY code::ANY employees::ANY+ territory::ANY
Employee:
        office::ANY number::ANY employeeCustomers::ANY+ lastName::ANY firstName::ANY extension::ANY email::ANY reportsTo::ANY jobTitle::ANY
Customer:
        customerOwner::ANY number::ANY orders::ANY+ payments::ANY+ salesRepEmployee::ANY name::ANY contactLastName::ANY contactFirstName::ANY creditLimit::ANY
Payment:
        customer::ANY checkNumber::ANY date::ANY amount::ANY
Order:
        customer::ANY orderDetails::ANY+ number::ANY date::ANY requiredDate::ANY shippedDate::ANY status::ANY comments::ANY
OrderDetail:
        order::ANY product::ANY quantityOrdered::ANY priceEach::ANY
