String:
        STR
Integer:
        INT
Boolean:
        "true"
        "false"
Any:
        _String
Any:
        _Link
Any:
        _Float
Any:
        _Integer
Any:
        _StringArray
Any:
        _FloatArray
Any:
        _IntegerArray
Any:
        _FloatMatrix
Any:
        _Coordinate2
Any:
        _Coordinate3
Any:
        _Angle
Any:
        _Torsion
Any:
        _List
Any:
        Molecule
Any:
        Formula
Any:
        Atom
Any:
        Atom_Array
Any:
        Bond
Any:
        Bond_Array
Any:
        Electron
Any:
        Reaction
Any:
        Crystal
Any:
        Sequence
Any:
        Feature
AngleUnits:
        degrees::EPSILON
        radians::EPSILON
AtomRefs_Element:
        _StringBuiltin
StringBuiltin:
        id::EPSILON
        elementType::EPSILON
        atomId::EPSILON
        residueType::EPSILON
        residueId::EPSILON
        atomRef::EPSILON
        order::EPSILON
        stereo::EPSILON
        spaceground::EPSILON
_String:
        
_Link:
        
FloatBuiltin:
        x2::EPSILON
        y2::EPSILON
        x3::EPSILON
        y3::EPSILON
        z3::EPSILON
        xFract::EPSILON
        yFract::EPSILON
        zFract::EPSILON
        occupancy::EPSILON
        isotope::EPSILON
        formalCharge::EPSILON
        hydrogenCount::EPSILON
        nonHydrogenCount::EPSILON
        atomParity::EPSILON
        length::EPSILON
        acell::EPSILON
        bcell::EPSILON
        ccell::EPSILON
        alpha::EPSILON
        beta::EPSILON
        gamma::EPSILON
        z::EPSILON
_Float:
        
IntegerBuiltin:
        isotope::EPSILON
        formalCharge::EPSILON
        hydrogenCount::EPSILON
        nonHydrogenCount::EPSILON
        atomParity::EPSILON
        z::EPSILON
_Integer:
        
_StringArray:
        delimiter::String
_FloatArray:
        
_IntegerArray:
        
_FloatMatrix:
        
Coordinate2Builtin:
        xy2::EPSILON
_Coordinate2:
        
Coordinate3Builtin:
        xyz3::EPSILON
        xyzFract::EPSILON
_Coordinate3:
        
_Angle:
        
_Torsion:
        
_List:
        any::Any+
Molecule:
        any::Any+
Formula:
        any::Any+
Atom:
        any::Any+
Atom_Array:
        any::Any+
Bond:
        any::Any+
Bond_Array:
        any::Any+
Electron:
        any::Any+
Reaction:
        any::Any+
Crystal:
        any::Any+
Sequence:
        any::Any+
Feature:
        any::Any+
