AngleUnits:
        degrees::EPSILON
        radians::EPSILON
AtomRefs_Element:
        _StringBuiltin
StringBuiltin:
        id::EPSILON
        elementType::EPSILON
        atomId::EPSILON
        residueType::EPSILON
        residueId::EPSILON
        atomRef::EPSILON
        order::EPSILON
        stereo::EPSILON
        spaceground::EPSILON
_String:
        EPSILON
_Link:
        EPSILON
FloatBuiltin:
        x2::EPSILON
        y2::EPSILON
        x3::EPSILON
        y3::EPSILON
        z3::EPSILON
        xFract::EPSILON
        yFract::EPSILON
        zFract::EPSILON
        occupancy::EPSILON
        isotope::EPSILON
        formalCharge::EPSILON
        hydrogenCount::EPSILON
        nonHydrogenCount::EPSILON
        atomParity::EPSILON
        length::EPSILON
        acell::EPSILON
        bcell::EPSILON
        ccell::EPSILON
        alpha::EPSILON
        beta::EPSILON
        gamma::EPSILON
        z::EPSILON
_Float:
        EPSILON
IntegerBuiltin:
        isotope::EPSILON
        formalCharge::EPSILON
        hydrogenCount::EPSILON
        nonHydrogenCount::EPSILON
        atomParity::EPSILON
        z::EPSILON
_Integer:
        EPSILON
_StringArray:
        delimiter::String
_FloatArray:
        EPSILON
_IntegerArray:
        EPSILON
_FloatMatrix:
        EPSILON
Coordinate2Builtin:
        xy2::EPSILON
_Coordinate2:
        EPSILON
Coordinate3Builtin:
        xyz3::EPSILON
        xyzFract::EPSILON
_Coordinate3:
        EPSILON
_Angle:
        EPSILON
_Torsion:
        EPSILON
_List:
        any::Any+
Molecule:
        any::Any+
Formula:
        any::Any+
Atom:
        any::Any+
Atom_Array:
        any::Any+
Bond:
        any::Any+
Bond_Array:
        any::Any+
Electron:
        any::Any+
Reaction:
        any::Any+
Crystal:
        any::Any+
Sequence:
        any::Any+
Feature:
        any::Any+
