PCDATA:
        EPSILON
Any:
        EPSILON
TitledElement:
        EPSILON
IdedElement:
        EPSILON
ConventionnedElement:
        EPSILON
DictRefElement:
        EPSILON
SimpleLink_Element:
        EPSILON
Counted_Element:
        EPSILON
Sized_Element:
        EPSILON
Rows_Element:
        EPSILON
Columns_Element:
        EPSILON
Min_Element:
        EPSILON
Max_Element:
        EPSILON
Units_Element:
        EPSILON
AngleUnits:
        degrees::EPSILON
        radians::EPSILON
AngleUnits_Element:
        EPSILON
UnitsRef_Element:
        EPSILON
AtomRefs_Element:
        EPSILON
StringBuiltin:
        id::EPSILON
        elementType::EPSILON
        atomId::EPSILON
        residueType::EPSILON
        residueId::EPSILON
        atomRef::EPSILON
        order::EPSILON
        stereo::EPSILON
        spaceground::EPSILON
_StringBuiltin:
        EPSILON
_String:
        EPSILON
_Link:
        EPSILON
FloatBuiltin:
        x2::EPSILON
        y2::EPSILON
        x3::EPSILON
        y3::EPSILON
        z3::EPSILON
        xFract::EPSILON
        yFract::EPSILON
        zFract::EPSILON
        occupancy::EPSILON
        isotope::EPSILON
        formalCharge::EPSILON
        hydrogenCount::EPSILON
        nonHydrogenCount::EPSILON
        atomParity::EPSILON
        length::EPSILON
        acell::EPSILON
        bcell::EPSILON
        ccell::EPSILON
        alpha::EPSILON
        beta::EPSILON
        gamma::EPSILON
        z::EPSILON
_FloatBuiltin:
        EPSILON
_Float:
        EPSILON
IntegerBuiltin:
        isotope::EPSILON
        formalCharge::EPSILON
        hydrogenCount::EPSILON
        nonHydrogenCount::EPSILON
        atomParity::EPSILON
        z::EPSILON
_IntegerBuiltin:
        EPSILON
_Integer:
        EPSILON
_StringArray:
        delimiter::ANY
_FloatArray:
        EPSILON
_IntegerArray:
        EPSILON
_FloatMatrix:
        EPSILON
Coordinate2Builtin:
        xy2::EPSILON
_Coordinate2Builtin:
        EPSILON
_Coordinate2:
        EPSILON
Coordinate3Builtin:
        xyz3::EPSILON
        xyzFract::EPSILON
_Coordinate3Builtin:
        EPSILON
_Coordinate3:
        EPSILON
_Angle:
        EPSILON
_Torsion:
        EPSILON
_List:
        any::ANY+
Molecule:
        any::ANY+
Formula:
        any::ANY+
Atom:
        any::ANY+
Atom_Array:
        any::ANY+
Bond:
        any::ANY+
Bond_Array:
        any::ANY+
Electron:
        any::ANY+
Reaction:
        any::ANY+
Crystal:
        any::ANY+
Sequence:
        any::ANY+
Feature:
        any::ANY+
