Thing:
        Conference
Thing:
        Conference
Meta-Reviewer:
        EPSILON
Reviewer:
        Meta-Reviewer
Reviewer:
        assignedByAdministrator::Administrator adjustBid::Bid readPaper::Paper hasBeenAssigned::Paper writeReview::Review assignExternalReviewer::ExternalReviewer
Decision:
        Acceptance
Decision:
        Rejection
Decision:
        Acceptance
        Rejection
Person:
        ConferenceMember
Person:
        ExternalReviewer
Person:
        User
Person:
        hasConflictOfInterest::Document email::String
Document:
        Review
Document:
        Paper
Document:
        Review
        Paper
Preference:
        EPSILON
ProgramCommittee:
        hasProgramCommitteeMember::ProgramCommitteeMember
Bid:
        adjustedBy::Reviewer
Conference:
        hasConferenceMember::ConferenceMember paperAssignmentFinalizedBy::Administrator reviewCriteriaEnteredBy::Administrator paperAssignmentToolsRunBy::Administrator virtualMeetingEnabledBy::Administrator hardcopyMailingManifestsPrintedBy::Administrator detailsEnteredBy::Administrator reviewerBiddingStartedBy::Administrator date::date reviewsPerPaper::Integer logoURL::anyURI acceptsHardcopySubmissions::Boolean siteURL::anyURI
ConferenceChair:
        EPSILON
ConferenceMember:
        memberOfConference::Conference
AssociatedChair:
        EPSILON
ProgramCommitteeMember:
        memberOfProgramCommittee::ProgramCommittee maxPapers::Integer addedBy::Administrator
AuthorNotReviewer:
        EPSILON
SubjectArea:
        EPSILON
ExternalReviewer:
        assignedByReviewer::Reviewer
Chairman:
        EPSILON
ProgramCommitteeChair:
        endReview::Review
Acceptance:
        EPSILON
Rejection:
        EPSILON
Review:
        Meta-Review
Review:
        writtenBy::Reviewer
Paper:
        PaperAbstract
Paper:
        PaperFullVersion
Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Author:
        AuthorNotReviewer
Author:
        Co-author
Author:
        submitPaper::Paper writePaper::Paper
User:
        Administrator
User:
        Administrator
Co-author:
        co-writePaper::Paper
PaperAbstract:
        EPSILON
PaperFullVersion:
        EPSILON
Administrator:
        finalizePaperAssignment::Conference runPaperAssignmentTools::Conference enableVirtualMeeting::Conference startReviewerBidding::Conference assignReviewer::Reviewer rejectPaper::Paper enterConferenceDetails::Conference printHardcopyMailingManifests::Conference setMaxPapers::ProgramCommitteeMember enterReviewCriteria::Conference acceptPaper::Paper addProgramCommitteeMember::ProgramCommitteeMember
Meta-Review:
        EPSILON
