COBOLUsageValue:
        cuv_binary::EPSILON
        cuv_dbcs::EPSILON
        cuv_double::EPSILON
        cuv_display::EPSILON
        cuv_float::EPSILON
        cuv_index::EPSILON
        cuv_objectReference::EPSILON
        cuv_packedDecimal::EPSILON
        cuv_pointer::EPSILON
        cuv_procedurePointer::EPSILON
COBOLInitialValueKind:
        civk_string_value::EPSILON
        civk_low_value::EPSILON
        civk_high_value::EPSILON
        civk_zero_value::EPSILON
        civk_quotes::EPSILON
        civk_null::EPSILON
        civk_all_literal::EPSILON
COBOLElement:
        level::ANY refined::ANY name::ANY sharedType::ANY group::ANY initial::ANY+ contains::ANY+ source::ANY array::ANY
COBOLClassifier:
        typeded::ANY name::ANY typedElements::ANY+
COBOLSimpleType:
        usageValue::ANY pictureString::ANY usage::ANY
COBOLComposedType:
        elements::ANY+
COBOLElementInitialValue:
        initVal::ANY valueKind::ANY
COBOL88Element:
        name::ANY has::ANY+
COBOL88ElementValue:
        lowerLimit::ANY upperLimit::ANY range::ANY
COBOLRedefiningElement:
        redefines::ANY
COBOL66Element:
        name::ANY end::ANY start::ANY
COBOLSourceText:
        source::ANY fileName::ANY
COBOLFixedLengthArray:
        maxUpper::ANY
COBOLVariableLengthArray:
        minUpper::ANY dependingOn::ANY
