Thing:
        Event
Thing:
        Role
Thing:
        Person
Thing:
        Document
Thing:
        Detail
Thing:
        Event
        Role
        Person
        Document
        Detail
Meta-Reviewer:
        EPSILON
Reviewer:
        Meta-Reviewer
Reviewer:
        assignedByAdministrator::Administrator adjustBid::Bid readPaper::Paper hasBeenAssigned::Paper writeReview::Review assignExternalReviewer::ExternalReviewer
Decision:
        Acceptance
Decision:
        Rejection
Decision:
        Acceptance
        Rejection
Preference:
        EPSILON
ProgramCommittee:
        hasProgramCommitteeMember::ProgramCommitteeMember
Bid:
        adjustedBy::Reviewer
Conference:
        hasConferenceMember::ConferenceMember paperAssignmentFinalizedBy::Administrator reviewCriteriaEnteredBy::Administrator paperAssignmentToolsRunBy::Administrator virtualMeetingEnabledBy::Administrator hardcopyMailingManifestsPrintedBy::Administrator detailsEnteredBy::Administrator reviewerBiddingStartedBy::Administrator date::date reviewsPerPaper::Integer logoURL::anyURI acceptsHardcopySubmissions::Boolean siteURL::anyURI
ConferenceChair:
        EPSILON
ConferenceMember:
        memberOfConference::Conference
AssociatedChair:
        EPSILON
ProgramCommitteeMember:
        memberOfProgramCommittee::ProgramCommittee maxPapers::Integer addedBy::Administrator
AuthorNotReviewer:
        EPSILON
SubjectArea:
        EPSILON
ExternalReviewer:
        assignedByReviewer::Reviewer
Chairman:
        EPSILON
ProgramCommitteeChair:
        endReview::Review
Acceptance:
        EPSILON
Rejection:
        EPSILON
Review:
        Meta-Review
Review:
        writtenBy::Reviewer
Paper:
        PaperAbstract
Paper:
        PaperFullVersion
Paper:
        Abstract
Paper:
        Invited_Paper
Paper:
        Short_Paper
Paper:
        Full_Paper
Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Author:
        AuthorNotReviewer
Author:
        Co-author
Author:
        Corresponding_Author
Author:
        submitPaper::Paper writePaper::Paper
Co-author:
        co-writePaper::Paper
PaperAbstract:
        EPSILON
PaperFullVersion:
        EPSILON
Administrator:
        approve::Event assign::Role finalizePaperAssignment::Conference runPaperAssignmentTools::Conference enableVirtualMeeting::Conference startReviewerBidding::Conference assignReviewer::Reviewer rejectPaper::Paper enterConferenceDetails::Conference printHardcopyMailingManifests::Conference setMaxPapers::ProgramCommitteeMember enterReviewCriteria::Conference acceptPaper::Paper addProgramCommitteeMember::ProgramCommitteeMember
Meta-Review:
        EPSILON
Workshop:
        EPSILON
Event:
        Workshop
Event:
        Symposium
Event:
        conists_of::Event_Tracks confirmed_by::Approval_Email defined_by::Event_Setup approved_by::Administrator
Account:
        registred_by::Person
Inforamtion:
        EPSILON
User:
        Committee
User:
        recieve::Document create::Thing+ submit::Document
Role:
        Admin_Role
Role:
        Author_Role
Role:
        Committe_Role
Role:
        Head_Role
Role:
        Reviewer_Role
Role:
        assigned_by::Administrator
Help_Request:
        Misc
Help_Request:
        Feature_Request
Help_Request:
        Assistance
Help_Request:
        Misc
        Feature_Request
        Assistance
Person:
        ConferenceMember
Person:
        ExternalReviewer
Person:
        User
Person:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person hasConflictOfInterest::Document email::String
Symposium:
        EPSILON
Abstract:
        EPSILON
Document:
        Review
Document:
        Paper
Document:
        Email
Document:
        Submission
Document:
        Template
Document:
        recieved_by::User used_by::Person submited__by::User
Invited_Paper:
        EPSILON
Admin_Role:
        EPSILON
Paper_Typologies:
        EPSILON
Event_Setup:
        Paper_Typologies
Event_Setup:
        Review_Form
Event_Setup:
        Submission_Template
Event_Setup:
        Event_Tracks
Event_Setup:
        Research_Topic
Event_Setup:
        Email_Template
Event_Setup:
        define::Event
Event_URL:
        concerned::Event
URL:
        Event_URL
URL:
        Event_URL
Notification_Email:
        EPSILON
Email:
        Notification_Email
Email:
        Group_Email
Email:
        Approval_Email
Email:
        Rejection_Email
Email:
        Notification_Email
        Group_Email
        Approval_Email
        Rejection_Email
Short_Paper:
        EPSILON
Author_Role:
        EPSILON
Preview:
        EPSILON
Review_Form:
        Preview
Review_Form:
        Review_Form_Setup
Review_Form:
        Preview
        Review_Form_Setup
Committe_Role:
        EPSILON
Group_Email:
        EPSILON
Submission_Template:
        EPSILON
Review_Form_Setup:
        EPSILON
Misc:
        EPSILON
Event_Creation:
        EPSILON
Approval_Email:
        confirm::Event
Rejection_Email:
        EPSILON
Submission:
        EPSILON
Template:
        EPSILON
Feature_Request:
        EPSILON
Committee:
        EPSILON
Event_Tracks:
        EPSILON
Request:
        Help_Request
Request:
        Help_Request
Activity:
        Event_Creation
Activity:
        Request
Activity:
        Event_Approval
Activity:
        Registration
Activity:
        has_result::Thing+ sent_by::Person
Head_Role:
        EPSILON
Detail:
        EPSILON
Corresponding_Author:
        EPSILON
Reviewer_Role:
        EPSILON
Event_Approval:
        EPSILON
Registration:
        EPSILON
Full_Paper:
        EPSILON
Research_Topic:
        EPSILON
Description:
        EPSILON
Assistance:
        EPSILON
Email_Template:
        EPSILON
