Thing:
        EPSILON
Reviewer:
        invites_co-reviewers::ANY invited_by::ANY has_a_review_reference_or_expertise::ANY+ assignedByAdministrator::ANY adjustBid::ANY readPaper::ANY hasBeenAssigned::ANY writeReview::ANY assignExternalReviewer::ANY
Meta-Reviewer:
        EPSILON
Decision:
        EPSILON
Preference:
        EPSILON
ProgramCommittee:
        hasProgramCommitteeMember::ANY
Bid:
        adjustedBy::ANY
Conference:
        is_in_phase::ANY hasConferenceMember::ANY paperAssignmentFinalizedBy::ANY reviewCriteriaEnteredBy::ANY paperAssignmentToolsRunBy::ANY virtualMeetingEnabledBy::ANY hardcopyMailingManifestsPrintedBy::ANY detailsEnteredBy::ANY reviewerBiddingStartedBy::ANY date::ANY reviewsPerPaper::ANY logoURL::ANY acceptsHardcopySubmissions::ANY siteURL::ANY
ConferenceChair:
        EPSILON
ConferenceMember:
        memberOfConference::ANY
AssociatedChair:
        EPSILON
ProgramCommitteeMember:
        memberOfProgramCommittee::ANY maxPapers::ANY addedBy::ANY
AuthorNotReviewer:
        EPSILON
SubjectArea:
        EPSILON
ExternalReviewer:
        assignedByReviewer::ANY
Chairman:
        EPSILON
ProgramCommitteeChair:
        endReview::ANY
Acceptance:
        EPSILON
Rejection:
        EPSILON
Review:
        reviews::ANY gives_classification::ANY is_created_in::ANY writtenBy::ANY
Paper:
        full_paper_size::ANY has_author::ANY hasCo-author::ANY hasBid::ANY hasDecision::ANY assignedTo::ANY hasSubjectArea::ANY readByReviewer::ANY paperID::ANY title::ANY hasAuthor::ANY acceptedBy::ANY rejectedBy::ANY readByMeta-Reviewer::ANY
Author:
        submitPaper::ANY writePaper::ANY
Co-author:
        co-writePaper::ANY
PaperAbstract:
        EPSILON
PaperFullVersion:
        EPSILON
Administrator:
        approve::ANY assign::ANY finalizePaperAssignment::ANY runPaperAssignmentTools::ANY enableVirtualMeeting::ANY startReviewerBidding::ANY assignReviewer::ANY rejectPaper::ANY enterConferenceDetails::ANY printHardcopyMailingManifests::ANY setMaxPapers::ANY enterReviewCriteria::ANY acceptPaper::ANY addProgramCommitteeMember::ANY
Meta-Review:
        EPSILON
Event:
        conists_of::ANY confirmed_by::ANY defined_by::ANY approved_by::ANY
Account:
        registred_by::ANY
Inforamtion:
        EPSILON
User:
        recieve::ANY create::ANY+ submit::ANY
Role:
        assigned_by::ANY
Help_Request:
        EPSILON
Person:
        hasConflictOfInterest::ANY email::ANY inverse_of_add::ANY+ execute::ANY+ get::ANY use::ANY register::ANY modify::ANY+ take_part_in::ANY remove::ANY+ add::ANY send::ANY added_by::ANY contributes::ANY has_an_email::ANY has_the_first_name::ANY has_gender::ANY has_the_last_name::ANY
Symposium:
        EPSILON
Abstract:
        EPSILON
Document:
        recieved_by::ANY used_by::ANY submited__by::ANY
Invited_Paper:
        EPSILON
Admin_Role:
        EPSILON
Paper_Typologies:
        EPSILON
Event_Setup:
        define::ANY
Event_URL:
        concerned::ANY
Notification_Email:
        EPSILON
Email:
        EPSILON
Short_Paper:
        EPSILON
Author_Role:
        EPSILON
Preview:
        EPSILON
Review_Form:
        EPSILON
Committe_Role:
        EPSILON
Group_Email:
        EPSILON
Submission_Template:
        EPSILON
Review_Form_Setup:
        EPSILON
Misc:
        EPSILON
Event_Creation:
        EPSILON
Approval_Email:
        confirm::ANY
Rejection_Email:
        EPSILON
Submission:
        EPSILON
Template:
        EPSILON
Feature_Request:
        EPSILON
Committee:
        has_members::ANY was_a_committee_of::ANY has_a_committee_co-chair::ANY has_a_committee_chair::ANY
Event_Tracks:
        EPSILON
Request:
        EPSILON
Activity:
        has_result::ANY+ sent_by::ANY
Head_Role:
        EPSILON
Detail:
        EPSILON
Corresponding_Author:
        EPSILON
Reviewer_Role:
        EPSILON
Event_Approval:
        EPSILON
Registration:
        EPSILON
Full_Paper:
        EPSILON
Research_Topic:
        EPSILON
Description:
        EPSILON
Assistance:
        EPSILON
Email_Template:
        EPSILON
Conference_participant:
        EPSILON
Active_conference_participant:
        gives_presentations::ANY
Passive_conference_participant:
        EPSILON
Review_expertise:
        has_a_submitted_contribution::ANY has_an_expertise::ANY
Submitted_contribution:
        has_a_review_expertise::ANY
Regular_author:
        EPSILON
Conference_contributor:
        EPSILON
Contribution_1th-author:
        EPSILON
Contribution_co-author:
        EPSILON
Conference_contribution:
        is_submitted_at::ANY
Co-chair:
        was_a_committe_co-chair_of::ANY
Committee_member:
        was_a_member_of::ANY
Abstract:
        is_the_1th_part_of::ANY+
Extended_abstract:
        EPSILON
Important_dates:
        is_an_abstract_submission_date::ANY is_a_full_paper_submission_date::ANY is_an_ending_date::ANY is_a_date_of_acceptance_announcement::ANY is_a_date_of_camera_ready_paper_submission::ANY is_a_starting_date::ANY belong_to_a_conference_volume::ANY
Invited_speaker:
        EPSILON
Conference_proceedings:
        has_an_ISBN::ANY has_a_publisher::ANY has_a_volume::ANY
Information_for_participants:
        EPSILON
Conference_document:
        has_authors::ANY has_a_date_of_issue::ANY
Organization:
        EPSILON
Regular_contribution:
        EPSILON
Poster:
        EPSILON
Written_contribution:
        EPSILON
Conference_applicant:
        EPSILON
Camera_ready_contribution:
        EPSILON
Accepted_contribution:
        EPSILON
Program_committee:
        was_a_program_committee_of::ANY
Organizing_committee:
        was_an_organizing_committee_of::ANY
Steering_committee:
        was_a_steering_committee_of::ANY
Conference_volume:
        has_parts::ANY has_workshops::ANY has_tracks::ANY has_tutorials::ANY has_a_commtitee::ANY has_a_steering_committee::ANY has_an_organizing_committee::ANY has_important_dates::ANY has_contributions::ANY has_a_location::ANY has_a_program_committee::ANY
Call_for_paper:
        EPSILON
Conference_announcement:
        EPSILON
Invited_talk:
        EPSILON
Conference_part:
        has_a_track-workshop-tutorial_topic::ANY is_part_of_conference_volumes::ANY has_a_track-workshop-tutorial_chair::ANY
Presentation:
        is_given_by::ANY
Chair:
        was_a_committee_chair_of::ANY
Track:
        EPSILON
Workshop:
        EPSILON
Tutorial:
        EPSILON
Rejected_contribution:
        EPSILON
Reviewed_contribution:
        has_a_review::ANY
Topic:
        belongs_to_a_review_reference::ANY is_a_topis_of_conference_parts::ANY
Late_paid_applicant:
        EPSILON
Paid_applicant:
        EPSILON
Early_paid_applicant:
        EPSILON
Organizer:
        EPSILON
Call_for_participation:
        EPSILON
Publisher:
        issues::ANY
Registeered_applicant:
        EPSILON
Track-workshop_chair:
        was_a_track-workshop_chair_of::ANY
Conference_www:
        has_a_URL::ANY
Conference_fees:
        EPSILON
Review_preference:
        has_a_topic_or_a_submission_contribution::ANY+ has_a_degree::ANY
EEnum:
        high::EPSILON
        medium::EPSILON
        low::EPSILON
        very high::EPSILON
        male::EPSILON
        female::EPSILON
Accepted_Paper:
        EPSILON
Rejected_Paper:
        EPSILON
Undecided_Paper:
        EPSILON
Manual_Paper_Assignment:
        manually_assign_paper::ANY+
Program_Committee_member:
        EPSILON
paper_assignment:
        assign_paper::ANY is_performed_by::ANY
intensity:
        EPSILON
start_date_of_camera-ready_submission:
        EPSILON
camera-ready_submission_date:
        EPSILON
date_of_notification:
        EPSILON
date:
        EPSILON
article:
        goes_through::ANY is_sent_to::ANY is_created_in::ANY structure_created_by::ANY has_author::ANY gives_classification::ANY
Contact_Person:
        EPSILON
bidding_of_reviewer:
        is_performed_by::ANY
activity:
        is_followed_by::ANY is_monitored_by::ANY has_intensity::ANY has_result::ANY is_performed_by::ANY is_supervised_by::ANY
URL:
        EPSILON
conference_setup:
        sets_member::ANY is_made_by::ANY includes_topic::ANY sets_date::ANY sets_URL::ANY
human:
        is_author_of::ANY performs_activity::ANY is_employed_in::ANY has_topic_of_interest::ANY supervises::ANY e-mail::ANY last_name::ANY first_name::ANY
managing_of_conference_process:
        EPSILON
Program_Committee_Chair:
        EPSILON
reviewing_proces:
        EPSILON
end_date_of_camera-ready_submission:
        EPSILON
abstract_submission_date:
        EPSILON
group_email:
        EPSILON
Senior_Reviewer_URL:
        EPSILON
notification:
        has_result::ANY is_performed_by::ANY
notification_email:
        EPSILON
Chair_URL:
        EPSILON
abstract_of_paper:
        EPSILON
submission_process:
        is_performed_by::ANY
topic:
        EPSILON
lower_tier_reviewing_process:
        EPSILON
start_date_of_conference:
        EPSILON
date_of_conference:
        EPSILON
Senior_Program_Committee_member:
        supervises::ANY
end_date_of_abstract_submission:
        EPSILON
phase_of_conference:
        EPSILON
Regular_Program_Committee_member:
        EPSILON
start_date_of_full_paper_submission:
        EPSILON
full_paper_submission_date:
        EPSILON
start_date_of_abstract_submission:
        EPSILON
end_date_of_conference:
        EPSILON
review_form:
        is_created_in::ANY
Automatic_Paper_Assignment:
        automatically_assign_paper::ANY+
institute:
        EPSILON
classification:
        EPSILON
summary_of_reviews:
        is_created_in::ANY
upper_tier_reviewing_process:
        is_performed_by::ANY
end_date_of_full_paper_submission:
        EPSILON
acceptance_notification_email:
        EPSILON
rejection_notification_email:
        EPSILON
Contact_Person_URL:
        EPSILON
Regular_Reviewer_URL:
        EPSILON
