ControllerAttribute:
        controller::ANY
Controller:
        controllerAttribute::ANY+ behavior::ANY
StateMachine:
        states::ANY+
State:
        substates::ANY+ theContainer::ANY outGoing::ANY+ incoming::ANY+
SubControllerState:
        controller::ANY
ViewState:
        EPSILON
StateTransition:
        source::ANY target::ANY trigger::ANY effect::ANY
StateMachineAction:
        EPSILON
Event:
        EPSILON
