CDerived:
        EPSILON
CStructured:
        EPSILON
CBehavorialFeature:
        EPSILON
CFunction:
        isVsrArg::ANY
CStructureContents:
        EPSILON
CField:
        EPSILON
CDerivableType:
        EPSILON
VisibilityKind:
        vk_public::EPSILON
        vk_private::EPSILON
        vk_protected::EPSILON
CPPReference:
        EPSILON
CPPExtern:
        linkage::ANY
CPPConst:
        EPSILON
CPPTemplate:
        classes::ANY+
CPPClass:
        isAbstract::ANY isVolatile::ANY visibility::ANY templates::ANY+ generalizations::ANY+
CPPGeneralization:
        visibility::ANY isVirtual::ANY supertype::ANY
CPPOperation:
        isStatic::ANY isExtern::ANY isInline::ANY isVirtual::ANY isPure::ANY visibility::ANY isCtor::ANY isDtor::ANY throws::ANY+
CPPOperator:
        isInline::ANY visibility::ANY
CPPMember:
        isStatic::ANY isVolatile::ANY isRegister::ANY visibility::ANY
