CDerived:
        CPPReference
CDerived:
        CPPExtern
CDerived:
        CPPConst
CDerived:
        CPPTemplate
CDerived:
        CPPReference
        CPPExtern
        CPPConst
        CPPTemplate
CStructured:
        CPPClass
CStructured:
        CPPClass
CBehavorialFeature:
        CFunction
CBehavorialFeature:
        CFunction
CFunction:
        isVsrArg::Boolean
CStructureContents:
        CPPOperator
CStructureContents:
        CPPOperator
CField:
        EPSILON
CDerivableType:
        EPSILON
VisibilityKind:
        vk_public::EPSILON
        vk_private::EPSILON
        vk_protected::EPSILON
CPPReference:
        EPSILON
CPPExtern:
        linkage::String
CPPConst:
        EPSILON
CPPTemplate:
        classes::CPPClass+
CPPClass:
        isAbstract::Boolean isVolatile::Boolean visibility::VisibilityKind templates::CPPTemplate+ generalizations::CPPGeneralization+
CPPGeneralization:
        visibility::VisibilityKind isVirtual::Boolean supertype::CPPClass
CPPOperation:
        isStatic::Boolean isExtern::Boolean isInline::Boolean isVirtual::Boolean isPure::Boolean visibility::VisibilityKind isCtor::Boolean isDtor::Boolean throws::CPPClass+
CPPOperator:
        isInline::Boolean visibility::VisibilityKind
CPPMember:
        isStatic::Boolean isVolatile::Boolean isRegister::Boolean visibility::VisibilityKind
