Plan:
        sub_plans::Plan+ super_plan::Plan objectives::Objective+ actions::Action+
Objective:
        objective_plan::Plan criterias::EvaluationCriteria+
EvaluationCriteria:
        criteria_objective::Objective
Action:
        action_plan::Plan sub_actions::Action+ super_action::Action actor::Actor resources::Resource+ timeSpecs::TimeSpec+
Actor:
        actor_action::Action sub_actors::Actor+ super_actor::Actor
Resource:
        resource_action::Action
TimeSpec:
        timeSpec_action::Action
