CSM:
        step::Step+ generalResource::GeneralResource+ scenarion::Scenarion+
GeneralResource:
        ActiveResource
GeneralResource:
        PassiveResource
GeneralResource:
        resourceAcquire::ResourceAcquire+ resourceRelease::ResourceRelease+
Step:
        Start
Step:
        End
Step:
        ResourceAcquire
Step:
        ResourceRelease
Step:
        postPath::PathConnection prePath::PathConnection activeResource::ActiveResource
Scenarion:
        Step
Scenarion:
        step::Step+ root::Start+
Start:
        workload::Workload
End:
        EPSILON
ResourceAcquire:
        generalResource::GeneralResource
ResourceRelease:
        generalResource::GeneralResource
Workload:
        start::Start
Component:
        EPSILON
ProcessingResource:
        EPSILON
ExternalService:
        EPSILON
ActiveResource:
        ProcessingResource
ActiveResource:
        ExternalService
ActiveResource:
        step::Step+
PassiveResource:
        Component
PassiveResource:
        Component
Message:
        EPSILON
PathConnection:
        Join
PathConnection:
        Fork
PathConnection:
        Merge
PathConnection:
        Branch
PathConnection:
        Seqence
PathConnection:
        message::Message post::Step+ pre::Step+
Join:
        EPSILON
Fork:
        EPSILON
Merge:
        EPSILON
Branch:
        EPSILON
Seqence:
        EPSILON
