VisibilityKind:
        vk_public_vis::EPSILON
        vk_private_vis::EPSILON
        vk_protected_vis::EPSILON
BooleanExpression:
        expresssion::ANY
ModelElement:
        name::ANY visibility::ANY contraints::ANY+ clientDependencies::ANY+ supplierDependencies::ANY+ namespace::ANY importers::ANY+
Dependency:
        kind::ANY clients::ANY+ suppliers::ANY+
Constraint:
        body::ANY constrainedElements::ANY+
Feature:
        owner::ANY
StructuralFeature:
        type::ANY
Attribute:
        EPSILON
NameSpace:
        ownedElements::ANY+
Classifier:
        features::ANY+
Package:
        importedElements::ANY+
Class:
        EPSILON
Datatype:
        EPSILON
Subsystem:
        EPSILON
Model:
        EPSILON
