Node:
        EPSILON
Device:
        nestedNode::ANY+ name::ANY
ExecutionEnvironment:
        nestedNode::ANY+ name::ANY
Specification:
        ownedNode::ANY+ ownedCommunicationLink::ANY+
CommunicationLink:
        source::ANY target::ANY name::ANY
