Node:
        Device
Node:
        ExecutionEnvironment
Device:
        nestedNode::Node+ name::String
ExecutionEnvironment:
        nestedNode::Node+ name::String
Specification:
        ownedNode::Node+ ownedCommunicationLink::CommunicationLink+
CommunicationLink:
        source::Node target::Node name::String
String:
        STR
