Dimension:
        width::ANY heigth::ANY
Point:
        x::ANY y::ANY
BezierPoint:
        controls::ANY
Property:
        key::ANY value::ANY
DiagramElement:
        EPSILON
Reference:
        isIndividualRepresentation::ANY referenced::ANY
GraphElement:
        EPSILON
GraphEdge:
        waypoints::ANY anchors::ANY
GraphNode:
        size::ANY
GraphConnector:
        position::ANY gc_graphElement::ANY graphEdges::ANY+
DiagramLink:
        zoom::ANY viewPort::ANY dl_graphElement::ANY dl_diagram::ANY
SemanticModelBridge:
        EPSILON
Diagram:
        name::ANY zoom::ANY viewPort::ANY diagramLinks::ANY+ namespace::ANY
SimpleSemanticModelElement:
        typeInfo::ANY
UML1SemanticModelBridge:
        element::ANY
CoreSemanticModelBridge:
        element::ANY
CoreElement:
        EPSILON
ElementsElement:
        EPSILON
LeafElement:
        EPSILON
TextElement:
        text::ANY
Image:
        uri::ANY mimeType::ANY
GraphicPrimitive:
        EPSILON
Polyline:
        waypoints::ANY closed::ANY
Ellipse:
        center::ANY radiusX::ANY radiusY::ANY rotation::ANY startAngle::ANY endAngle::ANY
