DocBook:
        books::Book+
Book:
        articles::Article+
TitledElement:
        Article
TitledElement:
        Sect1
Article:
        sections_1::Sect1+
Sect1:
        paras::Para+
Para:
        content::String
