Element:
        EPSILON
DoDAFModel:
        document::ANY+ sfd::ANY+ amSpecification::ANY+ sd::ANY+ task::ANY+ iaDocument::ANY+ position::ANY+ occupation::ANY+ ad::ANY+ system::ANY+ am::ANY+ spas::ANY+ its::ANY+ orpa::ANY+ ptcn::ANY+
Document:
        type::ANY cites::ANY+ describes::ANY+ records::ANY+ isTheReferenceFor::ANY+ isThePrimaryReferenceFor::ANY+
SystemFunctionalityDescription:
        EPSILON
FunctionalSpecification:
        mayBeA::ANY
AMSpecification:
        isUsedIn::ANY+
SystemDocument:
        name::ANY description::ANY view::ANY
ArchitectureDocument:
        name::ANY description::ANY view::ANY
System:
        isDesignedToProvide::ANY+ isDescribedBy::ANY+
SystemPA:
        isDefinedUsing::ANY+
IE:
        isAssociatedWith::ANY+ isOrdinateOf::ANY+ isSubordinateOf::ANY+
AMIERole:
        defines::ANY+ isRepresentedBy::ANY+
AMIERoleGraphic:
        name::ANY description::ANY view::ANY
Input:
        isTheInputThatIsDefinedBy::ANY+ source::ANY destination::ANY information::ANY
Output:
        source::ANY destination::ANY information::ANY
InformationAssetDocument:
        name::ANY description::ANY view::ANY
AMPA:
        isOrdinateOf::ANY+ isSubordinateOf::ANY+ defines::ANY+ isRepresentedBy::ANY+
AMPAGraphic:
        name::ANY description::ANY view::ANY
PA:
        isParentFor::ANY+ isChildFor::ANY+ isIncludedIn::ANY+ isAssignedTo::ANY+ represents::ANY+ correspondsTo::ANY+ has::ANY+ isPerformedBy::ANY+
PACapability:
        name::ANY description::ANY view::ANY
AM:
        type::ANY isCitedBy::ANY+ specifies::ANY+ includes::ANY+ isUsedToDescribe::ANY+ defines::ANY+
InformationAsset:
        isCitedIn::ANY+ describes::ANY+
DataStore:
        EPSILON
SystemFunction:
        EPSILON
SystemPAStandard:
        isUsedToDefine::ANY+
InformationTechnologyStandard:
        isUsedToDefine::ANY+
LineOfBusiness:
        appliesToTask::ANY+ appliesToBS::ANY+
Task:
        levelIdentifier::ANY references::ANY cost::ANY correspondsTo::ANY+ supports::ANY+
HumanBehaviourTask:
        EPSILON
OperationalCapabilityTask:
        EPSILON
TaskMissionArea:
        hasContributionFrom::ANY+
PATask:
        EPSILON
BusinessSubfunction:
        appliesTo::ANY+
ArchitectureBusinessSubFunction:
        name::ANY description::ANY view::ANY
OperationalRolePA:
        name::ANY description::ANY view::ANY
OperationalRole:
        performs::ANY+ isPerformedByOTOR::ANY+ isPerformedByOOR::ANY+
OrganizationTypeOperationalRole:
        name::ANY description::ANY view::ANY
OrganizationOperationalRole:
        name::ANY description::ANY view::ANY
Occupation:
        mayBeCitedForOR::ANY+ mayBeCitedForPT::ANY+
PersonType:
        mayBeCitedFor::ANY+ performsTo::ANY+ can::ANY+
PersonTypeCapabilityNorm:
        name::ANY description::ANY view::ANY
Skill:
        mayBeCitedFor::ANY+
Position:
        mayBeCitedFor::ANY+
