Element:
        DoDAFModel
Element:
        Document
Element:
        SystemDocument
Element:
        ArchitectureDocument
Element:
        System
Element:
        SystemPA
Element:
        IE
Element:
        AMIERole
Element:
        AMIERoleGraphic
Element:
        InformationAssetDocument
Element:
        AMPA
Element:
        AMPAGraphic
Element:
        PA
Element:
        PACapability
Element:
        InformationAsset
Element:
        SystemPAStandard
Element:
        InformationTechnologyStandard
Element:
        LineOfBusiness
Element:
        Task
Element:
        BusinessSubfunction
Element:
        ArchitectureBusinessSubFunction
Element:
        OperationalRolePA
Element:
        OperationalRole
Element:
        OrganizationTypeOperationalRole
Element:
        OrganizationOperationalRole
Element:
        Occupation
Element:
        PersonType
Element:
        PersonTypeCapabilityNorm
Element:
        Skill
Element:
        Position
DoDAFModel:
        document::Document+ sfd::SystemFunctionalityDescription+ amSpecification::AMSpecification+ sd::SystemDocument+ task::Task+ iaDocument::InformationAssetDocument+ position::Position+ occupation::Occupation+ ad::ArchitectureDocument+ system::System+ am::AM+ spas::SystemPAStandard+ its::InformationTechnologyStandard+ orpa::OperationalRolePA+ ptcn::PersonTypeCapabilityNorm+
Document:
        SystemFunctionalityDescription
Document:
        FunctionalSpecification
Document:
        AMSpecification
Document:
        type::String cites::InformationAssetDocument+ describes::SystemDocument+ records::ArchitectureDocument+ isTheReferenceFor::IE+ isThePrimaryReferenceFor::PA+
SystemFunctionalityDescription:
        EPSILON
FunctionalSpecification:
        mayBeA::SystemDocument
AMSpecification:
        isUsedIn::FunctionalSpecification+
SystemDocument:
        name::String description::String view::String
ArchitectureDocument:
        name::String description::String view::String
System:
        isDesignedToProvide::SystemPA+ isDescribedBy::SystemDocument+
SystemPA:
        isDefinedUsing::SystemPAStandard+
IE:
        isAssociatedWith::AMIERole+ isOrdinateOf::IE+ isSubordinateOf::IE+
AMIERole:
        Input
AMIERole:
        Output
AMIERole:
        defines::AMPA+ isRepresentedBy::AMIERoleGraphic+
AMIERoleGraphic:
        name::String description::String view::String
Input:
        isTheInputThatIsDefinedBy::Output+ source::String destination::String information::String
Output:
        source::String destination::String information::String
InformationAssetDocument:
        name::String description::String view::String
AMPA:
        isOrdinateOf::AMPA+ isSubordinateOf::AMPA+ defines::AMIERole+ isRepresentedBy::AMPAGraphic+
AMPAGraphic:
        name::String description::String view::String
PA:
        DataStore
PA:
        SystemFunction
PA:
        isParentFor::PA+ isChildFor::PA+ isIncludedIn::AMPA+ isAssignedTo::SystemPA+ represents::ArchitectureBusinessSubFunction+ correspondsTo::PATask+ has::PACapability+ isPerformedBy::OperationalRolePA+
PACapability:
        name::String description::String view::String
AM:
        type::String isCitedBy::PATask+ specifies::AMSpecification+ includes::AMPA+ isUsedToDescribe::SystemFunctionalityDescription+ defines::LineOfBusiness+
InformationAsset:
        AM
InformationAsset:
        isCitedIn::InformationAssetDocument+ describes::DataStore+
DataStore:
        EPSILON
SystemFunction:
        EPSILON
SystemPAStandard:
        isUsedToDefine::InformationTechnologyStandard+
InformationTechnologyStandard:
        isUsedToDefine::SystemPAStandard+
LineOfBusiness:
        appliesToTask::Task+ appliesToBS::BusinessSubfunction+
Task:
        HumanBehaviourTask
Task:
        OperationalCapabilityTask
Task:
        TaskMissionArea
Task:
        PATask
Task:
        levelIdentifier::String references::String cost::String correspondsTo::PATask+ supports::TaskMissionArea+
HumanBehaviourTask:
        EPSILON
OperationalCapabilityTask:
        EPSILON
TaskMissionArea:
        hasContributionFrom::OperationalCapabilityTask+
PATask:
        EPSILON
BusinessSubfunction:
        appliesTo::ArchitectureBusinessSubFunction+
ArchitectureBusinessSubFunction:
        name::String description::String view::String
OperationalRolePA:
        name::String description::String view::String
OperationalRole:
        performs::OperationalRolePA+ isPerformedByOTOR::OrganizationTypeOperationalRole+ isPerformedByOOR::OrganizationOperationalRole+
OrganizationTypeOperationalRole:
        name::String description::String view::String
OrganizationOperationalRole:
        name::String description::String view::String
Occupation:
        mayBeCitedForOR::OperationalRole+ mayBeCitedForPT::PersonType+
PersonType:
        mayBeCitedFor::OperationalRole+ performsTo::PersonTypeCapabilityNorm+ can::Skill+
PersonTypeCapabilityNorm:
        name::String description::String view::String
Skill:
        mayBeCitedFor::OperationalRole+
Position:
        mayBeCitedFor::OperationalRole+
