Element:
        EPSILON
DoDAFModel:
        document::ANY+ sftm::ANY+ sd::ANY+ am::ANY+ system::ANY+ task::ANY+ capability::ANY+ capabilityDocument::ANY+ systemCapability::ANY+
Document:
        type::ANY cites::ANY+ describes::ANY+ records::ANY+ isThePrimaryReferenceFor::ANY+
SystemFunctionTraceabilityMatrix:
        isDefinedBy::ANY+
SystemFunctionTraceabilityElement:
        systemFunction::ANY operationalActivity::ANY systemProcessActivity::ANY system::ANY capability::ANY supportStatusCode::ANY
SystemDocument:
        name::ANY description::ANY view::ANY
ArchitectureDocument:
        name::ANY description::ANY view::ANY
PA:
        isParentFor::ANY+ isChildFor::ANY+ correspondsTo::ANY+ isIncludedIn::ANY+ isAssignedTo::ANY+ isSupportedBy::ANY+ isTheConsumerFor::ANY+ isTheProducerFor::ANY+
SystemFunction:
        isCitedFor::ANY+
SystemPA:
        mayBeCitedFor::ANY+ provides::ANY+ enables::ANY+
SoftwareApplicationProcedurePA:
        name::ANY description::ANY view::ANY
AM:
        type::ANY isCitedBy::ANY+ includes::ANY+
InformationAsset:
        EPSILON
AMPA:
        isOrdinateOf::ANY+ isSubordinateOf::ANY+
System:
        isDesignedToProvide::ANY+ isDescribedBy::ANY+ performs::ANY+ isUsedToAccomplish::ANY+
Task:
        levelIdentifier::ANY references::ANY cost::ANY correspondsTo::ANY+ isSupportedBy::ANY+ isTheSourceOfNeedFor::ANY+ isTheDestinationOfNeedFor::ANY+ isCitedFor::ANY+
ArchitectureTask:
        name::ANY description::ANY view::ANY
OperationalCapabilityTask:
        isAccomplishedA::ANY
SystemOperationalCapabilityTask:
        EPSILON
PATask:
        EPSILON
Capability:
        isPerformedBy::ANY+ isOrdinateFor::ANY+ isSubordinateOf::ANY+ isPerformedByNC::ANY+ isPerformedByNLC::ANY+ isPerformedBySC::ANY+ isCitedInCD::ANY+ isUsedInMICN::ANY+ isUsedInOTCN::ANY+ isAttainedFor::ANY+
CapabilityDocument:
        isCitedIn::ANY+
SystemCapability:
        isCitedIn::ANY+
NetworkCapability:
        EPSILON
NodeLinkCapability:
        EPSILON
MaterielItemCapabilityNorm:
        EPSILON
OrganizationTypeCapabilityNorm:
        EPSILON
RequiredInformationTechnologyCapability:
        EPSILON
InformationTechnologyRequirement:
        specifies::ANY+
InformationExchangeRequirement:
        EPSILON
PAExchangeRequirement:
        isCitedIn::ANY+
SupportStatusCode:
        red::EPSILON
        yellow::EPSILON
        green::EPSILON
