Element:
        DoDAFModel
Element:
        Document
Element:
        AMSpecificationElement
Element:
        PAExchangeRequirement
Element:
        ArchitectureDocument
Element:
        IE
Element:
        AMIERole
Element:
        InformationAssetDocument
Element:
        AMPA
Element:
        PACapability
Element:
        PA
Element:
        InformationAsset
Element:
        Task
Element:
        Organization
Element:
        OrganizationType
Element:
        OperationalRole
Element:
        Occupation
Element:
        PersonType
Element:
        Skill
Element:
        DOSCR
DoDAFModel:
        document::Document+ am::AM+ task::Task+ iaDocument::InformationAssetDocument+ amSpecification::AMSpecification+ doscr::DOSCR+ organizationType::OrganizationType+
Document:
        AMSpecification
Document:
        type::String cites::InformationAssetDocument+ records::ArchitectureDocument+ isTheReferenceFor::IE+ isThePrimaryReferenceFor::PA+
AMSpecification:
        isSpecifiedUsing::AMSpecificationElement+
AMSpecificationElement:
        subject::PAExchangeRequirement
PAExchangeRequirement:
        isTheSubjectOf::AMSpecificationElement+
ArchitectureDocument:
        name::String description::String view::String
IE:
        isAssociatedWith::AMIERole+ isOrdinateOf::IE+ isSubordinateOf::IE+
AMIERole:
        Control
AMIERole:
        Input
AMIERole:
        Output
AMIERole:
        Mechanism
AMIERole:
        defines::AMPA+
Control:
        source::String destination::String
Input:
        isTheInputThatIsDefinedBy::Output+ source::String destination::String information::String
Output:
        source::String destination::String information::String
Mechanism:
        MechanismSystem
Mechanism:
        MechanismReference
Mechanism:
        MechanismFacility
Mechanism:
        source::String destination::String resourceType::String
MechanismSystem:
        EPSILON
MechanismReference:
        EPSILON
MechanismFacility:
        EPSILON
InformationAssetDocument:
        name::String description::String view::String
AMPA:
        isOrdinateOf::AMPA+ isSubordinateOf::AMPA+ defines::AMIERole+
PACapability:
        name::String description::String view::String
PA:
        isTheProducerFor::PAExchangeRequirement+ isTheConsumerFor::PAExchangeRequirement+ isParentFor::PA+ isChildFor::PA+ has::PACapability+ isIncludedIn::AMPA+ correspondsTo::PATask+
AM:
        type::String specifies::AMSpecification+ includes::AMPA+ paTask::PATask+
InformationAsset:
        AM
Task:
        PATask
Task:
        levelIdentifier::String references::String cost::String
PATask:
        isCitedBy::InformationAsset
Organization:
        type::OrganizationType supplies::InformationAsset+ providesStewardshipFor::InformationAsset+ owns::InformationAsset+ develops::IE+ isCitedAs::MechanismReference+
OrganizationType:
        isTheTypeOf::Organization+ isCitedAs::MechanismReference+
OperationalRole:
        isCitedAs::MechanismReference+
Occupation:
        mayBeCitedForOR::OperationalRole+ mayBeCitedForPT::PersonType+
PersonType:
        mayBeCitedFor::OperationalRole+ can::Skill+
Skill:
        mayBeCitedFor::OperationalRole+
DOSCR:
        mayBeAn::Occupation appliesTo::PersonType+ mayBeCitedFor::OperationalRole+
