Label:
        EPSILON
SimpleLabel:
        content::ANY
ComplexLabel:
        compartments::ANY+
Compartment:
        EPSILON
VerticalCompartment:
        complexLabel::ANY compartments::ANY anchor::ANY
HorizontalCompartment:
        complexLabel::ANY compartments::ANY anchor::ANY
SimpleCompartment:
        content::ANY
Anchor:
        name::ANY source::ANY
GraphElement:
        EPSILON
Graph:
        type::ANY rankDir::ANY labeljust::ANY labelloc::ANY concentrate::ANY nodes::ANY+ boundingBox::ANY compound::ANY layers::ANY+ nodeSeparation::ANY ordering::ANY size::ANY ratio::ANY center::ANY
Layer:
        nodes::ANY+ arcs::ANY+ graph::ANY layerSeparator::ANY
Nodelike:
        EPSILON
SubGraph:
        nodes::ANY+ labelloc::ANY
Node:
        fixedSize::ANY fontname::ANY fontsize::ANY height::ANY width::ANY shape::ANY
Arc:
        EPSILON
DirectedArc:
        arrowHead::ANY headlabel::ANY taillabel::ANY arrowTail::ANY tail_lp::ANY head_lp::ANY
UndirectedArc:
        fromNode::ANY toNode::ANY layers::ANY+ constraint::ANY group::ANY minlen::ANY sameHead::ANY sameTail::ANY lhead::ANY ltail::ANY decorate::ANY
Shape:
        EPSILON
NodeShape:
        EPSILON
SimpleNodeShape:
        
PointNodeShape:
        
ComplexNodeShape:
        EPSILON
PolygonNodeShape:
        sides::ANY skew::ANY distortion::ANY isRegular::ANY orientation::ANY
MNodeShape:
        toplabel::ANY bottomlabel::ANY
RecordNodeShape:
        
ArrowShape:
        clipping::ANY isPlain::ANY size::ANY
