NamedElement:
        Assembly
NamedElement:
        Module
NamedElement:
        MemberInfo
NamedElement:
        ParameterInfo
Assembly:
        location::String imageRuntimeVersion::String evidence::String codeBase::String entryPoint::MethodInfo modules::Module+ manifestModule::Module referencedAssembly::Assembly+ manifest::ManifestResource
ManifestResource:
        content::String assembly::Assembly
Module:
        qualifiedName::String scopeName::String assembly::Assembly types::Type+
MemberInfo:
        PropertyInfo
MemberInfo:
        FieldInfo
MemberInfo:
        EventInfo
MemberInfo:
        MethodBase
MemberInfo:
        Type
PropertyInfo:
        propertyType::Type attributes::PropertyAttributes+
FieldInfo:
        fieldType::Type attributes::FieldAttributes+
EventInfo:
        isMulticast::Boolean attributes::EventAttributes eventHandlerType::Type
ParameterInfo:
        defaultValue::String position::Integer attributes::ParameterAttributes+ parameterType::Type member::MethodBase
MethodBase:
        MethodInfo
MethodBase:
        ConstructorInfo
MethodInfo:
        returnType::Type
ConstructorInfo:
        attributes::MethodAttributes+ parameters::ParameterInfo+
Type:
        namespace::String genericParameterAttributes::GenericParameterAttributes+ typeAttributes::TypeAttributes+ baseType::Type module::Module interfaces::Type+ members::MemberInfo+
EventAttributes:
        None::EPSILON
        ReservedMask::EPSILON
        RTSpecialName::EPSILON
        SpecialName::EPSILON
FieldAttributes:
        FieldAccessMask::EPSILON
        PrivateScope::EPSILON
        Private::EPSILON
        Assembly::EPSILON
        Family::EPSILON
        FamANDAssem::EPSILON
        FamORAssem::EPSILON
        Public::EPSILON
        Shared::EPSILON
        InitOnly::EPSILON
        Literal::EPSILON
        NotSerialized::EPSILON
        SpecialName::EPSILON
        PinvokeImpl::EPSILON
        ReservedMask::EPSILON
        RTSpecialName::EPSILON
        HasFieldMarshal::EPSILON
        HasDefault::EPSILON
        HasFieldRVA::EPSILON
        Static::EPSILON
GenericParameterAttributes:
        HasElementType::EPSILON
        Abstract::EPSILON
        AnsiClass::EPSILON
        AutoClass::EPSILON
        AutoLayout::EPSILON
        ByRef::EPSILON
        Class::EPSILON
        COMObject::EPSILON
        Contextful::EPSILON
        Enum::EPSILON
        ExplicitLayout::EPSILON
        Import::EPSILON
        Interface::EPSILON
        LayoutSequential::EPSILON
        MarshalByRef::EPSILON
        NestedAssembly::EPSILON
        NestedFamADNAssem::EPSILON
        NestedFamily::EPSILON
        NestedFamORAssem::EPSILON
        NestedPrivate::EPSILON
        NestedPublic::EPSILON
        NotPublic::EPSILON
        Pointer::EPSILON
        Primitive::EPSILON
        Public::EPSILON
        Sealed::EPSILON
        Serializable::EPSILON
        SpecialName::EPSILON
        UnicodeClass::EPSILON
        ValueType::EPSILON
MemberTypes:
        Constructor::EPSILON
        Event::EPSILON
        Field::EPSILON
        Method::EPSILON
        Property::EPSILON
        TypeInfo::EPSILON
        Custom::EPSILON
        NestedType::EPSILON
        All::EPSILON
MethodAttributes:
        Abstract::EPSILON
        Assembly::EPSILON
        ChekedAccessOnOverride::EPSILON
        FamADNAssem::EPSILON
        Family::EPSILON
        FamORAssem::EPSILON
        Final::EPSILON
        HasSecurity::EPSILON
        HideBySig::EPSILON
        MemberAccessMask::EPSILON
        NewSlot::EPSILON
        PInvokeImpl::EPSILON
        Private::EPSILON
        PrivateScope::EPSILON
        Public::EPSILON
        RequiredSecObject::EPSILON
        ReservedMask::EPSILON
        ReuseSlot::EPSILON
        RTSpecialName::EPSILON
        SpecialName::EPSILON
        Static::EPSILON
        UnmanagedExport::EPSILON
        Virtual::EPSILON
        VtableLayoutMask::EPSILON
ParameterAttributes:
        HasDefault::EPSILON
        HasDefaultMArshal::EPSILON
        In::EPSILON
        Lcid::EPSILON
        None::EPSILON
        Optional::EPSILON
        Out::EPSILON
        Reserved3::EPSILON
        Reserved4::EPSILON
        ReservedMask::EPSILON
        RetVal::EPSILON
PropertyAttributes:
        NotSupported::EPSILON
        Optional::EPSILON
        Read::EPSILON
        Required::EPSILON
        Write::EPSILON
TypeAttributes:
        Abstract::EPSILON
        AnsiClass::EPSILON
        AutoClass::EPSILON
        AutoLayout::EPSILON
        BeforFieldInit::EPSILON
        Class::EPSILON
        ClassSemanticsMask::EPSILON
        ExplicitLayout::EPSILON
        HasSecutity::EPSILON
        Import::EPSILON
        Interface::EPSILON
        LayoutMask::EPSILON
        NestedAssembly::EPSILON
        NestedFamADNAssem::EPSILON
        NestedFamily::EPSILON
        NestedFamORAssem::EPSILON
        NestedPrivate::EPSILON
        NestedPublic::EPSILON
        NotPublic::EPSILON
        Public::EPSILON
        ReservedMask::EPSILON
        RTSpecialName::EPSILON
        Sealed::EPSILON
        SequentialLayout::EPSILON
        Serializable::EPSILON
        SpecialName::EPSILON
        StringFormatMask::EPSILON
        UnicodeClass::EPSILON
        VisibilityMask::EPSILON
