NamedElement:
        EPSILON
Assembly:
        location::ANY imageRuntimeVersion::ANY evidence::ANY codeBase::ANY entryPoint::ANY modules::ANY+ manifestModule::ANY referencedAssembly::ANY+ manifest::ANY
ManifestResource:
        content::ANY assembly::ANY
Module:
        qualifiedName::ANY scopeName::ANY assembly::ANY types::ANY+
MemberInfo:
        EPSILON
PropertyInfo:
        propertyType::ANY attributes::ANY+
FieldInfo:
        fieldType::ANY attributes::ANY+
EventInfo:
        isMulticast::ANY attributes::ANY eventHandlerType::ANY
ParameterInfo:
        defaultValue::ANY position::ANY attributes::ANY+ parameterType::ANY member::ANY
MethodBase:
        EPSILON
MethodInfo:
        returnType::ANY
ConstructorInfo:
        attributes::ANY+ parameters::ANY+
Type:
        namespace::ANY genericParameterAttributes::ANY+ typeAttributes::ANY+ baseType::ANY module::ANY interfaces::ANY+ members::ANY+
EventAttributes:
        None::EPSILON
        ReservedMask::EPSILON
        RTSpecialName::EPSILON
        SpecialName::EPSILON
FieldAttributes:
        FieldAccessMask::EPSILON
        PrivateScope::EPSILON
        Private::EPSILON
        Assembly::EPSILON
        Family::EPSILON
        FamANDAssem::EPSILON
        FamORAssem::EPSILON
        Public::EPSILON
        Shared::EPSILON
        InitOnly::EPSILON
        Literal::EPSILON
        NotSerialized::EPSILON
        SpecialName::EPSILON
        PinvokeImpl::EPSILON
        ReservedMask::EPSILON
        RTSpecialName::EPSILON
        HasFieldMarshal::EPSILON
        HasDefault::EPSILON
        HasFieldRVA::EPSILON
        Static::EPSILON
GenericParameterAttributes:
        HasElementType::EPSILON
        Abstract::EPSILON
        AnsiClass::EPSILON
        AutoClass::EPSILON
        AutoLayout::EPSILON
        ByRef::EPSILON
        Class::EPSILON
        COMObject::EPSILON
        Contextful::EPSILON
        Enum::EPSILON
        ExplicitLayout::EPSILON
        Import::EPSILON
        Interface::EPSILON
        LayoutSequential::EPSILON
        MarshalByRef::EPSILON
        NestedAssembly::EPSILON
        NestedFamADNAssem::EPSILON
        NestedFamily::EPSILON
        NestedFamORAssem::EPSILON
        NestedPrivate::EPSILON
        NestedPublic::EPSILON
        NotPublic::EPSILON
        Pointer::EPSILON
        Primitive::EPSILON
        Public::EPSILON
        Sealed::EPSILON
        Serializable::EPSILON
        SpecialName::EPSILON
        UnicodeClass::EPSILON
        ValueType::EPSILON
MemberTypes:
        Constructor::EPSILON
        Event::EPSILON
        Field::EPSILON
        Method::EPSILON
        Property::EPSILON
        TypeInfo::EPSILON
        Custom::EPSILON
        NestedType::EPSILON
        All::EPSILON
MethodAttributes:
        Abstract::EPSILON
        Assembly::EPSILON
        ChekedAccessOnOverride::EPSILON
        FamADNAssem::EPSILON
        Family::EPSILON
        FamORAssem::EPSILON
        Final::EPSILON
        HasSecurity::EPSILON
        HideBySig::EPSILON
        MemberAccessMask::EPSILON
        NewSlot::EPSILON
        PInvokeImpl::EPSILON
        Private::EPSILON
        PrivateScope::EPSILON
        Public::EPSILON
        RequiredSecObject::EPSILON
        ReservedMask::EPSILON
        ReuseSlot::EPSILON
        RTSpecialName::EPSILON
        SpecialName::EPSILON
        Static::EPSILON
        UnmanagedExport::EPSILON
        Virtual::EPSILON
        VtableLayoutMask::EPSILON
ParameterAttributes:
        HasDefault::EPSILON
        HasDefaultMArshal::EPSILON
        In::EPSILON
        Lcid::EPSILON
        None::EPSILON
        Optional::EPSILON
        Out::EPSILON
        Reserved3::EPSILON
        Reserved4::EPSILON
        ReservedMask::EPSILON
        RetVal::EPSILON
PropertyAttributes:
        NotSupported::EPSILON
        Optional::EPSILON
        Read::EPSILON
        Required::EPSILON
        Write::EPSILON
TypeAttributes:
        Abstract::EPSILON
        AnsiClass::EPSILON
        AutoClass::EPSILON
        AutoLayout::EPSILON
        BeforFieldInit::EPSILON
        Class::EPSILON
        ClassSemanticsMask::EPSILON
        ExplicitLayout::EPSILON
        HasSecutity::EPSILON
        Import::EPSILON
        Interface::EPSILON
        LayoutMask::EPSILON
        NestedAssembly::EPSILON
        NestedFamADNAssem::EPSILON
        NestedFamily::EPSILON
        NestedFamORAssem::EPSILON
        NestedPrivate::EPSILON
        NestedPublic::EPSILON
        NotPublic::EPSILON
        Public::EPSILON
        ReservedMask::EPSILON
        RTSpecialName::EPSILON
        Sealed::EPSILON
        SequentialLayout::EPSILON
        Serializable::EPSILON
        SpecialName::EPSILON
        StringFormatMask::EPSILON
        UnicodeClass::EPSILON
        VisibilityMask::EPSILON
