NamedElement:
        EPSILON
LoadedElement:
        EPSILON
Namespace:
        EPSILON
DomainModel:
        classifiers::ANY+ types::ANY+
Classifier:
        EPSILON
Class:
        isSerializationRoot::ANY
Relationship:
        isEmbedding::ANY roles::ANY
Role:
        min::ANY max::ANY isUnbounded::ANY accepts::ANY isOrdered::ANY isNavigableFrom::ANY isPropertyGenerator::ANY source::ANY type::ANY relation::ANY
ValueProperty:
        owner::ANY type::ANY
Type:
        EPSILON
SimpleType:
        EPSILON
EnumerationLiteral:
        value::ANY
Enumeration:
        literals::ANY+
