Model:
        domainModel::ANY contents::ANY+
Element:
        EPSILON
ModelElement:
        parentLink::ANY properties::ANY+ embeddinglinks::ANY+ referencelinks::ANY+
ModelElementLink:
        links::ANY+
EmbeddingLink:
        owner::ANY elements::ANY+
ReferenceLink:
        owner::ANY modelElement::ANY roles::ANY
NamedElement:
        EPSILON
Property:
        owner::ANY value::ANY
Role:
        element::ANY owner::ANY
Value:
        EPSILON
IntegerValue:
        value::ANY
DoubleValue:
        value::ANY
BooleanValue:
        value::ANY
StringValue:
        value::ANY
