Occurence:
        zeroOrOne::EPSILON
        zeroOrMore::EPSILON
        oneOrMore::EPSILON
        one::EPSILON
OtherAttributeTypeEnum:
        cdata::EPSILON
        id::EPSILON
        idref::EPSILON
        entityType::EPSILON
        entities::EPSILON
        nmtoken::EPSILON
        nmtakens::EPSILON
TypeDescription:
        EPSILON
Notation:
        content::ANY
Entity:
        content::ANY isInternal::ANY
Element:
        EPSILON
AnyElement:
        
RestrictedElement:
        content::ANY
ElementContent:
        EPSILON
Mixed:
        elements::ANY
Children:
        EPSILON
Sequence:
        children::ANY
Leaf:
        elementName::ANY
Choice:
        childrenChoice::ANY
AttributeList:
        containsAttributes::ANY+
AttributeDescription:
        EPSILON
NoDefaultValue:
        isRequired::ANY
DefaultValue:
        value::ANY isFixed::ANY
AttributeType:
        EPSILON
Enumeration:
        values::ANY
OtherAttributeType:
        type::ANY
