String:
        STR
Boolean:
        "true"
        "false"
Integer:
        INT
State:
        name::String isStart::Boolean isEnd::Boolean isFail::Boolean incoming::Transition+ outGoing::Transition+ formalParam::Parameter+
Transition:
        transProb::String+ to::State from::State
Parameter:
        name::String+ type::String+ state::State
