FCMSource:
        EAISource
FCMSource:
        EAISource
EAISource:
        resources::EAIResource+
FCMSink:
        EAISink
FCMSink:
        EAISink
EAISink:
        resources::EAIResource+
EAIResource:
        EAIQueue
EAIResource:
        EAIQueue
EAIQueue:
        maxLength::Integer name::String
