Application:
        name::String version::String author::String extensionPoints::ExtensionPoint+
ExtensionPoint:
        name::String id::String application::Application descriptions::Description+ plugIn::PlugIn
Description:
        xmlSchema::String extensionPoints::ExtensionPoint+
Extension:
        name::String id::String isConfiguredInto::ExtensionPoint
PlugIn:
        id::String displayableName::String version::String supplier::String configures::Extension+ extensionPoints::ExtensionPoint+ requires::PlugIn+ uses::Librairy+
Librairy:
        name::String plugIn::PlugIn classes::Class+
Class:
        name::String librairy::Librairy
