LaunchConfiguration:
        type::String attributes::Attribute+
Attribute:
        StringAttribute
Attribute:
        BooleanAttribute
Attribute:
        MapAttribute
Attribute:
        ListAttribute
StringAttribute:
        MapEntry
StringAttribute:
        value::String
BooleanAttribute:
        value::Boolean
MapAttribute:
        entries::MapEntry+
MapEntry:
        mapAttribute::MapAttribute
ListAttribute:
        entries::ListEntry+
ListEntry:
        listAttribute::ListAttribute value::String
