ExecutionGraph:
        node::Node+ nodeNested::Node
Node:
        Start
Node:
        End
Node:
        Control
Node:
        Basic
Node:
        predecessor::Node+ successor::Node+ executionGraph::ExecutionGraph nested::ExecutionGraph+
Start:
        EPSILON
End:
        EPSILON
Control:
        Branch
Control:
        Loop
Control:
        Fork
Control:
        Join
Control:
        Acquire
Control:
        Release
Control:
        Split
Control:
        Branch
        Loop
        Fork
        Join
        Acquire
        Release
        Split
Basic:
        EPSILON
Branch:
        EPSILON
Loop:
        EPSILON
Fork:
        EPSILON
Join:
        EPSILON
Acquire:
        EPSILON
Release:
        EPSILON
Split:
        EPSILON
