ExecutionGraph:
        node::ANY+ nodeNested::ANY
Node:
        predecessor::ANY+ successor::ANY+ executionGraph::ANY nested::ANY+
Start:
        EPSILON
End:
        EPSILON
Control:
        EPSILON
Basic:
        EPSILON
Branch:
        EPSILON
Loop:
        EPSILON
Fork:
        EPSILON
Join:
        EPSILON
Acquire:
        EPSILON
Release:
        EPSILON
Split:
        EPSILON
