RoutingChain:
        queuingNetwork::ANY+
QueuingNetwork:
        center::ANY+ workLoad::ANY
ExecutionGraph:
        nodeNested::ANY node::ANY+
Center:
        node::ANY queuingNetwork::ANY
Node:
        nested::ANY executionGraph::ANY demand::ANY+
Special:
        EPSILON
ActiveCenter:
        EPSILON
PassiveCenter:
        EPSILON
Source:
        EPSILON
Sink:
        EPSILON
Fork:
        EPSILON
Join:
        EPSILON
Split:
        EPSILON
Allocate:
        EPSILON
Release:
        EPSILON
