Node:
        description::ANY preliminary::ANY object::ANY attributes::ANY+ no_dst::ANY+ nx_dst::ANY+ cn_dst::ANY+
Attribute:
        description::ANY editable::ANY key::ANY value::ANY name::ANY node::ANY
Root:
        EPSILON
Child:
        cn_src::ANY+ cx_src::ANY+ co_src::ANY+
XORGroup:
        preliminary::ANY name::ANY nx_src::ANY+ cx_dst::ANY+
ORGroup:
        preliminary::ANY name::ANY no_src::ANY+ co_dst::ANY+
