Project:
        name::String company::String viewDate::Date viewIndex::Date ganttDividerLocation::Integer ressourceDividerLocation::Integer webLink::String tasks::Tasks ressources::Ressource+ allocations::Allocation+
Tasks:
        color::String tasks::Task+
Task:
        id::String name::String meeting::Boolean color::String expand::Boolean complete::Integer duration::Integer priority::Integer start::Date depends::Depend+
Depend:
        id::String type::Integer difference::Integer hardness::String task::Task
Ressource:
        Id::String name::String fonction::String contact::String phone::String
Date:
        year::Integer month::Integer day::Integer
Allocation:
        taskId::String ressourceId::String name::String function::String responsible::Boolean load::Integer
Vacation:
        EPSILON
Description:
        EPSILON
Previous:
        EPSILON
