LocatedElement:
        EPSILON
Outline:
        extension::ANY nodes::ANY+
Node:
        name::ANY label::ANY icon::ANY outline::ANY mapping::ANY+
Label:
        label::ANY methodCall::ANY labelSuite::ANY+
LabelSuite:
        label::ANY methodCall::ANY
Map:
        mapString::ANY
