LocatedElement:
        Outline
LocatedElement:
        Node
LocatedElement:
        Label
LocatedElement:
        LabelSuite
LocatedElement:
        Map
Outline:
        extension::String nodes::Node+
Node:
        name::String label::Label icon::String outline::Outline mapping::Map+
Label:
        label::String methodCall::String labelSuite::LabelSuite+
LabelSuite:
        label::String methodCall::String
Map:
        mapString::String
