Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
GeoTransfos:
        name::String transfos::GeoTransfo+
GeoTransfo:
        name::String freeze::Boolean subGeoTransfos::GeoTransfo+ superGeoTransfo::GeoTransfo params::Param+
Param:
        name::String param::Double geoTransfo::GeoTransfo
