LocatedElement:
        EPSILON
NamedElement:
        EPSILON
Grafcet:
        elements::ANY+ connections::ANY+
Element:
        EPSILON
Step:
        isInitial::ANY isActive::ANY action::ANY incomingConnections::ANY+ outgoingConnections::ANY+
Transition:
        condition::ANY incomingConnections::ANY+ outgoingConnections::ANY+
Connection:
        EPSILON
StepToTransition:
        from::ANY to::ANY
TransitionToStep:
        from::ANY to::ANY
