LocatedElement:
        EPSILON
Root:
        keys::ANY+ graphs::ANY+
Element:
        id::ANY datas::ANY+
Key:
        for::ANY attrName::ANY type::ANY defValue::ANY
Graph:
        contents::ANY+ edgeDefault::ANY
Edge:
        source::ANY target::ANY sourceport::ANY targetport::ANY
HyperEdge:
        endpoints::ANY+
Node:
        subgraph::ANY ports::ANY+
Port:
        name::ANY
EndPoint:
        node::ANY port::ANY
Data:
        key::ANY value::ANY
ElemType:
        edge::EPSILON
        node::EPSILON
        graph::EPSILON
AttrType:
        double::EPSILON
        string::EPSILON
        integer::EPSILON
        boolean::EPSILON
EdgeType:
        directed::EPSILON
        undirected::EPSILON
