LocatedElement:
        NamedElement
NamedElement:
        Graph
NamedElement:
        GraphElement
Graph:
        type::String rankDir::String dim::Integer contents::GraphElement+
GraphElement:
        DirectedArc
GraphElement:
        Constraint
Node:
        shape::String style::String
DirectedArc:
        sourceNode::String sourcePart::String targetNode::String targetPart::String shape::String
Constraint:
        val::String refers::String+
SubGraph:
        EPSILON
