LocatedElement:
        EPSILON
Named:
        EPSILON
GUI:
        guiTabs::ANY+
Tab:
        title::ANY gui::ANY group::ANY
Composant:
        EPSILON
Layout:
        default::EPSILON
        horizontal::EPSILON
        vertical::EPSILON
Group:
        title::ANY layout::ANY description::ANY tabGroup::ANY composants::ANY+
Label:
        text::ANY
TextArea:
        text::ANY nbRows::ANY
Table:
        tabColumns::ANY+
Column:
        title::ANY columnTab::ANY
ComboBox:
        listRows::ANY+
Row:
        rowList::ANY text::ANY listItems::ANY+
Item:
        itemList::ANY text::ANY
Button:
        title::ANY
