Place:
        net::ANY out::ANY+ in::ANY+ token::ANY+
Transition:
        net::ANY in::ANY+ out::ANY+
Net:
        place::ANY+ transition::ANY+
Arc:
        EPSILON
PTArc:
        dst::ANY src::ANY
TPArc:
        src::ANY dst::ANY
Token:
        place::ANY
