Thing:
        Person
Thing:
        Role
Thing:
        Detail
Thing:
        Review_expertise
Thing:
        Organizer
Thing:
        Review_preference
Thing:
        date
Thing:
        URL
Thing:
        conference_setup
Thing:
        Contribution
Thing:
        Event
Thing:
        Place
Thing:
        City
Thing:
        Person
        Role
        Detail
        Review_expertise
        Organizer
        Review_preference
        date
        URL
        conference_setup
        Contribution
        Event
        Place
        City
Meta-Reviewer:
        EPSILON
Reviewer:
        Meta-Reviewer
Reviewer:
        invites_co-reviewers::Reviewer invited_by::Reviewer has_a_review_reference_or_expertise::Thing+ writes_review::Review hasReviewHistory::PersonalReviewHistory assignedByAdministrator::Administrator adjustBid::Bid readPaper::Paper hasBeenAssigned::Paper writeReview::Review assignExternalReviewer::ExternalReviewer
Decision:
        Acceptance
Decision:
        Rejection
Decision:
        Acceptance
        Rejection
Person:
        ConferenceMember
Person:
        ExternalReviewer
Person:
        User
Person:
        Conference_participant
Person:
        Conference_contributor
Person:
        Committee_member
Person:
        Conference_applicant
Person:
        Track-workshop_chair
Person:
        Scholar
Person:
        Participant
Person:
        Member_PC
Person:
        Chair_PC
Person:
        Science_Worker
Person:
        Assistant
Person:
        Volunteer
Person:
        chair
Person:
        participant
Person:
        ConferenceChair
Person:
        Attendee
Person:
        SessionChair
Person:
        TPCMember
Person:
        Paper_Author
Person:
        Conference_Participant
Person:
        Agency_Staff_Member
Person:
        Possible_Reviewer
Person:
        Student
Person:
        Delegate
Person:
        Sponsor
Person:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String employedBy::Organization hasHomePage::String hasSurname::String hasFax::String hasFirstName::String hasPhone::String hasEmail::String attendeeAt::ConferenceEvent isMemberOf::Conference hasFirstName::String hasBiography::String hasLastName::String authorOf::Document prepare::Item occupy::Presenter_city+ is_present_in::Thing+ write::Item obtain::Item send::Item speak_in::Thing+ pay::Money sign::Item is_present::Time give::Thing+ need::Item hasConflictOfInterest::Document email::String
Preference:
        EPSILON
ProgramCommittee:
        hasProgramCommitteeMember::ProgramCommitteeMember
Bid:
        adjustedBy::Reviewer
Conference:
        Conference_volume
Conference:
        TwoLevelConference
Conference:
        SingleLevelConference
Conference:
        is_in_phase::phase_of_conference has_program::program hasMember::Person hasName::String endDate::dateTime paperDueOn::dateTime registrationDueOn::dateTime manuscriptDueOn::dateTime startDate::dateTime hasCountry::Country hasConferenceMember::ConferenceMember paperAssignmentFinalizedBy::Administrator reviewCriteriaEnteredBy::Administrator paperAssignmentToolsRunBy::Administrator virtualMeetingEnabledBy::Administrator hardcopyMailingManifestsPrintedBy::Administrator detailsEnteredBy::Administrator reviewerBiddingStartedBy::Administrator date::date reviewsPerPaper::Integer logoURL::anyURI acceptsHardcopySubmissions::Boolean siteURL::anyURI
ConferenceChair:
        EPSILON
ConferenceMember:
        memberOfConference::Conference
AssociatedChair:
        EPSILON
ProgramCommitteeMember:
        memberOfProgramCommittee::ProgramCommittee maxPapers::Integer addedBy::Administrator
AuthorNotReviewer:
        EPSILON
SubjectArea:
        EPSILON
ExternalReviewer:
        assignedByReviewer::Reviewer
Chairman:
        EPSILON
ProgramCommitteeChair:
        endReview::Review
Acceptance:
        EPSILON
Rejection:
        EPSILON
Co-author:
        co-writePaper::Paper
PaperAbstract:
        EPSILON
PaperFullVersion:
        EPSILON
Meta-Review:
        EPSILON
Account:
        registred_by::Person
Inforamtion:
        EPSILON
User:
        Committee
User:
        recieve::Document create::Thing+ submit::Document
Role:
        Admin_Role
Role:
        Author_Role
Role:
        Committe_Role
Role:
        Head_Role
Role:
        Reviewer_Role
Role:
        assigned_by::Administrator
Help_Request:
        Misc
Help_Request:
        Feature_Request
Help_Request:
        Assistance
Help_Request:
        Misc
        Feature_Request
        Assistance
Symposium:
        EPSILON
Administrator:
        finalizePaperAssignment::Conference runPaperAssignmentTools::Conference enableVirtualMeeting::Conference startReviewerBidding::Conference assignReviewer::Reviewer rejectPaper::Paper enterConferenceDetails::Conference printHardcopyMailingManifests::Conference setMaxPapers::ProgramCommitteeMember enterReviewCriteria::Conference acceptPaper::Paper addProgramCommitteeMember::ProgramCommitteeMember approve::Event assign::Role
Invited_Paper:
        EPSILON
Admin_Role:
        EPSILON
Paper_Typologies:
        EPSILON
Event_Setup:
        Paper_Typologies
Event_Setup:
        Review_Form
Event_Setup:
        Submission_Template
Event_Setup:
        Event_Tracks
Event_Setup:
        Research_Topic
Event_Setup:
        Email_Template
Event_Setup:
        define::Event
Event_URL:
        concerned::Event
Notification_Email:
        EPSILON
Email:
        Notification_Email
Email:
        Group_Email
Email:
        Approval_Email
Email:
        Rejection_Email
Email:
        Notification_Email
        Group_Email
        Approval_Email
        Rejection_Email
Short_Paper:
        EPSILON
Author_Role:
        EPSILON
Preview:
        EPSILON
Review_Form:
        Preview
Review_Form:
        Review_Form_Setup
Review_Form:
        Preview
        Review_Form_Setup
Committe_Role:
        EPSILON
Group_Email:
        EPSILON
Submission_Template:
        EPSILON
Review_Form_Setup:
        EPSILON
Misc:
        EPSILON
Event_Creation:
        EPSILON
Approval_Email:
        confirm::Event
Rejection_Email:
        EPSILON
Submission:
        Final_manuscript
Submission:
        Initial_manuscipt
Submission:
        Final_manuscript
        Initial_manuscipt
Template:
        EPSILON
Feature_Request:
        EPSILON
Event_Tracks:
        EPSILON
Request:
        Help_Request
Request:
        Help_Request
Head_Role:
        EPSILON
Detail:
        EPSILON
Corresponding_Author:
        EPSILON
Reviewer_Role:
        EPSILON
Event_Approval:
        EPSILON
Registration:
        EPSILON
Full_Paper:
        EPSILON
Research_Topic:
        EPSILON
Description:
        EPSILON
Assistance:
        EPSILON
Email_Template:
        EPSILON
Conference_participant:
        Passive_conference_participant
Conference_participant:
        Passive_conference_participant
Active_conference_participant:
        gives_presentations::Presentation
Passive_conference_participant:
        EPSILON
Review_expertise:
        has_a_submitted_contribution::Submitted_contribution has_an_expertise::EEnum
Submitted_contribution:
        Reviewed_contribution
Submitted_contribution:
        has_a_review_expertise::Review_expertise
Regular_author:
        Contribution_1th-author
Regular_author:
        Contribution_co-author
Regular_author:
        Contribution_1th-author
        Contribution_co-author
Conference_contributor:
        Regular_author
Conference_contributor:
        Invited_speaker
Conference_contributor:
        Regular_author
        Invited_speaker
Contribution_1th-author:
        EPSILON
Contribution_co-author:
        EPSILON
Conference_contribution:
        Poster
Conference_contribution:
        Written_contribution
Conference_contribution:
        is_submitted_at::Conference_volume
Co-chair:
        was_a_committe_co-chair_of::Committee
Committee:
        Program_committee
Committee:
        Organizing_committee
Committee:
        Steering_committee
Committee:
        has_members::Committee_member was_a_committee_of::Conference_volume has_a_committee_co-chair::Co-chair has_a_committee_chair::Chair
Committee_member:
        Co-chair
Committee_member:
        Chair
Committee_member:
        was_a_member_of::Committee
Abstract:
        Tutorial_Abstract
Abstract:
        Invited_Talk_Abstract
Abstract:
        part_of_article::article is_the_1th_part_of::Thing+
Extended_abstract:
        EPSILON
Important_dates:
        is_an_abstract_submission_date::date is_a_full_paper_submission_date::date is_an_ending_date::date is_a_date_of_acceptance_announcement::date is_a_date_of_camera_ready_paper_submission::date is_a_starting_date::date belong_to_a_conference_volume::Conference_volume
Invited_speaker:
        EPSILON
Conference_proceedings:
        has_an_ISBN::String has_a_publisher::Publisher has_a_volume::String
Information_for_participants:
        EPSILON
Conference_document:
        Conference_contribution
Conference_document:
        Information_for_participants
Conference_document:
        Call_for_paper
Conference_document:
        Conference_announcement
Conference_document:
        Call_for_participation
Conference_document:
        Conference_www
Conference_document:
        has_authors::Person has_a_date_of_issue::date
Regular_contribution:
        Extended_abstract
Regular_contribution:
        Extended_abstract
Poster:
        EPSILON
Written_contribution:
        Submitted_contribution
Written_contribution:
        Regular_contribution
Written_contribution:
        Submitted_contribution
        Regular_contribution
Conference_applicant:
        Registeered_applicant
Conference_applicant:
        Registeered_applicant
Camera_ready_contribution:
        EPSILON
Accepted_contribution:
        Camera_ready_contribution
Accepted_contribution:
        Camera_ready_contribution
Program_committee:
        was_a_program_committee_of::Conference_volume
Organizing_committee:
        was_an_organizing_committee_of::Conference_volume
Steering_committee:
        was_a_steering_committee_of::Conference_volume
Conference_volume:
        has_parts::Conference_part has_workshops::Workshop has_tracks::Track has_tutorials::Tutorial has_a_commtitee::Committee has_a_steering_committee::Steering_committee has_an_organizing_committee::Organizing_committee has_important_dates::Important_dates has_contributions::Conference_contribution has_a_location::String has_a_program_committee::Program_committee
Call_for_paper:
        EPSILON
Conference_announcement:
        EPSILON
Invited_talk:
        EPSILON
Conference_part:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair
Chair:
        was_a_committee_chair_of::Committee
Tutorial:
        EPSILON
Rejected_contribution:
        EPSILON
Reviewed_contribution:
        Accepted_contribution
Reviewed_contribution:
        Rejected_contribution
Reviewed_contribution:
        has_a_review::Review
Late_paid_applicant:
        EPSILON
Paid_applicant:
        Late_paid_applicant
Paid_applicant:
        Early_paid_applicant
Paid_applicant:
        Late_paid_applicant
        Early_paid_applicant
Early_paid_applicant:
        EPSILON
Organizer:
        EPSILON
Call_for_participation:
        EPSILON
Publisher:
        issues::Conference_proceedings
Registeered_applicant:
        Paid_applicant
Registeered_applicant:
        Paid_applicant
Track-workshop_chair:
        was_a_track-workshop_chair_of::Conference_part
Conference_www:
        has_a_URL::String
Conference_fees:
        EPSILON
Review_preference:
        has_a_topic_or_a_submission_contribution::Thing+ has_a_degree::Integer
EEnum:
        male::EPSILON
        female::EPSILON
        high::EPSILON
        medium::EPSILON
        low::EPSILON
        very high::EPSILON
Accepted_Paper:
        EPSILON
Rejected_Paper:
        EPSILON
Undecided_Paper:
        EPSILON
Manual_Paper_Assignment:
        manually_assign_paper::Program_Committee_member+
Program_Committee_member:
        Senior_Program_Committee_member
Program_Committee_member:
        Regular_Program_Committee_member
Program_Committee_member:
        Senior_Program_Committee_member
        Regular_Program_Committee_member
paper_assignment:
        Manual_Paper_Assignment
paper_assignment:
        Automatic_Paper_Assignment
paper_assignment:
        assign_paper::Program_Committee_member is_performed_by::human
intensity:
        EPSILON
start_date_of_camera-ready_submission:
        EPSILON
camera-ready_submission_date:
        start_date_of_camera-ready_submission
camera-ready_submission_date:
        end_date_of_camera-ready_submission
camera-ready_submission_date:
        start_date_of_camera-ready_submission
        end_date_of_camera-ready_submission
date_of_notification:
        EPSILON
date:
        camera-ready_submission_date
date:
        date_of_notification
date:
        abstract_submission_date
date:
        date_of_conference
date:
        full_paper_submission_date
date:
        camera-ready_submission_date
        date_of_notification
        abstract_submission_date
        date_of_conference
        full_paper_submission_date
Contact_Person:
        EPSILON
bidding_of_reviewer:
        is_performed_by::human
URL:
        Event_URL
URL:
        Senior_Reviewer_URL
URL:
        Chair_URL
URL:
        Contact_Person_URL
URL:
        Regular_Reviewer_URL
URL:
        Event_URL
        Senior_Reviewer_URL
        Chair_URL
        Contact_Person_URL
        Regular_Reviewer_URL
conference_setup:
        sets_member::human is_made_by::human includes_topic::Topic sets_date::date sets_URL::URL
human:
        Program_Committee_member
human:
        Contact_Person
human:
        Program_Committee_Chair
human:
        is_author_of::article performs_activity::Activity is_employed_in::institute has_topic_of_interest::Topic supervises::Activity e-mail::String last_name::String first_name::String
managing_of_conference_process:
        EPSILON
Program_Committee_Chair:
        EPSILON
reviewing_proces:
        lower_tier_reviewing_process
reviewing_proces:
        upper_tier_reviewing_process
reviewing_proces:
        lower_tier_reviewing_process
        upper_tier_reviewing_process
end_date_of_camera-ready_submission:
        EPSILON
abstract_submission_date:
        end_date_of_abstract_submission
abstract_submission_date:
        start_date_of_abstract_submission
abstract_submission_date:
        end_date_of_abstract_submission
        start_date_of_abstract_submission
group_email:
        EPSILON
Senior_Reviewer_URL:
        EPSILON
notification:
        has_result::article is_performed_by::human
notification_email:
        acceptance_notification_email
notification_email:
        rejection_notification_email
notification_email:
        acceptance_notification_email
        rejection_notification_email
Chair_URL:
        EPSILON
abstract_of_paper:
        EPSILON
submission_process:
        is_performed_by::human
lower_tier_reviewing_process:
        EPSILON
start_date_of_conference:
        EPSILON
date_of_conference:
        start_date_of_conference
date_of_conference:
        end_date_of_conference
date_of_conference:
        start_date_of_conference
        end_date_of_conference
Senior_Program_Committee_member:
        supervises::Activity
end_date_of_abstract_submission:
        EPSILON
phase_of_conference:
        EPSILON
Regular_Program_Committee_member:
        EPSILON
start_date_of_full_paper_submission:
        EPSILON
full_paper_submission_date:
        start_date_of_full_paper_submission
full_paper_submission_date:
        end_date_of_full_paper_submission
full_paper_submission_date:
        start_date_of_full_paper_submission
        end_date_of_full_paper_submission
start_date_of_abstract_submission:
        EPSILON
end_date_of_conference:
        EPSILON
review_form:
        is_created_in::Activity
Automatic_Paper_Assignment:
        automatically_assign_paper::Program_Committee_member+
institute:
        EPSILON
classification:
        EPSILON
summary_of_reviews:
        is_created_in::Activity
upper_tier_reviewing_process:
        is_performed_by::human
end_date_of_full_paper_submission:
        EPSILON
acceptance_notification_email:
        EPSILON
rejection_notification_email:
        EPSILON
Contact_Person_URL:
        EPSILON
Regular_Reviewer_URL:
        EPSILON
Trip:
        EPSILON
Banquet:
        EPSILON
Reception:
        EPSILON
Social_event:
        Trip
Social_event:
        Banquet
Social_event:
        Reception
Social_event:
        Trip
        Banquet
        Reception
Contribution:
        Poster
Contribution:
        Short_paper
Contribution:
        writtenBy::Author dealsWith::Topic remark::String abstract::String contactEmail::String hasKeyword::String hasTitle::String
Country:
        EPSILON
Company:
        EPSILON
University:
        EPSILON
Scholar:
        studyAt::University
Poster:
        EPSILON
Short_paper:
        EPSILON
Reviewing_results_event:
        EPSILON
Administrative_event:
        Reviewing_results_event
Administrative_event:
        Reviewing_event
Administrative_event:
        Registration_of_participants_event
Administrative_event:
        Submission_event
Administrative_event:
        Camera_Ready_event
Administrative_event:
        follows::Administrative_event parallel_with::Administrative_event
Reviewing_event:
        EPSILON
Registration_of_participants_event:
        EPSILON
Submission_event:
        EPSILON
Camera_Ready_event:
        EPSILON
Workshop:
        EPSILON
Working_event:
        hasTopic::Topic hasAdministrativeEvent::Administrative_event
Member:
        EPSILON
Participant:
        Member
Participant:
        Student
Participant:
        Regular
Participant:
        earlyRegistration::Boolean
Member_PC:
        expertOn::Topic reviewes::Contribution
Chair_PC:
        EPSILON
Student:
        EPSILON
Science_Worker:
        EPSILON
Assistant:
        EPSILON
Volunteer:
        EPSILON
Regular:
        EPSILON
pc_meeting:
        EPSILON
session:
        EPSILON
chair:
        assigns_reviewers_to_article::Reviewer creates_program::program
article:
        group_email
article:
        notification_email
article:
        abstract_of_paper
article:
        review_form
article:
        summary_of_reviews
article:
        goes_through::Activity is_sent_to::human is_created_in::Activity structure_created_by::human has_author::human gives_classification::classification article_written_by::Author has_reviewer::Reviewer has_abstract::Abstract
participant:
        submits_to_conference::Conference
program:
        program_created_by::chair has_session::session
SlideSet:
        EPSILON
Programme:
        belongsToEvent::ConferenceEvent
MealMenu:
        isMenuOf::MealEvent
Topic:
        ParallelAndDistributedComputingTopic
Topic:
        WirelessCommunicationsTopic
Topic:
        OperatingTopicsystems
Topic:
        ComputerNetworksTopic
Topic:
        SatelliteAndSpaceCommunicationsTopic
Topic:
        CADTopic
Topic:
        MultimediaTopic
Topic:
        CommunicationsTopic
Topic:
        PowerlineTransmissionTopic
Topic:
        AntennasTopic
Topic:
        PerformanceTopic
Topic:
        SignalProcessingTopic
Topic:
        MicroelectronicsTopic
Topic:
        TestOnlyTopic
Topic:
        RadioCommunicationsTopic
Topic:
        ComputerArchitectureTopic
Topic:
        MedicineTopic
Topic:
        SecurityTopic
Topic:
        MobileComputingTopic
Topic:
        CryptographyTopic
Topic:
        CommunicationTheoryTopic
Topic:
        belongs_to_a_review_reference::Review_preference is_a_topis_of_conference_parts::Conference_part isTopicOf::Working_event
ConferenceEvent:
        NonAcademicEvent
ConferenceEvent:
        AcademicEvent
ConferenceEvent:
        hasAttendee::Person hasLocation::Place hasProgramme::Programme hasEndDateTime::dateTime hasStartDateTime::dateTime
Call:
        CallForPapers
Call:
        CallForReviews
Call:
        CallForManuscripts
Call:
        forEvent::AcademicEvent isInitiatedBy::Person+ hasSubmissionInstructions::String hasSubmissionDeadline::dateTime
ReviewRating:
        WeekRejectRating
ReviewRating:
        AcceptRating
ReviewRating:
        AccpetIfRoomRating
ReviewRating:
        RejectRating
ReviewRating:
        WeekRejectRating
        AcceptRating
        AccpetIfRoomRating
        RejectRating
Organization:
        Company
Organization:
        AcademiaOrganization
Organization:
        IndustryOrganization
Organization:
        NGO
Organization:
        GovernmentOrganization
Organization:
        isProviderOf::Sponsorship
ReviewForm:
        EPSILON
PersonalHistory:
        PersonalPublicationHistory
PersonalHistory:
        PersonalReviewHistory
PersonalHistory:
        PersonalPublicationHistory
        PersonalReviewHistory
Sponsorship:
        TravelGrant
Sponsorship:
        providedBy::Organization hasCostCurrency::String hasCostAmount::Integer
ReviewQuestion:
        TextualReviewQuestion
ReviewQuestion:
        NumericalReviewQuestion
ReviewQuestion:
        TextualReviewQuestion
        NumericalReviewQuestion
ConferenceSession:
        EPSILON
ContactInformation:
        hasCity::String hasStreet::String hasPostalCode::String hasPhone::String
WeekRejectRating:
        EPSILON
AcceptRating:
        EPSILON
AccpetIfRoomRating:
        EPSILON
RejectRating:
        EPSILON
MealEvent:
        ConferenceDinner
MealEvent:
        hasMenu::MealMenu
NonAcademicEvent:
        MealEvent
NonAcademicEvent:
        BreakEvent
NonAcademicEvent:
        SocialEvent
NonAcademicEvent:
        MealEvent
        BreakEvent
        SocialEvent
BreakEvent:
        CoffeeBreak
BreakEvent:
        FreeTimeBreak
BreakEvent:
        MealBreak
BreakEvent:
        CoffeeBreak
        FreeTimeBreak
        MealBreak
ParallelAndDistributedComputingTopic:
        EPSILON
WirelessCommunicationsTopic:
        EPSILON
OperatingTopicsystems:
        EPSILON
ComputerNetworksTopic:
        ComputerNetworksEnterpriseTopic
ComputerNetworksTopic:
        ComputerNetworksSwitchingTopic
ComputerNetworksTopic:
        ComputerNetworksSensorTopic
ComputerNetworksTopic:
        ComputerNetworksSecurityTopic
ComputerNetworksTopic:
        ComputerNetworksOpticalTopic
ComputerNetworksTopic:
        ComputerNetworksMeasurementsTopic
ComputerNetworksTopic:
        ComputerNetworksManagementTopic
ComputerNetworksTopic:
        ComputerNetworksAapplicationsTopic
ComputerNetworksTopic:
        ComputerNetworksEnterpriseTopic
        ComputerNetworksSwitchingTopic
        ComputerNetworksSensorTopic
        ComputerNetworksSecurityTopic
        ComputerNetworksOpticalTopic
        ComputerNetworksMeasurementsTopic
        ComputerNetworksManagementTopic
        ComputerNetworksAapplicationsTopic
SatelliteAndSpaceCommunicationsTopic:
        EPSILON
CADTopic:
        EPSILON
MultimediaTopic:
        EPSILON
CommunicationsTopic:
        EPSILON
PowerlineTransmissionTopic:
        EPSILON
AntennasTopic:
        EPSILON
PerformanceTopic:
        EPSILON
SignalProcessingTopic:
        EPSILON
MicroelectronicsTopic:
        EPSILON
TestOnlyTopic:
        EPSILON
RadioCommunicationsTopic:
        EPSILON
ComputerArchitectureTopic:
        EPSILON
MedicineTopic:
        EPSILON
SecurityTopic:
        EPSILON
MobileComputingTopic:
        EPSILON
CryptographyTopic:
        EPSILON
CommunicationTheoryTopic:
        EPSILON
ConferenceChair:
        EPSILON
DiningPlace:
        EPSILON
AcademiaOrganization:
        EPSILON
IndustryOrganization:
        EPSILON
NGO:
        EPSILON
GovernmentOrganization:
        EPSILON
ComputerNetworksEnterpriseTopic:
        EPSILON
ComputerNetworksSwitchingTopic:
        EPSILON
ComputerNetworksSensorTopic:
        EPSILON
ComputerNetworksSecurityTopic:
        EPSILON
ComputerNetworksOpticalTopic:
        EPSILON
ComputerNetworksMeasurementsTopic:
        EPSILON
ComputerNetworksManagementTopic:
        EPSILON
ComputerNetworksAapplicationsTopic:
        EPSILON
ActivePaper:
        RatedPapers
ActivePaper:
        hasRating::ReviewRating
PendingPaper:
        EPSILON
WithdrawnPaper:
        EPSILON
RejectedPaper:
        EPSILON
AcceptedPaper:
        relatedToEvent::PaperPresentation
PublishedPaper:
        EPSILON
Attendee:
        EPSILON
CoffeeBreak:
        EPSILON
FreeTimeBreak:
        EPSILON
MealBreak:
        EPSILON
ClosingTalk:
        EPSILON
WelcomeTalk:
        EPSILON
TalkEvent:
        ClosingTalk
TalkEvent:
        WelcomeTalk
TalkEvent:
        ClosingTalk
        WelcomeTalk
SessionChair:
        EPSILON
TPCMember:
        EPSILON
TwoLevelConference:
        EPSILON
CallForPapers:
        EPSILON
TextualReviewQuestion:
        EPSILON
NumericalReviewQuestion:
        EPSILON
OrganizationalMeeting:
        EPSILON
PaperPresentation:
        relatedToPaper::AcceptedPaper
AcademicEvent:
        TalkEvent
AcademicEvent:
        OrganizationalMeeting
AcademicEvent:
        PaperPresentation
AcademicEvent:
        hasCall::Call
PersonalPublicationHistory:
        EPSILON
Excursion:
        EPSILON
SocialEvent:
        Excursion
SocialEvent:
        Reception
SocialEvent:
        Excursion
        Reception
CallForReviews:
        EPSILON
PersonalReviewHistory:
        isReviewHistoryOf::Reviewer
ConferenceVenuePlace:
        EPSILON
CallForManuscripts:
        EPSILON
Reception:
        EPSILON
SingleLevelConference:
        EPSILON
MeetingRoomPlace:
        EPSILON
AccommodationPlace:
        EPSILON
RatedPapers:
        EPSILON
TravelGrant:
        EPSILON
ConferenceDinner:
        EPSILON
Event:
        Symposium
Event:
        Social_event
Event:
        Administrative_event
Event:
        Working_event
Event:
        pc_meeting
Event:
        session
Event:
        Social_Event
Event:
        Scientific_Event
Event:
        conists_of::Event_Tracks confirmed_by::Approval_Email defined_by::Event_Setup approved_by::Administrator starts_on::String ends_on::String has_startdate::dateTime has_enddate::dateTime eventOnList::Thing+ partOfEvent::Event hasEvent::Event organisedBy::Thing+ heldIn::Location
Accepted_Paper:
        EPSILON
Rejected_Paper:
        EPSILON
Evaluated_Paper:
        Accepted_Paper
Evaluated_Paper:
        Rejected_Paper
Evaluated_Paper:
        hasReview::Review
Camera_Ready_Paper:
        EPSILON
Positive_Review:
        EPSILON
Workshop_Paper:
        EPSILON
Industrial_Paper:
        EPSILON
Paper:
        PaperAbstract
Paper:
        PaperFullVersion
Paper:
        Invited_Paper
Paper:
        Short_Paper
Paper:
        Full_Paper
Paper:
        Accepted_Paper
Paper:
        Rejected_Paper
Paper:
        Undecided_Paper
Paper:
        ActivePaper
Paper:
        PendingPaper
Paper:
        WithdrawnPaper
Paper:
        RejectedPaper
Paper:
        AcceptedPaper
Paper:
        PublishedPaper
Paper:
        Camera_Ready_Paper
Paper:
        Workshop_Paper
Paper:
        Industrial_Paper
Paper:
        Conference_Paper
Paper:
        Submitted_Paper
Paper:
        Poster_Paper
Paper:
        Regular_Paper
Paper:
        Demo_Paper
Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer full_paper_size::Integer has_author::human isWrittenBy::Author isReviewedBy::Person+ hasReview::Review hasReviewer::Possible_Reviewer
Conference_Paper:
        EPSILON
Industrial_Session:
        EPSILON
Conference_Session:
        Industrial_Session
Conference_Session:
        Industrial_Session
Regular_Session:
        EPSILON
Poster_Session:
        EPSILON
Demo_Session:
        EPSILON
Paper_Author:
        EPSILON
Conference_Trip:
        EPSILON
Social_Event:
        Conference_Trip
Social_Event:
        Conference_Banquet
Social_Event:
        Conference_Trip
        Conference_Banquet
Tutorial_Abstract:
        EPSILON
Conference_Participant:
        Demo_Chair
Conference_Participant:
        OC_Member
Conference_Participant:
        Early-Registered_Participant
Conference_Participant:
        Late-Registered_Participant
Conference_Participant:
        Demo_Chair
        OC_Member
        Early-Registered_Participant
        Late-Registered_Participant
Submitted_Paper:
        Assigned_Paper
Submitted_Paper:
        Assigned_Paper
Assigned_Paper:
        Evaluated_Paper
Assigned_Paper:
        hasReviewer::Possible_Reviewer
Negative_Review:
        EPSILON
Neutral_Review:
        EPSILON
Research_Topic:
        topicCoveredBy::Thing
Organising_Agency:
        EPSILON
Academic_Institution:
        Research_Institute
Academic_Institution:
        scientificallyOrganises::Academic_Institution
Organisation:
        Organising_Agency
Organisation:
        Academic_Institution
Organisation:
        Proceedings_Publisher
Organisation:
        publisherOf::Thing+ technicallyOrganises::Thing
Proceedings_Publisher:
        EPSILON
Poster_Paper:
        EPSILON
Regular_Paper:
        EPSILON
Demo_Paper:
        EPSILON
Location:
        locationOf::Event
Research_Institute:
        EPSILON
Scientific_Event:
        Individual_Presentation
Scientific_Event:
        Individual_Presentation
Invited_Talk_Abstract:
        EPSILON
Agency_Staff_Member:
        EPSILON
Workshop_Session:
        EPSILON
Track:
        EPSILON
Invited_Talk:
        EPSILON
Contributed_Talk:
        presentationOfPaper::Document+
Demo_Chair:
        EPSILON
Tutorial_Chair:
        EPSILON
PC_Chair:
        EPSILON
PC_Member:
        SC_Member
PC_Member:
        SC_Member
OC_Member:
        OC_Chair
OC_Member:
        OC_Chair
Proceedings:
        Conference_Proceedings
Proceedings:
        Conference_Proceedings
Programme_Brochure:
        EPSILON
Flyer:
        EPSILON
Web_Site:
        EPSILON
Multi-author_Volume:
        Proceedings
Multi-author_Volume:
        Proceedings
Individual_Presentation:
        Invited_Talk
Individual_Presentation:
        Contributed_Talk
Individual_Presentation:
        presentationOfPaper::Document+
OC_Chair:
        EPSILON
Conference_Banquet:
        EPSILON
Workshop_Chair:
        EPSILON
Conference_Proceedings:
        EPSILON
Session_Chair:
        EPSILON
Early-Registered_Participant:
        EPSILON
Late-Registered_Participant:
        EPSILON
Possible_Reviewer:
        PC_Member
Possible_Reviewer:
        reviewerOfPaper::Paper
Student:
        EPSILON
Invited_Speaker:
        EPSILON
Presenter:
        Invited_Speaker
Presenter:
        Invited_Speaker
SC_Member:
        EPSILON
Presenter_house:
        EPSILON
Building:
        Presenter_house
Building:
        Conference_restaurant
Building:
        Conference_building
Building:
        Conference_airport
Building:
        Conference_hotel
Building:
        Sponsor_company_house
Building:
        Presenter_university
Building:
        Presenter_house
        Conference_restaurant
        Conference_building
        Conference_airport
        Conference_hotel
        Sponsor_company_house
        Presenter_university
Presenter_state:
        EPSILON
Delegate:
        One_day_presenter
Delegate:
        Technical_commitee
Delegate:
        Listener
Delegate:
        Session_chair
Delegate:
        Speaker
Delegate:
        Hotel_presenter
Delegate:
        Non_speaker
Delegate:
        IASTED_non_member
Delegate:
        Conference_Hiker
Delegate:
        IASTED_member
Delegate:
        One_day_presenter
        Technical_commitee
        Listener
        Session_chair
        Speaker
        Hotel_presenter
        Non_speaker
        IASTED_non_member
        Conference_Hiker
        IASTED_member
Presenter_city:
        EPSILON
Hotel_registration_form:
        EPSILON
Deadline_hotel_reservation:
        EPSILON
Form:
        Hotel_registration_form
Form:
        Registration_form
Form:
        Author_information_form
Form:
        Hotel_registration_form
        Registration_form
        Author_information_form
Car:
        EPSILON
Transport_vehicle:
        Car
Transport_vehicle:
        Taxi
Transport_vehicle:
        Shuttle_bus
Transport_vehicle:
        Van
Transport_vehicle:
        Car
        Taxi
        Shuttle_bus
        Van
Mailing_list:
        EPSILON
Document:
        Email
Document:
        Submission
Document:
        Template
Document:
        article
Document:
        SlideSet
Document:
        Programme
Document:
        MealMenu
Document:
        Programme_Brochure
Document:
        Flyer
Document:
        Web_Site
Document:
        Multi-author_Volume
Document:
        Form
Document:
        Mailing_list
Document:
        Record_of_attendance
Document:
        Brief_introduction_for_Session_chair
Document:
        Invitation_letter
Document:
        Viza
Document:
        Transparency
Document:
        Payment_document
Document:
        recieved_by::User used_by::Person submited__by::User relatesTo::Thing+ writtenBy::Person hasUpdatedVersion::Document updatedVersionOf::Document
Renting:
        EPSILON
Activity_before_conference:
        Renting
Activity_before_conference:
        Research
Activity_before_conference:
        Refusing_manuscript
Activity_before_conference:
        Accepting_manuscript
Activity_before_conference:
        Receiving_manuscript
Activity_before_conference:
        Renting
        Research
        Refusing_manuscript
        Accepting_manuscript
        Receiving_manuscript
Dinner_banquet:
        EPSILON
One_day_presenter:
        EPSILON
Social_program:
        Dinner_banquet
Social_program:
        Dinner_banquet
Activity:
        Event_Creation
Activity:
        Request
Activity:
        Event_Approval
Activity:
        Registration
Activity:
        paper_assignment
Activity:
        bidding_of_reviewer
Activity:
        managing_of_conference_process
Activity:
        reviewing_proces
Activity:
        notification
Activity:
        submission_process
Activity:
        Activity_before_conference
Activity:
        Conference_activity
Activity:
        Activity_after_conference
Activity:
        has_result::Thing+ sent_by::Person is_followed_by::Activity is_monitored_by::human has_intensity::intensity has_result::article is_performed_by::human is_supervised_by::human is_held_before::Time is_held_in::Trip_day+ is_held_after::Time is_dated_on::dateTime
PowerPoint_presentation:
        EPSILON
Presentation:
        Invited_talk
Presentation:
        PowerPoint_presentation
Presentation:
        Video_presentation
Presentation:
        is_given_by::Active_conference_participant
Conference_restaurant:
        EPSILON
Conference_city:
        EPSILON
Conference_state:
        EPSILON
Submissions_deadline:
        EPSILON
Deadline:
        Deadline_hotel_reservation
Deadline:
        Submissions_deadline
Deadline:
        Deadline_for_notification_of_acceptance
Deadline:
        Registation_deadline
Deadline:
        Camera_ready_manuscript_deadline
Deadline:
        done_till::date
Simulating:
        EPSILON
Research:
        Simulating
Research:
        Modelling
Research:
        Simulating
        Modelling
Technic_activity:
        EPSILON
Conference_activity:
        Social_program
Conference_activity:
        Technic_activity
Conference_activity:
        Registration
Conference_activity:
        Introduction
Conference_activity:
        Welcome_address
Conference_activity:
        Lecture
Conference_activity:
        Coffee_break
Conference_activity:
        Coctail_reception
Conference_activity:
        Social_program
        Technic_activity
        Registration
        Introduction
        Welcome_address
        Lecture
        Coffee_break
        Coctail_reception
Technical_commitee:
        EPSILON
Place:
        DiningPlace
Place:
        ConferenceVenuePlace
Place:
        MeetingRoomPlace
Place:
        AccommodationPlace
Place:
        Building
Place:
        Session_room
Place:
        Hotel_room
Place:
        Conference_hall
Place:
        Main_office
Place:
        isLocationOf::ConferenceEvent is_equipped_by::Item
Author_cd_proceedings_included:
        EPSILON
Author:
        AuthorNotReviewer
Author:
        Co-author
Author:
        Corresponding_Author
Author:
        Author_cd_proceedings_included
Author:
        Lecturer
Author:
        Plenary_lecture_speaker
Author:
        Tutorial_speaker
Author:
        Author_book_proceedings_included
Author:
        submitPaper::Paper writePaper::Paper writes::Contribution writes_article::article assigns_article_to_conference::article hasRelatedPaper::Paper
Cd_proceening:
        EPSILON
Trip_day:
        EPSILON
Time:
        Deadline
Time:
        Trip_day
Time:
        Conference_days
Time:
        Deadline
        Trip_day
        Conference_days
Record_of_attendance:
        EPSILON
Listener:
        EPSILON
Session_room:
        EPSILON
Brief_introduction_for_Session_chair:
        EPSILON
Session_chair:
        EPSILON
Invitation_letter:
        EPSILON
Registration_form:
        EPSILON
Viza:
        EPSILON
Registration:
        EPSILON
Conference_days:
        One_conference_day
Conference_days:
        One_conference_day
Conference_building:
        EPSILON
Registration_fee:
        Author_attendee_book_registration_fee
Registration_fee:
        Nonmember_registration_fee
Registration_fee:
        Nonauthor_registration_fee
Registration_fee:
        Memeber_registration_fee
Registration_fee:
        Student_registration_fee
Registration_fee:
        Author_attendee_cd_registration_fee
Registration_fee:
        Author_attendee_book_registration_fee
        Nonmember_registration_fee
        Nonauthor_registration_fee
        Memeber_registration_fee
        Student_registration_fee
        Author_attendee_cd_registration_fee
Departure:
        EPSILON
Activity_after_conference:
        Departure
Activity_after_conference:
        Full_day_tour
Activity_after_conference:
        Departure
        Full_day_tour
Conference_airport:
        EPSILON
Worker_lecturer:
        EPSILON
Lecturer:
        Worker_lecturer
Lecturer:
        Student_lecturer
Lecturer:
        Worker_lecturer
        Student_lecturer
Transparency:
        EPSILON
Speaker:
        EPSILON
City:
        Presenter_city
City:
        Conference_city
City:
        Sponsor_city
City:
        Trip_city
City:
        Presenter_city
        Conference_city
        Sponsor_city
        Trip_city
Card:
        Credit_card
Card:
        Credit_card
Item:
        Transport_vehicle
Item:
        Card
Item:
        Audiovisual_equipment
Item:
        Publication
Item:
        go_through::Activity is_used_for::Thing+ is_signed_by::Person is_made_from::Item is_sent_after::Time is_needed_for::Person is_sent_before::Time is_prepared_by::Person is_used_by::Person is_given_to::Person is_sent_by::Person is_writen_by::Person
Author_attendee_book_registration_fee:
        EPSILON
Book_proceeding:
        EPSILON
Video_cassette_player:
        EPSILON
Audiovisual_equipment:
        Video_cassette_player
Audiovisual_equipment:
        LCD_projector
Audiovisual_equipment:
        Computer
Audiovisual_equipment:
        Overhead_projector
Audiovisual_equipment:
        Video_cassette_player
        LCD_projector
        Computer
        Overhead_projector
Video_presentation:
        EPSILON
Hotel_room:
        Single_hotel_room
Hotel_room:
        Double_hotel_room
Hotel_room:
        Single_hotel_room
        Double_hotel_room
Hotel_presenter:
        EPSILON
Conference_hotel:
        EPSILON
Money:
        Tax
Money:
        Fee
Money:
        Sponzorship
Money:
        Tip
Money:
        is_paid_with::Item is_paid_by::Person is_paid_in::Building is_paid_for::Thing+ has_amount_of::Money
State:
        Presenter_state
State:
        Conference_state
State:
        Sponsor_state
State:
        Presenter_state
        Conference_state
        Sponsor_state
Introduction:
        Introduction_of_speaker
Introduction:
        Introduction_of_speaker
Welcome_address:
        EPSILON
Value_added_tax:
        EPSILON
Tax:
        Value_added_tax
Tax:
        Departure_tax
Tax:
        Value_added_tax
        Departure_tax
Refusing_manuscript:
        EPSILON
Final_manuscript:
        EPSILON
Accepting_manuscript:
        EPSILON
Sponsor_city:
        EPSILON
Sponsor:
        EPSILON
Time_zone:
        EPSILON
Introduction_of_speaker:
        EPSILON
Conference_hall:
        EPSILON
Plenary_lecture:
        EPSILON
Lecture:
        Plenary_lecture
Lecture:
        Plenary_lecture
Plenary_lecture_speaker:
        EPSILON
LCD_projector:
        EPSILON
Deadline_for_notification_of_acceptance:
        EPSILON
Tutorial_speaker:
        EPSILON
Session:
        Conference_Session
Session:
        Regular_Session
Session:
        Poster_Session
Session:
        Demo_Session
Session:
        Workshop_Session
Session:
        Speaker_lecture
Session:
        Conference_Session
        Regular_Session
        Poster_Session
        Demo_Session
        Workshop_Session
        Speaker_lecture
Registation_deadline:
        EPSILON
Single_hotel_room:
        EPSILON
Non_speaker:
        Worker_non_speaker
Non_speaker:
        Student_non_speaker
Non_speaker:
        Worker_non_speaker
        Student_non_speaker
Author_information_form:
        EPSILON
Nonmember_registration_fee:
        EPSILON
IASTED_non_member:
        EPSILON
Hotel_fee:
        EPSILON
Fee:
        Registration_fee
Fee:
        Hotel_fee
Fee:
        Fee_for_extra_trip
Fee:
        Registration_fee
        Hotel_fee
        Fee_for_extra_trip
Publication:
        Cd_proceening
Publication:
        Book_proceeding
Publication:
        Cd_proceening
        Book_proceeding
Taxi:
        EPSILON
Sponsor_state:
        EPSILON
Review:
        Meta-Review
Review:
        Positive_Review
Review:
        Negative_Review
Review:
        Neutral_Review
Review:
        writtenBy::Reviewer reviews::Reviewed_contribution gives_classification::classification is_created_in::Activity review_written_by::Reviewer reviewOfPaper::Paper reviewWrittenBy::Possible_Reviewer
Modelling:
        EPSILON
Worker_non_speaker:
        EPSILON
Nonauthor_registration_fee:
        EPSILON
Payment_document:
        Cheque
Payment_document:
        Bank_transfer
Payment_document:
        Cheque
        Bank_transfer
Camera_ready_manuscript_deadline:
        EPSILON
One_conference_day:
        EPSILON
Fee_for_extra_trip:
        EPSILON
Full_day_tour:
        EPSILON
Conference_Hiker:
        EPSILON
Computer:
        EPSILON
IASTED_member:
        EPSILON
Memeber_registration_fee:
        EPSILON
Author_book_proceedings_included:
        EPSILON
Sponsor_company_house:
        EPSILON
Sponzorship:
        EPSILON
Student_lecturer:
        EPSILON
Trip_city:
        EPSILON
Cheque:
        EPSILON
Shuttle_bus:
        EPSILON
Student_non_speaker:
        EPSILON
Student_registration_fee:
        EPSILON
Author_attendee_cd_registration_fee:
        EPSILON
Tip:
        EPSILON
Credit_card:
        EPSILON
Van:
        EPSILON
Main_office:
        EPSILON
Presenter_university:
        EPSILON
Departure_tax:
        EPSILON
Receiving_manuscript:
        EPSILON
Double_hotel_room:
        EPSILON
Initial_manuscipt:
        EPSILON
Coffee_break:
        EPSILON
Bank_transfer:
        EPSILON
Overhead_projector:
        EPSILON
Speaker_lecture:
        EPSILON
Coctail_reception:
        EPSILON
Currency:
        EPSILON
