Element:
        EPSILON
IEEE1471Model:
        system::ANY environment::ANY missions::ANY+ architecture::ANY stakeholders::ANY+ concerns::ANY+ viewpoints::ANY+ libraryViewpoints::ANY+ architecturalDescription::ANY rationale::ANY
System:
        fulfils::ANY+ inhabits::ANY hasAn::ANY has::ANY+
Mission:
        name::ANY content::ANY
Environment:
        influences::ANY
Architecture:
        describedBy::ANY
Rationale:
        provides::ANY
ArchitecturalDescription:
        identifiesS::ANY+ identifiesC::ANY+ selects::ANY+ organizedBy::ANY+ aggregates::ANY+
View:
        conformsTo::ANY consitsOf::ANY+
Model:
        participatesInV::ANY+ participatesInAD::ANY
Stakeholder:
        has::ANY+
Concern:
        isImportantTo::ANY+
Viewpoint:
        hasSource::ANY usedToCover::ANY+ establishesMethodsFor::ANY+
LibraryViewpoint:
        name::ANY content::ANY
