String:
        STR
Element:
        IEEE1471Model
Element:
        System
Element:
        Mission
Element:
        Environment
Element:
        Architecture
Element:
        Rationale
Element:
        ArchitecturalDescription
Element:
        View
Element:
        Model
Element:
        Stakeholder
Element:
        Concern
Element:
        Viewpoint
Element:
        LibraryViewpoint
IEEE1471Model:
        system::System environment::Environment missions::Mission+ architecture::Architecture stakeholders::Stakeholder+ concerns::Concern+ viewpoints::Viewpoint+ libraryViewpoints::LibraryViewpoint+ architecturalDescription::ArchitecturalDescription rationale::Rationale
System:
        fulfils::Mission+ inhabits::Environment hasAn::Architecture has::Stakeholder+
Mission:
        name::String content::String
Environment:
        influences::System
Architecture:
        describedBy::ArchitecturalDescription
Rationale:
        provides::ArchitecturalDescription
ArchitecturalDescription:
        identifiesS::Stakeholder+ identifiesC::Concern+ selects::Viewpoint+ organizedBy::View+ aggregates::Model+
View:
        conformsTo::Viewpoint consitsOf::Model+
Model:
        participatesInV::View+ participatesInAD::ArchitecturalDescription
Stakeholder:
        has::Concern+
Concern:
        isImportantTo::Stakeholder+
Viewpoint:
        hasSource::LibraryViewpoint usedToCover::Concern+ establishesMethodsFor::Model+
LibraryViewpoint:
        name::String content::String
