Viewpoint:
        source::ViewpointImport+ covers::Concern+ supplierDependency::ViewpointDependency+ clientDependency::ViewpointDependency+ isImportTo::Stakeholder architecturalConstruct::ArchitecturalConstruct+ process::Process
Concern:
        EPSILON
Stakeholder:
        concerns::Concern
ViewpointImport:
        EPSILON
ViewpointDependency:
        supplier::Viewpoint client::Viewpoint
Process:
        methodology::Technique+
Technique:
        methods::AnalysisMethod+ applies::Rule+
AnalysisMethod:
        analysis::Language
ArchitecturalConstruct:
        Rule
ArchitecturalConstruct:
        Language
ArchitecturalConstruct:
        Mapping
ArchitecturalConstruct:
        Pattern
ArchitecturalConstruct:
        Rule
        Language
        Mapping
        Pattern
Rule:
        ModelOrganization
Rule:
        techniques::Technique+ guidance::Language
ModelOrganization:
        EPSILON
ModellingRule:
        EPSILON
Language:
        EPSILON
Mapping:
        input::Language ouput::Language
Pattern:
        EPSILON
