Viewpoint:
        source::ANY+ covers::ANY+ supplierDependency::ANY+ clientDependency::ANY+ isImportTo::ANY architecturalConstruct::ANY+ process::ANY
Concern:
        EPSILON
Stakeholder:
        concerns::ANY
ViewpointImport:
        EPSILON
ViewpointDependency:
        supplier::ANY client::ANY
Process:
        methodology::ANY+
Technique:
        methods::ANY+ applies::ANY+
AnalysisMethod:
        analysis::ANY
ArchitecturalConstruct:
        EPSILON
Rule:
        techniques::ANY+ guidance::ANY
ModelOrganization:
        EPSILON
ModellingRule:
        EPSILON
Language:
        EPSILON
Mapping:
        input::ANY ouput::ANY
Pattern:
        EPSILON
