OIMAPrefixFormats:
        opp_one::EPSILON
        opp_two::EPSILON
TwoByteField:
        EPSILON
VariableLengthField:
        EPSILON
IMSTransactionMessage:
        OIMAPrefixFormat::OIMAPrefixFormats standardFieldsFlag::Boolean OIMAPrefixComponent::OIMAPrefix standardFieldComponent::StandardFields messageComponent::ApplicationData
OIMAPrefix:
        controlDataComponent::ControlData stateDataComponent::StateData securityDataComponent::SecurityData userDataComponent::UserData
ControlData:
        EPSILON
StateData:
        EPSILON
SecurityData:
        EPSILON
UserData:
        EPSILON
StandardFields:
        length::TwoByteField reservedField::TwoByteField transactionCode::VariableLengthField
ApplicationData:
        languageElements::TDLangElement+ fieldComponents::Field+
Field:
        fieldContainer::ApplicationData
TDLangElement:
        EPSILON
