OIMAPrefixFormats:
        opp_one::EPSILON
        opp_two::EPSILON
TwoByteField:
        EPSILON
VariableLengthField:
        EPSILON
IMSTransactionMessage:
        OIMAPrefixFormat::ANY standardFieldsFlag::ANY OIMAPrefixComponent::ANY standardFieldComponent::ANY messageComponent::ANY
OIMAPrefix:
        controlDataComponent::ANY stateDataComponent::ANY securityDataComponent::ANY userDataComponent::ANY
ControlData:
        EPSILON
StateData:
        EPSILON
SecurityData:
        EPSILON
UserData:
        EPSILON
StandardFields:
        length::ANY reservedField::ANY transactionCode::ANY
ApplicationData:
        languageElements::ANY+ fieldComponents::ANY+
Field:
        fieldContainer::ANY
TDLangElement:
        EPSILON
