Element:
        NamedElement
Element:
        Extended
Element:
        Typed
Element:
        RuleSetDeclaration
Element:
        Binding
Element:
        RuleCondition
Element:
        RuleAction
Element:
        location::String commentsBefore::String+ commentsAfter::String+
NamedElement:
        ExtendedIdentifier
NamedElement:
        RuleSet
NamedElement:
        Type
NamedElement:
        RulesetElementDefinition
ExtendedIdentifier:
        parentIdentifier::ExtendedIdentifier extendedIdentifierOwner::Extended
Extended:
        Definition
Extended:
        ClassInstancesDeclaration
Definition:
        ImportDefinition
Definition:
        PropertyDefinition
RuleSet:
        importDefinitions::ImportDefinition+ propertyDefinitions::IRLDeclarations/PropertyDefinition rulesetElementDefinitions::IRLRules/RulesetElementDefinition+
ImportDefinition:
        importDefinitionOwners::RuleSet dotStar::Boolean
Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
