AbstractTypeDeclaration:
        EPSILON
Annotation:
        type::ANY values::ANY+
AnnotationMemberValuePair:
        member::ANY value::ANY
AnnotationTypeDeclaration:
        originalFileContent::ANY package::ANY bodyDeclarations::ANY+ superInterfaces::ANY+ commentsAfterBody::ANY+ imports::ANY+ commentsBeforeBody::ANY+
AnnotationTypeMemberDeclaration:
        type::ANY default::ANY
AnonymousClassDeclaration:
        bodyDeclarations::ANY+
ArrayAccess:
        index::ANY array::ANY
ArrayCreation:
        dimensions::ANY+ initializer::ANY type::ANY
ArrayInitializer:
        expressions::ANY+
ArrayLengthAccess:
        array::ANY
AssertStatement:
        message::ANY expression::ANY
Assignment:
        operator::ANY rightHandSide::ANY leftHandSide::ANY
ASTNode:
        EPSILON
BodyDeclaration:
        EPSILON
Block:
        statements::ANY+
BlockComment:
        content::ANY isEnclosedByParent::ANY isPrefixOfParent::ANY
BreakStatement:
        label::ANY
CastExpression:
        type::ANY expression::ANY
CatchClause:
        exception::ANY body::ANY
ClassInstanceCreation:
        arguments::ANY+ type::ANY expression::ANY anonymousClassDeclaration::ANY
Comment:
        EPSILON
ConditionalExpression:
        elseExpression::ANY thenExpression::ANY expression::ANY
ContinueStatement:
        label::ANY
ConstructorInvocation:
        arguments::ANY+
DoStatement:
        expression::ANY body::ANY
EmptyStatement:
        
EnhancedForStatement:
        parameter::ANY expression::ANY body::ANY
EnumConstantDeclaration:
        arguments::ANY+ anonymousClassDeclaration::ANY
EnumDeclaration:
        enumConstants::ANY+
Expression:
        EPSILON
ExpressionStatement:
        expression::ANY
FieldAccess:
        field::ANY expression::ANY
FieldDeclaration:
        type::ANY
ForStatement:
        body::ANY expression::ANY initializers::ANY+ updaters::ANY+
InfixExpression:
        operator::ANY extendedOperands::ANY+ rightOperand::ANY leftOperand::ANY
IfStatement:
        expression::ANY elseStatement::ANY thenStatement::ANY
ImportDeclaration:
        static::ANY importedElement::ANY
Initializer:
        body::ANY
InstanceofExpression:
        leftOperand::ANY rightOperand::ANY
Javadoc:
        tags::ANY+
LabeledStatement:
        body::ANY
LineComment:
        content::ANY isEnclosedByParent::ANY isPrefixOfParent::ANY
MemberRef:
        qualifier::ANY member::ANY
MethodDeclaration:
        extraArrayDimensions::ANY constructor::ANY varargs::ANY body::ANY parameters::ANY+ typeParameters::ANY+ thrownExceptions::ANY+ returnType::ANY
MethodInvocation:
        method::ANY arguments::ANY+ expression::ANY
MethodRef:
        qualifier::ANY parameters::ANY+ method::ANY
MethodRefParameter:
        name::ANY isVarargs::ANY type::ANY
Model:
        name::ANY ownedElements::ANY+ orphanTypes::ANY+
MultipleValuedNamedElement:
        EPSILON
NamedElement:
        EPSILON
NamedElementRef:
        extraArrayDimensions::ANY element::ANY qualifier::ANY
OrphanType:
        name::ANY proxy::ANY
PackageDeclaration:
        model::ANY ownedElements::ANY+
ParameterizedType:
        typeArguments::ANY+ type::ANY
ParenthesizedExpression:
        expression::ANY
PostfixExpression:
        operator::ANY operand::ANY
PrefixExpression:
        operator::ANY operand::ANY
PrimitiveType:
        EPSILON
ReturnStatement:
        expression::ANY
ThrowStatement:
        expression::ANY
SingleVariableDeclaration:
        modifiers::ANY isVarargs::ANY type::ANY
Statement:
        EPSILON
SuperConstructorInvocation:
        arguments::ANY+ expression::ANY
SuperFieldAccess:
        qualifier::ANY field::ANY
SuperMethodInvocation:
        arguments::ANY+ qualifier::ANY method::ANY
SwitchCase:
        expressionInitialized::ANY expression::ANY
SwitchStatement:
        statements::ANY+ expression::ANY
SynchronizedStatement:
        body::ANY expression::ANY
TagElement:
        tagName::ANY fragments::ANY+
TextElement:
        text::ANY
ThisExpression:
        qualifier::ANY
TryStatement:
        finally::ANY body::ANY catchClauses::ANY+
TypeDeclaration:
        isInterface::ANY typeParameters::ANY+ superclass::ANY
TypeDeclarationStatement:
        declaration::ANY
TypeLiteral:
        type::ANY
TypeParameter:
        bounds::ANY+
UnresolvedItem:
        EPSILON
ValuedNamedElement:
        EPSILON
VariableDeclarationExpression:
        modifiers::ANY type::ANY
VariableDeclarationStatement:
        modifiers::ANY type::ANY
WildCardType:
        isUpperBound::ANY bound::ANY
WhileStatement:
        expression::ANY body::ANY
