Modifier:
        EPSILON
Class:
        superClass::ANY implement::ANY+ methods::ANY+ fields::ANY+
Interface:
        superInterface::ANY+ implementedBy::ANY+ abstractMethods::ANY+ constants::ANY+
Method:
        share::ANY class::ANY interface::ANY resultOf::ANY parameters::ANY+
Field:
        share::ANY class::ANY interface::ANY value::ANY typeOf::ANY
Value:
        EPSILON
Parameter:
        name::ANY typeOf::ANY owner::ANY
Type:
        EPSILON
ReferenceType:
        reference::ANY
PrimitiveType:
        EPSILON
Int:
        EPSILON
