JavaSource:
        classes::ANY+
NamedElement:
        EPSILON
ClassDeclaration:
        superclass::ANY methods::ANY+
MethodDefinition:
        class::ANY invocations::ANY+
MethodInvocation:
        method::ANY
