JavaProject:
        ownedPackageFragment::PackageFragment+
PackageFragment:
        ownedCompilationUnit::CompilationUnit+
CompilationUnit:
        importDeclaration::ImportDeclaration+ ownedType::Type+ declaration::PackageDeclaration
ImportDeclaration:
        name::String
Type:
        nestedType::Type+ ownedSuperType::Type+ elementName::String member_kind::MEMBER_KIND methods::Method+ fields::Field+
Field:
        
Method:
        returnType::String parametersName::String+ parametersType::String+
JavaElement:
        Type
JavaElement:
        Field
JavaElement:
        Method
MEMBER_KIND:
        class::EPSILON
        enum::EPSILON
        interface::EPSILON
        Annotation::EPSILON
NamedElement:
        JavaProject
NamedElement:
        PackageFragment
NamedElement:
        CompilationUnit
NamedElement:
        ImportDeclaration
NamedElement:
        JavaElement
NamedElement:
        PackageDeclaration
PackageDeclaration:
        name::String
