Element:
        EPSILON
ModelElement:
        EPSILON
KDMEntity:
        EPSILON
KDMContainer:
        EPSILON
KDMGroup:
        EPSILON
KDMRelationship:
        EPSILON
Annotation:
        note::ANY
Attribute:
        tag::ANY value::ANY
KDMExtensionFamily:
        name::ANY stereotype::ANY+
Stereotype:
        baseClass::ANY name::ANY family::ANY extendedElement::ANY tag::ANY+
TagDefinition:
        tag::ANY type::ANY
TaggedValue:
        value::ANY tag::ANY
KDMFramework:
        EPSILON
KDMModel:
        EPSILON
