Resource:
        name::ANY type::ANY capacity::ANY schedulingPolicy::ANY description::ANY acquire::ANY release::ANY
Service:
        name::ANY formalParams::ANY speedAttr::ANY failAttr::ANY description::ANY behavior::ANY+ behaviorUsed::ANY+ serviceCall::ANY+
Behavior:
        stepn::ANY stepb::ANY+ service::ANY usedService::ANY+ workLoad::ANY
WorkLoad:
        workLoadType::ANY arrivalProcess::ANY population::ANY initialResource::ANY behavior::ANY
Step:
        name::ANY repetition::ANY internalExecTime::ANY internalFailProb::ANY completionModel::ANY serviceCall::ANY+ predecessor::ANY+ successor::ANY+ behavior::ANY nestedBehavior::ANY
Start:
        EPSILON
End:
        EPSILON
Control:
        EPSILON
InternalActivity:
        EPSILON
ServiceCall:
        resourceType::ANY serviceName::ANY isSynch::ANY actualParam::ANY+ step::ANY calledService::ANY
ActualParam:
        value::ANY serviceCall::ANY
Branch:
        branchProbs::ANY
Fork:
        EPSILON
Join:
        EPSILON
Acquire:
        resourceUnits::ANY resource::ANY
Release:
        resourceUnits::ANY resource::ANY
