LocatedElement:
        EPSILON
ModelElement:
        EPSILON
Classifier:
        name::ANY package::ANY
DataType:
        EPSILON
Enumeration:
        literals::ANY+
EnumLiteral:
        name::ANY package::ANY
Class:
        isAbstract::ANY supertypes::ANY+ structuralFeatures::ANY+
StructuralFeature:
        lower::ANY upper::ANY isOrdered::ANY isUnique::ANY owner::ANY type::ANY
Attribute:
        EPSILON
Reference:
        isContainer::ANY opposite::ANY
Package:
        contents::ANY+ metamodel::ANY
Metamodel:
        contents::ANY+
