Node:
        EPSILON
ElementNode:
        EPSILON
AttributeNode:
        value::ANY
RootNode:
        EPSILON
TextNode:
        nodes::ANY+
KMLNode:
        EPSILON
KMLRootNode:
        
Address:
        value::ANY
AltitudeMode:
        value::ANY
AltitudeModeValue:
        clampedToGround::EPSILON
        relativeToGround::EPSILON
        absolute::EPSILON
BalloonStyle:
        
Color:
        value::ANY
ColorMode:
        value::ANY
ColorModeValue:
        normal::EPSILON
        random::EPSILON
Cookie:
        value::ANY
Coordinates:
        
Coordinate:
        
Description:
        value::ANY
Document:
        
DrawOrder:
        value::ANY
East:
        value::ANY
Extrude:
        value::ANY
Fill:
        value::ANY
FlyToView:
        value::ANY
Folder:
        
GroundOverlay:
        
H:
        value::ANY
Heading:
        value::ANY
Href:
        value::ANY
Icon:
        
IconStyle:
        
InnerBoundaryIs:
        
Key:
        value::ANY
LabelStyle:
        
Latitude:
        value::ANY
LatLonBox:
        
LinearRing:
        
LineString:
        
LineStyle:
        id::ANY
LinkDescription:
        value::ANY
LinkName:
        value::ANY
Longitude:
        value::ANY
LookAt:
        
Message:
        
MinRefreshPeriod:
        value::ANY
MultiGeometry:
        
Name:
        value::ANY
NetworkLink:
        
NetworkLinkControl:
        
North:
        value::ANY
ObjArrayField:
        
ObjField:
        
Open:
        value::ANY
OuterBoundaryIs:
        
Outline:
        value::ANY
OverlayXY:
        x::ANY y::ANY xunits::ANY yunits::ANY
Pair:
        
Parent:
        value::ANY
Placemark:
        
Point:
        
Polygon:
        
PolyStyle:
        
Range:
        value::ANY
RefreshInterval:
        value::ANY
RefreshMode:
        value::ANY
RefreshVisibility:
        value::ANY
Rotation:
        value::ANY
Schema:
        
Scale:
        value::ANY
ScreenOverlay:
        id::ANY
ScreenXY:
        x::ANY y::ANY xunits::ANY yunits::ANY
SimpleArrayField:
        
SimpleField:
        
Size:
        x::ANY y::ANY xunits::ANY yunits::ANY
South:
        value::ANY
Snippet:
        
Style:
        id::ANY
StyleMap:
        
StyleUrl:
        value::ANY
Tessellate:
        value::ANY
Text:
        
TextColor:
        value::ANY
Tilt:
        value::ANY
Type:
        value::ANY
Url:
        
ViewBoundScale:
        value::ANY
ViewRefreshMode:
        value::ANY
ViewRefreshTime:
        value::ANY
ViewFormat:
        value::ANY
Visibility:
        value::ANY
W:
        value::ANY
West:
        value::ANY
Width:
        value::ANY
X:
        value::ANY
Y:
        value::ANY
