ValuedElement:
        EPSILON
Type:
        value::ANY
Title:
        value::ANY
Name:
        author::ANY organisation::ANY
Date:
        value::ANY
Author:
        names::ANY+
Adress:
        value::ANY
Organisation:
        names::ANY+ adress::ANY heading::ANY
Phone:
        value::ANY
Fax:
        value::ANY
EMail:
        value::ANY
Heading:
        organisations::ANY+ phone::ANY fax::ANY email::ANY
Abstract:
        value::ANY
Keywords:
        value::ANY
SectionBody:
        corps::ANY+ section::ANY
Corps:
        EPSILON
Value:
        EPSILON
Cite:
        EPSILON
Path:
        value::ANY
Label:
        value::ANY
Figure:
        path::ANY label::ANY title::ANY
Item:
        itemscontainer::ANY enumeratecontainer::ANY
Items:
        item::ANY+
Enumerate:
        item::ANY+
Section:
        title::ANY sectionBody::ANY
Description:
        date::ANY
Citation:
        label::ANY author::ANY description::ANY bibliography::ANY
Bibliography:
        citations::ANY+ documentbody::ANY
DocumentBody:
        sections::ANY+ bibliography::ANY+ document::ANY
Document:
        type::ANY title::ANY author::ANY date::ANY heading::ANY abstract::ANY keywords::ANY documentbody::ANY
