ValuedElement:
        Type
ValuedElement:
        Title
ValuedElement:
        Name
ValuedElement:
        Date
ValuedElement:
        Adress
ValuedElement:
        Phone
ValuedElement:
        Fax
ValuedElement:
        EMail
ValuedElement:
        Abstract
ValuedElement:
        Keywords
ValuedElement:
        Path
ValuedElement:
        Label
ValuedElement:
        Item
ValuedElement:
        Description
Type:
        value::String
Title:
        value::String
Name:
        author::Author organisation::Organisation
Date:
        value::String
Author:
        names::Name+
Adress:
        value::String
Organisation:
        names::Name+ adress::Adress heading::Heading
Phone:
        value::String
Fax:
        value::String
EMail:
        value::String
Heading:
        organisations::Organisation+ phone::Phone fax::Fax email::EMail
Abstract:
        value::String
Keywords:
        value::String
SectionBody:
        corps::Corps+ section::Section
Corps:
        Figure
Corps:
        Items
Corps:
        Enumerate
Corps:
        Section
Value:
        EPSILON
Cite:
        EPSILON
Path:
        value::String
Label:
        value::String
Figure:
        path::Path label::Label title::Title
Item:
        itemscontainer::Items enumeratecontainer::Enumerate
Items:
        item::Item+
Enumerate:
        item::Item+
Section:
        title::Title sectionBody::SectionBody
Description:
        date::Date
Citation:
        label::Label author::Author description::Description bibliography::Bibliography
Bibliography:
        citations::Citation+ documentbody::DocumentBody
DocumentBody:
        sections::Section+ bibliography::Bibliography+ document::Document
Document:
        type::Type title::Title author::Author date::Date heading::Heading abstract::Abstract keywords::Keywords documentbody::DocumentBody
