IdentifiedElement:
        MElement
IdentifiedElement:
        Field
IdentifiedElement:
        Collection
IdentifiedElement:
        ComputedValue
MElement:
        Module
MElement:
        ModuleMember
MElementReference:
        alias::String referencedElement::MElement
Module:
        imports::ImportDirective+ exports::ExportDirective+ moduleMembers::ModuleMember+
ModuleMember:
        DerivedType
ModuleMember:
        Language
ModuleMember:
        Entity
ImportDirective:
        module::Module importedElements::MElementReference+
ExportDirective:
        module::Module exportedElements::ModuleMember+
Value:
        NumericalValue
Value:
        StringValue
Value:
        BooleanValue
NumericalValue:
        IntegerValue
NumericalValue:
        DecimalValue
StringValue:
        value::String
IntegerValue:
        value::Integer
DecimalValue:
        value::Double
BooleanValue:
        value::Boolean
