Makefile:
        name::ANY comment::ANY elements::ANY+
Element:
        EPSILON
Rule:
        dependencies::ANY+ shellLines::ANY+
Macro:
        value::ANY
ShellLine:
        command::ANY display::ANY ruleShellLine::ANY
Comment:
        text::ANY
Dependency:
        EPSILON
RuleDep:
        ruledep::ANY
FileDep:
        name::ANY
