RelationshipType:
        rt_related to::EPSILON
        rt_parent of::EPSILON
        rt_child of::EPSILON
        rt_duplicate of::EPSILON
        rt_has duplicate::EPSILON
MantisRoot:
        issues::ANY+
IdentifiedElt:
        EPSILON
PrivateElt:
        EPSILON
Issue:
        i_mantisRoot::ANY project::ANY category::ANY priority::ANY severity::ANY status::ANY reporter::ANY summary::ANY description::ANY version::ANY build::ANY platform::ANY os::ANY osVersion::ANY reproducibility::ANY stepsToReproduce::ANY additionalInfo::ANY dateSubmitted::ANY assignedTo::ANY projection::ANY eta::ANY resolution::ANY fixedInVersion::ANY attachments::ANY+ relationships::ANY+ notes::ANY+ lastUpdate::ANY
ValueWithId:
        value::ANY
Person:
        login::ANY
Relationship:
        type::ANY
TimeStampedElt:
        EPSILON
Note:
        author::ANY text::ANY
Attachment:
        filename::ANY size::ANY contentType::ANY downloadUrl::ANY
