Element:
        Comment
Element:
        NamedElement
Element:
        TemplateableElement
Element:
        Relationship
Element:
        TemplateSignature
Element:
        TemplateParameter
Element:
        ParameterableElement
Element:
        TemplateParameterSubstitution
Element:
        MultiplicityElement
Element:
        Image
Element:
        ActivityGroup
Element:
        Slot
Element:
        ExceptionHandler
Comment:
        body::MARTE_PrimitivesTypes/String annotatedElement::Element+
Package:
        Profile
Package:
        ownedType::Type+ packageMerge::PackageMerge+ packagedElement::PackageableElement+ nestedPackage::Package+ nestingPackage::Package profileApplication::ProfileApplication+
NamedElement:
        Namespace
NamedElement:
        TypedElement
NamedElement:
        RedefinableElement
NamedElement:
        DeploymentTarget
NamedElement:
        CollaborationUse
NamedElement:
        Message
NamedElement:
        Lifeline
NamedElement:
        Trigger
NamedElement:
        Vertex
NamedElement:
        ParameterSet
NamedElement:
        DeployedArtifact
NamedElement:
        MessageEnd
NamedElement:
        InteractionFragment
NamedElement:
        GeneralOrdering
NamedElement:
        PackageableElement
NamedElement:
        ActivityPartition
NamedElement:
        Include
NamedElement:
        Extend
StructuralFeature:
        Property
ConnectableElement:
        Parameter
ConnectableElement:
        Variable
TemplateableElement:
        StringExpression
Property:
        Port
Property:
        class::Class datatype::DataType owningAssociation::Association association::Association isDerived::MARTE_PrimitivesTypes/Boolean isDerivedUnion::MARTE_PrimitivesTypes/Boolean default::MARTE_PrimitivesTypes/String aggregation::AggregationKind isComposite::MARTE_PrimitivesTypes/Boolean redefinedProperty::Property+ defaultValue::ValueSpecification opposite::Property subsettedProperty::Property+ qualifier::Property+ associationEnd::Property
VisibilityKind:
        public::EPSILON
        private::EPSILON
        protected::EPSILON
        package::EPSILON
Dependency:
        Abstraction
Dependency:
        Deployment
Dependency:
        supplier::NamedElement+ client::NamedElement+
DirectedRelationship:
        ElementImport
DirectedRelationship:
        PackageImport
DirectedRelationship:
        TemplateBinding
DirectedRelationship:
        Generalization
DirectedRelationship:
        PackageMerge
DirectedRelationship:
        ProfileApplication
DirectedRelationship:
        ProtocolConformance
DirectedRelationship:
        Dependency
DirectedRelationship:
        Include
DirectedRelationship:
        Extend
Relationship:
        DirectedRelationship
Relationship:
        Association
Namespace:
        Package
Namespace:
        Classifier
Namespace:
        BehavioralFeature
Namespace:
        Region
Namespace:
        Transition
Namespace:
        State
Namespace:
        InteractionOperand
ElementImport:
        visibility::VisibilityKind alias::MARTE_PrimitivesTypes/String importedElement::PackageableElement importingNamespace::Namespace
PackageImport:
        visibility::VisibilityKind importedPackage::Package importingNamespace::Namespace
Constraint:
        IntervalConstraint
Constraint:
        InteractionConstraint
Constraint:
        constrainedElement::Element+ specification::ValueSpecification context::Namespace
TypedElement:
        ConnectableElement
TypedElement:
        ValueSpecification
TypedElement:
        ObjectNode
Association:
        Extension
Association:
        isDerived::MARTE_PrimitivesTypes/Boolean ownedEnd::Property+ endType::Type+ memberEnd::Property navigableOwnedEnd::Property+
Classifier:
        BehavioredClassifier
Classifier:
        DataType
Classifier:
        Signal
Classifier:
        Interface
Classifier:
        StructuredClassifier
Classifier:
        Association
Classifier:
        Artifact
RedefinableElement:
        Feature
RedefinableElement:
        ExtensionPoint
RedefinableElement:
        ActivityNode
RedefinableElement:
        ActivityEdge
RedefinableElement:
        Region
RedefinableElement:
        Transition
TemplateBinding:
        signature::TemplateSignature parameterSubstitution::TemplateParameterSubstitution+ boundElement::TemplateableElement
TemplateSignature:
        parameter::TemplateParameter+ ownedParameter::TemplateParameter+ template::TemplateableElement
TemplateParameter:
        signature::TemplateSignature parameteredElement::ParameterableElement ownedParameteredElement::ParameterableElement default::ParameterableElement ownedDefault::ParameterableElement
ParameterableElement:
        ConnectableElement
ParameterableElement:
        PackageableElement
TemplateParameterSubstitution:
        formal::TemplateParameter actual::ParameterableElement+ ownedActual::ParameterableElement+ templateBinding::TemplateBinding
Generalization:
        isSubstitutable::MARTE_PrimitivesTypes/Boolean general::Classifier generalizationSet::GeneralizationSet+ specific::Classifier
GeneralizationSet:
        isCovering::MARTE_PrimitivesTypes/Boolean isDisjoint::MARTE_PrimitivesTypes/Boolean powertype::Classifier generalization::Generalization+
Feature:
        Connector
Feature:
        StructuralFeature
Feature:
        BehavioralFeature
Substitution:
        contract::Classifier substitutingClassifier::Classifier
PackageableElement:
        Constraint
PackageableElement:
        Type
PackageableElement:
        GeneralizationSet
PackageableElement:
        Observation
PackageableElement:
        Event
PackageableElement:
        Dependency
PackageableElement:
        ValueSpecification
PackageMerge:
        mergedPackage::Package receivingPackage::Package
ProfileApplication:
        appliedProfile::Profile isStrict::MARTE_PrimitivesTypes/Boolean applyingPackage::Package
Profile:
        ownedStereotype::Stereotype+ metaclassReference::ElementImport+ metamodelReference::PackageImport+
Stereotype:
        icon::Image+
Class:
        Stereotype
Class:
        Behavior
Class:
        nestedClassifier::Classifier+ ownedOperation::Operation+ superClass::Class+ isActive::MARTE_PrimitivesTypes/Boolean ownedReception::Reception+ extension::Extension+
StringExpression:
        subExpression::StringExpression+ owningExpression::StringExpression
Expression:
        StringExpression
Expression:
        symbol::MARTE_PrimitivesTypes/String operand::ValueSpecification+
ValueSpecification:
        Expression
ValueSpecification:
        OpaqueExpression
ValueSpecification:
        TimeExpression
ValueSpecification:
        Duration
ValueSpecification:
        Interval
BehavioredClassifier:
        UseCase
BehavioredClassifier:
        Collaboration
BehavioredClassifier:
        Class
Behavior:
        StateMachine
Behavior:
        Activity
Behavior:
        Interaction
MultiplicityElement:
        ConnectorEnd
MultiplicityElement:
        Parameter
MultiplicityElement:
        Pin
MultiplicityElement:
        Variable
DeploymentTarget:
        InstanceSpecification
DataType:
        Enumeration
DataType:
        ownedAttribute::Property+ ownedOperation::Operation+
AggregationKind:
        none::EPSILON
        shared::EPSILON
        composite::EPSILON
CollaborationUse:
        type::Collaboration roleBinding::Dependency+
UseCase:
        include::Include+ extend::Extend+ extensionPoint::ExtensionPoint+ subject::Classifier+
Realization:
        Substitution
Realization:
        InterfaceRealization
Realization:
        Substitution
        InterfaceRealization
Abstraction:
        Realization
Abstraction:
        Manifestation
Abstraction:
        mapping::OpaqueExpression
Image:
        content::MARTE_PrimitivesTypes/String location::MARTE_PrimitivesTypes/String format::MARTE_PrimitivesTypes/String
OpaqueExpression:
        body::MARTE_PrimitivesTypes/String+ language::MARTE_PrimitivesTypes/String+ result::Parameter behavior::Behavior
Parameter:
        direction::ParameterDirectionKind default::MARTE_PrimitivesTypes/String defaultValue::ValueSpecification operation::Operation parameterSet::ParameterSet+ isException::MARTE_PrimitivesTypes/Boolean isStream::MARTE_PrimitivesTypes/Boolean effect::ParameterEffectKind
EncapsulatedClassifier:
        Class
Operation:
        interface::Interface class::Class isQuery::MARTE_PrimitivesTypes/Boolean isOrdered::MARTE_PrimitivesTypes/Boolean isUnique::MARTE_PrimitivesTypes/Boolean lower::MARTE_PrimitivesTypes/Integer upper::MARTE_PrimitivesTypes/UnlimitedNatural precondition::Constraint+ postcondition::Constraint+ redefinedOperation::Operation+ datatype::DataType bodyCondition::Constraint type::Type
Reception:
        signal::Signal
Extension:
        isRequired::MARTE_PrimitivesTypes/Boolean metaclass::Class
EnumerationLiteral:
        enumeration::Enumeration
ActivityPartition:
        isDimension::MARTE_PrimitivesTypes/Boolean isExternal::MARTE_PrimitivesTypes/Boolean node::ActivityNode+ subpartition::ActivityPartition+ superPartition::ActivityPartition represents::Element edge::ActivityEdge+
Enumeration:
        ownedLiteral::EnumerationLiteral+
InstanceSpecification:
        EnumerationLiteral
InstanceSpecification:
        classifier::Classifier+ slot::Slot+ specification::ValueSpecification
BehavioralFeature:
        Reception
BehavioralFeature:
        Operation
Signal:
        ownedAttribute::Property+
TimeExpression:
        expr::ValueSpecification observation::Observation+
Observation:
        TimeObservation
Observation:
        DurationObservation
Duration:
        expr::ValueSpecification observation::Observation+
DurationInterval:
        min::ValueSpecification max::ValueSpecification
Interval:
        DurationInterval
Interval:
        TimeInterval
Interval:
        min::ValueSpecification max::ValueSpecification
TimeConstraint:
        firstEvent::MARTE_PrimitivesTypes/Boolean
IntervalConstraint:
        TimeConstraint
IntervalConstraint:
        DurationConstraint
IntervalConstraint:
        TimeConstraint
        DurationConstraint
TimeInterval:
        min::ValueSpecification max::ValueSpecification
DurationConstraint:
        firstEvent::MARTE_PrimitivesTypes/Boolean
TimeObservation:
        event::NamedElement firstEvent::MARTE_PrimitivesTypes/Boolean
DurationObservation:
        event::NamedElement firstEvent::MARTE_PrimitivesTypes/Boolean
ConnectorEnd:
        definingEnd::Property partWithPort::Property role::ConnectableElement
TimeEvent:
        isRelative::MARTE_PrimitivesTypes/Boolean when::ValueSpecification
Event:
        TimeEvent
Port:
        isBehavior::MARTE_PrimitivesTypes/Boolean isService::MARTE_PrimitivesTypes/Boolean required::Interface+ redefinedPort::Port+ provided::Interface+ protocol::ProtocolStateMachine
Action:
        InvocationAction
Action:
        StructuredActivityNode
Message:
        messageKind::MessageKind messageSort::MessageSort receiveEvent::MessageEnd sendEvent::MessageEnd connector::Connector interaction::Interaction argument::ValueSpecification+ signature::NamedElement
Lifeline:
        represents::ConnectableElement interaction::Interaction selector::ValueSpecification decomposedAs::PartDecomposition coveredBy::InteractionFragment+
Connector:
        type::Association redefinedConnector::Connector+ end::ConnectorEnd kind::ConnectorKind contract::Behavior+
Collaboration:
        collaborationRole::ConnectableElement+
Interface:
        ownedAttribute::Property+ ownedOperation::Operation+ nestedClassifier::Classifier+ redefinedInterface::Interface+ ownedReception::Reception+ protocol::ProtocolStateMachine
InterfaceRealization:
        contract::Interface implementingClassifier::BehavioredClassifier
Trigger:
        event::Event port::Port+
ProtocolStateMachine:
        conformance::ProtocolConformance+
StateMachine:
        ProtocolStateMachine
StateMachine:
        region::Region+ submachineState::State+ connectionPoint::Pseudostate+ extendedStateMachine::StateMachine+
ProtocolConformance:
        generalMachine::ProtocolStateMachine specificMachine::ProtocolStateMachine
Deployment:
        deployedArtifact::DeployedArtifact+ configuration::DeploymentSpecification+ location::DeploymentTarget
Include:
        addition::UseCase includingCase::UseCase
Extend:
        extendedCase::UseCase condition::Constraint extensionLocation::ExtensionPoint+ extension::UseCase
ExtensionPoint:
        useCase::UseCase
Region:
        subvertex::Vertex+ transition::Transition+ state::State extendedRegion::Region stateMachine::StateMachine
StructuredClassifier:
        EncapsulatedClassifier
StructuredClassifier:
        Collaboration
Vertex:
        Pseudostate
Vertex:
        ConnectionPointReference
Transition:
        kind::TransitionKind container::Region redefinedTransition::Transition guard::Constraint effect::Behavior trigger::Trigger+ target::Vertex source::Vertex
TransitionKind:
        internal::EPSILON
        local::EPSILON
        external::EPSILON
State:
        isComposite::MARTE_PrimitivesTypes/Boolean isOrthogonal::MARTE_PrimitivesTypes/Boolean isSimple::MARTE_PrimitivesTypes/Boolean isSubmachineState::MARTE_PrimitivesTypes/Boolean submachine::StateMachine connection::ConnectionPointReference+ connectionPoint::Pseudostate+ redefinedState::State stateInvariant::Constraint entry::Behavior exit::Behavior doActivity::Behavior deferrableTrigger::Trigger+ region::Region+
ParameterSet:
        parameter::Parameter+ condition::Constraint+
ActivityNode:
        ExecutableNode
ActivityNode:
        ObjectNode
ActivityGroup:
        InterruptibleActivityRegion
ActivityGroup:
        ActivityPartition
ParameterDirectionKind:
        in::EPSILON
        inout::EPSILON
        out::EPSILON
        return::EPSILON
ParameterEffectKind:
        create::EPSILON
        read::EPSILON
        update::EPSILON
        delete::EPSILON
InterruptibleActivityRegion:
        node::ActivityNode+ interruptingEdge::ActivityEdge+
DeployedArtifact:
        Artifact
Slot:
        definingFeature::StructuralFeature value::ValueSpecification+ owningInstance::InstanceSpecification
ExecutableNode:
        Action
OutputPin:
        isControl::MARTE_PrimitivesTypes/Boolean
Pin:
        OutputPin
Pin:
        InputPin
Pin:
        isControl::MARTE_PrimitivesTypes/Boolean
InputPin:
        isControl::MARTE_PrimitivesTypes/Boolean
MessageKind:
        complete::EPSILON
        lost::EPSILON
        found::EPSILON
        unknown::EPSILON
ExceptionHandler:
        handlerBody::ExecutableNode exceptionInput::ObjectNode exceptionType::Classifier+ protectedNode::ExecutableNode
ObjectNode:
        Pin
ObjectNodeOrderingKind:
        unordered::EPSILON
        ordered::EPSILON
        LIFO::EPSILON
        FIFO::EPSILON
MessageEnd:
        Gate
MessageSort:
        synchCall::EPSILON
        asynchCall::EPSILON
        asynchSignal::EPSILON
        createMessage::EPSILON
        deleteMessage::EPSILON
        reply::EPSILON
Interaction:
        lifeline::Lifeline+ fragment::InteractionFragment+ action::Action+ formalGate::Gate+ message::Message+
PartDecomposition:
        refersTo::Interaction actualGate::Gate+ argument::Action+
InteractionUse:
        PartDecomposition
InteractionUse:
        refersTo::Interaction actualGate::Gate+ argument::Action+
InteractionFragment:
        ExecutionSpecification
InteractionFragment:
        InteractionUse
InteractionFragment:
        OccurrenceSpecification
InteractionFragment:
        Interaction
InteractionFragment:
        InteractionOperand
ConnectorKind:
        assembly::EPSILON
        delegation::EPSILON
Pseudostate:
        kind::PseudostateKind stateMachine::StateMachine state::State
PseudostateKind:
        initial::EPSILON
        deepHistory::EPSILON
        shallowHistory::EPSILON
        join::EPSILON
        fork::EPSILON
        junction::EPSILON
        choice::EPSILON
        entryPoint::EPSILON
        exitPoint::EPSILON
        terminate::EPSILON
ConnectionPointReference:
        entry::Pseudostate+ exit::Pseudostate+ state::State
StructuredActivityNode:
        variable::Variable+ edge::ActivityEdge+ mustIsolate::MARTE_PrimitivesTypes/Boolean node::ActivityNode+
Variable:
        scope::StructuredActivityNode activityScope::Activity
Activity:
        structuredNode::StructuredActivityNode+ variable::Variable+ node::ActivityNode+ isReadOnly::MARTE_PrimitivesTypes/Boolean edge::ActivityEdge+ partition::ActivityPartition+ isSingleExecution::MARTE_PrimitivesTypes/Boolean group::ActivityGroup+
OccurrenceSpecification:
        toBefore::GeneralOrdering+ event::Event toAfter::GeneralOrdering+
DeploymentSpecification:
        deploymentLocation::MARTE_PrimitivesTypes/String executionLocation::MARTE_PrimitivesTypes/String deployment::Deployment
Gate:
        message::Message
Artifact:
        DeploymentSpecification
Artifact:
        fileName::MARTE_PrimitivesTypes/String nestedArtifact::Artifact+ manifestation::Manifestation+ ownedOperation::Operation+ ownedAttribute::Property+
GeneralOrdering:
        before::OccurrenceSpecification after::OccurrenceSpecification
Manifestation:
        utilizedElement::PackageableElement
InteractionOperand:
        guard::InteractionConstraint fragment::InteractionFragment+
InteractionConstraint:
        minint::ValueSpecification maxint::ValueSpecification
