Element:
        EPSILON
Comment:
        body::ANY annotatedElement::ANY+
Package:
        ownedType::ANY+ packageMerge::ANY+ packagedElement::ANY+ nestedPackage::ANY+ nestingPackage::ANY profileApplication::ANY+
NamedElement:
        EPSILON
StructuralFeature:
        EPSILON
ConnectableElement:
        EPSILON
TemplateableElement:
        EPSILON
Property:
        class::ANY datatype::ANY owningAssociation::ANY association::ANY isDerived::ANY isDerivedUnion::ANY default::ANY aggregation::ANY isComposite::ANY redefinedProperty::ANY+ defaultValue::ANY opposite::ANY subsettedProperty::ANY+ qualifier::ANY+ associationEnd::ANY
VisibilityKind:
        public::EPSILON
        private::EPSILON
        protected::EPSILON
        package::EPSILON
Dependency:
        supplier::ANY+ client::ANY+
DirectedRelationship:
        EPSILON
Relationship:
        EPSILON
Namespace:
        EPSILON
ElementImport:
        visibility::ANY alias::ANY importedElement::ANY importingNamespace::ANY
PackageImport:
        visibility::ANY importedPackage::ANY importingNamespace::ANY
Constraint:
        constrainedElement::ANY+ specification::ANY context::ANY
TypedElement:
        EPSILON
Type:
        EPSILON
Association:
        isDerived::ANY ownedEnd::ANY+ endType::ANY+ memberEnd::ANY navigableOwnedEnd::ANY+
Classifier:
        EPSILON
RedefinableElement:
        EPSILON
TemplateBinding:
        signature::ANY parameterSubstitution::ANY+ boundElement::ANY
TemplateSignature:
        parameter::ANY+ ownedParameter::ANY+ template::ANY
TemplateParameter:
        signature::ANY parameteredElement::ANY ownedParameteredElement::ANY default::ANY ownedDefault::ANY
ParameterableElement:
        EPSILON
TemplateParameterSubstitution:
        formal::ANY actual::ANY+ ownedActual::ANY+ templateBinding::ANY
Generalization:
        isSubstitutable::ANY general::ANY generalizationSet::ANY+ specific::ANY
GeneralizationSet:
        isCovering::ANY isDisjoint::ANY powertype::ANY generalization::ANY+
Feature:
        EPSILON
Substitution:
        contract::ANY substitutingClassifier::ANY
PackageableElement:
        EPSILON
PackageMerge:
        mergedPackage::ANY receivingPackage::ANY
ProfileApplication:
        appliedProfile::ANY isStrict::ANY applyingPackage::ANY
Profile:
        ownedStereotype::ANY+ metaclassReference::ANY+ metamodelReference::ANY+
Stereotype:
        icon::ANY+
Class:
        nestedClassifier::ANY+ ownedOperation::ANY+ superClass::ANY+ isActive::ANY ownedReception::ANY+ extension::ANY+
StringExpression:
        subExpression::ANY+ owningExpression::ANY
Expression:
        symbol::ANY operand::ANY+
ValueSpecification:
        EPSILON
BehavioredClassifier:
        EPSILON
Behavior:
        EPSILON
MultiplicityElement:
        EPSILON
DeploymentTarget:
        EPSILON
DataType:
        ownedAttribute::ANY+ ownedOperation::ANY+
AggregationKind:
        none::EPSILON
        shared::EPSILON
        composite::EPSILON
CollaborationUse:
        type::ANY roleBinding::ANY+
UseCase:
        include::ANY+ extend::ANY+ extensionPoint::ANY+ subject::ANY+
Realization:
        EPSILON
Abstraction:
        mapping::ANY
Image:
        content::ANY location::ANY format::ANY
OpaqueExpression:
        body::ANY+ language::ANY+ result::ANY behavior::ANY
Parameter:
        direction::ANY default::ANY defaultValue::ANY operation::ANY parameterSet::ANY+ isException::ANY isStream::ANY effect::ANY
EncapsulatedClassifier:
        EPSILON
Operation:
        interface::ANY class::ANY isQuery::ANY isOrdered::ANY isUnique::ANY lower::ANY upper::ANY precondition::ANY+ postcondition::ANY+ redefinedOperation::ANY+ datatype::ANY bodyCondition::ANY type::ANY
Reception:
        signal::ANY
Extension:
        isRequired::ANY metaclass::ANY
EnumerationLiteral:
        enumeration::ANY
ActivityPartition:
        isDimension::ANY isExternal::ANY node::ANY+ subpartition::ANY+ superPartition::ANY represents::ANY edge::ANY+
Enumeration:
        ownedLiteral::ANY+
InstanceSpecification:
        classifier::ANY+ slot::ANY+ specification::ANY
BehavioralFeature:
        EPSILON
Signal:
        ownedAttribute::ANY+
TimeExpression:
        expr::ANY observation::ANY+
Observation:
        EPSILON
Duration:
        expr::ANY observation::ANY+
DurationInterval:
        EPSILON
Interval:
        min::ANY max::ANY
TimeConstraint:
        firstEvent::ANY
IntervalConstraint:
        EPSILON
TimeInterval:
        EPSILON
DurationConstraint:
        firstEvent::ANY
TimeObservation:
        event::ANY firstEvent::ANY
DurationObservation:
        event::ANY firstEvent::ANY
ConnectorEnd:
        definingEnd::ANY partWithPort::ANY role::ANY
TimeEvent:
        isRelative::ANY when::ANY
Event:
        EPSILON
Port:
        isBehavior::ANY isService::ANY required::ANY+ redefinedPort::ANY+ provided::ANY+ protocol::ANY
Action:
        EPSILON
Message:
        messageKind::ANY messageSort::ANY receiveEvent::ANY sendEvent::ANY connector::ANY interaction::ANY argument::ANY+ signature::ANY
Lifeline:
        represents::ANY interaction::ANY selector::ANY decomposedAs::ANY coveredBy::ANY+
ExecutionSpecification:
        EPSILON
InvocationAction:
        EPSILON
Connector:
        type::ANY redefinedConnector::ANY+ end::ANY kind::ANY contract::ANY+
Collaboration:
        collaborationRole::ANY+
Interface:
        ownedAttribute::ANY+ ownedOperation::ANY+ nestedClassifier::ANY+ redefinedInterface::ANY+ ownedReception::ANY+ protocol::ANY
InterfaceRealization:
        contract::ANY implementingClassifier::ANY
Trigger:
        event::ANY port::ANY+
ProtocolStateMachine:
        conformance::ANY+
StateMachine:
        region::ANY+ submachineState::ANY+ connectionPoint::ANY+ extendedStateMachine::ANY+
ProtocolConformance:
        generalMachine::ANY specificMachine::ANY
Deployment:
        deployedArtifact::ANY+ configuration::ANY+ location::ANY
Include:
        addition::ANY includingCase::ANY
Extend:
        extendedCase::ANY condition::ANY extensionLocation::ANY+ extension::ANY
ExtensionPoint:
        useCase::ANY
Region:
        subvertex::ANY+ transition::ANY+ state::ANY extendedRegion::ANY stateMachine::ANY
StructuredClassifier:
        EPSILON
Vertex:
        EPSILON
Transition:
        kind::ANY container::ANY redefinedTransition::ANY guard::ANY effect::ANY trigger::ANY+ target::ANY source::ANY
TransitionKind:
        internal::EPSILON
        local::EPSILON
        external::EPSILON
State:
        isComposite::ANY isOrthogonal::ANY isSimple::ANY isSubmachineState::ANY submachine::ANY connection::ANY+ connectionPoint::ANY+ redefinedState::ANY stateInvariant::ANY entry::ANY exit::ANY doActivity::ANY deferrableTrigger::ANY+ region::ANY+
ParameterSet:
        parameter::ANY+ condition::ANY+
ActivityNode:
        EPSILON
ActivityGroup:
        EPSILON
ParameterDirectionKind:
        in::EPSILON
        inout::EPSILON
        out::EPSILON
        return::EPSILON
ParameterEffectKind:
        create::EPSILON
        read::EPSILON
        update::EPSILON
        delete::EPSILON
ActivityEdge:
        EPSILON
InterruptibleActivityRegion:
        node::ANY+ interruptingEdge::ANY+
DeployedArtifact:
        EPSILON
Slot:
        definingFeature::ANY value::ANY+ owningInstance::ANY
ExecutableNode:
        EPSILON
OutputPin:
        EPSILON
Pin:
        isControl::ANY
InputPin:
        EPSILON
MessageKind:
        complete::EPSILON
        lost::EPSILON
        found::EPSILON
        unknown::EPSILON
ExceptionHandler:
        handlerBody::ANY exceptionInput::ANY exceptionType::ANY+ protectedNode::ANY
ObjectNode:
        EPSILON
ObjectNodeOrderingKind:
        unordered::EPSILON
        ordered::EPSILON
        LIFO::EPSILON
        FIFO::EPSILON
MessageEnd:
        EPSILON
MessageSort:
        synchCall::EPSILON
        asynchCall::EPSILON
        asynchSignal::EPSILON
        createMessage::EPSILON
        deleteMessage::EPSILON
        reply::EPSILON
Interaction:
        lifeline::ANY+ fragment::ANY+ action::ANY+ formalGate::ANY+ message::ANY+
PartDecomposition:
        EPSILON
InteractionUse:
        refersTo::ANY actualGate::ANY+ argument::ANY+
InteractionFragment:
        EPSILON
ConnectorKind:
        assembly::EPSILON
        delegation::EPSILON
Pseudostate:
        kind::ANY stateMachine::ANY state::ANY
PseudostateKind:
        initial::EPSILON
        deepHistory::EPSILON
        shallowHistory::EPSILON
        join::EPSILON
        fork::EPSILON
        junction::EPSILON
        choice::EPSILON
        entryPoint::EPSILON
        exitPoint::EPSILON
        terminate::EPSILON
ConnectionPointReference:
        entry::ANY+ exit::ANY+ state::ANY
StructuredActivityNode:
        variable::ANY+ edge::ANY+ mustIsolate::ANY node::ANY+
Variable:
        scope::ANY activityScope::ANY
Activity:
        structuredNode::ANY+ variable::ANY+ node::ANY+ isReadOnly::ANY edge::ANY+ partition::ANY+ isSingleExecution::ANY group::ANY+
OccurrenceSpecification:
        toBefore::ANY+ event::ANY toAfter::ANY+
DeploymentSpecification:
        deploymentLocation::ANY executionLocation::ANY deployment::ANY
Gate:
        message::ANY
Artifact:
        fileName::ANY nestedArtifact::ANY+ manifestation::ANY+ ownedOperation::ANY+ ownedAttribute::ANY+
GeneralOrdering:
        before::ANY after::ANY
Manifestation:
        utilizedElement::ANY
InteractionOperand:
        guard::ANY fragment::ANY+
InteractionConstraint:
        minint::ANY maxint::ANY
