Agent:
        service::ANY+ non_Functionnal_Requirement::ANY+ requirement::ANY+ belongs::ANY cooperationRules::ANY+ fipa_Platform_Agent::ANY role::ANY representation::ANY characteristic::ANY skill::ANY aptitude::ANY
Service:
        inputs::ANY outputs::ANY pre-conditions::ANY post-conditions::ANY
Non Functionnal Requirement:
        EPSILON
Requirement:
        EPSILON
Organization:
        observes::ANY+ organizational_Structure::ANY
Organizational Structure:
        organization::ANY+
SafetyRule:
        EPSILON
LivenessRule:
        EPSILON
CooperationRules:
        ncs::ANY
NCS:
        cooperationRules::ANY
FIPA-Platform Agent:
        agentF::ANY fipa_Platform_Task::ANY+
FIPA-Platform Task:
        fipa_Platform_AgentF::ANY task::ANY
Task:
        name::ANY fipa_Platform_TaskT::ANY
Role:
        agentR::ANY activity::ANY+ actsOn::ANY+ scenario::ANY+ participant::ANY+ has::ANY+
Representation:
        agentRep::ANY ontology::ANY environnement::ANY
Characteristic:
        agentC::ANY
Skill:
        agentS::ANY
Aptitude:
        agentA::ANY
Ontology:
        environnement::ANY
Concept:
        EPSILON
Predicat:
        EPSILON
Action:
        EPSILON
Environnement:
        resource::ANY
Responsibility:
        EPSILON
LivenessProperty:
        EPSILON
SafetyProperty:
        EPSILON
Resource:
        name::ANY environnement::ANY action::ANY
Communication:
        name::ANY Exchanged Knoledge::ANY scenario::ANY+ aip::ANY message::ANY+
AIP:
        name::ANY performative::ANY
Performative:
        aip::ANY
Message:
        communication::ANY Comm_Act::ANY
Scenario:
        EPSILON
