Matlab:
        model::ANY+
BlockDefaults:
        blockDefaults::ANY model::ANY
Model:
        name::ANY matlab::ANY annotationDefaults::ANY+ system::ANY+ blockDefaults::ANY+ lineDefaults::ANY+ simulink::ANY
AnnotationDefaults:
        annotationDefaults::ANY model::ANY
LineDefaults:
        lineDefaults::ANY model::ANY
System:
        name::ANY blocks::ANY+ lines::ANY+ annotations::ANY+ model::ANY parentSubsystem::ANY
Subsystem:
        system::ANY
Block:
        name::ANY blockType::ANY description::ANY priority::ANY tag::ANY position::ANY mySystem::ANY ports::ANY+
Annotation:
        position::ANY text::ANY system::ANY
Line:
        points::ANY id::ANY srcPort::ANY system::ANY
DirectLine:
        destPort1::ANY
InputPort:
        owningDirectLine::ANY owningDirectBranch::ANY
Branch:
        points::ANY branchedLine::ANY nestedBranch::ANY
BranchedLine:
        branchs::ANY+
Primitive:
        id::ANY parameters::ANY+ refPort::ANY
Port:
        id::ANY number::ANY portBlock::ANY primitive::ANY
Reference:
        sourceType::ANY sourceBlock::ANY parameters::ANY+
Masked:
        EPSILON
Normal:
        EPSILON
Parameter:
        name::ANY le_reference::ANY primitive::ANY
OutputPort:
        owningLine::ANY
Type:
        value::ANY
Double:
        value::ANY
INteger:
        value::ANY
Enumeration:
        value::ANY
BOolean:
        value::ANY
TrueFalse:
        True::EPSILON
        False::EPSILON
Text:
        value::ANY
Vector:
        value::ANY
DirectBranch:
        id::ANY destPort::ANY
NestedBranch:
        branchs::ANY+
Machine:
        name::ANY id::ANY events::ANY+ data::ANY+ instances::ANY+ targets::ANY+ stateFlow::ANY
Junction:
        _id::ANY id::ANY type::ANY position::ANY state::ANY chart::ANY
Transition:
        _id::ANY dataLimites::ANY id::ANY trigger::ANY condition::ANY conditionAction::ANY action::ANY chart::ANY state::ANY
Event:
        name::ANY id::ANY scope::ANY description::ANY trigger::ANY machine::ANY chart::ANY state::ANY
Data:
        name::ANY id::ANY scope::ANY description::ANY units::ANY dataType::ANY props::ANY+ state::ANY chart::ANY machine::ANY
Instance:
        _id::ANY id::ANY name::ANY machine::ANY
Target:
        name::ANY id::ANY codeCommand::ANY description::ANY makeCommand::ANY codeFlags::ANY checksumOld::ANY machine::ANY
Chart:
        name::ANY id::ANY _id::ANY decomposotion::ANY updateMethode::ANY sampleTime::ANY junctions::ANY+ events::ANY+ transitions::ANY+ data::ANY+ states::ANY+
State:
        name::ANY id::ANY _id::ANY type::ANY entryAction::ANY exitAction::ANY duringAction::ANY eventActions::ANY decomposition::ANY position::ANY junctions::ANY+ events::ANY+ transitions::ANY+ data::ANY+ chart::ANY states::ANY+
Props:
        initialValue::ANY arrays::ANY+ ranges::ANY+ data::ANY
Range:
        maximum::ANY minimum::ANY props::ANY
Array:
        firstIndex::ANY size::ANY props::ANY
StateFlow:
        stateFlow::ANY machines::ANY+ simulink::ANY
TransitionTerminal:
        _id::ANY
Simulink:
        simulink::ANY stateFlows::ANY+ models::ANY+
