Project:
        id::ANY groupId::ANY artifactId::ANY name::ANY description::ANY mailingLists::ANY+ developersAndContributors::ANY+ build::ANY dependencies::ANY+
Build:
        defaultGoal::ANY sourceDirectory::ANY unitTestSourceDirectory::ANY uniTest::ANY+ resources::ANY+
Resource:
        targetPath::ANY filtering::ANY directory::ANY includes::ANY excludes::ANY
MailingList:
        name::ANY subscribe::ANY unsubscribe::ANY post::ANY archive::ANY otherArchives::ANY
Person:
        EPSILON
Developer:
        id::ANY
Contributor:
        name::ANY email::ANY url::ANY organization::ANY organizationUrl::ANY roles::ANY timezone::ANY properties::ANY
