Project:
        id::String groupId::String artifactId::String name::String description::String mailingLists::MailingList+ developersAndContributors::Person+ build::Build dependencies::Project+
Build:
        defaultGoal::String sourceDirectory::String unitTestSourceDirectory::String uniTest::Resource+ resources::Resource+
Resource:
        targetPath::String filtering::String directory::String includes::String excludes::String
MailingList:
        name::String subscribe::String unsubscribe::String post::String archive::String otherArchives::String
Person:
        Developer
Person:
        Contributor
Developer:
        id::String
Contributor:
        name::String email::String url::String organization::String organizationUrl::String roles::String timezone::String properties::String
