ModelKind:
        KM3::EPSILON
        UML2::EPSILON
RootMeasureSet:
        modelType::ANY categories::ANY+ measureSets::ANY+
Category:
        name::ANY desc::ANY metrics::ANY+ root::ANY
Metric:
        name::ANY desc::ANY preferredValue::ANY category::ANY
ElementKind:
        metamodel::EPSILON
        model::EPSILON
        package::EPSILON
        interface::EPSILON
        class::EPSILON
MeasureSet:
        elementName::ANY elementType::ANY measures::ANY+ root::ANY subsets::ANY+ parent::ANY
Measure:
        EPSILON
IntegerMeasure:
        value::ANY
DoubleMeasure:
        value::ANY
PercentageMeasure:
        value::ANY
