Metric:
        name::ANY values::ANY+
MetricValue:
        EPSILON
StringMetricValue:
        value::ANY
BooleanMetricValue:
        value::ANY
IntegerMetricValue:
        value::ANY
DoubleMetricValue:
        value::ANY
