Case:
        name::ANY caseMode::ANY caseInput::ANY documentation::ANY listOfStep::ANY+
Step:
        name::ANY description::ANY belongsToCase::ANY embedsOperator::ANY predecessors::ANY+ successors::ANY+
LoopStep:
        EPSILON
MultiStep:
        iterationCondition::ANY
Operator:
        EPSILON
Parameter:
        name::ANY place::ANY parameterType::ANY belongsToOperator::ANY
ParameterType:
        Value::EPSILON
        Concept::EPSILON
        RelationShip::EPSILON
        FeatureAttribute::EPSILON
FeatureConstruction:
        scalingFactor::ANY
DataMinStep:
        loopable::ANY numberOfInputParameters::ANY numberOfOutputParameters::ANY manual::ANY tool::ANY input::ANY+ output::ANY+ realizes::ANY
TimeOperator:
        loopable::ANY numberOfInputParameters::ANY numberOfOutputParameters::ANY manual::ANY tool::ANY input::ANY+ output::ANY+ realizes::ANY
FeatureSelection:
        loopable::ANY numberOfInputParameters::ANY numberOfOutputParameters::ANY manual::ANY tool::ANY input::ANY+ output::ANY+ realizes::ANY
MultiRelFeatureConstr:
        loopable::ANY numberOfInputParameters::ANY numberOfOutputParameters::ANY manual::ANY tool::ANY input::ANY+ output::ANY+ realizes::ANY
RowSelection:
        loopable::ANY numberOfInputParameters::ANY numberOfOutputParameters::ANY manual::ANY tool::ANY input::ANY+ output::ANY+ realizes::ANY
Agregation:
        EPSILON
Scaling:
        EPSILON
Discretization:
        EPSILON
Segmentation:
        EPSILON
Sampling:
        EPSILON
ExecutionElement:
        source::ANY target::ANY
DataObject:
        source::ANY target::ANY
MSL-Tool:
        EPSILON
TransformationGroup:
        transformation::ANY+
Transformation:
        transformationGroup::ANY
Function:
        nameOf::ANY signature::ANY
StoredProcedure:
        nameOf::ANY signature::ANY
SQLQuery:
        EPSILON
ModelElement:
        EPSILON
Classifier:
        EPSILON
StructuralFeature:
        EPSILON
Class:
        name::ANY attributes::ANY+
DataType:
        attribute::ANY
Attribute:
        class::ANY has::ANY
