ModelElement:
        Classifier
ModelElement:
        StructuralFeature
ModelElement:
        Classifier
        StructuralFeature
Classifier:
        Class
Classifier:
        DataType
Classifier:
        Class
        DataType
StructuralFeature:
        Attribute
Class:
        Concept
Class:
        ColumnSet
Class:
        name::String attributes::Attribute+
DataType:
        Integer
DataType:
        String
DataType:
        DomainDataType
DataType:
        attribute::Attribute
Attribute:
        Column
Attribute:
        FeatureAttribute
Attribute:
        Value
Attribute:
        RoleRestriction
Attribute:
        class::Class has::DataType
Concept:
        name::String attributes::Attribute+
ColumnSet:
        name::String attributes::Attribute+
Column:
        class::Class has::DataType
FeatureAttribute:
        class::Class has::DataType
Value:
        class::Class has::DataType
RoleRestriction:
        class::Class has::DataType
Integer:
        attribute::Attribute
String:
        attribute::Attribute
DomainDataType:
        attribute::Attribute
