ModelElement:
        EPSILON
Classifier:
        EPSILON
StructuralFeature:
        EPSILON
Class:
        name::ANY attributes::ANY+
DataType:
        attribute::ANY
Attribute:
        class::ANY has::ANY
Concept:
        EPSILON
ColumnSet:
        EPSILON
Column:
        EPSILON
FeatureAttribute:
        EPSILON
Value:
        EPSILON
RoleRestriction:
        EPSILON
Integer:
        EPSILON
String:
        EPSILON
DomainDataType:
        EPSILON
