ModelElement:
        Classifier
ModelElement:
        StructuralFeature
ModelElement:
        Classifier
        StructuralFeature
Classifier:
        Class
Classifier:
        DataType
Classifier:
        Class
        DataType
StructuralFeature:
        Attribute
StructuralFeature:
        Attribute
Class:
        Concept
Class:
        ColumnSet
Class:
        name::String attributes::Attribute+
DataType:
        Integer
DataType:
        String
DataType:
        DomainDataType
DataType:
        attribute::Attribute
Attribute:
        Column
Attribute:
        FeatureAttribute
Attribute:
        Value
Attribute:
        RoleRestriction
Attribute:
        class::Class has::DataType
Concept:
        EPSILON
ColumnSet:
        EPSILON
Column:
        EPSILON
FeatureAttribute:
        EPSILON
Value:
        EPSILON
RoleRestriction:
        EPSILON
Integer:
        EPSILON
String:
        EPSILON
DomainDataType:
        EPSILON
