String:
        STR
Integer:
        INT
Boolean:
        "true"
        "false"
InOut:
        Input::EPSILON
        OutPut::EPSILON
LinkPackage:
        type::InOut dataObject::CaseRepresentation/DataObject value::DataRepresentation/Value column::DataRepresentation/Column columnSet::DataRepresentation/ColumnSet
