Action:
        time::DvTemporal description::ItemStructure ismTransition::DvCodedString instructionDetails::DvCodedString
Activity:
        description::ItemStructure timing::DvParsable actions::DvToken+
AdminEntry:
        data::ItemStructure
ASKR:
        EPSILON
ASKU:
        NAV
ASKU:
        NAV
Attestation:
        attestedView::DvMedia proof::DvParsable reason::DvCodedString commiter::PartyProxy timeCommited::DvTemporal isPending::DvBoolean
CareEntry:
        Action
CareEntry:
        Evaluation
CareEntry:
        Instruction
CareEntry:
        Observation
CCD:
        definition::Locatable metaData::MetaDataSet+ ontology::Ontology
Cluster:
        items::Item+
Composition:
        attestation::Attestation links::Link+ original::DvToken predecessor::DvToken created::DvTemporal composer::PartyProxy territory::Location category::DvCodedString language::DvLanguage context::EventContext content::Locatable
ContentItem:
        Entry
ContentItem:
        Section
DataStructure:
        History
DataStructure:
        ItemStructure
DER:
        EPSILON
Device:
        details::ItemStructure
DvAny:
        DvBoolean
DvAny:
        DvChar
DvAny:
        DvEncapsulated
DvAny:
        DvInterval
DvAny:
        DvNumeric
DvAny:
        DvOrdered
DvAny:
        DvParagraph
DvAny:
        DvURI
DvAny:
        PartyProxy
DvAny:
        ReferenceRange
DvBoolean:
        dv::ANY
DvByte:
        dv::ANY
DvChar:
        DvLanguage
DvChar:
        DvNormalizedString
DvChar:
        DvString
DvChar:
        DvToken
DvCodedString:
        codeString::ANY terminologyName::ANY terminologyAbbrev::ANY
DvCount:
        count::ANY
DvDate:
        dv::ANY
DvDateTime:
        dv::ANY
DvDecimal:
        dv::ANY
DvDuration:
        dv::ANY
DvEncapsulated:
        DvMedia
DvEncapsulated:
        DvParsable
DvIdentifier:
        issuer::ANY assigner::ANY name::ANY
DvInt:
        dv::INT
DvInteger:
        dv::ANY
DvInterval:
        lower::DvOrdered upper::DvOrdered lowerIncluded::ANY upperIncluded::ANY lowerUnbounded::ANY upperUnbounded::ANY
DvLanguage:
        dv::ANY
DvLong:
        dv::ANY
DvMedia:
        DvMediaApp
DvMedia:
        DvMediaAudio
DvMedia:
        DvMediaImage
DvMedia:
        DvMediaModel
DvMedia:
        DvMediaMsg
DvMedia:
        DvMediaMultipart
DvMedia:
        DvMediaText
DvMedia:
        DvMediaVideo
DvMediaApp:
        dv::ANY
DvMediaAudio:
        dv::ANY
DvMediaImage:
        dv::ANY
DvMediaModel:
        dv::ANY
DvMediaMsg:
        dv::ANY
DvMediaMultipart:
        dv::ANY
DvMediaText:
        dv::STR
DvMediaVideo:
        dv::ANY
DvNegativeInteger:
        dv::ANY
DvNonNegativeInteger:
        dv::ANY
DvNonPositiveInteger:
        dv::ANY
DvNormalizedString:
        uuid::ANY language::ANY dv::ANY
DvNumeric:
        DvByte
DvNumeric:
        DvDecimal
DvNumeric:
        DvInt
DvNumeric:
        DvInteger
DvNumeric:
        DvLong
DvNumeric:
        DvNegativeInteger
DvNumeric:
        DvNonNegativeInteger
DvNumeric:
        DvNonPositiveInteger
DvNumeric:
        DvPositiveInteger
DvNumeric:
        DvShort
DvNumeric:
        DvUnsignedByte
DvNumeric:
        DvUnsignedInt
DvNumeric:
        DvUnsignedLong
DvNumeric:
        DvUnsignedShort
DvOrdered:
        DvOrdinal
DvOrdered:
        DvQuantified
DvOrdinal:
        dv::ANY symbol::STR
DvParagraph:
        items::DvString+
DvParsable:
        dv::ANY formalism::ANY
DvPositiveInteger:
        dv::ANY
DvProportion:
        proportionType::ANY
DvQuantified:
        DvCount
DvQuantified:
        DvQuantity
DvQuantified:
        DvRatio
DvQuantity:
        units::ANY
DvRate:
        rateType::ANY
DvRatio:
        DvProportion
DvRatio:
        DvRate
DvShort:
        dv::ANY
DvString:
        DvCodedString
DvString:
        DvIdentifier
DvString:
        uuid::ANY language::ANY dv::STR
DvTemporal:
        DvDate
DvTemporal:
        DvDateTime
DvTemporal:
        DvDuration
DvTemporal:
        DvTime
DvTime:
        dv::ANY
DvToken:
        dv::ANY
DvUnsignedByte:
        dv::ANY
DvUnsignedInt:
        dv::ANY
DvUnsignedLong:
        dv::ANY
DvUnsignedShort:
        dv::ANY
DvURI:
        dv::ANY
Element:
        dv::DvAny
EntityRef:
        uuid::ANY namespace::ANY objType::ANY
Entry:
        AdminEntry
Entry:
        CareEntry
Evaluation:
        data::ItemStructure
Event:
        IntervalEvent
Event:
        PointEvent
EventContext:
        healthcareFacility::Organization startTime::DvTemporal endTime::DvTemporal participation::Participation location::Location setting::DvCodedString
ExceptionalValue:
        NI
FeederAudit:
        originatingSystemAudit::FeederAuditDetails originatingSystemItemIds::DvIdentifier+ feederSystemAudit::FeederAuditDetails feederSystemIds::DvIdentifier+ originalContent::DvEncapsulated
FeederAuditDetails:
        systemId::DvIdentifier versionId::DvNormalizedString provider::PartyIdentified location::Location time::DvTemporal subject::PartyProxy+
Folder:
        items::Composition+
Group:
        members::Party+
History:
        origin::DvTemporal events::Event+ period::DvDuration duration::DvDuration summary::ItemStructure
Instruction:
        expiryTime::DvTemporal narrative::DvString wfDefinition::DvParsable activities::Activity+
IntervalEvent:
        width::DvDuration mathFunction::DvCodedString sampleCount::DvCount
INV:
        DER
INV:
        OTH
INV:
        UNC
INV:
        DER
        OTH
        UNC
Item:
        Cluster
Item:
        Element
Item:
        Slot
ItemList:
        items::Item+
ItemSingle:
        item::Item
ItemStructure:
        ItemList
ItemStructure:
        ItemSingle
ItemStructure:
        ItemTable
ItemStructure:
        ItemTree
ItemTable:
        rows::Cluster+
ItemTree:
        items::Item+
Link:
        relation::Relationship target::DvToken
Locatable:
        Activity
Locatable:
        Attestation
Locatable:
        Composition
Locatable:
        ContentItem
Locatable:
        DataStructure
Locatable:
        Event
Locatable:
        EventContext
Locatable:
        Folder
Locatable:
        Item
Locatable:
        Location
Locatable:
        Party
Locatable:
        Relationship
Locatable:
        Role
Location:
        details::ItemStructure description::DvString isPrimary::DvBoolean
MetaDataEntry:
        title::STR contents::STR
MetaDataSet:
        name::STR entries::MetaDataEntry+
MSK:
        EPSILON
NA:
        EPSILON
NASK:
        EPSILON
NAV:
        EPSILON
NI:
        INV
NI:
        MSK
NI:
        NA
NI:
        UNK
NI:
        INV
        MSK
        NA
        UNK
NINF:
        EPSILON
NonHuman:
        details::ItemStructure
ObjectRef:
        EntityRef
ObjectRef:
        uuid::ANY namespace::ANY objType::ANY
Observation:
        data::History state::History
Ontology:
        names::STR+ internalVocabularies::STR+ lookupTables::STR+ terminologies::STR+ generalEntries::OntologyEntry+
OntologyEntry:
        contents::STR+
Organization:
        details::ItemStructure
OTH:
        NINF
OTH:
        PINF
OTH:
        NINF
        PINF
Participation:
        performer::PartyProxy function::DvCodedString mode::DvCodedString time::DvTemporal
Party:
        Device
Party:
        Group
Party:
        NonHuman
Party:
        Organization
Party:
        Person
PartyIdentified:
        PartyRelated
PartyIdentified:
        name::DvString identifiers::DvIdentifier+
PartyProxy:
        PartyIdentified
PartyProxy:
        PartySelf
PartyRelated:
        relationship::Relationship
PartySelf:
        externalRef::EntityRef
Person:
        details::ItemStructure
PINF:
        EPSILON
PointEvent:
        time::DvTemporal data::DvAny state::ItemStructure
QS:
        EPSILON
ReferenceRange:
        definition::DvString dataRange::DvInterval
Relationship:
        targets::DvToken+
Role:
        details::ItemStructure description::DvString isPrimary::DvBoolean
Section:
        items::ContentItem+
Slot:
        ccd::DvToken allowedCcds::DvToken+
TRC:
        EPSILON
UNC:
        EPSILON
UNK:
        ASKR
UNK:
        ASKU
UNK:
        NASK
UNK:
        QS
UNK:
        TRC
UNK:
        ASKR
        ASKU
        NASK
        QS
        TRC
