Element:
        EPSILON
MoDAFModel:
        enterprise::ANY environment::ANY operationalMissions::ANY+ architectures::ANY+ architecturalDescription::ANY+ architecturalReferences::ANY+ architecturalFrameworks::ANY+ architectureMetadatas::ANY+ metaDatas::ANY+ stakeholders::ANY+ stakeholderHasConcerns::ANY+
Enterprise:
        inhabits::ANY fulfills::ANY+
Environment:
        influences::ANY
OperationalMission:
        name::ANY content::ANY
Architecture:
        enterprise::ANY describedBy::ANY
ArchitecturalDescription:
        approvialAuthority::ANY architect::ANY assumptionAndConstraints::ANY creatingOrganisation::ANY dateCompleted::ANY purpose::ANY recommendations::ANY summaryOfFindings::ANY tollsUsed::ANY viewpoints::ANY+ products::ANY+ taxonomy::ANY
ArchitecturalReference:
        referred::ANY referrer::ANY
ArchitecturalProduct:
        description::ANY architecturalElements::ANY+ definingView::ANY addresses::ANY+
Elements:
        name::ANY content::ANY
ArchitecturalFramework:
        ownedMember::ANY+
View:
        framework::ANY frameworkWebsite::ANY viewCode::ANY viewDescription::ANY viewName::ANY definingFramework::ANY usedToCover::ANY+
Concern:
        adressedBy::ANY+
StakeholderHasConcern:
        client::ANY supplier::ANY owner::ANY
Stakeholder:
        name::ANY content::ANY
MetaData:
        dublinCoreElement::ANY modMetaDataElement::ANY name::ANY body::ANY
ArchitectureMetaData:
        annotatedArchitecture::ANY
Taxonomy:
        date::ANY url::ANY version::ANY contents::ANY+
ClassifiedElement:
        EPSILON
Standard:
        identifier::ANY publishedWebsite::ANY publisher::ANY ratificationDate::ANY version::ANY withdrawalDate::ANY
MeasurableProperty:
        maxValue::ANY minValue::ANY
CapabilityRequirement:
        taxonomy::ANY
Effect:
        taxonomy::ANY
EnduringTask:
        taxonomy::ANY
OperationalConstraint:
        nodeUsageContext::ANY
PostType:
        taxonomy::ANY
OrganisationType:
        taxonomy::ANY
RoleInOrganisation:
        taxonomy::ANY
LocationType:
        taxonomy::ANY
OperationalActivity:
        taxonomy::ANY
Node:
        taxonomy::ANY
InformationExchange:
        identifier::ANY requirementText::ANY
Competence:
        taxonomy::ANY
InformationElement:
        taxonomy::ANY
NodeConnectionType:
        taxonomy::ANY
System:
        taxonomy::ANY
DataElement:
        taxonomy::ANY
SystemFunction:
        systemUsageContext::ANY
SystemConnectionSpecification:
        taxonomy::ANY
ProjectType:
        taxonomy::ANY
Service:
        taxonomy::ANY
Unit:
        taxonomy::ANY
Dimension:
        taxonomy::ANY
OrganisationProjectRelationship:
        taxonomy::ANY
ProjectThreadType:
        taxonomy::ANY
TimeExpression:
        value::ANY
LiteralSpecification:
        value::ANY
Property:
        value::ANY
