Element:
        MoDAFModel
Element:
        Enterprise
Element:
        OperationalMission
Element:
        Architecture
Element:
        ArchitecturalDescription
Element:
        ArchitecturalReference
Element:
        ArchitecturalProduct
Element:
        Elements
Element:
        ArchitecturalFramework
Element:
        View
Element:
        Concern
Element:
        Stakeholder
Element:
        Taxonomy
Element:
        ClassifiedElement
MoDAFModel:
        enterprise::Enterprise environment::Environment operationalMissions::OperationalMission+ architectures::Architecture+ architecturalDescription::ArchitecturalDescription+ architecturalReferences::ArchitecturalReference+ architecturalFrameworks::ArchitecturalFramework+ architectureMetadatas::ArchitectureMetaData+ metaDatas::MetaData+ stakeholders::Stakeholder+ stakeholderHasConcerns::StakeholderHasConcern+
Enterprise:
        inhabits::Environment fulfills::OperationalMission+
Environment:
        influences::Enterprise
OperationalMission:
        name::String content::String
Architecture:
        enterprise::Enterprise describedBy::ArchitecturalDescription
ArchitecturalDescription:
        approvialAuthority::String architect::String assumptionAndConstraints::String creatingOrganisation::String dateCompleted::String purpose::String recommendations::String summaryOfFindings::String tollsUsed::String viewpoints::View+ products::ArchitecturalProduct+ taxonomy::Taxonomy
ArchitecturalReference:
        referred::ArchitecturalDescription referrer::ArchitecturalDescription
ArchitecturalProduct:
        description::String architecturalElements::Elements+ definingView::View addresses::Concern+
Elements:
        name::String content::String
ArchitecturalFramework:
        ownedMember::View+
View:
        framework::String frameworkWebsite::String viewCode::String viewDescription::String viewName::String definingFramework::ArchitecturalFramework usedToCover::Concern+
Concern:
        adressedBy::ArchitecturalProduct+
StakeholderHasConcern:
        client::Stakeholder supplier::Concern owner::MoDAFModel
Stakeholder:
        name::String content::String
MetaData:
        ArchitectureMetaData
MetaData:
        dublinCoreElement::String modMetaDataElement::String name::String body::String
ArchitectureMetaData:
        annotatedArchitecture::ArchitecturalDescription
Taxonomy:
        date::String url::String version::String contents::ClassifiedElement+
ClassifiedElement:
        Environment
ClassifiedElement:
        Standard
ClassifiedElement:
        MeasurableProperty
ClassifiedElement:
        CapabilityRequirement
ClassifiedElement:
        Effect
ClassifiedElement:
        EnduringTask
ClassifiedElement:
        OperationalConstraint
ClassifiedElement:
        PostType
ClassifiedElement:
        OrganisationType
ClassifiedElement:
        RoleInOrganisation
ClassifiedElement:
        LocationType
ClassifiedElement:
        OperationalActivity
ClassifiedElement:
        Node
ClassifiedElement:
        InformationExchange
ClassifiedElement:
        Competence
ClassifiedElement:
        InformationElement
ClassifiedElement:
        NodeConnectionType
ClassifiedElement:
        System
ClassifiedElement:
        DataElement
ClassifiedElement:
        SystemFunction
ClassifiedElement:
        SystemConnectionSpecification
ClassifiedElement:
        ProjectType
ClassifiedElement:
        Service
ClassifiedElement:
        Unit
ClassifiedElement:
        Dimension
ClassifiedElement:
        OrganisationProjectRelationship
ClassifiedElement:
        ProjectThreadType
Standard:
        identifier::String publishedWebsite::String publisher::String ratificationDate::TimeExpression version::String withdrawalDate::TimeExpression
MeasurableProperty:
        maxValue::LiteralSpecification minValue::LiteralSpecification
CapabilityRequirement:
        taxonomy::Taxonomy
Effect:
        taxonomy::Taxonomy
EnduringTask:
        taxonomy::Taxonomy
OperationalConstraint:
        nodeUsageContext::Property
PostType:
        taxonomy::Taxonomy
OrganisationType:
        taxonomy::Taxonomy
RoleInOrganisation:
        taxonomy::Taxonomy
LocationType:
        taxonomy::Taxonomy
OperationalActivity:
        taxonomy::Taxonomy
Node:
        taxonomy::Taxonomy
InformationExchange:
        identifier::String requirementText::String
Competence:
        taxonomy::Taxonomy
InformationElement:
        taxonomy::Taxonomy
NodeConnectionType:
        taxonomy::Taxonomy
System:
        taxonomy::Taxonomy
DataElement:
        taxonomy::Taxonomy
SystemFunction:
        systemUsageContext::Property
SystemConnectionSpecification:
        taxonomy::Taxonomy
ProjectType:
        taxonomy::Taxonomy
Service:
        taxonomy::Taxonomy
Unit:
        taxonomy::Taxonomy
Dimension:
        taxonomy::Taxonomy
OrganisationProjectRelationship:
        taxonomy::Taxonomy
ProjectThreadType:
        taxonomy::Taxonomy
TimeExpression:
        value::String
LiteralSpecification:
        value::String
Property:
        value::String
