ModelElement:
        level::ANY name::ANY potency::ANY hasClass::ANY classElement::ANY+ elementTarget::ANY elementSource::ANY attributes::ANY+ attType::ANY
Attribute:
        type::ANY
Relationship:
        EPSILON
Generalization:
        target::ANY source::ANY
Association:
        maxSource::ANY maxTarget::ANY minSource::ANY minTarget::ANY
