DateTimeType:
        year::ANY month::ANY day::ANY hour::ANY minute::ANY second::ANY
VersionType:
        n::ANY nn::ANY
ValueType:
        EPSILON
StringValue:
        value::ANY
FloatValue:
        value::ANY
DateTimeTypeValue:
        value::ANY
BooleanValue:
        value::ANY
DocumentPropertiesCollection:
        dp_wordDocument::ANY title::ANY subject::ANY keywords::ANY description::ANY category::ANY author::ANY lastAuthor::ANY manager::ANY company::ANY hyperlinkBase::ANY revision::ANY presentationFormat::ANY guid::ANY appName::ANY version::ANY totalTime::ANY lastPrinted::ANY created::ANY lastSaved::ANY pages::ANY words::ANY characters::ANY charactersWithSpaces::ANY bytes::ANY lines::ANY paragraphs::ANY
CustomDocumentPropertiesCollection:
        cdp_wordDocument::ANY customDocumentProperties::ANY+
CustomDocumentProperty:
        customDocumentProperty_cdpe::ANY name::ANY value::ANY
SmartTagType:
        smartTagType_ste::ANY namespaceuri::ANY name::ANY url::ANY
SmartTagsCollection:
        st_wordDocument::ANY smartTagTypes::ANY+
StringProperty:
        EPSILON
StringType:
        val::ANY
BreakType:
        bt_page::EPSILON
        bt_column::EPSILON
        bt_text_wrapping::EPSILON
NoteValue:
        ftn_normal::EPSILON
        ftn_separator::EPSILON
        ftn_continuation_separator::EPSILON
        ftn_continuation_notice::EPSILON
OnOffType:
        oot_on::EPSILON
        oot_off::EPSILON
FldCharTypeProperty:
        fctp_begin::EPSILON
        fctp_separate::EPSILON
        fctp_end::EPSILON
WordDocument:
        wd_smartTags::ANY wd_docProperties::ANY wd_customDocProperties::ANY ignoreSubtree::ANY ignoreElements::ANY fonts::ANY lists::ANY styles::ANY docPr::ANY body::ANY
DocPrElt:
        dpe_wordDocument::ANY
BodyElt:
        be_wordDocument::ANY blockLevelElts::ANY+ sectPr::ANY
BlockLevelElt:
        EPSILON
BlockLevelChunkElt:
        EPSILON
ParaElt:
        pPr::ANY pContentElts::ANY+
ParaPrElt:
        ppe_pElt::ANY
ParaContentElt:
        EPSILON
RunElt:
        rPr::ANY rContentElts::ANY+
RunPrElt:
        rpe_rElt::ANY
RunContentElt:
        EPSILON
BreakElt:
        type::ANY
Text:
        EPSILON
DelText:
        EPSILON
InstrText:
        EPSILON
DelInstrText:
        EPSILON
NoBreakHyphen:
        rce_rElt::ANY
SoftHyphen:
        rce_rElt::ANY
AnnotationRef:
        rce_rElt::ANY
FootnoteRef:
        rce_rElt::ANY
EndnoteRef:
        rce_rElt::ANY
Separator:
        rce_rElt::ANY
ContinuationSeparator:
        rce_rElt::ANY
PgNum:
        rce_rElt::ANY
Cr:
        rce_rElt::ANY
Footnote:
        EPSILON
Endnote:
        EPSILON
NoteElt:
        EPSILON
Picture:
        EPSILON
Symbol:
        EPSILON
SymElt:
        font::ANY char::ANY
Tab:
        EPSILON
FldChar:
        EPSILON
FldCharElt:
        fldData::ANY fldCharType::ANY fldLock::ANY
FontsListElt:
        fle_wordDocument::ANY
ListsElt:
        le_wordDocument::ANY
StylesElt:
        se_wordDocument::ANY
SectPrElt:
        spe_bodyElt::ANY
RunLevelElt:
        
CfChunk:
        ble_bodyElt::ANY ble_note::ANY
SimpleFieldElt:
        pce_pElt::ANY
HLinkElt:
        pce_pElt::ANY
SubDocElt:
        pce_pElt::ANY
PictureType:
        EPSILON
TabElt:
        EPSILON
