DateTimeType:
        year::ANY month::ANY day::ANY hour::ANY minute::ANY second::ANY
VersionType:
        n::ANY nn::ANY
ValueType:
        EPSILON
StringValue:
        value::ANY
FloatValue:
        value::ANY
DateTimeTypeValue:
        value::ANY
BooleanValue:
        value::ANY
DocumentPropertiesCollection:
        dp_wordDocument::ANY title::ANY subject::ANY keywords::ANY description::ANY category::ANY author::ANY lastAuthor::ANY manager::ANY company::ANY hyperlinkBase::ANY revision::ANY presentationFormat::ANY guid::ANY appName::ANY version::ANY totalTime::ANY lastPrinted::ANY created::ANY lastSaved::ANY pages::ANY words::ANY characters::ANY charactersWithSpaces::ANY bytes::ANY lines::ANY paragraphs::ANY
CustomDocumentPropertiesCollection:
        cdp_wordDocument::ANY customDocumentProperties::ANY+
CustomDocumentProperty:
        customDocumentProperty_cdpe::ANY name::ANY value::ANY
SmartTagType:
        smartTagType_ste::ANY namespaceuri::ANY name::ANY url::ANY
SmartTagsCollection:
        st_wordDocument::ANY smartTagTypes::ANY+
StringProperty:
        EPSILON
StringType:
        val::ANY
BreakType:
        bt_page::EPSILON
        bt_column::EPSILON
        bt_text_wrapping::EPSILON
NoteValue:
        ftn_normal::EPSILON
        ftn_separator::EPSILON
        ftn_continuation_separator::EPSILON
        ftn_continuation_notice::EPSILON
OnOffType:
        oot_on::EPSILON
        oot_off::EPSILON
FldCharTypeProperty:
        fctp_begin::EPSILON
        fctp_separate::EPSILON
        fctp_end::EPSILON
HintType:
        ht_default::EPSILON
        ht_fareast::EPSILON
        ht_cs::EPSILON
StyleKindValue:
        skv_paragraph::EPSILON
        skv_character::EPSILON
        skv_table::EPSILON
        skv_list::EPSILON
UnderlineProperty:
        val::ANY color::ANY
UnderlineValues:
        uv_single::EPSILON
        uv_words::EPSILON
        uv_double::EPSILON
        uv_thick::EPSILON
        uv_dotted::EPSILON
        uv_dotted_heavy::EPSILON
        uv_dash::EPSILON
        uv_dashed_heavy::EPSILON
        uv_dash_long::EPSILON
        uv_dash_long_heavy::EPSILON
        uv_dot_dash::EPSILON
        uv_dash_dot_heavy::EPSILON
        uv_dot_dot_dash::EPSILON
        uv_dash_dot_dot_heavy::EPSILON
        uv_wave::EPSILON
        uv_wavy_heavy::EPSILON
        uv_wavy_double::EPSILON
        uv_none::EPSILON
HighlightColorValues:
        hcv_black::EPSILON
        hcv_blue::EPSILON
        hcv_cyan::EPSILON
        hcv_green::EPSILON
        hcv_magenta::EPSILON
        hcv_red::EPSILON
        hcv_yellow::EPSILON
        hcv_white::EPSILON
        hcv_dark_blue::EPSILON
        hcv_dark_cyan::EPSILON
        hcv_dark_green::EPSILON
        hcv_dark_magenta::EPSILON
        hcv_dark_red::EPSILON
        hcv_dark_yellow::EPSILON
        hcv_dark_gray::EPSILON
        hcv_light_gray::EPSILON
        hcv_none::EPSILON
VerticalAlignRunType:
        vart_baseline::EPSILON
        vart_superscript::EPSILON
        vart_subscript::EPSILON
JustificationValue:
        jv_left::EPSILON
        jv_center::EPSILON
        jv_right::EPSILON
        jv_both::EPSILON
WordDocument:
        wd_smartTags::ANY wd_docProperties::ANY wd_customDocProperties::ANY ignoreSubtree::ANY ignoreElements::ANY fonts::ANY lists::ANY styles::ANY docPr::ANY body::ANY
DocPrElt:
        dpe_wordDocument::ANY
BodyElt:
        be_wordDocument::ANY blockLevelElts::ANY+ sectPr::ANY
BlockLevelElt:
        EPSILON
BlockLevelChunkElt:
        EPSILON
ParaElt:
        pPr::ANY pContentElts::ANY+
ParaPrElt:
        ppe_pElt::ANY ppe_styleElt::ANY pStyle::ANY keepNext::ANY keepLines::ANY pageBreakBefore::ANY supressLineNumbers::ANY suppressAutoHyphens::ANY contextualSpacing::ANY bidi::ANY justification::ANY
ParaContentElt:
        EPSILON
RunElt:
        rPr::ANY rContentElts::ANY+
RunPrElt:
        rpe_rElt::ANY rpe_styleElt::ANY rStyle::ANY rFonts::ANY bold::ANY bold_cs::ANY italic::ANY italic_cs::ANY capitals::ANY smallCapitals::ANY strike::ANY doubleStrike::ANY outline::ANY shadow::ANY emboss::ANY imprint::ANY noProof::ANY vanish::ANY specVanish::ANY rtl::ANY cs::ANY underline::ANY color::ANY highlight::ANY verticalAlign::ANY language::ANY
LangElt:
        le_runPrElt::ANY val::ANY bidi::ANY
RunContentElt:
        EPSILON
BreakElt:
        type::ANY
Text:
        EPSILON
DelText:
        EPSILON
InstrText:
        EPSILON
DelInstrText:
        EPSILON
NoBreakHyphen:
        rce_rElt::ANY
SoftHyphen:
        rce_rElt::ANY
AnnotationRef:
        rce_rElt::ANY
FootnoteRef:
        rce_rElt::ANY
EndnoteRef:
        rce_rElt::ANY
Separator:
        rce_rElt::ANY
ContinuationSeparator:
        rce_rElt::ANY
PgNum:
        rce_rElt::ANY
Cr:
        rce_rElt::ANY
Footnote:
        EPSILON
Endnote:
        EPSILON
NoteElt:
        EPSILON
Picture:
        EPSILON
Symbol:
        EPSILON
SymElt:
        font::ANY char::ANY
Tab:
        EPSILON
FldChar:
        EPSILON
FldCharElt:
        fldData::ANY fldCharType::ANY fldLock::ANY
TableElt:
        tblPr::ANY tblGrid::ANY tblContent::ANY+
TablePrElt:
        tpe_tblElt::ANY tpe_styleElt::ANY
TableGridElt:
        tge_tblElt::ANY
TableContentElt:
        tce_tblElt::ANY tr::ANY+ tce_runLevelElts::ANY
RowElt:
        re_tblContentElt::ANY tblPrEx::ANY trPr::ANY rowContent::ANY+
TablePrExElt:
        tpee_rowElt::ANY
TableRowPrElt:
        tpe_rowElt::ANY trpe_styleElt::ANY
RowContentElt:
        rce_rowElt::ANY tc::ANY+ rce_runLevelElts::ANY
TableCellElt:
        tce_rowContentElt::ANY tcPr::ANY tce_content::ANY+
TableCellPrElt:
        tcpe_tableCellElt::ANY tcpe_styleElt::ANY
FontsListElt:
        fle_wordDocument::ANY defaultFonts::ANY fonts::ANY+
FontsElt:
        fse_fontsListElt::ANY fse_runPrElt::ANY hint::ANY ascii::ANY h_ansi::ANY fareast::ANY cs::ANY
FontElt:
        fe_fontsListElt::ANY name::ANY altName::ANY
StylesElt:
        se_wordDocument::ANY versionOfBuiltInStylenames::ANY styles::ANY+
StyleElt:
        se_stylesElt::ANY type::ANY styleId::ANY default::ANY name::ANY aliases::ANY sti::ANY basedOn::ANY next::ANY link::ANY autoRedefine::ANY hidden::ANY semiHidden::ANY locked::ANY personal::ANY personalCompose::ANY personalReply::ANY rsid::ANY se_pPr::ANY se_rPr::ANY se_tblPr::ANY se_trPr::ANY se_tcPr::ANY
ListsElt:
        le_wordDocument::ANY
SectPrElt:
        spe_bodyElt::ANY
RunLevelElt:
        rle_tblContentElt::ANY rle_rowContentElt::ANY
CfChunk:
        ble_bodyElt::ANY ble_note::ANY ble_tableCellElt::ANY
SimpleFieldElt:
        pce_pElt::ANY
HLinkElt:
        pce_pElt::ANY
SubDocElt:
        pce_pElt::ANY
PictureType:
        EPSILON
TabElt:
        EPSILON
