StringProperty:
        EPSILON
StringType:
        val::ANY
BreakType:
        bt_page::EPSILON
        bt_column::EPSILON
        bt_text_wrapping::EPSILON
NoteValue:
        ftn_normal::EPSILON
        ftn_separator::EPSILON
        ftn_continuation_separator::EPSILON
        ftn_continuation_notice::EPSILON
OnOffType:
        oot_on::EPSILON
        oot_off::EPSILON
FldCharTypeProperty:
        fctp_begin::EPSILON
        fctp_separate::EPSILON
        fctp_end::EPSILON
WordDocument:
        ignoreSubtree::ANY ignoreElements::ANY body::ANY
BodyElt:
        be_wordDocument::ANY blockLevelElts::ANY+
BlockLevelElt:
        EPSILON
BlockLevelChunkElt:
        EPSILON
ParaElt:
        pContentElts::ANY+
ParaContentElt:
        EPSILON
RunElt:
        rContentElts::ANY+
RunContentElt:
        EPSILON
BreakElt:
        type::ANY
Text:
        EPSILON
DelText:
        EPSILON
InstrText:
        EPSILON
DelInstrText:
        EPSILON
NoBreakHyphen:
        rce_rElt::ANY
SoftHyphen:
        rce_rElt::ANY
AnnotationRef:
        rce_rElt::ANY
FootnoteRef:
        rce_rElt::ANY
EndnoteRef:
        rce_rElt::ANY
Separator:
        rce_rElt::ANY
ContinuationSeparator:
        rce_rElt::ANY
PgNum:
        rce_rElt::ANY
Cr:
        rce_rElt::ANY
Footnote:
        EPSILON
Endnote:
        EPSILON
NoteElt:
        EPSILON
Picture:
        rce_rElt::ANY
Symbol:
        EPSILON
SymElt:
        font::ANY char::ANY
Tab:
        rce_rElt::ANY
FldChar:
        EPSILON
FldCharElt:
        fldData::ANY fldCharType::ANY fldLock::ANY
