CellType:
        unit::ANY formula::ANY err::ANY value::ANY
VisioDocument:
        docMasters::ANY docPages::ANY
PageSheet:
        EPSILON
NamedElt:
        EPSILON
IdentifiedElt:
        EPSILON
UniqueIdElt:
        EPSILON
Shape:
        ss_shapes::ANY lineStyle::ANY fillStyle::ANY textStyle::ANY shapeElts::ANY+
ShapeElt:
        EPSILON
IXElt:
        EPSILON
DelElt:
        EPSILON
Geom:
        noFill::ANY noLine::ANY noShow::ANY noSnap::ANY linesTo::ANY+ movesTo::ANY+ arcsTo::ANY+ splineKnots::ANY+ polylinesTo::ANY+ infiniteLines::ANY+ ellipses::ANY+ ellipticalArcsTo::ANY+ splineStarts::ANY+ nurbsTo::ANY+
XYElt:
        EPSILON
LineTo:
        lt_geom::ANY
MoveTo:
        mt_geom::ANY
XYAElt:
        EPSILON
ArcTo:
        ac_geom::ANY
SplineKnot:
        sk_geom::ANY
PolylineTo:
        pt_geom::ANY
XYABElt:
        EPSILON
InfiniteLine:
        il_geom::ANY
XYABCDElt:
        EPSILON
Ellipse:
        e_geom::ANY
EllipticalArcTo:
        eat_geom::ANY
SplineStart:
        ss_geom::ANY
XYABCDEElt:
        EPSILON
NURBSTo:
        nt_geom::ANY
Text:
        textElts::ANY+
TextElt:
        EPSILON
StringElt:
        value::ANY
MastersCollection:
        ms_visioDocument::ANY masters::ANY+ masterShortCuts::ANY+
MasterShortCut:
        m_masterShortCuts::ANY iconSize::ANY patternFlags::ANY prompt::ANY shortcutURL::ANY shortcutHelp::ANY alignName::ANY icons::ANY+
Icon:
        i_masterShortCut::ANY value::ANY
Master:
        m_masters::ANY baseID::ANY matchByName::ANY iconSize::ANY patternFlags::ANY prompt::ANY hidden::ANY iconUpdate::ANY alignName::ANY masterElts::ANY+
ShapesCollection:
        shapes::ANY+
ConnectsCollection:
        connections::ANY+
Connect:
        c_connects::ANY fromSheet::ANY toSheet::ANY fromCell::ANY toCell::ANY fromPart::ANY toPart::ANY
MasterElt:
        EPSILON
PagesCollection:
        ps_visioDocument::ANY pages::ANY+
Page:
        p_pages::ANY background::ANY backPage::ANY viewScale::ANY viewCenterX::ANY ViewCenterY::ANY reviewerID::ANY associatedPage::ANY pageElts::ANY+
PageElt:
        EPSILON
