Element:
        Newspaper
Element:
        News
Newspaper:
        language::String copyright::String pubDate::Date category::Category news::News+
News:
        author::String comments::String pubDate::Date category::Category newspaper::Newspaper
Category:
        value::String
Date:
        eDay::DayKind day::Integer month::Integer year::Integer hours::Integer minutes::Integer seconds::Integer
DayKind:
        Monday::EPSILON
        Tuesday::EPSILON
        Wednesday::EPSILON
        Thursday::EPSILON
        Friday::EPSILON
        Saturday::EPSILON
        Sunday::EPSILON
