Element:
        EPSILON
Newspaper:
        language::ANY copyright::ANY pubDate::ANY category::ANY news::ANY+
News:
        author::ANY comments::ANY pubDate::ANY category::ANY newspaper::ANY
Category:
        value::ANY
Date:
        eDay::ANY day::ANY month::ANY year::ANY hours::ANY minutes::ANY seconds::ANY
DayKind:
        Monday::EPSILON
        Tuesday::EPSILON
        Wednesday::EPSILON
        Thursday::EPSILON
        Friday::EPSILON
        Saturday::EPSILON
        Sunday::EPSILON
