OCCAM_Program:
        occam_Elements::ANY+ files::ANY+
OCCAM_Element:
        name::ANY
Process:
        declaration::ANY constructors::ANY+ parameters::ANY+ libraries::ANY+ toChannel::ANY
Channel:
        name::ANY type::ANY toServer::ANY toProcess::ANY
Action:
        constructor::ANY while::ANY if::ANY
Assignment:
        EPSILON
Input:
        EPSILON
Output:
        EPSILON
Constructor:
        process::ANY actions::ANY+ buckels::ANY+ childrens::ANY+
Buckel:
        constructor::ANY
If:
        conditions::ANY+ actions::ANY+
While:
        conditions::ANY+ actions::ANY+
Condition:
        elementRight::ANY elementLeft::ANY typeCondition::ANY if::ANY while::ANY
Sequential:
        EPSILON
Parallel:
        EPSILON
Alternative:
        EPSILON
DataType:
        dataType::ANY
Library:
        name::ANY
File:
        name::ANY
Server:
        name::ANY toChannel::ANY
Declaration:
        name::ANY process::ANY elements::ANY+
