InvariantSchema:
        constrainer_AT::ANY+ constrainer_ATy::ANY+ constrainer_SC::ANY+ constrainer_S::ANY+ constrainer_IOT::ANY+ constrainer_IOTy::ANY+
InformationObjectTemplate:
        IOT_IO::ANY+ IOT_constrainer::ANY+
InformationObjectType:
        IOTy_IO::ANY+ IOTy_constrainer::ANY+
InformationObject:
        describer::ANY+ IO_IOT::ANY+ IO_IOTy::ANY+ IO_A::ANY+ IO_S::ANY
State:
        change::ANY causeSC::ANY S_IO::ANY S_constrainer::ANY+
StateChange:
        startState::ANY endState::ANY specifier::ANY+ cause::ANY+ SC_constrainer::ANY+
DynamicSchema:
        dsStateChange::ANY+
StaticSchema:
        locationTime::ANY SS_IO::ANY+
Action:
        effect::ANY+ A_AT::ANY+ participant::ANY+ A_ATy::ANY+
ActionType:
        ATy_A::ANY+ ATy_constrainer::ANY+
ActionTemplate:
        AT_A::ANY+ AT_constrainer::ANY+
