EnvironmentContract:
        ec_to_a::ANY+ specifier_ec::ANY
ComputationalTemplate:
        EPSILON
ComputationalObject:
        co_to_i::ANY+ co_to_bh::ANY specifier_co::ANY co_to_st::ANY
BindingObject:
        EPSILON
ComputationalObjectTemplate:
        cot_to_co::ANY+ part_provide::ANY+ part_request::ANY+
ComputationalInterfaceTemplate:
        cit_to_i::ANY+ aggregate_provide::ANY+ aggregate_request::ANY+ cit_to_intsig::ANY
Interface:
        EPSILON
Binding:
        bd_to_i::ANY
SignalInterface:
        EPSILON
OperationInterface:
        EPSILON
StreamInterface:
        EPSILON
InterfaceSignature:
        EPSILON
SignalInterfaceSignature:
        sgisig_to_ssig::ANY+
OperationInterfaceSignature:
        optisig_to_ansig::ANY+ optisig_to_intsig::ANY+
StreamInterfaceSignature:
        strisig_to_fsig::ANY+
InteractionSignature:
        EPSILON
Parameter:
        param_to_isig::ANY
AnnouncementSignature:
        ansig_to_optisig::ANY
InterrogationSignature:
        intsig_to_optisig::ANY intsig_to_tersig::ANY+
TerminationSignature:
        tersig_to_intsig::ANY
SignalSignature:
        ssig_to_sgisig::ANY
FlowSignature:
        fsig_to_strisig::ANY
ActionTemplate:
        at_to_a::ANY+ at_to_isig::ANY
Behaviour:
        specifier_bh::ANY owner_bh::ANY bh_to_a::ANY+
Action:
        constrainer_ec::ANY+ changedState::ANY+ specifier_a::ANY a_to_bh::ANY
State:
        startState::ANY endState::ANY changer::ANY+ st_to_co::ANY
InternalAction:
        EPSILON
Interaction:
        EPSILON
Flow:
        EPSILON
Signal:
        EPSILON
Operation:
        EPSILON
Announcement:
        EPSILON
Interrogation:
        int_to_ter::ANY
Invocation:
        inv_to_ter::ANY inv_to_opt::ANY
Termination:
        owner_ter::ANY ter_to_inv::ANY
