Program:
        name::String variables::Variable+ types::Type+ procedures::Procedure+
Variable:
        Parameter
Variable:
        name::String program::Program procedure::Procedure type::Type
Type:
        name::String program::Program variables::Variable+
Parameter:
        procedure_parameter::Procedure
Instruction:
        Calculation
Instruction:
        Control
Instruction:
        Assignment
Instruction:
        Block
Instruction:
        block::Block
Calculation:
        EPSILON
Control:
        Conditional
Control:
        Loop
Control:
        Procedure
Control:
        Conditional
        Loop
        Procedure
Assignment:
        EPSILON
Block:
        instructions::Instruction+ procedure::Procedure loop::Loop conditional::Conditional
Conditional:
        blocks::Block
Loop:
        For
Loop:
        While
Loop:
        Repeat
Loop:
        block_loop::Block
Procedure:
        Function
Procedure:
        name::String program::Program variables::Variable+ parameters::Parameter+ block_procedure::Block
Function:
        returnType::Type
For:
        EPSILON
While:
        EPSILON
Repeat:
        EPSILON
