Thing:
        EPSILON
Meta-Reviewer:
        EPSILON
Reviewer:
        invites_co-reviewers::ANY invited_by::ANY has_a_review_reference_or_expertise::ANY+ writes_review::ANY hasReviewHistory::ANY executes::ANY cooperates::ANY IsAssignedTo::ANY hasConflictedPaper::ANY hasPreferredPaper::ANY hasPreferredTopic::ANY writeReview::ANY has_made_review::ANY UserName::ANY Comments_to_Chair::ANY Other_Areas::ANY refuses::ANY reviews::ANY bidsFor::ANY confirmes::ANY assignedPaperBy::ANY assignedByAdministrator::ANY adjustBid::ANY readPaper::ANY hasBeenAssigned::ANY assignExternalReviewer::ANY
Decision:
        EPSILON
Preference:
        EPSILON
Bid:
        adjustedBy::ANY
Conference:
        is_in_phase::ANY has_program::ANY hasMember::ANY hasName::ANY endDate::ANY paperDueOn::ANY registrationDueOn::ANY manuscriptDueOn::ANY startDate::ANY hasCountry::ANY isOrganizedBy::ANY annualOrder::ANY takesPlace::ANY hasAcronym::ANY finishedBy::ANY focusesOn::ANY startedBy::ANY takesPlace::ANY has_conference_member::ANY WebSite::ANY Topic_of_conference::ANY Date::ANY hasConferenceMember::ANY paperAssignmentFinalizedBy::ANY reviewCriteriaEnteredBy::ANY paperAssignmentToolsRunBy::ANY virtualMeetingEnabledBy::ANY hardcopyMailingManifestsPrintedBy::ANY detailsEnteredBy::ANY reviewerBiddingStartedBy::ANY date::ANY reviewsPerPaper::ANY logoURL::ANY acceptsHardcopySubmissions::ANY siteURL::ANY
ConferenceChair:
        EPSILON
AssociatedChair:
        EPSILON
AuthorNotReviewer:
        EPSILON
SubjectArea:
        EPSILON
ExternalReviewer:
        assignedByReviewer::ANY cooperatesReviewer::ANY
Chairman:
        EPSILON
ProgramCommitteeChair:
        endReview::ANY
Acceptance:
        EPSILON
Rejection:
        EPSILON
Paper:
        full_paper_size::ANY isWrittenBy::ANY isReviewedBy::ANY+ hasReview::ANY hasReviewer::ANY paperIsSubmittedBy::ANY isRejectedBy::ANY isAcceptedBy::ANY paperIsAssignedTo::ANY hasSecondaryTopic::ANY hasMainTopic::ANY hasAuthor::ANY hasStatus::ANY hasTitle::ANY hasID::ANY hasAbstract::ANY isRatedBy::ANY is_written_by::ANY Abstract::ANY Title::ANY Students::ANY Keywords::ANY rejectedBy::ANY acceptedBy::ANY reviewedBy::ANY discussedBy::ANY isPaperTypeOf::ANY assignedToReviewBy::ANY hasBid::ANY Summary::ANY rejected_paper_by::ANY accepted_by::ANY written_paper_by::ANY hasCo-author::ANY hasBid::ANY hasDecision::ANY assignedTo::ANY hasSubjectArea::ANY readByReviewer::ANY paperID::ANY title::ANY readByMeta-Reviewer::ANY
Author:
        submitsPaper::ANY writePaper::ANY writes_Paper::ANY changes::ANY write_paper::ANY submitPaper::ANY writes::ANY writes_article::ANY assigns_article_to_conference::ANY hasRelatedPaper::ANY conflictsWith::ANY+ isAuthorOf::ANY conducts::ANY
PaperFullVersion:
        EPSILON
Administrator:
        approve::ANY assign::ANY assigns::ANY send::ANY generate::ANY finalizePaperAssignment::ANY runPaperAssignmentTools::ANY enableVirtualMeeting::ANY startReviewerBidding::ANY assignReviewer::ANY rejectPaper::ANY enterConferenceDetails::ANY printHardcopyMailingManifests::ANY setMaxPapers::ANY enterReviewCriteria::ANY acceptPaper::ANY addProgramCommitteeMember::ANY
Meta-Review:
        EPSILON
Event:
        starts_on::ANY ends_on::ANY has_startdate::ANY has_enddate::ANY eventOnList::ANY+ partOfEvent::ANY hasEvent::ANY organisedBy::ANY+ heldIn::ANY conists_of::ANY confirmed_by::ANY defined_by::ANY approved_by::ANY
Account:
        registred_by::ANY
Inforamtion:
        EPSILON
User:
        recieve::ANY create::ANY+ submit::ANY
Role:
        assigned_by::ANY
Help_Request:
        EPSILON
Symposium:
        EPSILON
Document:
        writtenBy::ANY hasUpdatedVersion::ANY updatedVersionOf::ANY relatesTo::ANY+ submited_by::ANY Document_ID::ANY recieved_by::ANY used_by::ANY submited__by::ANY
Invited_Paper:
        EPSILON
Admin_Role:
        EPSILON
Paper_Typologies:
        EPSILON
Event_Setup:
        define::ANY
Event_URL:
        concerned::ANY
Notification_Email:
        EPSILON
Short_Paper:
        EPSILON
Author_Role:
        EPSILON
Preview:
        EPSILON
Review_Form:
        EPSILON
Committe_Role:
        EPSILON
Group_Email:
        EPSILON
Submission_Template:
        EPSILON
Review_Form_Setup:
        EPSILON
Misc:
        EPSILON
Event_Creation:
        EPSILON
Approval_Email:
        confirm::ANY
Rejection_Email:
        EPSILON
Template:
        EPSILON
Feature_Request:
        EPSILON
Event_Tracks:
        EPSILON
Request:
        EPSILON
Activity:
        hasTopic::ANY expectedAttendance::ANY isPartOf::ANY is_followed_by::ANY is_monitored_by::ANY has_intensity::ANY has_result::ANY is_performed_by::ANY is_supervised_by::ANY is_held_before::ANY is_held_in::ANY is_held_after::ANY is_dated_on::ANY has_result::ANY sent_by::ANY
Head_Role:
        EPSILON
Detail:
        EPSILON
Corresponding_Author:
        EPSILON
Reviewer_Role:
        EPSILON
Event_Approval:
        EPSILON
Registration:
        EPSILON
Full_Paper:
        EPSILON
Research_Topic:
        EPSILON
Description:
        EPSILON
Assistance:
        EPSILON
Email_Template:
        EPSILON
Conference_participant:
        EPSILON
Active_conference_participant:
        gives_presentations::ANY
Passive_conference_participant:
        EPSILON
Person:
        loggin_in::ANY submit::ANY get::ANY E-mail::ANY hasMail::ANY worksForCompany::ANY employedBy::ANY hasHomePage::ANY hasSurname::ANY hasFax::ANY hasFirstName::ANY hasPhone::ANY hasEmail::ANY attendeeAt::ANY isMemberOf::ANY hasFirstName::ANY hasBiography::ANY hasLastName::ANY authorOf::ANY prepare::ANY occupy::ANY+ is_present_in::ANY+ write::ANY obtain::ANY send::ANY speak_in::ANY+ pay::ANY sign::ANY is_present::ANY give::ANY+ need::ANY hasAffiliation::ANY hasFirstName::ANY hasLastName::ANY hasEmail::ANY hasName::ANY hasConflictOfInterest::ANY email::ANY inverse_of_add::ANY+ execute::ANY+ get::ANY use::ANY register::ANY modify::ANY+ take_part_in::ANY remove::ANY+ add::ANY added_by::ANY contributes::ANY has_an_email::ANY has_the_first_name::ANY has_gender::ANY has_the_last_name::ANY
Review_expertise:
        has_a_submitted_contribution::ANY has_an_expertise::ANY
Submitted_contribution:
        has_a_review_expertise::ANY
Regular_author:
        EPSILON
Conference_contributor:
        EPSILON
Contribution_1th-author:
        EPSILON
Contribution_co-author:
        EPSILON
Conference_contribution:
        is_submitted_at::ANY
Co-chair:
        was_a_committe_co-chair_of::ANY
Committee:
        has_members::ANY was_a_committee_of::ANY has_a_committee_co-chair::ANY has_a_committee_chair::ANY
Committee_member:
        was_a_member_of::ANY
Extended_abstract:
        EPSILON
Important_dates:
        is_an_abstract_submission_date::ANY is_a_full_paper_submission_date::ANY is_an_ending_date::ANY is_a_date_of_acceptance_announcement::ANY is_a_date_of_camera_ready_paper_submission::ANY is_a_starting_date::ANY belong_to_a_conference_volume::ANY
Invited_speaker:
        EPSILON
Conference_proceedings:
        has_an_ISBN::ANY has_a_publisher::ANY has_a_volume::ANY
Information_for_participants:
        EPSILON
Conference_document:
        has_authors::ANY has_a_date_of_issue::ANY
Regular_contribution:
        EPSILON
Poster:
        EPSILON
Written_contribution:
        EPSILON
Conference_applicant:
        EPSILON
Camera_ready_contribution:
        EPSILON
Accepted_contribution:
        EPSILON
Program_committee:
        was_a_program_committee_of::ANY
Organizing_committee:
        was_an_organizing_committee_of::ANY
Steering_committee:
        was_a_steering_committee_of::ANY
Conference_volume:
        has_parts::ANY has_workshops::ANY has_tracks::ANY has_tutorials::ANY has_a_commtitee::ANY has_a_steering_committee::ANY has_an_organizing_committee::ANY has_important_dates::ANY has_contributions::ANY has_a_location::ANY has_a_program_committee::ANY
Call_for_paper:
        EPSILON
Conference_announcement:
        EPSILON
Invited_talk:
        EPSILON
Conference_part:
        has_a_track-workshop-tutorial_topic::ANY is_part_of_conference_volumes::ANY has_a_track-workshop-tutorial_chair::ANY
Rejected_contribution:
        EPSILON
Reviewed_contribution:
        has_a_review::ANY
Review:
        gives_classification::ANY is_created_in::ANY review_written_by::ANY reviewOfPaper::ANY reviewWrittenBy::ANY containsEvaluation::ANY rates::ANY isWritenBy::ANY assigned_review_by::ANY written_review_by::ANY writtenBy::ANY reviews::ANY
Late_paid_applicant:
        EPSILON
Paid_applicant:
        EPSILON
Early_paid_applicant:
        EPSILON
Call_for_participation:
        EPSILON
Publisher:
        issues::ANY
Registeered_applicant:
        EPSILON
Track-workshop_chair:
        was_a_track-workshop_chair_of::ANY
Conference_www:
        has_a_URL::ANY
Conference_fees:
        EPSILON
Review_preference:
        has_a_topic_or_a_submission_contribution::ANY+ has_a_degree::ANY
EEnum:
        Yes::EPSILON
        No::EPSILON
        Unsure::EPSILON
        Accept::EPSILON
        Reject::EPSILON
        Unsure::EPSILON
        submitted::EPSILON
        missing::EPSILON
        notStarted::EPSILON
        active::EPSILON
        finished::EPSILON
        accepted::EPSILON
        rejected::EPSILON
        regular::EPSILON
        invited::EPSILON
        lowBid::EPSILON
        -::EPSILON
        CONFLICT::EPSILON
        wantNot::EPSILON
        highBid::EPSILON
        Compilers::EPSILON
        Microarchitecture::EPSILON
        Systems::EPSILON
        ForwardLookingIdea::EPSILON
        1::EPSILON
        2::EPSILON
        3::EPSILON
        4::EPSILON
        5::EPSILON
        6::EPSILON
        7::EPSILON
        male::EPSILON
        female::EPSILON
        high::EPSILON
        medium::EPSILON
        low::EPSILON
        very high::EPSILON
Accepted_Paper:
        EPSILON
Rejected_Paper:
        EPSILON
Undecided_Paper:
        EPSILON
Manual_Paper_Assignment:
        manually_assign_paper::ANY+
Program_Committee_member:
        EPSILON
paper_assignment:
        assign_paper::ANY is_performed_by::ANY
intensity:
        EPSILON
start_date_of_camera-ready_submission:
        EPSILON
camera-ready_submission_date:
        EPSILON
date_of_notification:
        EPSILON
date:
        EPSILON
article:
        article_written_by::ANY has_reviewer::ANY has_abstract::ANY goes_through::ANY is_sent_to::ANY is_created_in::ANY structure_created_by::ANY has_author::ANY gives_classification::ANY
Contact_Person:
        EPSILON
bidding_of_reviewer:
        is_performed_by::ANY
URL:
        EPSILON
conference_setup:
        sets_member::ANY is_made_by::ANY includes_topic::ANY sets_date::ANY sets_URL::ANY
human:
        is_author_of::ANY performs_activity::ANY is_employed_in::ANY has_topic_of_interest::ANY supervises::ANY e-mail::ANY last_name::ANY first_name::ANY
managing_of_conference_process:
        EPSILON
Program_Committee_Chair:
        EPSILON
reviewing_proces:
        EPSILON
end_date_of_camera-ready_submission:
        EPSILON
abstract_submission_date:
        EPSILON
group_email:
        EPSILON
Senior_Reviewer_URL:
        EPSILON
notification:
        has_result::ANY is_performed_by::ANY
notification_email:
        EPSILON
Chair_URL:
        EPSILON
abstract_of_paper:
        EPSILON
submission_process:
        is_performed_by::ANY
lower_tier_reviewing_process:
        EPSILON
start_date_of_conference:
        EPSILON
date_of_conference:
        EPSILON
Senior_Program_Committee_member:
        supervises::ANY
end_date_of_abstract_submission:
        EPSILON
phase_of_conference:
        EPSILON
Regular_Program_Committee_member:
        EPSILON
start_date_of_full_paper_submission:
        EPSILON
full_paper_submission_date:
        EPSILON
start_date_of_abstract_submission:
        EPSILON
end_date_of_conference:
        EPSILON
review_form:
        is_created_in::ANY
Automatic_Paper_Assignment:
        automatically_assign_paper::ANY+
institute:
        EPSILON
classification:
        EPSILON
summary_of_reviews:
        is_created_in::ANY
upper_tier_reviewing_process:
        is_performed_by::ANY
end_date_of_full_paper_submission:
        EPSILON
acceptance_notification_email:
        EPSILON
rejection_notification_email:
        EPSILON
Contact_Person_URL:
        EPSILON
Regular_Reviewer_URL:
        EPSILON
Trip:
        EPSILON
Banquet:
        EPSILON
Reception:
        EPSILON
Social_event:
        EPSILON
Organization:
        isProviderOf::ANY
Country:
        EPSILON
Company:
        EPSILON
Scholar:
        studyAt::ANY
Poster:
        EPSILON
Short_paper:
        EPSILON
Reviewing_results_event:
        EPSILON
Administrative_event:
        follows::ANY parallel_with::ANY
Reviewing_event:
        EPSILON
Registration_of_participants_event:
        EPSILON
Submission_event:
        EPSILON
Camera_Ready_event:
        EPSILON
Tutorial:
        EPSILON
Working_event:
        hasTopic::ANY hasAdministrativeEvent::ANY
Member:
        Web_address::ANY
Participant:
        submits_to_conference::ANY earlyRegistration::ANY
Member_PC:
        expertOn::ANY reviewes::ANY
Chair_PC:
        EPSILON
Student:
        EPSILON
Science_Worker:
        EPSILON
Assistant:
        EPSILON
Volunteer:
        EPSILON
Regular:
        EPSILON
pc_meeting:
        EPSILON
session:
        EPSILON
chair:
        was_a_committee_chair_of::ANY assigns_reviewers_to_article::ANY creates_program::ANY
Abstract:
        is_the_1th_part_of::ANY+ part_of_article::ANY
program:
        program_created_by::ANY has_session::ANY
SlideSet:
        EPSILON
Programme:
        belongsToEvent::ANY
MealMenu:
        isMenuOf::ANY
Topic:
        isIncluded::ANY belongs_to_a_review_reference::ANY is_a_topis_of_conference_parts::ANY isTopicOf::ANY
ConferenceEvent:
        hasAttendee::ANY hasLocation::ANY hasProgramme::ANY hasEndDateTime::ANY hasStartDateTime::ANY
Call:
        forEvent::ANY isInitiatedBy::ANY+ hasSubmissionInstructions::ANY hasSubmissionDeadline::ANY
ReviewRating:
        EPSILON
ReviewForm:
        EPSILON
PersonalHistory:
        EPSILON
Sponsorship:
        providedBy::ANY hasCostCurrency::ANY hasCostAmount::ANY
ConferenceSession:
        EPSILON
ContactInformation:
        hasCity::ANY hasStreet::ANY hasPostalCode::ANY hasPhone::ANY
WeekRejectRating:
        EPSILON
AcceptRating:
        EPSILON
AccpetIfRoomRating:
        EPSILON
RejectRating:
        EPSILON
MealEvent:
        hasMenu::ANY
NonAcademicEvent:
        EPSILON
BreakEvent:
        EPSILON
ParallelAndDistributedComputingTopic:
        EPSILON
WirelessCommunicationsTopic:
        EPSILON
OperatingTopicsystems:
        EPSILON
ComputerNetworksTopic:
        EPSILON
SatelliteAndSpaceCommunicationsTopic:
        EPSILON
CADTopic:
        EPSILON
MultimediaTopic:
        EPSILON
CommunicationsTopic:
        EPSILON
PowerlineTransmissionTopic:
        EPSILON
AntennasTopic:
        EPSILON
PerformanceTopic:
        EPSILON
SignalProcessingTopic:
        EPSILON
MicroelectronicsTopic:
        EPSILON
TestOnlyTopic:
        EPSILON
RadioCommunicationsTopic:
        EPSILON
ComputerArchitectureTopic:
        EPSILON
MedicineTopic:
        EPSILON
SecurityTopic:
        EPSILON
MobileComputingTopic:
        EPSILON
CryptographyTopic:
        EPSILON
CommunicationTheoryTopic:
        EPSILON
DiningPlace:
        EPSILON
Presenter:
        EPSILON
AcademiaOrganization:
        EPSILON
IndustryOrganization:
        EPSILON
NGO:
        EPSILON
GovernmentOrganization:
        EPSILON
ComputerNetworksEnterpriseTopic:
        EPSILON
ComputerNetworksSwitchingTopic:
        EPSILON
ComputerNetworksSensorTopic:
        EPSILON
ComputerNetworksSecurityTopic:
        EPSILON
ComputerNetworksOpticalTopic:
        EPSILON
ComputerNetworksMeasurementsTopic:
        EPSILON
ComputerNetworksManagementTopic:
        EPSILON
ComputerNetworksAapplicationsTopic:
        EPSILON
ActivePaper:
        hasRating::ANY
PendingPaper:
        EPSILON
WithdrawnPaper:
        EPSILON
RejectedPaper:
        EPSILON
PublishedPaper:
        EPSILON
Attendee:
        EPSILON
CoffeeBreak:
        EPSILON
FreeTimeBreak:
        EPSILON
MealBreak:
        EPSILON
ClosingTalk:
        EPSILON
WelcomeTalk:
        EPSILON
TalkEvent:
        EPSILON
SessionChair:
        EPSILON
TPCMember:
        EPSILON
TwoLevelConference:
        EPSILON
CallForPapers:
        EPSILON
TextualReviewQuestion:
        EPSILON
NumericalReviewQuestion:
        EPSILON
OrganizationalMeeting:
        EPSILON
PaperPresentation:
        relatedToPaper::ANY
AcademicEvent:
        hasCall::ANY
PersonalPublicationHistory:
        EPSILON
Excursion:
        EPSILON
SocialEvent:
        EPSILON
CallForReviews:
        EPSILON
PersonalReviewHistory:
        isReviewHistoryOf::ANY
ConferenceVenuePlace:
        EPSILON
CallForManuscripts:
        EPSILON
Reception:
        EPSILON
SingleLevelConference:
        EPSILON
MeetingRoomPlace:
        EPSILON
AccommodationPlace:
        EPSILON
RatedPapers:
        EPSILON
TravelGrant:
        EPSILON
ConferenceDinner:
        EPSILON
Accepted_Paper:
        EPSILON
Rejected_Paper:
        EPSILON
Evaluated_Paper:
        hasReview::ANY
Camera_Ready_Paper:
        EPSILON
Positive_Review:
        EPSILON
Workshop_Paper:
        EPSILON
Industrial_Paper:
        EPSILON
Conference_Paper:
        EPSILON
Industrial_Session:
        EPSILON
Conference_Session:
        EPSILON
Regular_Session:
        EPSILON
Poster_Session:
        EPSILON
Demo_Session:
        EPSILON
Paper_Author:
        EPSILON
Conference_Trip:
        EPSILON
Social_Event:
        EPSILON
Tutorial_Abstract:
        EPSILON
Conference_Participant:
        EPSILON
Assigned_Paper:
        hasReviewer::ANY
Negative_Review:
        EPSILON
Neutral_Review:
        EPSILON
Research_Topic:
        topicCoveredBy::ANY
Organising_Agency:
        EPSILON
Academic_Institution:
        scientificallyOrganises::ANY
Organisation:
        publisherOf::ANY+ technicallyOrganises::ANY
Proceedings_Publisher:
        EPSILON
Poster_Paper:
        EPSILON
Regular_Paper:
        EPSILON
Demo_Paper:
        EPSILON
Location:
        locationOf::ANY
Research_Institute:
        EPSILON
Scientific_Event:
        EPSILON
Invited_Talk_Abstract:
        EPSILON
Agency_Staff_Member:
        EPSILON
Workshop_Session:
        EPSILON
Track:
        EPSILON
Invited_Talk:
        EPSILON
Workshop:
        EPSILON
Contributed_Talk:
        presentationOfPaper::ANY+
Demo_Chair:
        EPSILON
Tutorial_Chair:
        EPSILON
PC_Chair:
        EPSILON
PC_Member:
        EPSILON
OC_Member:
        EPSILON
Programme_Brochure:
        EPSILON
Flyer:
        EPSILON
Web_Site:
        EPSILON
Multi-author_Volume:
        EPSILON
Individual_Presentation:
        presentationOfPaper::ANY+
OC_Chair:
        EPSILON
Conference_Banquet:
        EPSILON
Workshop_Chair:
        EPSILON
Conference_Proceedings:
        EPSILON
Session_Chair:
        EPSILON
Early-Registered_Participant:
        EPSILON
Late-Registered_Participant:
        EPSILON
University:
        EPSILON
Possible_Reviewer:
        reviewerOfPaper::ANY
Student:
        EPSILON
Invited_Speaker:
        EPSILON
SC_Member:
        EPSILON
Presenter_house:
        EPSILON
Building:
        EPSILON
Presenter_state:
        EPSILON
Delegate:
        EPSILON
Presenter_city:
        EPSILON
Hotel_registration_form:
        EPSILON
Deadline_hotel_reservation:
        EPSILON
Form:
        EPSILON
Car:
        EPSILON
Transport_vehicle:
        EPSILON
Mailing_list:
        EPSILON
Renting:
        EPSILON
Activity_before_conference:
        EPSILON
Dinner_banquet:
        EPSILON
One_day_presenter:
        EPSILON
Social_program:
        EPSILON
PowerPoint_presentation:
        EPSILON
Presentation:
        is_given_by::ANY
Conference_restaurant:
        EPSILON
Conference_city:
        EPSILON
Conference_state:
        EPSILON
Submissions_deadline:
        EPSILON
Deadline:
        done_till::ANY
Simulating:
        EPSILON
Research:
        EPSILON
Technic_activity:
        EPSILON
Conference_activity:
        EPSILON
Technical_commitee:
        EPSILON
Place:
        isLocationOf::ANY is_equipped_by::ANY
Author_cd_proceedings_included:
        EPSILON
Cd_proceening:
        EPSILON
Trip_day:
        EPSILON
Time:
        EPSILON
Record_of_attendance:
        EPSILON
Listener:
        EPSILON
Session_room:
        EPSILON
Brief_introduction_for_Session_chair:
        EPSILON
Session_chair:
        EPSILON
Invitation_letter:
        EPSILON
Registration_form:
        EPSILON
Viza:
        EPSILON
Registration:
        EPSILON
Conference_days:
        EPSILON
Conference_building:
        EPSILON
Registration_fee:
        EPSILON
Departure:
        EPSILON
Activity_after_conference:
        EPSILON
Conference_airport:
        EPSILON
Worker_lecturer:
        EPSILON
Lecturer:
        EPSILON
Transparency:
        EPSILON
City:
        EPSILON
Card:
        EPSILON
Item:
        go_through::ANY is_used_for::ANY+ is_signed_by::ANY is_made_from::ANY is_sent_after::ANY is_needed_for::ANY is_sent_before::ANY is_prepared_by::ANY is_used_by::ANY is_given_to::ANY is_sent_by::ANY is_writen_by::ANY
Author_attendee_book_registration_fee:
        EPSILON
Book_proceeding:
        EPSILON
Video_cassette_player:
        EPSILON
Audiovisual_equipment:
        EPSILON
Video_presentation:
        EPSILON
Hotel_room:
        EPSILON
Hotel_presenter:
        EPSILON
Conference_hotel:
        EPSILON
Money:
        is_paid_with::ANY is_paid_by::ANY is_paid_in::ANY is_paid_for::ANY+ has_amount_of::ANY
State:
        EPSILON
Introduction:
        EPSILON
Welcome_address:
        EPSILON
Value_added_tax:
        EPSILON
Tax:
        EPSILON
Refusing_manuscript:
        EPSILON
Final_manuscript:
        EPSILON
Accepting_manuscript:
        EPSILON
Submission:
        writtenBy::ANY dealsWith::ANY remark::ANY abstract::ANY contactEmail::ANY hasKeyword::ANY hasTitle::ANY
Sponsor_city:
        EPSILON
Sponsor:
        EPSILON
Time_zone:
        EPSILON
Introduction_of_speaker:
        EPSILON
Conference_hall:
        EPSILON
Plenary_lecture:
        EPSILON
Plenary_lecture_speaker:
        EPSILON
LCD_projector:
        EPSILON
Deadline_for_notification_of_acceptance:
        EPSILON
Tutorial_speaker:
        EPSILON
Registation_deadline:
        EPSILON
Single_hotel_room:
        EPSILON
Non_speaker:
        EPSILON
Author_information_form:
        EPSILON
Nonmember_registration_fee:
        EPSILON
IASTED_non_member:
        EPSILON
Hotel_fee:
        EPSILON
Fee:
        EPSILON
Publication:
        EPSILON
Taxi:
        EPSILON
Sponsor_state:
        EPSILON
Modelling:
        EPSILON
Worker_non_speaker:
        EPSILON
Nonauthor_registration_fee:
        EPSILON
Payment_document:
        EPSILON
Camera_ready_manuscript_deadline:
        EPSILON
One_conference_day:
        EPSILON
Fee_for_extra_trip:
        EPSILON
Full_day_tour:
        EPSILON
Conference_Hiker:
        EPSILON
Computer:
        EPSILON
IASTED_member:
        EPSILON
Memeber_registration_fee:
        EPSILON
Author_book_proceedings_included:
        EPSILON
Sponsor_company_house:
        EPSILON
Sponzorship:
        EPSILON
Student_lecturer:
        EPSILON
Trip_city:
        EPSILON
Cheque:
        EPSILON
Shuttle_bus:
        EPSILON
Student_non_speaker:
        EPSILON
Student_registration_fee:
        EPSILON
Author_attendee_cd_registration_fee:
        EPSILON
Tip:
        EPSILON
Credit_card:
        EPSILON
Van:
        EPSILON
Main_office:
        EPSILON
Presenter_university:
        EPSILON
Departure_tax:
        EPSILON
Receiving_manuscript:
        EPSILON
Double_hotel_room:
        EPSILON
Initial_manuscipt:
        EPSILON
Coffee_break:
        EPSILON
Bank_transfer:
        EPSILON
Overhead_projector:
        EPSILON
Speaker_lecture:
        EPSILON
Coctail_reception:
        EPSILON
Currency:
        EPSILON
OrganizingCommittee:
        organizes::ANY
ProgramCoChair:
        EPSILON
Organizer:
        EPSILON
PublicationsChair:
        EPSILON
OutsideReferee:
        EPSILON
Lecture:
        hasAcronym::ANY
ActivitySubmissionForm:
        isSubmittedBy::ANY hasAuthor::ANY submissionDeadline::ANY
WorkshopTutorialChair:
        EPSILON
DoubleBlindReview:
        isExecutedBy::ANY
TutorialProposal:
        EPSILON
RegistrationChair:
        EPSILON
StudentAdvocate:
        EPSILON
FinanceChair:
        EPSILON
QualitatvieLecture:
        EPSILON
TraditionalLecture:
        EPSILON
PaperSubmissionChair:
        EPSILON
PublicityWebChair:
        EPSILON
SteeringCommittee:
        EPSILON
GeneralCoChair:
        EPSILON
WorksopProposal:
        EPSILON
ProgramCommitteeMember:
        memberOfProgramCommittee::ANY maxPapers::ANY addedBy::ANY isMemberOf::ANY hasPassword::ANY
ContactAuthor:
        submitsAbstract::ANY
ConferenceProgram:
        isProgramOf::ANY consistsOf::ANY
PaperStatus:
        isStatusOf::ANY
Slot:
        date::ANY endsAt::ANY beginsAt::ANY forms::ANY hosts::ANY
Session:
        hasAssignedPaper::ANY room::ANY isAssociatedTo::ANY hasChair::ANY
ResearchTopic:
        EPSILON
Question:
        EPSILON
PaymentMode:
        EPSILON
OutputDocument:
        isProducedBy::ANY
ProgramCommittee:
        hasProgramCommitteeMember::ANY hasMember::ANY
Criterion:
        hasWeight::ANY
AcceptedPaper:
        relatedToEvent::ANY isAssignedToSession::ANY
RejectedPaper:
        EPSILON
Chair:
        produces::ANY sets::ANY accepts::ANY rejects::ANY asksForPreference::ANY isChairOf::ANY
ConferenceAttendant:
        mustPay::ANY hasAdress::ANY paid::ANY hasPhone::ANY
Evaluation:
        isContainedIn::ANY
PaperAbstract:
        isAbstractOf::ANY abstractIsSubmittedBy::ANY
ReviewQuestion:
        EPSILON
PaperQuestion:
        EPSILON
CD-ROM:
        EPSILON
IndexOfAuthors:
        EPSILON
ExternalReviewersList:
        EPSILON
Proceedings:
        includes::ANY+
Program:
        EPSILON
PCMembersList:
        EPSILON
ListOfAbstracts:
        EPSILON
BookletOfAbstracts:
        EPSILON
RFC:
        EPSILON
Topics:
        EPSILON
Classic_Papers:
        EPSILON
Networking:
        EPSILON
Humour:
        EPSILON
Programming:
        EPSILON
Computer_Science:
        EPSILON
Format:
        EPSILON
Value_Partition:
        EPSILON
Adobe_PDF:
        EPSILON
MS_Word:
        EPSILON
Corel_Word_Perfect:
        EPSILON
HTML:
        EPSILON
PostScript:
        EPSILON
RTF:
        EPSILON
Text:
        EPSILON
High:
        EPSILON
Reviewer_Famliliarity:
        EPSILON
Low:
        EPSILON
Moderate:
        EPSILON
Marginal_Tend_to_Reject:
        EPSILON
Reccommendation:
        EPSILON
Marginal_Tend_to_Accept:
        EPSILON
Portable_Reject:
        EPSILON
Must_Accept:
        EPSILON
Clear_Reject:
        EPSILON
Clear_Accept:
        EPSILON
Program_chair:
        made_program::ANY
Conference_Program:
        Program_made_by::ANY planned_papers::ANY
Domain_Topic:
        EPSILON
Planed_Paper:
        is_planned_in::ANY
Valuable_Confirmation_of_Present_Knowledge:
        EPSILON
Other:
        EPSILON
Not_Much:
        EPSILON
New_Information:
        EPSILON
New_Perspective_Issue_Problem_Solving:
        EPSILON
Clarity_to_Present_Understanding:
        EPSILON
Overall_Value:
        EPSILON
Tends_Towards_Theoretical:
        EPSILON
Paper_Categorization:
        EPSILON
Tends_Towards_Practical:
        EPSILON
Balanced_Theory_and_Practice:
        EPSILON
Highly_Theoretical:
        EPSILON
Highly_Practical:
        EPSILON
Reviewed_Paper:
        EPSILON
Submitted_Paper:
        is_stored_in::ANY has_been_sent_by::ANY Paper_Id::ANY Comments_To_Chair::ANY
Paper_Review:
        is_Candidate_for_Award::ANY appropriate_length::ANY has_Categorization::ANY has_Overall::ANY has_Reccommendation::ANY Review_made_by::ANY Comments_for_Author::ANY Comments_for_Program_Committee::ANY
Long_bool:
        EPSILON
Review_Values:
        EPSILON
Review_Committee:
        EPSILON
Committees:
        EPSILON
Advocate:
        will_advocate::ANY
Advocated_Paper:
        to_advocate_by::ANY
Contact_Author:
        has_sent::ANY Alternate_Email::ANY
Result_of_Advocate:
        EPSILON
People:
        Surname::ANY Name::ANY Country::ANY E-mail::ANY Organisation::ANY
Source_Archive:
        EPSILON
Poster:
        EPSILON
Camera_Ready_Copy:
        EPSILON
Paper_File:
        is_Type::ANY
Slides:
        EPSILON
Contribution_File:
        hasContributionFileStatus::ANY
Discussion:
        EPSILON
PhaseOfConferencePreparation:
        hasPhaseStatus::ANY
Program_Comitee:
        discusses::ANY
Contribution:
        writtenBy::ANY dealsWith::ANY remark::ANY abstract::ANY contactEmail::ANY hasKeyword::ANY hasTitle::ANY changedBy::ANY hasContributionStatus::ANY
Conflict_Of_Interest:
        EPSILON
Conflict_Rules:
        EPSILON
Program_Comitee_Meeting:
        EPSILON
Setup_Phase:
        EPSILON
Camera_Ready_Copy_Phase:
        EPSILON
Assignment_Phase:
        EPSILON
Blocked_Phase:
        EPSILON
Abstract_And_Paper_Submission_Phase:
        EPSILON
Invitation_Of_Reviewers_Phase:
        EPSILON
Review_Phase:
        EPSILON
Closed_Phase:
        EPSILON
Bidding_Phase:
        EPSILON
Speaker:
        EPSILON
Program_Comitee_Chair:
        finishes::ANY headOf::ANY switches::ANY starts::ANY accepts::ANY assignsToReview::ANY assignsPaper::ANY rejects::ANY
Confirmed_Conflict:
        EPSILON
Pending_Proposed_Conflict:
        refusedBy::ANY confirmedBy::ANY
Hidden_Conflict:
        EPSILON
Deleted_Conflict:
        EPSILON
Proposed_Conflict:
        conflictProposedBy::ANY
Self_Conflict:
        EPSILON
Co-Author:
        co-writePaper::ANY
MainAuthor:
        EPSILON
Bidding_And_Paper_Submission_Phase:
        EPSILON
Bidding_Without_Paper_Submission_Phase:
        EPSILON
E-mail_PC_Meeting:
        EPSILON
PC_Meeting:
        EPSILON
External_Reviewer:
        EPSILON
Accepted_paper:
        read_paper_by::ANY rateed_paper_by::ANY Score::ANY
Report:
        EPSILON
Secondary_Reviewer:
        EPSILON
CommitteeMember:
        isMemberOf::ANY reject_paper::ANY accept::ANY
Email:
        sended_by::ANY Receiver_of_email::ANY Message_of_email::ANY Subject_of_email::ANY
ConferenceMember:
        memberOfConference::ANY member_of_conference::ANY
Information:
        EPSILON
Electronic_proceeding:
        EPSILON
System:
        EPSILON
CD:
        EPSILON
Invitation:
        EPSILON
Web_site:
        EPSILON
Rejected_paper:
        EPSILON
Primary_Reviewer:
        assign_review::ANY
