LocatedElement:
        NamedElement
NamedElement:
        PetriNet
NamedElement:
        Element
NamedElement:
        Arc
PetriNet:
        elements::Element+ arcs::Arc+ execs::Execution+
Element:
        Place
Element:
        Transition
Place:
        incomingArc::TransitionToPlace+ outgoingArc::PlaceToTransition+
Transition:
        incomingArc::PlaceToTransition+ outgoingArc::TransitionToPlace+
Arc:
        PlaceToTransition
Arc:
        TransitionToPlace
PlaceToTransition:
        from::Place to::Transition
TransitionToPlace:
        from::Transition to::Place
Execution:
        net::PetriNet markings::Marking+ movements::Movement+
Token:
        placedAt::Place marking::Marking
Marking:
        exec::Execution tokens::Token+
Movement:
        exec::Execution fire::Transition source::Marking target::Marking
