Element:
        EPSILON
PetriNet:
        places::ANY+ transitions::ANY+ arcs::ANY+
Place:
        incoming::ANY+ outgoing::ANY+
Transition:
        incoming::ANY+ outgoing::ANY+
Arc:
        EPSILON
PlaceToTransArc:
        source::ANY target::ANY
TransToPlaceArc:
        source::ANY target::ANY
