Entity:
        EPSILON
Activity:
        EPSILON
Object:
        EPSILON
Timepoint:
        EPSILON
Relation:
        EPSILON
Decision:
        EPSILON
Agent:
        EPSILON
Creates:
        EPSILON
Modifies:
        EPSILON
Before:
        EPSILON
Uses:
        EPSILON
Performs:
        EPSILON
ActivityStatus:
        EPSILON
Succesor:
        EPSILON
