LocatedElement:
        Eclipse
LocatedElement:
        Bundle
LocatedElement:
        RequireBundleAttribute
LocatedElement:
        Version
LocatedElement:
        RequiredBundle
LocatedElement:
        ImportedPackage
LocatedElement:
        ExportedPackage
LocatedElement:
        Package
LocatedElement:
        Xfriends
Resolution:
        Mandatory::EPSILON
        Optional::EPSILON
Visibility:
        Private::EPSILON
        Reexport::EPSILON
Eclipse:
        bundles::Bundle+ packages::Package+
Bundle:
        symbolicName::String singleton::Boolean manifestVersion::Integer require::RequiredBundle+ version::Version export::ExportedPackage+ import::ImportedPackage+ packages::Package+
RequireBundleAttribute:
        AttResolution
RequireBundleAttribute:
        AttVisibility
RequireBundleAttribute:
        Range
AttResolution:
        value::Resolution
AttVisibility:
        value::Visibility
Range:
        isLeftInclusive::Boolean isRightInclusive::Boolean lowerBound::Version upperBound::Version
Version:
        major::Integer minor::Integer micro::Integer qualification::String
RequiredBundle:
        requireBundleAttribute::RequireBundleAttribute+ bundle::Bundle
ImportedPackage:
        resolution::Resolution package::Package range::Range
ExportedPackage:
        Xinternal
ExportedPackage:
        package::Package version::Version xFriends::Xfriends
Package:
        fqn::String importedBy::ImportedPackage+ exportedBy::ExportedPackage
Xfriends:
        bundles::Bundle+
Xinternal:
        value::Boolean
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
