LocatedElement:
        EPSILON
Resolution:
        Mandatory::EPSILON
        Optional::EPSILON
Visibility:
        Private::EPSILON
        Reexport::EPSILON
Eclipse:
        bundles::ANY+ packages::ANY+
Bundle:
        symbolicName::ANY singleton::ANY manifestVersion::ANY require::ANY+ version::ANY export::ANY+ import::ANY+ packages::ANY+
RequireBundleAttribute:
        EPSILON
AttResolution:
        value::ANY
AttVisibility:
        value::ANY
Range:
        isLeftInclusive::ANY isRightInclusive::ANY lowerBound::ANY upperBound::ANY
Version:
        major::ANY minor::ANY micro::ANY qualification::ANY
RequiredBundle:
        requireBundleAttribute::ANY+ bundle::ANY
ImportedPackage:
        resolution::ANY package::ANY range::ANY
ExportedPackage:
        package::ANY version::ANY xFriends::ANY
Package:
        fqn::ANY importedBy::ANY+ exportedBy::ANY
Xfriends:
        bundles::ANY+
Xinternal:
        value::ANY
