IdedElement:
        EPSILON
URI:
        value::ANY
Color:
        EPSILON
AnyElement:
        name::ANY text::ANY
RotationType:
        rtvertical::EPSILON
        rthorizontal::EPSILON
        rtdiagonal::EPSILON
ShapeType:
        shtline::EPSILON
        shtcurve::EPSILON
StyleType:
        sttsolid::EPSILON
        sttdash::EPSILON
        sttdot::EPSILON
DecorationType:
        dtunderligne::EPSILON
        dtoverligne::EPSILON
        dtlinethrough::EPSILON
AlignType:
        atleft::EPSILON
        atcenter::EPSILON
        atright::EPSILON
PNMLDocument:
        xmlns::ANY nets::ANY+
NetElement:
        type::ANY document::ANY contents::ANY+ tools::ANY+ netgraphics::ANY name::ANY
NetContent:
        EPSILON
ToolSpecific:
        tool::ANY version::ANY anyelement::ANY+ net::ANY arc::ANY node::ANY
LabeledElement:
        EPSILON
Label:
        text::ANY namedelement::ANY
Name:
        net::ANY netcontent::ANY
Inscription:
        arc::ANY
InitialMarking:
        place::ANY
NetContentElement:
        EPSILON
Arc:
        source::ANY target::ANY tools::ANY+ edgegraphics::ANY inscription::ANY
Node:
        netcontentelement::ANY tools::ANY+ nodegraphics::ANY
Place:
        initialmarking::ANY
Transition:
        node::ANY
Graphics:
        EPSILON
NetGraphics:
        net::ANY
NodeGraphics:
        node::ANY position::ANY dimension::ANY fill::ANY line::ANY
EdgeGraphics:
        arc::ANY position::ANY+ fill::ANY line::ANY
AnnotationGraphics:
        namedelement::ANY offset::ANY font::ANY fill::ANY line::ANY
Coordinate:
        EPSILON
Position:
        nodegraphics::ANY edgegraphics::ANY
Offset:
        annotationgraphics::ANY
Dimension:
        width::ANY height::ANY nodegraphics::ANY
Fill:
        gradientrotation::ANY interiorcolor::ANY gradientcolor::ANY image::ANY nodegraphics::ANY edgegraphics::ANY annotationgraphics::ANY
Line:
        color::ANY width::ANY shape::ANY style::ANY nodegraphics::ANY edgegraphics::ANY annotationgraphics::ANY
Font:
        family::ANY style::ANY weight::ANY size::ANY decoration::ANY align::ANY rotation::ANY annotationgraphics::ANY
