LocatedElement:
        EPSILON
IdedElement:
        EPSILON
URI:
        value::ANY
PNMLDocument:
        xmlns::ANY nets::ANY+
NetElement:
        type::ANY document::ANY contents::ANY+ name::ANY
NetContent:
        EPSILON
LabeledElement:
        EPSILON
Label:
        text::ANY labeledElement::ANY
Name:
        net::ANY netContent::ANY
NetContentElement:
        EPSILON
Arc:
        source::ANY target::ANY
Place:
        
Transition:
        
