LocatedElement:
        EPSILON
NamedElement:
        EPSILON
Structure:
        EPSILON
ProcContainerElement:
        EPSILON
Program:
        monitors::ANY+
Monitor:
        program::ANY
Procedure:
        container::ANY parameters::ANY+ statements::ANY+
VariableDeclaration:
        type::ANY initialValue::ANY structure::ANY
Parameter:
        direction::ANY procedure::ANY
Direction:
        in::EPSILON
        out::EPSILON
Type:
        name::ANY
Expression:
        EPSILON
VariableExp:
        declaration::ANY
PropertyCallExp:
        EPSILON
OperatorCallExp:
        right::ANY
AttributeCallExp:
        source::ANY name::ANY
ProcedureCallExp:
        arguments::ANY+
LiteralExp:
        EPSILON
BooleanExp:
        symbol::ANY
IntegerExp:
        symbol::ANY
Statement:
        EPSILON
AssignmentStat:
        target::ANY value::ANY
ConditionalStat:
        condition::ANY thenStats::ANY+ elseStats::ANY+
WhileStat:
        condition::ANY doStats::ANY+
ExpressionStat:
        expression::ANY
