Strong:
        EPSILON
Start:
        EPSILON
End:
        EPSILON
FeedBack:
        EPSILON
Weak:
        EPSILON
Grouping:
        EPSILON
Precedence:
        deprecs::ANY+ parbind::ANY+
DynPrecedence:
        EPSILON
DerPrecedence:
        precs::ANY+ auxTasks::ANY+
BasPrecedence:
        EPSILON
MetaTaskOccurence:
        dprecs::ANY+ taskCl::ANY+
ParBinding:
        inclusion::ANY precs::ANY+ targetPar::ANY sourcePar::ANY
ParameterPrec:
        parbindsTar::ANY+ parbindsSour::ANY+ dstParams::ANY+ orParams::ANY+
ModelElement:
        dependencyUMLsupp::ANY dependencyUMLcli::ANY
DependancyUML:
        suppier::ANY+ client::ANY+
MetaTask:
        params::ANY+ occurs::ANY+
ParameterUML:
        task::ANY doc::ANY+
MetaDocument:
        params::ANY+
