TimeBase:
        EPSILON
Instant:
        EPSILON
TimeValue:
        EPSILON
TimeInterval:
        EPSILON
Interval:
        EPSILON
SingleTimeBase:
        currentValue::ANY maximumValue::ANY currentInstant::ANY
SingleInstant:
        coPoint::ANY
SingleInterval:
        first::ANY last::ANY members::ANY+
SingleTimeValue:
        denotedInstant::ANY+ ref::ANY
SingleTimeInterval:
        start::ANY end::ANY
DiscreteTimeBase:
        refEvent::ANY
DiscreteInstant:
        next::ANY previous::ANY refOcc::ANY
Event:
        EPSILON
EventOccurence:
        EPSILON
PhysicalTime:
        EPSILON
PhysicalInstant:
        EPSILON
Duration:
        EPSILON
MultipleTimeBase:
        bases::ANY+
CoincidencePoint:
        coincidenceInstants::ANY+
MultipleInterval:
        first::ANY+ last::ANY+
MultipleTimeValue:
        values::ANY+
MetricTimeValue:
        EPSILON
DiscreteTimeValue:
        denotedInstant::ANY+ ref::ANY
MetricTimeInterval:
        EPSILON
DiscreteTimeInterval:
        endValues::ANY denotedInterval::ANY+
SimultaneousEventOccurrence:
        at::ANY occurence::ANY
TimedEvent:
        timestamp::ANY+
TimedEventOccurence:
        at::ANY timestamp::ANY
TimedAction:
        duration::ANY+ start::ANY+ end::ANY+
Delay:
        EPSILON
TimingMechanism:
        stability::ANY drift::ANY skew::ANY origin::ANY resolution::ANY refClock::ANY state::ANY
Clock:
        accuracy::ANY offset::ANY generatedInterrupt::ANY+
Timer:
        isPeriodic::ANY duration::ANY genratedTimeOuts::ANY+
TimeOut:
        EPSILON
ClockInterrupt:
        EPSILON
System:
        dimension::ANY+
Model:
        ownes::ANY+
AnnotatedModel:
        conformsTo::ANY+ import::ANY+
ModelElement:
        owner::ANY
AnnotatedModelElement:
        annotation::ANY+
NFP:
        measurementQuantity::ANY storedBy::ANY+ groupedBy::ANY
NFPLibrary:
        refersTo::ANY+ usedNFP::ANY+
NFPCategory:
        setOf::ANY+ ownes::ANY+ owner::ANY
ModelingConcern:
        relevantQuantity::ANY+ annotedModel::ANY
AnalysisConcern:
        EPSILON
DesignConcern:
        EPSILON
Quantity:
        EPSILON
BasicQuantity:
        EPSILON
DerivedQuantity:
        EPSILON
QualitativeNFP:
        parameter::ANY+
QuantitativeNFP:
        sampleSet::ANY+ measure::ANY+
Realization:
        function::ANY+ owner::ANY
Measure:
        appliesTo::ANY+ owner::ANY
ComplexNFP:
        parent::ANY+ child::ANY+ ownes::ANY+
BasicNFP:
        statisticalQualifier::ANY directon::ANY typedBy::ANY valuedBy::ANY+ dimensionOf::ANY+
NFPType:
        valueSpecificationLanguage::ANY source::ANY constrainedSpec::ANY+
NFPInstantType:
        value::ANY unit::ANY
NFPurationType:
        value::ANY unit::ANY
NFPRateType:
        value::ANY unit::ANY
NFPProbabilityType:
        value::ANY unit::ANY
NFPSizeType:
        value::ANY unit::ANY
NFPValueSpecification:
        constrainedBy::ANY+ expression::ANY
NFPConstant:
        ownerList::ANY
NFPListConstant:
        listElements::ANY+
NFPStringConstant:
        body::ANY
NFPIntegerConstant:
        body::ANY
NFPRealConstant:
        bodyBeforeComa::ANY bodyAfterComa::ANY
NFPBooleanConstant:
        body::ANY
NFPVariable:
        varName::ANY
NFPExpression:
        body::ANY+ operand::ANY+
SourceKinds:
        est::EPSILON
        meas::EPSILON
        req::EPSILON
        implicit::EPSILON
        calc::EPSILON
DirectionKinds:
        increasing::EPSILON
        decreasing::EPSILON
        undefined::EPSILON
StatisticalQualifierKinds:
        max::EPSILON
        min::EPSILON
        range::EPSILON
        mean::EPSILON
        variance::EPSILON
        standardDeviation::EPSILON
        percentil::EPSILON
        frequency::EPSILON
        moment::EPSILON
        distribution::EPSILON
        instantaneous::EPSILON
InstantUnitKinds:
        TAI::EPSILON
        UT0::EPSILON
        UT1::EPSILON
        UTC::EPSILON
        TT::EPSILON
        TDB::EPSILON
        TCG::EPSILON
        TCB::EPSILON
        Sideral::EPSILON
        Local::EPSILON
DurationUnitKinds:
        ns::EPSILON
        us::EPSILON
        ms::EPSILON
        s::EPSILON
        min::EPSILON
        hrs::EPSILON
        dys::EPSILON
        wks::EPSILON
        mos::EPSILON
        yrs::EPSILON
RateUnitKinds:
        kbs::EPSILON
        MIPS::EPSILON
ProbabilityUnitKinds:
        us::EPSILON
        s::EPSILON
SizeUnitKinds:
        bits::EPSILON
        bytes::EPSILON
        Mb::EPSILON
        MB::EPSILON
Classifier:
        EPSILON
ResourceClassifier:
        EPSILON
ResourceServiceClassifier:
        EPSILON
InstanceSpecification:
        EPSILON
ResourceInstanceSpecification:
        EPSILON
ResourceServiceInstanceSpecification:
        EPSILON
Hardware:
        owner::ANY containH::ANY+ containHL::ANY+ containHE::ANY+ deploymentConfiguration::ANY+
HardwareLibrary:
        owner::ANY
HardwareEntity:
        owner::ANY
HardwareDeployment:
        owner::ANY contain::ANY+
HardwareEntityInstance:
        owner::ANY
ECUInstance:
        composedOf::ANY+
ChannelInstance:
        gateInstances::ANY
ECUGateInstance:
        channel::ANY
ECU:
        contain::ANY+
ECUGate:
        owner::ANY kindOf::ANY
Channel:
        specify::ANY
AnalysisContext:
        global::ANY+ workload::ANY behavior::ANY usedResources::ANY+
Workload:
        transaction::ANY+
Transaction:
        workload::ANY+ trigger::ANY+ response::ANY
Trigger:
        arrivalPattern::ANY effect::ANY+
Response:
        efficiency::ANY endToEndLatency::ANY cause::ANY+ behavior::ANY+
Behavior:
        scenario::ANY+
Scenario:
        behavior::ANY+ scenarionLatency::ANY+ steps::ANY+ root::ANY endToEndResponse::ANY
Step:
        predecessor::ANY+ successor::ANY+ stepLatency::ANY+ usedResourceService::ANY+
Resource:
        EPSILON
BasicResource:
        EPSILON
StructuredResource:
        basicResource::ANY
ProcessingResource:
        links::ANY+ components::ANY+
Link:
        EPSILON
ProcessResource:
        components::ANY+
Component:
        process::ANY+ interfaces::ANY+
StructuredComponent:
        EPSILON
BasicComponent:
        EPSILON
LogicalResource:
        EPSILON
ServerResource:
        services::ANY+
Service:
        resource::ANY interface::ANY
Interface:
        service::ANY
