Strong:
        EPSILON
Start:
        EPSILON
End:
        EPSILON
FeedBack:
        EPSILON
Weak:
        EPSILON
Grouping:
        EPSILON
Precedence:
        DynPrecedence
Precedence:
        DerPrecedence
Precedence:
        BasPrecedence
Precedence:
        deprecs::DerPrecedence+ parbind::ParBinding+
DynPrecedence:
        EPSILON
DerPrecedence:
        precs::Precedence+ auxTasks::MetaTaskOccurence+
BasPrecedence:
        EPSILON
MetaTaskOccurence:
        dprecs::DerPrecedence+ taskCl::MetaTask+
ParBinding:
        inclusion::Boolean precs::Precedence+ targetPar::ParameterPrec sourcePar::ParameterPrec
ParameterPrec:
        parbindsTar::ParBinding+ parbindsSour::ParBinding+ dstParams::ParameterPrec+ orParams::ParameterPrec+
ModelElement:
        MetaTaskOccurence
ModelElement:
        MetaTask
ModelElement:
        dependencyUMLsupp::DependancyUML dependencyUMLcli::DependancyUML
DependancyUML:
        suppier::ModelElement+ client::ModelElement+
MetaTask:
        params::ParameterUML+ occurs::MetaTaskOccurence+
ParameterUML:
        ParameterPrec
ParameterUML:
        task::MetaTask doc::MetaDocument+
MetaDocument:
        params::ParameterUML+
