EDataType:
        value::ANY
NamedObject:
        name::ANY
Attribute:
        att_container::ANY value::ANY
Entity:
        attributes::ANY+ parameters::ANY+ ports::ANY+
Port:
        po_container::ANY links::ANY+
Relation:
        ports::ANY+
Director:
        ca_container::ANY
Parameter:
        pa_container::ANY dataType::ANY
ComponentPort:
        EPSILON
ComponentRelation:
        re_container::ANY
ComponentEntity:
        ce_container::ANY
AtomicActor:
        EPSILON
CompositeEntity:
        containees::ANY+ relations::ANY+
WorkSpace:
        EPSILON
CompositeActor:
        directors::ANY
