QoSComponent:
        profile::ANY+ operations::ANY
QoSProfile:
        EPSILON
QoSContraints:
        EPSILON
Operation:
        EPSILON
CompoundProfile:
        profileTransition::ANY+ simpleProfile::ANY+
SimpleProfile:
        compoundProfile::ANY use::ANY provides::ANY
ProfileTransition:
        operations::ANY+ from::ANY to::ANY compoundProfile::ANY
QoSStatement:
        contraints::ANY+ relation::ANY parameter::ANY+
SingleQoSStatement:
        contraint::ANY
CoumpoundQoSStatement:
        statement::ANY
QoSContraint:
        qualification::ANY
QualificationKind:
        value::ANY
QoSCharacteristic:
        invariant::ANY parallel_and_composition::ANY parallel_or_composition::ANY sequential_composition::ANY values::ANY statisticalAttribute::ANY+ parameter::ANY domain::ANY
BooleanExpression:
        value::ANY
MappingExpression:
        value::ANY
StatisticalAttributekindKind:
        EPSILON
Parameter:
        EPSILON
DataType:
        EPSILON
Domain:
        direction::ANY
DirectionKind:
        value::ANY
Numeric:
        EPSILON
Set:
        stringSet::ANY+
Enumeration:
        EPSILON
StringSet:
        string::ANY+
