CollectionTypes:
        individual::EPSILON
        set::EPSILON
        orderedSet::EPSILON
        bag::EPSILON
        sequence::EPSILON
PredicateCategory:
        closed::EPSILON
        open::EPSILON
        partial::EPSILON
ExternalVocabularyLanguage:
        RDFS::EPSILON
        UML::EPSILON
        OWL::EPSILON
PredicateType:
        ObjectClassificationPredicate::EPSILON
        AttributionPredicate::EPSILON
        AssociationPredicate::EPSILON
        ReferencePropertyPredicate::EPSILON
        EqualityPredicate::EPSILON
        InequalityPredicate::EPSILON
        DatatypePredicate::EPSILON
        DataClassificationPredicate::EPSILON
ReactionRuleSet:
        rules::ANY+
ProductionRuleSet:
        rules::ANY+
EventType:
        eventTypeID::ANY
RuleSet:
        EPSILON
RuleBase:
        vocabularies::ANY externalVocabulaires::ANY+ rules::ANY+ ruleBaseID::ANY
IntegrityRuleSet:
        rules::ANY+
DerivationRuleSet:
        rules::ANY+
