NamedElement:
        DataBase
NamedElement:
        Table
DataBase:
        SGBDname::String tables::Table+
Table:
        database::DataBase tuples::Tuple+
Tuple:
        owner::Table elements::TupleElement+
TupleElement:
        tuple::Tuple value::String
