Subsystem:
        classes::Class+ relations::Relation+
Relation:
        subsystem::Subsystem classes::Class
Class:
        name::String is_deferred::Boolean features::Feature+ parentSubsystem::Subsystem subsystem::Subsystem relations::Relation+
Feature:
        Entity
Feature:
        Routine
Feature:
        theClass::Class type::Type
Type:
        name::String
Entity:
        EPSILON
Routine:
        EPSILON
