Subsystem:
        classes::ANY+ relations::ANY+
Relation:
        subsystem::ANY classes::ANY
Class:
        name::ANY is_deferred::ANY features::ANY+ parentSubsystem::ANY subsystem::ANY relations::ANY+
Feature:
        theClass::ANY type::ANY
Type:
        name::ANY
Entity:
        EPSILON
Routine:
        EPSILON
