Project:
        documents::ANY+
TypedElement:
        EPSILON
ElementWithIL:
        EPSILON
Document:
        project::ANY sections::ANY+
TextElement:
        EPSILON
Section:
        document::ANY sectionChildren::ANY+ sectionParent::ANY requirements::ANY+
AbstractRequirement:
        EPSILON
Requirement:
        section::ANY isContained::ANY coverLinks::ANY+ attribute::ANY+
MacroRequirement:
        contains::ANY+
CoverLink:
        linkWith::ANY
Attribute:
        value::ANY
