DescribedElt:
        EPSILON
NamedElt:
        EPSILON
ContainerElt:
        EPSILON
Project:
        content::ANY+ packages::ANY+
Package:
        parentPackage::ANY
ContainedElt:
        EPSILON
TypedElt:
        EPSILON
Document:
        EPSILON
Attribute:
        value::ANY
Requirement:
        text::ANY attributes::ANY+ location::ANY parent::ANY children::ANY+ coverLink::ANY+
