RSS:
        version::String channel::Channel
Channel:
        title::String link::String description::String language::String copyright::String managingEditor::String webmaster::String generator::String docs::String ttl::Integer rating::String skipHours::Integer+ skipDays::DayKind+ rss::RSS pubDate::Date lastBuildDate::Date image::Image textInput::TextInput cloud::Cloud category::Category items::Item+
Item:
        title::String link::String description::String author::String comments::String guid::String source::Source pubDate::Date enclosure::Enclosure category::Category channel::Channel
Image:
        url::String title::String link::String description::String width::Integer height::Integer channel::Channel
TextInput:
        title::String description::String name::String link::String channel::Channel
Cloud:
        domain::String port::Integer path::String registerProcedure::String protocol::String channel::Channel
Category:
        domain::String value::String
Enclosure:
        url::String lenght::Integer type::String
Source:
        url::String value::String
Date:
        eDay::DayKind day::Integer month::Integer year::Integer hours::Integer minutes::Integer seconds::Integer
DayKind:
        Monday::EPSILON
        Tuesday::EPSILON
        Wednesday::EPSILON
        Thursday::EPSILON
        Friday::EPSILON
        Saturday::EPSILON
        Sunday::EPSILON
