RSS:
        version::ANY channel::ANY
Channel:
        title::ANY link::ANY description::ANY language::ANY copyright::ANY managingEditor::ANY webmaster::ANY generator::ANY docs::ANY ttl::ANY rating::ANY skipHours::ANY+ skipDays::ANY+ rss::ANY pubDate::ANY lastBuildDate::ANY image::ANY textInput::ANY cloud::ANY category::ANY items::ANY+
Item:
        title::ANY link::ANY description::ANY author::ANY comments::ANY guid::ANY source::ANY pubDate::ANY enclosure::ANY category::ANY channel::ANY
Image:
        url::ANY title::ANY link::ANY description::ANY width::ANY height::ANY channel::ANY
TextInput:
        title::ANY description::ANY name::ANY link::ANY channel::ANY
Cloud:
        domain::ANY port::ANY path::ANY registerProcedure::ANY protocol::ANY channel::ANY
Category:
        domain::ANY value::ANY
Enclosure:
        url::ANY lenght::ANY type::ANY
Source:
        url::ANY value::ANY
Date:
        eDay::ANY day::ANY month::ANY year::ANY hours::ANY minutes::ANY seconds::ANY
DayKind:
        Monday::EPSILON
        Tuesday::EPSILON
        Wednesday::EPSILON
        Thursday::EPSILON
        Friday::EPSILON
        Saturday::EPSILON
        Sunday::EPSILON
