Actuality:
        EPSILON
StateOfAffairs:
        EPSILON
Thing:
        name::ANY+
Name:
        EPSILON
Designation:
        implicitlyIsUnderstood::ANY signifier::ANY
Representation:
        meaning::ANY expression::ANY
Meaning:
        representation::ANY+
Expression:
        EPSILON
BindableTarget:
        EPSILON
AdoptedDefinition:
        EPSILON
Definition:
        EPSILON
Advice:
        EPSILON
ElementOfGuidance:
        isPracticable::ANY
Proposition:
        isFalse::ANY isTrue::ANY statement::ANY+ isPossiblyTrue::ANY isObligatedToBeTrue::ANY isPermittedToBeTrue::ANY isNecessarilyTrue::ANY
Statement:
        EPSILON
AdviceOfContingency:
        EPSILON
AdviceOfPossibility:
        EPSILON
AdviceOfOptionality:
        EPSILON
AdviceOfPermission:
        EPSILON
AdviceStatement:
        EPSILON
GuidanceStatement:
        EPSILON
AggregationFormulation:
        EPSILON
ProjectingFormulation:
        projection::ANY
LogicalFormulation:
        EPSILON
SemanticFormulation:
        EPSILON
Projection:
        constrainingFormulation::ANY projectionVariable::ANY+ auxiliaryVariable::ANY+
Variable:
        restrictingFormulation::ANY projectionPosition::ANY rangedoverConcept::ANY isUnitary::ANY
PositiveInteger:
        EPSILON
NonnegativeInteger:
        EPSILON
Integer:
        value::ANY
Number:
        EPSILON
Quantity:
        EPSILON
NounConcept:
        EPSILON
Concept:
        attributiveNamespace::ANY+ definition::ANY+ moreGeneralConcept::ANY+ category::ANY+ essentialCharacteristic::ANY+ instance::ANY+ referenceScheme::ANY+ impliedCharacteristic::ANY+ necessaryCharacteristic::ANY+ designation::ANY+ extension::ANY
AttributiveNamespace:
        EPSILON
Namespace:
        uri::ANY+
Uri:
        EPSILON
Text:
        value::ANY
Characteristic:
        EPSILON
FactType:
        factTypeForm::ANY+ role::ANY+
FactTypeForm:
        placeholder::ANY+
Placeholder:
        startingCharacterPosition::ANY
FactTypeRole:
        roleBinding::ANY+
Role:
        EPSILON
RoleBinding:
        EPSILON
ReferenceScheme:
        simplyUsedRole::ANY+ identifyingCharacteristic::ANY+ extensionallyUsedRole::ANY+
Set:
        cardinality::ANY element::ANY+
AuxiliaryVariable:
        EPSILON
AnswerNominalization:
        EPSILON
AssociativeFactType:
        EPSILON
AssortmentFactType:
        EPSILON
AtleastnQuantification:
        minimumCardinality::ANY
Quantification:
        scopeFormulation::ANY
AtmostnQuantification:
        maximumCardinality::ANY
AtmostoneQuantification:
        EPSILON
AtomicFormulation:
        roleBinding::ANY+
BagProjection:
        EPSILON
BinaryFactType:
        EPSILON
BinaryLogicalOperation:
        logicalOperand2::ANY+ logicalOperand1::ANY+
LogicalOperation:
        logicalOperand::ANY
BodyOfSharedConcepts:
        EPSILON
BodyOfSharedGuidance:
        EPSILON
BodyOfSharedMeanings:
        elementaryFactType::ANY+
BusinessPolicy:
        EPSILON
ElementOfGovernance:
        isDirectlyEnforceable::ANY
BusinessPolicyStatement:
        EPSILON
BusinessRule:
        EPSILON
Rule:
        EPSILON
BusinessVocabulary:
        EPSILON
Vocabulary:
        EPSILON
CategorizationFactType:
        EPSILON
SpecializationFactType:
        EPSILON
CategorizationScheme:
        EPSILON
CategorizationType:
        EPSILON
CharacteristicType:
        EPSILON
ConceptType:
        EPSILON
ObjectType:
        categorizationScheme::ANY+ categorizationType::ANY+
ClosedLogicalFormulation:
        EPSILON
ClosedSemanticFormulation:
        EPSILON
ClosedProjection:
        EPSILON
CommunicationContent:
        EPSILON
Community:
        uri::ANY+ subcommunity::ANY+
ConceptOfThingAsComposite:
        EPSILON
ConceptOfThingAsContinuant:
        EPSILON
ConceptOfThingAsDeveloped:
        EPSILON
ConceptOfThingAsOccurrent:
        EPSILON
ConceptOfThingAsPrimitive:
        EPSILON
ConceptOfThingAsUnitary:
        EPSILON
ConceptOfThingExistingDependently:
        EPSILON
ConceptOfThingExistingIndependently:
        EPSILON
ConceptualSchema:
        EPSILON
Conjunction:
        EPSILON
ContextOfThing:
        EPSILON
Segmentation:
        EPSILON
ContextualizationFactType:
        EPSILON
ContextualizedConcept:
        EPSILON
ContingencyStatement:
        EPSILON
StatementOfAdviceOfPossibility:
        EPSILON
DefiniteDescription:
        EPSILON
IntensionalDefinition:
        EPSILON
DerivableConcept:
        EPSILON
Description:
        EPSILON
DescriptiveExample:
        EPSILON
Disjunction:
        EPSILON
Equivalence:
        EPSILON
ExactlynQuantification:
        cardinality::ANY
ExactlyoneQuantification:
        EPSILON
ExclusiveDisjunction:
        EPSILON
ExistentialQuantification:
        EPSILON
ExplicitnessOfRepresentation:
        EPSILON
ExtensionalDefinition:
        EPSILON
Facet:
        EPSILON
Fact:
        EPSILON
FactModel:
        EPSILON
FactSymbol:
        EPSILON
FactTypeHasFactInFactModel:
        factType::ANY fact::ANY factModel::ANY
FactTypeNominalization:
        EPSILON
FactTypeRoleDesignation:
        EPSILON
FactTypeTemplating:
        EPSILON
FormalRepresentation:
        EPSILON
FundamentalConcept:
        EPSILON
Icon:
        EPSILON
NonverbalDesignation:
        EPSILON
Implication:
        consequent::ANY+ antecedent::ANY+
ImpossibilityStatement:
        EPSILON
StructuralRuleStatement:
        EPSILON
RuleStatement:
        EPSILON
IndividualConcept:
        EPSILON
InformalRepresentation:
        EPSILON
InstantiationFormulation:
        EPSILON
IsfacetofFactType:
        EPSILON
IspropertyofFactType:
        EPSILON
IsroleofFactType:
        EPSILON
KindOfGuidanceStatement:
        EPSILON
Language:
        EPSILON
LevelOfEnforcement:
        EPSILON
LogicalFormulationKind:
        EPSILON
LogicalNegation:
        EPSILON
ModalFormulation:
        EPSILON
NandFormulation:
        EPSILON
NecessityFormulation:
        EPSILON
NecessityStatement:
        EPSILON
NonnecessityStatement:
        EPSILON
NonobligationStatement:
        EPSILON
StatementOfAdviceOfPermission:
        EPSILON
NorFormulation:
        EPSILON
Note:
        EPSILON
NounConceptNominalization:
        EPSILON
NounForm:
        EPSILON
NumericRangeQuantification:
        maximumCardinality::ANY minimumCardinality::ANY
Objectification:
        EPSILON
ObligationFormulation:
        EPSILON
ObligationStatement:
        EPSILON
OperativeBusinessRuleStatement:
        EPSILON
OperativeBusinessRule:
        levelOfEnforcement::ANY+
OptionalityStatement:
        EPSILON
OwnedDefinition:
        EPSILON
PartitiveFactType:
        EPSILON
PermissibilityFormulation:
        EPSILON
PermissionStatement:
        EPSILON
PossibilityFormulation:
        EPSILON
PossibilityStatement:
        EPSILON
PreferredDesignation:
        EPSILON
ProhibitedDesignation:
        EPSILON
ProhibitionStatement:
        EPSILON
PropositionNominalization:
        EPSILON
Question:
        EPSILON
QuestionNominalization:
        EPSILON
RealworldNumericalCorrespondence:
        EPSILON
Reference:
        EPSILON
RepresentationFormality:
        EPSILON
Res:
        EPSILON
RestrictedPermissionStatement:
        EPSILON
RestrictedPossibilityStatement:
        EPSILON
Rulebook:
        EPSILON
SemanticCommunity:
        speechCommunity::ANY+
SpeechCommunity:
        EPSILON
SententialForm:
        EPSILON
SetProjection:
        EPSILON
Situation:
        EPSILON
SituationalRole:
        EPSILON
SpeechCommunityAdoptsAdoptedDefinitionCitingReference:
        speechCommunity::ANY adoptedDefinition::ANY reference::ANY
StateOfAffairsInvolvesThingInRole:
        stateOfAffairs::ANY thing::ANY role::ANY
StructuralBusinessRule:
        EPSILON
StructuralRule:
        EPSILON
SubjectField:
        EPSILON
Term:
        EPSILON
TerminologicalDictionary:
        uri::ANY+
ThingInContext:
        EPSILON
UniversalQuantification:
        EPSILON
Viewpoint:
        EPSILON
VocabularyNamespace:
        EPSILON
WhetherornotFormulation:
        inconsequent::ANY+ consequent::ANY+
