LocatedElement:
        EPSILON
Root:
        entries::ANY+
VocabularyEntry:
        primaryRep::ANY caption::ANY+
Caption:
        EPSILON
DefCaption:
        definition::ANY
DescCaption:
        description::ANY
SrcCaption:
        source::ANY
DBCaption:
        dictionaryBasis::ANY
GenCCaption:
        generalConcept::ANY
CTypCaption:
        conceptType::ANY+
Necessity:
        exp::ANY
Possibility:
        exp::ANY
RefSCaption:
        referenceScheme::ANY
NoteCaption:
        note::ANY
ExCaption:
        example::ANY+
SynCaption:
        synonym::ANY+
SynFCaption:
        synonymousForm::ANY+
SeeCaption:
        see::ANY
SFCaption:
        subjectField::ANY
NSURICaption:
        namespaceURI::ANY
PrimaryRepresentation:
        EPSILON
NotFactTypeRepresentation:
        EPSILON
TermRepresentation:
        term::ANY+
NameRepresentation:
        hasThe::ANY name::ANY+
FactTypeFormRepresentation:
        primaryRep1::ANY verbExp::ANY+ primaryRep2::ANY
ConceptDefinition:
        exp::ANY conjexp::ANY+
ConceptSource:
        source::ANY+
Note:
        sentences::ANY+
Sentence:
        words::ANY+
NameSpaceURI:
        URI::ANY+
Word:
        EPSILON
StringWord:
        val::ANY
QuotedStringWord:
        val::ANY
NameWord:
        val::ANY
Verb:
        is::EPSILON
        relevant::EPSILON
        comprises::EPSILON
        to::EPSILON
        work::EPSILON
        in::EPSILON
        trades::EPSILON
        as::EPSILON
        are::EPSILON
        accepted::EPSILON
        generally::EPSILON
        important::EPSILON
        across::EPSILON
        share::EPSILON
        sets::EPSILON
        assigned::EPSILON
        by::EPSILON
        contains::EPSILON
        for::EPSILON
        has::EPSILON
        specifies::EPSILON
        specified::EPSILON
ConjonctionnalKeyWord:
        and::EPSILON
        or::EPSILON
        if::EPSILON
        whether::EPSILON
ModalVerb:
        must::EPSILON
        may::EPSILON
        never::EPSILON
        always::EPSILON
Join:
        that::EPSILON
        who::EPSILON
Link:
        of::EPSILON
        quoteS::EPSILON
Qualif:
        the::EPSILON
        The::EPSILON
        a::EPSILON
        A::EPSILON
        an::EPSILON
        An::EPSILON
        Each::EPSILON
        each::EPSILON
        Some::EPSILON
        some::EPSILON
        At::EPSILON
        at::EPSILON
        Exactly::EPSILON
        exactly::EPSILON
EndOperator:
        given::EPSILON
        thanone::EPSILON
        one::EPSILON
        isobligatorythat::EPSILON
        ispermittedthat::EPSILON
        isprohibitedthat::EPSILON
        isnecessarythat::EPSILON
        ispossiblethat::EPSILON
        isimpossiblethat::EPSILON
        isnotthecasethat::EPSILON
        least::EPSILON
        leastone::EPSILON
        most::EPSILON
        mostone::EPSILON
        leastnandatmostm::EPSILON
        andonlyif::EPSILON
        ornot::EPSILON
        not::EPSILON
        of::EPSILON
SBVRExpression:
        hasPoint::ANY firstProposition::ANY nextProposition::ANY+
SBVRPropWithKW:
        conjonction::ANY endConj::ANY proposition::ANY
ModalForm:
        modal::ANY isNeg::ANY
SimpleSBVRProp:
        modal::ANY concept1::ANY modalVerb::ANY verbs::ANY+ concept2::ANY
SubSBVRProp:
        join::ANY modalVerb::ANY verbs::ANY+ concept2::ANY
LinkSBVRConcept:
        link::ANY concept::ANY
ConjConcept:
        conjonction::ANY concept::ANY
Concept:
        EPSILON
NameConcept:
        the::ANY name::ANY+
ObjectConcept:
        operatoredConcept::ANY qualify::ANY
StringConcept:
        stringWord::ANY+
NounConcept:
        qualif::ANY noun::ANY+
Qualification:
        generalConcept::ANY+
GeneralConcept:
        EPSILON
NameGConcept:
        name::ANY
NounGConcept:
        noun::ANY+
Qualifier:
        op::ANY endOperator::ANY min::ANY max::ANY
ModalBegin:
        endOperator::ANY
ModalBeginC:
        EPSILON
