Man:
        language::ANY title::ANY type::ANY date::ANY name::ANY keyword::ANY exemple::ANY meta::ANY+
Meta:
        meta::ANY path::ANY category::ANY version_CSI::ANY version_DOC::ANY author::ANY man::ANY
Short_Description:
        name::ANY verb::ANY+
Calling_Sequence:
        calling_Sequence_Item::ANY+
Calling_Sequence_Item:
        calling_Sequence_Item::ANY+ calling_Sequence::ANY
Param:
        target::ANY param_Indent::ANY+
Param_Indent:
        param::ANY param_Description::ANY param_Item::ANY+
Param_Item:
        label::ANY param_Indent::ANY param_Name::ANY param_Description::ANY
Param_Name:
        verb::ANY+ param_Item::ANY
Param_Description:
        param_Indent::ANY+ param_Item::ANY
Description:
        itemize::ANY+ description_Indent::ANY+
Description_Indent:
        description::ANY description_Item::ANY+
Description_Item:
        label::ANY description_Indent::ANY
AIMG:
        verb::ANY+
See_Also:
        see_Also_Item::ANY+
Exemple:
        exemple::ANY xml_space::ANY
See_Also_Item:
        see_Also::ANY link::ANY+
A:
        href::ANY psppp::ANY authors_Item::ANY
Img:
        src::ANY psppp::ANY
Biblio:
        p::ANY+ sp::ANY+ pp::ANY+
Used_Functions:
        verbatim::ANY+ table::ANY+
PSPPP:
        verb::ANY+ em::ANY+ bd::ANY+ tt::ANY+ a::ANY+ link::ANY+ img::ANY+
P:
        biblio::ANY
SP:
        biblio::ANY
PP:
        biblio::ANY
Itemize:
        label::ANY item::ANY section::ANY authors_Item::ANY description::ANY
Item:
        itemize::ANY+
Table:
        table_New_Row::ANY+ used_Functions::ANY
Table_New_Row:
        table_New_Column::ANY+ table::ANY
Table_New_Column:
        Verb::ANY+ em::ANY+ bd::ANY+ tt::ANY+ table_New_Row::ANY
Link:
        link::ANY psppp::ANY see_Also_Item::ANY authors_Item::ANY
Authors:
        authors_Item::ANY+
Authors_Item:
        Verb::ANY+ em::ANY+ bd::ANY+ tt::ANY+ verbatim::ANY+ label::ANY a::ANY+ link::ANY+ authors::ANY itemize::ANY+
Section:
        itemize::ANY+
InOut:
        in::EPSILON
        out::EPSILON
PreDef:
        Preserve::EPSILON
        Default::EPSILON
