SystemDefinitionModel:
        information::ANY import::ANY+ designData::ANY settingDefinitions::ANY communicationDefinition::ANY+ containmentDefinition::ANY+ delegationDefinition::ANY+ referenceDefinition::ANY+ endpointDefinition::ANY+ resourceDefinition::ANY+ systemDefinition::ANY+ constraintDefinition::ANY+ manager::ANY+ nameSpace::ANY namespaceIdentity::ANY documentLanguage::ANY+ compilationHash::ANY+
Information:
        sdm::ANY friendlyname::ANY companyname::ANY copyright::ANY trademark::ANY description::ANY comments::ANY compilerversion::ANY
Import:
        sdm::ANY alias::ANY identity::ANY
ImportNamespaceIdentity:
        import::ANY
SDMCommunicationDefinition:
        sdm::ANY
SDMContainmentDefinition:
        sdm::ANY
SDMDelegationDefinition:
        sdm::ANY
SDMReferenceDefinition:
        sdm::ANY
SDMEndpointDefinition:
        sdm::ANY
SDMResourceDefinition:
        sdm::ANY
SDMSystemDefinition:
        sdm::ANY
SDMConstraintDefinition:
        sdm::ANY
SDMManager:
        sdm::ANY
ManagerDeclaration:
        description::ANY name::ANY assemblyName::ANY version::ANY publicKeyToken::ANY culture::ANY platform::ANY sourcePath::ANY
ObjectDefinition:
        flow::ANY+ relationshipConstraint::ANY+ constraint::ANY+ constraintGroup::ANY+ endpointDefinition::ANY+ systemDefinition::ANY+ resourceDefinition::ANY+ communicationDefinition::ANY+ containmentDefinition::ANY+ delegationDefinition::ANY+ referenceDefinition::ANY+ hostingDefinition::ANY+ endpoint::ANY+ subsystem::ANY+ resource::ANY+ hosting::ANY+ containment::ANY+ connection::ANY+ delegation::ANY+ obreference::ANY+ layer::ANY extends::ANY abstract::ANY
OBFlow:
        objectDefinition::ANY
OBRelationshipConstraint:
        objectDefinition::ANY
OBConstraint:
        objectDefinition::ANY
OBConstraintGroup:
        objectDefinition::ANY
OBEndpointDefinition:
        objectDefinition::ANY
OBSystemDefinition:
        objectDefinition::ANY
OBResourceDefinition:
        objectDefinition::ANY
OBCommunicationDefinition:
        objectDefinition::ANY
OBContainmentDefinition:
        objectDefinition::ANY
OBDelegationDefinition:
        objectDefinition::ANY
OBReferenceDefinition:
        objectDefinition::ANY
OBHostingDefinition:
        objectDefinition::ANY
OBEndpoint:
        objectDefinition::ANY
OBSubsystem:
        objectDefinition::ANY
OBResource:
        objectDefinition::ANY
OBHosting:
        objectDefinition::ANY
OBContainment:
        objectDefinition::ANY
OBConnection:
        objectDefinition::ANY
OBDelegation:
        objectDefinition::ANY
OBReference:
        objectDefinition::ANY
SystemDefinition:
        simulationRoot::ANY
EndpointDefinition:
        EPSILON
ResourceDefinition:
        EPSILON
RelationshipDefinition:
        objectConstraint::ANY+ constraint::ANY+ constraintGroup::ANY+ flow::ANY+ connection::ANY+ hosting::ANY+ delegation::ANY+ reference::ANY+ containment::ANY+ extends::ANY abstract::ANY
RDObjectConstraint:
        relationshipDefinition::ANY
RDConstraint:
        relationshipDefinition::ANY
RDConstraintGroup:
        relationshipDefinition::ANY
RDFlow:
        relationshipDefinition::ANY
RDConnection:
        relationshipDefinition::ANY
RDHosting:
        relationshipDefinition::ANY
RDDelegation:
        relationshipDefinition::ANY
RDReference:
        relationshipDefinition::ANY
RDContainment:
        relationshipDefinition::ANY
CommunicationDefinition:
        clientDefinition::ANY serverDefinition::ANY
HostingDefinition:
        guestDefinition::ANY hostDefinition::ANY simulationRoot::ANY
ContainmentDefinition:
        parentDefinition::ANY memberDefinition::ANY
DelegationDefinition:
        proxyDefinition::ANY delegateDefinition::ANY
ReferenceDefinition:
        dependentDefinition::ANY sourceDefinition::ANY
Member:
        description::ANY+ designData::ANY settingValue::ANY+ settingValueList::ANY+ name::ANY definition::ANY
MembSettingValue:
        member::ANY
MembSettingValueList:
        member::ANY
ObjectMember:
        minOccurs::ANY maxOccurs::ANY reference::ANY proxy::ANY
RelationshipMember:
        EPSILON
SystemMember:
        EPSILON
EndpointMember:
        EPSILON
ResourceMember:
        EPSILON
HostingMember:
        guestMember::ANY hostMember::ANY
CommunicationMember:
        clientMember::ANY serverMember::ANY
ContainmentMember:
        childMember::ANY
DelegationMember:
        proxyMember::ANY delegateMember::ANY
ReferenceMember:
        dependentMember::ANY sourceMember::ANY
DesignData:
        nameSpace::ANY+
NameSpace:
        designData::ANY
ObjectConstraint:
        constraint::ANY+ relationshipConstraint::ANY+ constraintGroup::ANY+ primaryRole::ANY primaryObjectDefinition::ANY secondaryRole::ANY+ secondaryObjectDefinition::ANY+ minOccurs::ANY+ maxOccurs::ANY+
OCConstraint:
        objectConstraint::ANY
OCRelationshipConstraint:
        objectConstraint_OC::ANY
OCConstraintGroup:
        objectConstraint_OC::ANY
RelationshipConstraint:
        constraint::ANY+ relationshipConstraint::ANY+ objectConstraint::ANY+ constraintGroup::ANY+ relationshipDefinition::ANY targetRole::ANY targetObjectDefinition::ANY minOccurs::ANY maxOccurs::ANY delegationAware::ANY
RCConstraint:
        relationshipConstraint::ANY
RCRelationshipConstraint:
        relationshipConstraint_RC::ANY
RCObjectConstraint:
        relationshipConstraint_RC::ANY
RCConstraintGroup:
        relationshipConstraint_RC::ANY
ConstraintGroup:
        constraint::ANY+ relationshipConstraint::ANY+ objectConstraint::ANY+
CGConstraint:
        constraintGroup::ANY
CGRelationshipConstraint:
        constraintGroup_CG::ANY
CGObjectConstraint:
        constraintGroup_CG::ANY
StructuralConstraint:
        description::ANY designData::ANY name::ANY evaluate::ANY raiseError::ANY returnEarly::ANY
ConstraintDefinition:
        relationshipConstraint::ANY+ constraintGroup::ANY+ objectConstraint::ANY+ constraint::ANY+ targetDefinition::ANY returnEarly::ANY
CDRelationshipConstraint:
        constraintDefinition::ANY
CDConstraintGroup:
        constraintDefinition::ANY
CDObjectConstraint:
        constraintDefinition::ANY
CDConstraint:
        constraintDefinition::ANY
ConstraintMember:
        input::ANY+ raiseError::ANY evaluate::ANY
Definition:
        description::ANY designData::ANY settingDeclaration::ANY+ settingValue::ANY+ settingValueList::ANY+ name::ANY manager::ANY className::ANY
DefSettingDeclaration:
        definition_DSD::ANY
DefSettingValue:
        definition::ANY
DefSettingValueList:
        definition::ANY
SimpleName:
        EPSILON
QualifiedName:
        EPSILON
Path:
        EPSILON
SettingPath:
        EPSILON
NamespaceIdentity:
        name::ANY version::ANY publicKey::ANY publicKeyToken::ANY culture::ANY platform::ANY
FlowDefinition:
        EPSILON
FlowMember:
        input::ANY+ output::ANY+
ValueTransfer:
        name::ANY path::ANY cast::ANY convert::ANY
Output:
        fixed::ANY replace::ANY
Input:
        EPSILON
SettingDefinitions:
        nameSpace::ANY manager::ANY clrNameSpace::ANY
SettingMember:
        facet::ANY+ settingAttributes::ANY
SettingsAttributes:
        list::ANY access::ANY secure::ANY deploymentTime::ANY required::ANY canBeNull::ANY elementsCanBeNull::ANY defaultRead::ANY defaultWrite::ANY
SettingMemberAccess:
        ReadWrite::EPSILON
        ReadOnly::EPSILON
        WriteOnly::EPSILON
SettingMemberSecure:
        Always::EPSILON
        PerInstance::EPSILON
        Never::EPSILON
Facet:
        name::ANY
SettingValue:
        contents::ANY+ settingValueAttributes::ANY
SettingValueList:
        value::ANY+ settingValueAttributes::ANY
Value:
        contents::ANY+ null::ANY
SettingValueAttributes:
        path::ANY null::ANY fixed::ANY unset::ANY definition::ANY convert::ANY secure::ANY reference::ANY
Description:
        entry::ANY+ resourceId::ANY manager::ANY
Entry:
        description::ANY
DescriptionEntry:
        name::ANY resourceId::ANY manager::ANY substitute::ANY
Substitute:
        descriptionEntry::ANY
PathList:
        settingPath::ANY+
MaxOccurs:
        EPSILON
MinOccurs:
        EPSILON
FourPartVersionType:
        EPSILON
PublicKeyType:
        EPSILON
PublicKeyTokenType:
        EPSILON
CompilationHashType:
        EPSILON
RolesList:
        Host::EPSILON
        Guest::EPSILON
        Parent::EPSILON
        Member::EPSILON
        Source::EPSILON
        Dependent::EPSILON
        Proxy::EPSILON
        Delegate::EPSILON
        Client::EPSILON
        Server::EPSILON
Culture:
        EPSILON
CultureNeutral:
        EPSILON
ProcessorArchitectures:
        x86::EPSILON
        ia64::EPSILON
        amd64::EPSILON
        wow64::EPSILON
        msil::EPSILON
        shx::EPSILON
        arm::EPSILON
        data::EPSILON
Platform:
        x86::EPSILON
        ia64::EPSILON
        amd64::EPSILON
        wow64::EPSILON
        msil::EPSILON
        shx::EPSILON
        arm::EPSILON
        data::EPSILON
        *::EPSILON
        neutral::EPSILON
ConstraintEvaluation:
        Design::EPSILON
        Never::EPSILON
Element:
        value::ANY
