Group:
        subjectGroup::Subject+
User:
        EPSILON
Subject:
        Group
Subject:
        User
Subject:
        group::Group role::Role+
Role:
        roleHierarchy::Role+ subjectAssignment::Subject+ permissionAssignment::Permission+
Permission:
        role::Role+ constraintAssignment::AuthorizationConstraint actionAssignment::Action+
AuthorizationConstraint:
        permission::Permission+
AtomicAction:
        EPSILON
CompositeAction:
        subordinatedAction::Action+
Action:
        AtomicAction
Action:
        CompositeAction
Action:
        permission::Permission+ resource::Resource actionHyerarchy::CompositeAction+
Resource:
        resourceAction::Action+
