LogFile:
        file::ANY instance::ANY logger::ANY
Logger:
        instance::ANY expression::ANY logFile::ANY
Expression:
        loggingOn::ANY logger::ANY
Literal:
        value::ANY
VariableExpression:
        name::ANY
NumberExpression:
        EPSILON
UnaryOperator:
        operand::ANY
UnaryPlusOp:
        EPSILON
UnaryMinusOp:
        EPSILON
BinaryOperator:
        operand1::ANY operand2::ANY
PlusOperator:
        EPSILON
MinusOperator:
        EPSILON
