SeminarSchedulingSystem:
        presenter::ANY+ seminar::ANY+
Presenter:
        name::ANY seminarSchedulingSystem::ANY qualifiedFor::ANY+ offering::ANY+
Seminar:
        title::ANY seminarSchedulingSystem::ANY qualified::ANY+ offering::ANY+
Offering:
        is_cancelled::ANY date::ANY attendee::ANY+ presenter::ANY seminar::ANY
Date:
        year::ANY month::ANY day::ANY
Attendee:
        name::ANY offering::ANY+
