ModelElement:
        EPSILON
Classifier:
        EPSILON
Operation:
        name::ANY
Service:
        operations::ANY+
BusinessObject:
        operations::ANY+
ServiceOperation:
        BOFlows::ANY+ rules::ANY+
BusinessObjectOperation:
        rules::ANY+
BusinessRule:
        expr::ANY
Flow:
        EPSILON
Service2BusinessObjectFlow:
        source::ANY target::ANY
