RootFolder:
        compoundComponent::CompoundComponent+
CompoundComponent:
        rootFolder::RootFolder baseComponent::BaseComponent+ localPort::LocalPort+
PrimitiveComponent:
        EPSILON
BaseComponent:
        CompoundComponent
BaseComponent:
        PrimitiveComponent
BaseComponent:
        name::String position::String signal::Signal+ outputPort::OutputPort+ inputPort::InputPort+ compoundComponent::CompoundComponent
InputPort:
        baseComponent::BaseComponent
LocalPort:
        compoundComponent::CompoundComponent
OutputPort:
        baseComponent::BaseComponent
PortBase:
        InputPort
PortBase:
        LocalPort
PortBase:
        OutputPort
PortBase:
        name::String position::String associationPortBase_PortBasesrc::AssociationPortBase_PortBase associationPortBase_PortBasedst::AssociationPortBase_PortBase
Signal:
        name::String position::String baseComponent::BaseComponent associationPortBase_PortBase::AssociationPortBase_PortBase
AssociationPortBase_PortBase:
        srcPortBase::PortBase+ dstPortBase::PortBase+ signal::Signal
