Root:
        elements::ANY+
Element:
        objectName::ANY
Representation:
        meaning::ANY
Designation:
        text::ANY
Text:
        value::ANY
Meaning:
        representations::ANY+
Concept:
        EPSILON
NounConcept:
        EPSILON
ObjectType:
        specializes::ANY generalizes::ANY+
IndividualConcept:
        instanceOf::ANY
DataType:
        EPSILON
NonEmptyString:
        value::ANY
NonNegativeInteger:
        value::ANY
FactType:
        EPSILON
BinaryFactType:
        role1::ANY role2::ANY
IsPropertyOfFactType:
        EPSILON
AssociativeFactType:
        EPSILON
CategorizationFactType:
        EPSILON
ObjectificationFactType:
        EPSILON
Role:
        nounConcept::ANY
FactTypeRole:
        EPSILON
LogicalFormulation:
        EPSILON
AtomicFormulation:
        isBasedOn::ANY
BinaryAtomicFormulation:
        roleBinding1::ANY roleBinding2::ANY
NecessityFormulation:
        EPSILON
Quantification:
        introducedVariable::ANY scopesOver::ANY
UniversalQuantification:
        EPSILON
AtLeastNQuantification:
        minCardinality::ANY
ExactlyNQuantification:
        cardinality::ANY
AtMostNQuantification:
        maxCardinality::ANY
BindableTarget:
        EPSILON
Variable:
        rangesOver::ANY
RoleBinding:
        occursIn::ANY isOf::ANY bindsTo::ANY
