Airport:
        name::ANY departingFlight::ANY+ arrivingFlight::ANY+
Flight:
        departTime::ANY duration::ANY maxnrPassengers::ANY passenger::ANY+ airline::ANY origin::ANY destination::ANY
Airline:
        name::ANY nationality::ANY flight::ANY+
Passenger:
        name::ANY age::ANY gender::ANY needsAssistance::ANY flight::ANY
Genre:
        male::EPSILON
        female::EPSILON
Time:
        year::ANY month::ANY day::ANY hour::ANY minute::ANY second::ANY
