DateType:
        day::Integer month::Integer year::Integer
ControlsSequence:
        controls::Control+
Control:
        c_controlsSequence::ControlsSequence responsible::String component::String developmentPhase::String scope::String date::DateType controlledElt::String eltRef::String eltAuthor::String formRef::String type::ControlType
ControlType:
        BugTracking
BugTracking:
        bugs::Bug+
Bug:
        b_bugTracking::BugTracking number::Integer componentVersion::String description::String status::BugStatusType originator::String responsible::String commentsAnswers::String openDate::String closeDate::String
BugStatusType:
        bst_open::EPSILON
        bst_closed::EPSILON
        bst_skipped::EPSILON
