ArtifactUsageName:
        isInput::ANY isOutput::ANY hasWorkPerArtifact::ANY artifactKind::ANY workDefinition::ANY
ProcessDefinitionElement:
        guidances::ANY+ processComponents::ANY+
Guidance:
        processDefinitionElements::ANY+
ArtifactKind:
        artifactUsageNames::ANY+ responsible::ANY
WorkItem:
        EPSILON
RoleKind:
        artifactKinds::ANY+
Condition:
        EPSILON
ProcessComponent:
        processDefinitionElements::ANY+
Goal:
        workDefinition::ANY
Precondition:
        workDefinition::ANY
WorkDefinition:
        artifactUsageNames::ANY+ goal::ANY precondition::ANY
ActivityKind:
        performer::ANY+ assistant::ANY+
Iteration:
        EPSILON
Phase:
        EPSILON
Lifecycle:
        EPSILON
