LocatedElement:
        EPSILON
NamedElement:
        EPSILON
Database:
        tables::ANY+
Table:
        database::ANY referencedBy::ANY+ elements::ANY+ parameters::ANY+
TableElement:
        EPSILON
Column:
        referencedBy::ANY+ name::ANY type::ANY canBeNull::ANY default::ANY keys::ANY+
Key:
        EPSILON
SimpleKey:
        isUnique::ANY name::ANY columns::ANY+
PrimaryKey:
        isUnique::ANY name::ANY columns::ANY+
ForeignKey:
        referencedTable::ANY referencedColumns::ANY+
Type:
        length::ANY isUnsigned::ANY
Parameter:
        table::ANY value::ANY
Value:
        EPSILON
IntegerVal:
        value::ANY
NullVal:
        
StringVal:
        value::ANY
