Element:
        EPSILON
StructuralElement:
        EPSILON
Image:
        referee::ANY+
Svg:
        owner_SVG::ANY+ children::ANY+ namespace::ANY version::ANY baseProfile::ANY
GroupingElement:
        EPSILON
G:
        name::ANY
Defs:
        groupContent::ANY+
Symbol:
        groupContent::ANY+
Use:
        use::ANY+
GraphicalElement:
        EPSILON
Shape:
        EPSILON
TextElement:
        EPSILON
Rect:
        rx::ANY ry::ANY
Circle:
        
Ellipse:
        
Line:
        between::ANY markerEnd::ANY markerStart::ANY
Polyline:
        waypoints::ANY+ strokeDashArray::ANY markerEnd::ANY markerStart::ANY
Polygon:
        waypoints::ANY+ markerEnd::ANY markerStart::ANY
Path:
        pathLength::ANY d::ANY markerEnd::ANY markerStart::ANY
Point:
        
Marker:
        markerUnits::ANY refX::ANY refY::ANY markerWidth::ANY markerHeight::ANY orient::ANY drawing::ANY+
Text:
        lengthAdjust::ANY content::ANY
Tspan:
        content::ANY
Tref:
        xlinkHref::ANY
Attribute:
        EPSILON
Transform:
        EPSILON
Scale:
        sx::ANY sy::ANY
Translate:
        tx::ANY ty::ANY
Rotate:
        angle::ANY cx::ANY cy::ANY
Visibility:
        visible::ANY
FontWeight:
        bold::ANY
FontStyle:
        italic::ANY
Dimension:
        width::ANY height::ANY
Coordinates:
        EPSILON
RelativeCoord:
        x::ANY y::ANY
AbsoluteCoord:
        x::ANY y::ANY
ReferencedFile:
        EPSILON
SvgFile:
        tag::ANY elements::ANY+
