Bibliography:
        publications::ANY+
Publication:
        EPSILON
Article:
        author::ANY+ journal::ANY month::ANY number::ANY pages::ANY volume::ANY
Book:
        month::ANY number::ANY volume::ANY series::ANY source::ANY address::ANY edition::ANY isbn::ANY price::ANY editor::ANY publisher::ANY author::ANY+
InBook:
        author::ANY+ publisher::ANY editor::ANY month::ANY number::ANY pages::ANY volume::ANY series::ANY chapter::ANY type::ANY address::ANY
Booklet:
        author::ANY+ month::ANY address::ANY edition::ANY howpublished::ANY
InCollection:
        editor::ANY author::ANY+ publisher::ANY month::ANY number::ANY pages::ANY address::ANY edition::ANY volume::ANY series::ANY chapter::ANY type::ANY booktitle::ANY
InProceedings:
        editor::ANY author::ANY+ month::ANY number::ANY pages::ANY address::ANY volume::ANY series::ANY booktitle::ANY organization::ANY publisher::ANY
Proceedings:
        editor::ANY publisher::ANY organization::ANY month::ANY number::ANY volume::ANY address::ANY series::ANY
Manual:
        author::ANY+ organization::ANY month::ANY address::ANY edition::ANY
Misc:
        month::ANY howpublished::ANY
Unpublished:
        author::ANY+ month::ANY
Thesis:
        EPSILON
MasterThesis:
        author::ANY+ school::ANY month::ANY address::ANY type::ANY
PhDThesis:
        author::ANY+ school::ANY month::ANY address::ANY type::ANY
Report:
        EPSILON
ProjectReport:
        describesProject::ANY
TechnicalReport:
        series::ANY organization::ANY
Event:
        name::ANY date::ANY eventTitle::ANY location::ANY atEvent::ANY hasPartEvent::ANY
Conference:
        series::ANY
Workshop:
        series::ANY
Exhibition:
        EPSILON
Lecture:
        givenBy::ANY
Meeting:
        title::ANY participant::ANY+
ProjectMeeting:
        EPSILON
Person:
        address::ANY name::ANY email::ANY fax::ANY homepage::ANY phone::ANY photo::ANY
Employee:
        affiliation::ANY
Manager:
        EPSILON
AdministrativeStaff:
        EPSILON
TechnicalStaff:
        EPSILON
AcademicStaff:
        cooperateWith::ANY+ editor::ANY headOf::ANY headOfGroup::ANY memberOfPC::ANY organizerOrChairOf::ANY publication::ANY+ supervises::ANY+ worksAtProject::ANY
Lecturer:
        EPSILON
FacultyMember:
        EPSILON
FullProfessor:
        EPSILON
AssistantProfessor:
        EPSILON
AssociateProfessor:
        EPSILON
Student:
        studiesAt::ANY
Undergraduate:
        EPSILON
Graduate:
        EPSILON
PhDStudent:
        publication::ANY+ worksAtProject::ANY supervisor::ANY
Organization:
        location::ANY name::ANY carriesOut::ANY+ develops::ANY+ employs::ANY+ finances::ANY+ publishes::ANY+ technicalReport::ANY+
ResearchGroup:
        head::ANY member::ANY+
Association:
        EPSILON
Department:
        hasParts::ANY
Institute:
        cooperateWith::ANY hasParts::ANY+
Enterprise:
        EPSILON
University:
        hasParts::ANY+ student::ANY+
Project:
        EPSILON
ResearchProject:
        name::ANY carriedOutBy::ANY financedBy::ANY head::ANY isAbout::ANY+ member::ANY+ projectInfo::ANY+
DevelopmentProject:
        name::ANY carriedOutBy::ANY financedBy::ANY head::ANY isAbout::ANY+ member::ANY+ projectInfo::ANY+
SoftwareProject:
        product::ANY
Product:
        name::ANY developedBy::ANY
SoftwareComponent:
        hasPrice::ANY
Topic:
        name::ANY
ResearchTopic:
        dealWithIn::ANY isWorkedOnBy::ANY+
