Bibliography:
        publications::Publication+
Publication:
        Article
Publication:
        Book
Publication:
        InBook
Publication:
        Booklet
Publication:
        InCollection
Publication:
        InProceedings
Publication:
        Proceedings
Publication:
        Manual
Publication:
        Misc
Publication:
        Unpublished
Publication:
        Thesis
Publication:
        Report
Article:
        author::Person+ journal::String month::String number::Integer pages::String volume::Integer
Book:
        month::String number::Integer volume::Integer series::String source::String address::String edition::String isbn::String price::String editor::Person publisher::Organization author::Person+
InBook:
        author::Person+ publisher::Organization editor::Person month::String number::Integer pages::String volume::Integer series::String chapter::String type::String address::String
Booklet:
        author::Person+ month::String address::String edition::String howpublished::String
InCollection:
        editor::Person author::Person+ publisher::Organization month::String number::Integer pages::String address::String edition::String volume::Integer series::String chapter::String type::String booktitle::String
InProceedings:
        editor::Person author::Person+ month::String number::Integer pages::String address::String volume::Integer series::String booktitle::String organization::Organization publisher::Organization
Proceedings:
        editor::Person publisher::Organization organization::Organization month::String number::String volume::String address::String series::String
Manual:
        author::Person+ organization::Organization month::String address::String edition::String
Misc:
        month::String howpublished::String
Unpublished:
        author::Person+ month::String
Thesis:
        MasterThesis
Thesis:
        PhDThesis
MasterThesis:
        author::Person+ school::University month::String address::String type::String
PhDThesis:
        author::Person+ school::University month::String address::String type::String
Report:
        ProjectReport
Report:
        TechnicalReport
ProjectReport:
        describesProject::Project
TechnicalReport:
        series::String organization::Organization
Event:
        Conference
Event:
        Workshop
Event:
        Exhibition
Event:
        Lecture
Event:
        Meeting
Event:
        name::String date::String eventTitle::String location::String atEvent::Event hasPartEvent::Event
Conference:
        series::String
Workshop:
        series::String
Exhibition:
        name::String date::String eventTitle::String location::String atEvent::Event hasPartEvent::Event
Lecture:
        givenBy::Person
Meeting:
        ProjectMeeting
Meeting:
        title::String participant::Person+
ProjectMeeting:
        title::String participant::Person+
Person:
        Employee
Person:
        AcademicStaff
Person:
        Student
Person:
        address::String name::String email::String fax::String homepage::String phone::String photo::String
Employee:
        Manager
Employee:
        AdministrativeStaff
Employee:
        TechnicalStaff
Employee:
        affiliation::Organization
Manager:
        affiliation::Organization
AdministrativeStaff:
        affiliation::Organization
TechnicalStaff:
        affiliation::Organization
AcademicStaff:
        Lecturer
AcademicStaff:
        FacultyMember
AcademicStaff:
        cooperateWith::AcademicStaff+ editor::Publication headOf::Project headOfGroup::ResearchGroup memberOfPC::Event organizerOrChairOf::Event publication::Publication+ supervises::PhDStudent+ worksAtProject::ResearchTopic
Lecturer:
        cooperateWith::AcademicStaff+ editor::Publication headOf::Project headOfGroup::ResearchGroup memberOfPC::Event organizerOrChairOf::Event publication::Publication+ supervises::PhDStudent+ worksAtProject::ResearchTopic
FacultyMember:
        FullProfessor
FacultyMember:
        AssistantProfessor
FacultyMember:
        AssociateProfessor
FacultyMember:
        FullProfessor
        AssistantProfessor
        AssociateProfessor
FullProfessor:
        EPSILON
AssistantProfessor:
        EPSILON
AssociateProfessor:
        EPSILON
Student:
        Undergraduate
Student:
        Graduate
Student:
        studiesAt::University
Undergraduate:
        studiesAt::University
Graduate:
        PhDStudent
PhDStudent:
        publication::Publication+ worksAtProject::Project supervisor::AcademicStaff
Organization:
        ResearchGroup
Organization:
        Association
Organization:
        Department
Organization:
        Institute
Organization:
        Enterprise
Organization:
        University
Organization:
        location::String name::String carriesOut::Project+ develops::Product+ employs::Employee+ finances::Project+ publishes::Publication+ technicalReport::TechnicalReport+
ResearchGroup:
        head::AcademicStaff member::Employee+
Association:
        location::String name::String carriesOut::Project+ develops::Product+ employs::Employee+ finances::Project+ publishes::Publication+ technicalReport::TechnicalReport+
Department:
        hasParts::Institute
Institute:
        cooperateWith::Institute hasParts::ResearchGroup+
Enterprise:
        location::String name::String carriesOut::Project+ develops::Product+ employs::Employee+ finances::Project+ publishes::Publication+ technicalReport::TechnicalReport+
University:
        hasParts::Department+ student::Student+
Project:
        ResearchProject
Project:
        DevelopmentProject
Project:
        SoftwareProject
ResearchProject:
        name::String carriedOutBy::Organization financedBy::Organization head::AcademicStaff isAbout::ResearchTopic+ member::Person+ projectInfo::ProjectReport+
DevelopmentProject:
        name::String carriedOutBy::Organization financedBy::Organization head::AcademicStaff isAbout::ResearchTopic+ member::Person+ projectInfo::ProjectReport+
SoftwareProject:
        product::Product
Product:
        SoftwareComponent
Product:
        name::String developedBy::Organization
SoftwareComponent:
        hasPrice::Integer
Topic:
        ResearchTopic
Topic:
        name::String
ResearchTopic:
        dealWithIn::Project isWorkedOnBy::AcademicStaff+
String:
        STR
Integer:
        INT
