Entity:
        EPSILON
NamedElement:
        EPSILON
Dependency:
        name::ANY
Conform:
        target::ANY source::ANY
Package:
        name::ANY
View:
        conformsTo::ANY
Class:
        name::ANY
Viewpoint:
        stakeholders::ANY+ purpose::ANY concerns::ANY+ languages::ANY+ methods::ANY+
Comment:
        content::ANY
Rationale:
        EPSILON
Problem:
        EPSILON
Block:
        isEncapsulated::ANY
ConstraintBlock:
        EPSILON
Property:
        
BlockProperty:
        EPSILON
ConstraintProperty:
        EPSILON
DistributedProperty:
        EPSILON
DataType:
        
ValueType:
        unit::ANY dimension::ANY
Unit:
        EPSILON
Dimension:
        EPSILON
ConnectorEnd:
        
NestedConnectorEnd:
        propertyPath::ANY
Port:
        isBehavior::ANY
FlowPort:
        isAtomic::ANY direction::ANY isConjugated::ANY
FlowProperty:
        direction::ANY
Interface:
        
FlowSpecification:
        ownedFlowProperty::ANY+
FlowDirection:
        in::EPSILON
        out::EPSILON
        inout::EPSILON
Classifier:
        
InformationItem:
        represented::ANY+
InformationFlow:
        conveyed::ANY+ source::ANY+ target::ANY+
ItemFlow:
        itemProperty::ANY
Parameter:
        
ActivityEdge:
        
ParameterSet:
        
Optional:
        EPSILON
Rate:
        instance::ANY
InstanceSpecification:
        
Continous:
        EPSILON
Discrete:
        EPSILON
Probability:
        probability::ANY
ValueSpecification:
        
Behavior:
        
Operation:
        
ControlOperation:
        EPSILON
ObjectNode:
        
NoBuffer:
        EPSILON
Overwrite:
        EPSILON
Abstraction:
        
Allocate:
        EPSILON
Allocated:
        allocatedFrom::ANY+ allocatedTo::ANY+
ActivityPartition:
        
AllocateActivityPartition:
        EPSILON
Trace:
        
DeriveReqt:
        EPSILON
Verify:
        EPSILON
Copy:
        EPSILON
Realization:
        
Satisfy:
        EPSILON
Requirement:
        text::ANY id::ANY derived::ANY+ derivedFrom::ANY+ satisfiedBy::ANY+ refinedBy::ANY+ tracedTo::ANY+ verifiedBy::ANY+ master::ANY
TestCase:
        EPSILON
RequirementRelated:
        verifies::ANY+ tracedFrom::ANY+ satisfies::ANY+ refines::ANY+
BasicInterval:
        min::ANY max::ANY
Interval:
        EPSILON
Uniform:
        EPSILON
Normal:
        mean::ANY standardDeviation::ANY
