TextualPathExp:
        path::Path
Path:
        transitions::Transition+
Transition:
        AlternativeTrans
Transition:
        PrimitiveTrans
AlternativeTrans:
        altPaths::Path+
PrimitiveTrans:
        name::String
