Trace:
        levels::ANY+ name::ANY
Level:
        trace::ANY calls::ANY+
Call:
        level::ANY indexes::ANY+ methodName::ANY DBAccessesNumber::ANY DBRowsNumber::ANY CPUTime::ANY
Index:
        value::ANY
