Trace:
        levels::Level+ name::String
Level:
        trace::Trace calls::Call+
Call:
        level::Level indexes::Index+ methodName::String DBAccessesNumber::Integer DBRowsNumber::Integer CPUTime::Integer
Index:
        value::Integer
