Actor:
        dependencyE::Dependency+ dependencyR::Dependency+ goal::Goal+ plan::Plan+ resource::Resource+
Goal:
        SoftGoal
Goal:
        HardGoal
Goal:
        wanter::Actor plan::Plan+ dependencyWG::Dependency+ dependencyG::Dependency+
SoftGoal:
        EPSILON
HardGoal:
        EPSILON
Dependency:
        dependee::Actor depender::Actor goal::Goal WhyG::Goal WhyR::Resource resourceD::Resource WhyP::Plan plan::Plan
Plan:
        isFulfilled::Goal capableOf::Actor dependencyWP::Dependency+ dependencyP::Dependency+
Resource:
        use::Actor dependencyWR::Dependency dependencyR::Dependency
