Actor:
        Agent
Actor:
        Position
Actor:
        Role
Actor:
        Agent
        Position
        Role
Agent:
        occupy::Position play::Role+
Position:
        cover::Role+
Role:
        EPSILON
