BusinessTemplate:
        EPSILON
BusinessContact:
        EPSILON
BusinessService:
        EPSILON
BusinessEntity:
        businessContacts::BusinessContact+ businessServices::BusinessService+ identifierBag::IdentifierBag
IdentifierBag:
        EPSILON
TModel:
        overviewDocuments::OverviewDocument+ identifierBag::IdentifierBag
OverviewDocument:
        EPSILON
