BusinessTemplate:
        EPSILON
BusinessContact:
        EPSILON
BusinessService:
        EPSILON
BusinessEntity:
        businessContacts::ANY+ businessServices::ANY+ identifierBag::ANY
IdentifierBag:
        EPSILON
TModel:
        overviewDocuments::ANY+ identifierBag::ANY
OverviewDocument:
        EPSILON
