UEMLObject:
        has::ANY model::ANY
UEMLModel:
        contains::ANY+
Geometry:
        object::ANY
Port:
        EPSILON
Flow:
        associationConnector::ANY
Activity:
        resourceRole::ANY+ parent::ANY hasOutput::ANY
Object:
        ioFlow::ANY
InformationObject:
        controlFlow::ANY
Resource:
        carries::ANY plays::ANY+
MaterialResource:
        EPSILON
HumanResource:
        EPSILON
ResourceFlow:
        resourceCarries::ANY+
IOFlow:
        carries::ANY+
ControlFlow:
        carries::ANY+
TriggerFlow:
        EPSILON
ConstraintFlow:
        EPSILON
ResourceRole:
        resourcePlays::ANY+ roleQualifier::ANY in::ANY
RoleType:
        EPSILON
Anchor:
        target::ANY origin::ANY
OutputPort:
        activity::ANY
InputPort:
        EPSILON
ConnectionOperator:
        EPSILON
AssociationConnector:
        origin::ANY+ target::ANY+ classAssociation::ANY
Process:
        child::ANY fulfills::ANY+ realises::ANY
Service:
        process::ANY
Agent:
        obliger::ANY claimer::ANY has_parties::ANY
Contract:
        process::ANY+ agent::ANY collection_of::ANY+
Task:
        fulfills::ANY+
Commitment:
        task::ANY agentO::ANY agentC::ANY contract::ANY
