UEMLObject:
        has::ANY model::ANY
UEMLModel:
        contains::ANY+
Geometry:
        object::ANY
Port:
        EPSILON
Flow:
        associationConnector::ANY
Activity:
        resourceRole::ANY+ child::ANY+ parent::ANY hasOutput::ANY+ hasInput::ANY+ activityType::ANY
Object:
        ioFlow::ANY
InformationObject:
        controlFlow::ANY
Resource:
        carries::ANY plays::ANY+ resourceType::ANY
MaterialResource:
        EPSILON
HumanResource:
        EPSILON
ResourceFlow:
        resourceCarries::ANY+
IOFlow:
        carries::ANY+
ControlFlow:
        carries::ANY+
TriggerFlow:
        EPSILON
ConstraintFlow:
        EPSILON
ResourceRole:
        resourcePlays::ANY+ roleQualifier::ANY in::ANY
RoleType:
        EPSILON
Anchor:
        target::ANY origin::ANY
OutputPort:
        activity::ANY
InputPort:
        activity::ANY
ConnectionOperator:
        EPSILON
AssociationConnector:
        origin::ANY+ target::ANY+ classAssociation::ANY
ResourceType:
        resource::ANY+
ActivityType:
        activityT::ANY+
