ReuseContract:
        supplier::ANY client::ANY
Dependency:
        owningDependency::ANY subDependency::ANY+
ProviderClause:
        EPSILON
Package:
        EPSILON
ReuserClause:
        EPSILON
CompositeProvider:
        subcontract::ANY
BasicProvider:
        EPSILON
CompositeReuser:
        subreuser::ANY+
BasicReuser:
        EPSILON
