Signal:
        powertypeRange::ANY+ feature::ANY+
Action:
        EPSILON
CreateAction:
        instantiation::ANY
DestroyAction:
        actualArgument::ANY+ actionSequence::ANY recurrence::ANY target::ANY isAsynchronous::ANY script::ANY
UninterpretedAction:
        actualArgument::ANY+ actionSequence::ANY recurrence::ANY target::ANY isAsynchronous::ANY script::ANY
CallAction:
        operation::ANY
SendAction:
        signal::ANY
ActionSequence:
        action::ANY+
Argument:
        action::ANY value::ANY
ReturnAction:
        actualArgument::ANY+ actionSequence::ANY recurrence::ANY target::ANY isAsynchronous::ANY script::ANY
TerminateAction:
        actualArgument::ANY+ actionSequence::ANY recurrence::ANY target::ANY isAsynchronous::ANY script::ANY
Exception:
        EPSILON
Element:
        EPSILON
ModelElement:
        EPSILON
GeneralizableElement:
        EPSILON
Namespace:
        EPSILON
Classifier:
        EPSILON
Feature:
        EPSILON
Relationship:
        EPSILON
BehavioralFeature:
        EPSILON
Operation:
        concurrency::ANY isRoot::ANY isLeaf::ANY isAbstract::ANY specification::ANY
Parameter:
        type::ANY behavioralFeature::ANY defaultValue::ANY kind::ANY
Generalization:
        parent::ANY powertype::ANY child::ANY discriminator::ANY
AggregationKind:
        ak_none::EPSILON
        ak_aggregate::EPSILON
        ak_composite::EPSILON
ChangeableKind:
        ck_changeable::EPSILON
        ck_frozen::EPSILON
        ck_addOnly::EPSILON
OrderingKind:
        ok_unordered::EPSILON
        ok_ordered::EPSILON
CallConcurrencyKind:
        cck_sequential::EPSILON
        cck_guarded::EPSILON
        cck_concurrent::EPSILON
ParameterDirectionKind:
        pdk_in::EPSILON
        pdk_inout::EPSILON
        pdk_out::EPSILON
        pdk_return::EPSILON
PseudostateKind:
        pk_choice::EPSILON
        pk_deepHistory::EPSILON
        pk_fork::EPSILON
        pk_initial::EPSILON
        pk_join::EPSILON
        pk_junction::EPSILON
        pk_shallowHistory::EPSILON
ScopeKind:
        sk_instance::EPSILON
        sk_classifier::EPSILON
VisibilityKind:
        vk_public::EPSILON
        vk_protected::EPSILON
        vk_private::EPSILON
        vk_package::EPSILON
Multiplicity:
        range::ANY+
MultiplicityRange:
        multiplicity::ANY lower::ANY upper::ANY
Expression:
        language::ANY body::ANY
BooleanExpression:
        EPSILON
ObjectSetExpression:
        EPSILON
ActionExpression:
        EPSILON
IterationExpression:
        EPSILON
TimeExpression:
        EPSILON
ArgListsExpression:
        EPSILON
StateMachine:
        context::ANY submachineState::ANY+ top::ANY transitions::ANY+
Event:
        EPSILON
StateVertex:
        EPSILON
State:
        EPSILON
TimeEvent:
        when::ANY
CallEvent:
        operation::ANY
SignalEvent:
        signal::ANY
Transition:
        target::ANY trigger::ANY stateMachine::ANY source::ANY effect::ANY guard::ANY
CompositeState:
        subvertex::ANY+ isConcurrent::ANY
ChangeEvent:
        changeExpression::ANY
Guard:
        transition::ANY expression::ANY
Pseudostate:
        kind::ANY
SimpleState:
        deferrableEvent::ANY+ internalTransition::ANY+ exit::ANY doActivity::ANY entry::ANY stateMachine::ANY
SubmachineState:
        submachine::ANY
SynchState:
        bound::ANY
StubState:
        referenceState::ANY
FinalState:
        deferrableEvent::ANY+ internalTransition::ANY+ exit::ANY doActivity::ANY entry::ANY stateMachine::ANY
ActivityGraph:
        partition::ANY+
Partition:
        contents::ANY+ activityGraph::ANY
SubactivityState:
        isDynamic::ANY dynamicArguments::ANY dynamicMultiplicity::ANY
ActionState:
        isDynamic::ANY dynamicArguments::ANY dynamicMultiplicity::ANY
CallState:
        EPSILON
ObjectFlowState:
        type::ANY parameter::ANY+ isSynch::ANY
ClassifierInState:
        inState::ANY+ type::ANY
