VisibilityKind:
        vk_public_vis::EPSILON
        vk_private_vis::EPSILON
        vk_protected_vis::EPSILON
ScopeKind:
        sk_instance_level::EPSILON
        sk_classifier_level::EPSILON
MultiplicityType:
        lower::ANY upper::ANY isOrdered::ANY isUnique::ANY
ModelElement:
        name::ANY
Feature:
        ownerScope::ANY visibility::ANY owner::ANY
NameSpace:
        EPSILON
GeneralizableElement:
        isRoot::ANY isLeaf::ANY isAbstract::ANY
Classifier:
        feature::ANY+
Class:
        isActive::ANY
StructuralFeature:
        multiplicity::ANY isChangeable::ANY targetScope::ANY
Attribute:
        initialValue::ANY
BehavioralFeature:
        isQuery::ANY
Operation:
        isRoot::ANY isLeaf::ANY isAbstract::ANY specification::ANY
