Node:
        EPSILON
Resource:
        context::ANY
Literal:
        EPSILON
Fact:
        object::ANY subject::ANY predicate::ANY context::ANY
Package:
        EPSILON
Ontology:
        imports::ANY+
