Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
Node:
        Resource
Node:
        Literal
Node:
        Resource
        Literal
Resource:
        Package
Resource:
        context::Package
Literal:
        EPSILON
Fact:
        object::Node subject::Resource predicate::Resource context::Package
Package:
        Ontology
Ontology:
        imports::Package+
