NamedElement:
        File
File:
        Directory
File:
        TextFile
Directory:
        FileSystemRoot
Directory:
        contents::File+
FileSystemRoot:
        EPSILON
TextFile:
        owner::String group::String
