Actor:
        name::ANY
UseCase:
        include::ANY+ extend::ANY+
Extend:
        extension::ANY+
Include:
        includingCase::ANY+
UseCaseContainer:
        ownedElement::ANY+
BehavioredClassifier:
        EPSILON
NamedElement:
        EPSILON
Association:
        actor::ANY useCase::ANY
