Requirement:
        EPSILON
NonFunctionnelRequirement:
        scopes::ANY+
FunctionnelRequirement:
        specifies::ANY+
UseCase:
        scenario::ANY+ condition::ANY+ interacter::ANY+ specified_by::ANY+ scoped_by::ANY+ meet_by::ANY+
Goal:
        to_meet::ANY+
Role:
        interacted_with::ANY+
HumanRole:
        EPSILON
SystemRole:
        EPSILON
EventRole:
        EPSILON
Manage:
        managed_Resource::ANY+
Resource:
        EPSILON
ScenarioDescription:
        useCase::ANY
Condition:
        constrained_with::ANY+
Pre:
        EPSILON
Post:
        EPSILON
