Actor:
        name::String
UseCase:
        include::Include+ extend::Extend+
Extend:
        extension::UseCase+
Include:
        includingCase::UseCase+
UseCaseContainer:
        ownedElement::NamedElement+
BehavioredClassifier:
        EPSILON
NamedElement:
        Actor
NamedElement:
        UseCase
NamedElement:
        Association
Association:
        actor::Actor useCase::UseCase
