Task:
        id::String name::String category::String frequency::Integer importance::Integer structurationLevel::Integer complexityLevel::Integer criticity::Integer centrality::Integer terminationValue::String taskType::String taskItem::String decompositionTasks::Task+ decomposedTask::Task leftOperator::BinaryOperator rightOperator::BinaryOperator decoration::UnaryOperator
Operator:
        BinaryOperator
Operator:
        UnaryOperator
BinaryOperator:
        type::BinaryType leftTask::Task rightTask::Task
UnaryOperator:
        FiniteInteration
UnaryOperator:
        UnaryType::UnaryType decoratedTask::Task
FiniteInteration:
        interation::Integer
BinaryType:
        Enabling::EPSILON
        Disabling::EPSILON
        SuspendResume::EPSILON
        OrderIndependence::EPSILON
        IndependentConcurrency::EPSILON
        ConcurencyWithInformationPassing::EPSILON
        UnderterministicChoice::EPSILON
        EnablingWithInformationPassing::EPSILON
UnaryType:
        Optional::EPSILON
        Iteration::EPSILON
        finitIteration::EPSILON
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
