Task:
        id::ANY name::ANY category::ANY frequency::ANY importance::ANY structurationLevel::ANY complexityLevel::ANY criticity::ANY centrality::ANY terminationValue::ANY taskType::ANY taskItem::ANY decompositionTasks::ANY+ decomposedTask::ANY leftOperator::ANY rightOperator::ANY decoration::ANY
Operator:
        EPSILON
BinaryOperator:
        type::ANY leftTask::ANY rightTask::ANY
UnaryOperator:
        UnaryType::ANY decoratedTask::ANY
FiniteInteration:
        interation::ANY
BinaryType:
        Enabling::EPSILON
        Disabling::EPSILON
        SuspendResume::EPSILON
        OrderIndependence::EPSILON
        IndependentConcurrency::EPSILON
        ConcurencyWithInformationPassing::EPSILON
        UnderterministicChoice::EPSILON
        EnablingWithInformationPassing::EPSILON
UnaryType:
        Optional::EPSILON
        Iteration::EPSILON
        finitIteration::EPSILON
