Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
HyperLink:
        server::Server/ServerPage+
ClientPage:
        hyperlink::HyperLink
ClientPageModule:
        consistsOf::Client/ClientPage
LogicInterface:
        EPSILON
DesignElement:
        EPSILON
ServerPage:
        useBusinessLogic::Server/BusinessLogic useDesignTemplate::Server/DesignTemplate generates::Client/ClientPage+ link::HyperLink+
BusinessLogic:
        EPSILON
DesignTemplate:
        EPSILON
