WorkflowProcessDefinition:
        participantSpecificatons::WorkflowParticipantSpecification+ revelantDatas::WorkflowRelevantData+ applicationDeclarations::WorkflowApplicationDeclaration+ processActivities::WorkflowProcessActivity+ transitionInformations::TransitionInformation+
WorkflowApplicationDeclaration:
        processDefinition::WorkflowProcessDefinition processActivities::WorkflowProcessActivity+ revelantDatas::WorkflowRelevantData+
WorkflowRelevantData:
        processDefinition::WorkflowProcessDefinition applicationDeclarations::WorkflowApplicationDeclaration+ processActivities::WorkflowProcessActivity+ participantSpecifications::WorkflowParticipantSpecification+ transitionInformations::TransitionInformation+
WorkflowParticipantSpecification:
        processDefinition::WorkflowProcessDefinition revelantDatas::WorkflowRelevantData+ processActivities::WorkflowProcessActivity+
WorkflowProcessActivity:
        processDefinition::WorkflowProcessDefinition applicationDeclarations::WorkflowApplicationDeclaration+ revelantDatas::WorkflowRelevantData+ participantSpecifications::WorkflowParticipantSpecification+ to_transitionInformation::TransitionInformation from_transitionInformation::TransitionInformation
TransitionInformation:
        processDefinition::WorkflowProcessDefinition revelantDatas::WorkflowRelevantData+ to_processActivity::WorkflowProcessActivity from_processActivity::WorkflowProcessActivity
