LocatedElement:
        EPSILON
Table:
        border::ANY style::ANY class::ANY caption::ANY rows::ANY+
Caption:
        content::ANY
Row:
        cells::ANY+
Cell:
        isHeading::ANY align::ANY style::ANY content::ANY
