Port:
        name::String service::Service binding::Binding
Service:
        name::String ports::Port+
Param:
        Input
Param:
        Output
Param:
        name::String message::Message
Input:
        operation::Operation
Output:
        operation::Operation
PortType:
        name::String operations::Operation+ bindings::Binding+
Operation:
        name::String input::Input output::Output type::PortType faults::Fault+
StartWithExtensions:
        Binding
StartWithExtensions:
        BindingFault
StartWithExtensions:
        BindingOperation
StartWithExtensions:
        Binding
        BindingFault
        BindingOperation
Binding:
        name::String ports::Port+ type::PortType operations::BindingOperation+
BindingFault:
        operation::BindingOperation binding::Fault
BindingOperation:
        name::String bind::Binding binding::Operation input::StartWithExtensions output::StartWithExtensions faults::BindingFault+
Fault:
        name::String operation::Operation message::Message
Message:
        name::String params::Param+ faults::Fault+ parts::Part+
Part:
        name::String message::Message
String:
        STR
