Classifier:
        name::ANY
Class:
        is_persistent::ANY parent::ANY attrs::ANY+
PrimitiveDataType:
        EPSILON
Association:
        name::ANY src::ANY dest::ANY
Attribute:
        name::ANY is_primary::ANY type::ANY
