Page:
        xmlns::NameSpace+ title::String graphContainer::GraphicalContainer pageResources::PageResource
NameSpace:
        namespace::String identifier::String
PageResource:
        dictionaries::ResourceDictionary+
GraphicalContainer:
        Grid
WinFXElement:
        Name
ResourceDictionary:
        source::String
Grid:
        object3D::Object3D+
Workshop3D:
        elements3D::Element3D+
Element3D:
        UI3Delement
Element3D:
        UI3Delement
UI3Delement:
        transform::String material::String name::Name
XyzAxis3D:
        length::Double
Box3D:
        EPSILON
Square3D:
        EPSILON
Name:
        name::String
