Page:
        xmlns::ANY+ title::ANY graphContainer::ANY pageResources::ANY
NameSpace:
        namespace::ANY identifier::ANY
PageResource:
        dictionaries::ANY+
GraphicalContainer:
        EPSILON
WinFXElement:
        EPSILON
PerspectiveElement:
        EPSILON
ResourceDictionary:
        source::ANY
Grid:
        object3D::ANY+
Object3D:
        EPSILON
Workshop3D:
        elements3D::ANY+
Element3D:
        EPSILON
UI3Delement:
        transform::ANY material::ANY name::ANY
XyzAxis3D:
        length::ANY
Box3D:
        EPSILON
Square3D:
        EPSILON
Name:
        name::ANY
