Transformation:
        TranslateTransform3D
Transformation:
        ScaleTransform3D
Transformation:
        RotateTransform3D
WinFXElement:
        Key
NameSpace:
        namespace::String identifier::String
ResourceGroup:
        Transform3DGroup
ResourceGroup:
        MaterialGroup
ResourceGroup:
        key::Key
Material:
        DiffuseMaterial
Key:
        name::String
ResourceDictionary:
        resourcegroups::ResourceGroup+ xmlns::NameSpace+
Transform3DGroup:
        transformations::Transformation+
MaterialGroup:
        materials::Material+
DiffuseMaterial:
        Brush::String
TranslateTransform3D:
        OffsetX::Double OffsetY::Double OffsetZ::Double
ScaleTransform3D:
        ScaleX::Double ScaleY::Double ScaleZ::Double
RotateTransform3D:
        CenterX::Double CenterY::Double rotation::RotateTransformat3DRotation
RotateTransformat3DRotation:
        axisAngleRotation3D::AxisAngleRotation3D
AxisAngleRotation3D:
        angle::Integer axis::String
