Node:
        EPSILON
Attribute:
        startLine::ANY startColumn::ANY endLine::ANY endColumn::ANY name::ANY value::ANY parent::ANY
Text:
        startLine::ANY startColumn::ANY endLine::ANY endColumn::ANY name::ANY value::ANY parent::ANY
Element:
        children::ANY+
Root:
        EPSILON
