Node:
        Attribute
Node:
        Text
Node:
        Element
Attribute:
        startLine::Integer startColumn::Integer endLine::Integer endColumn::Integer name::String value::String parent::Element
Text:
        startLine::Integer startColumn::Integer endLine::Integer endColumn::Integer name::String value::String parent::Element
Element:
        Root
Element:
        children::Node+
Root:
        EPSILON
