AttributeUseType:
        null::EPSILON
        optional::EPSILON
        prohibited::EPSILON
        required::EPSILON
AnnotedElement:
        EPSILON
Annotation:
        documentations::ANY+ applicationInfos::ANY+ annotedElement::ANY
Documentation:
        text::ANY
ApplicationInfo:
        text::ANY
NamedElement:
        EPSILON
XSchema:
        namespace::ANY contents::ANY+
XSchemaContentElement:
        EPSILON
Parameters:
        EPSILON
Element:
        references::ANY+
Occurable:
        EPSILON
AbstractContent:
        EPSILON
Container:
        EPSILON
AtomicContent:
        EPSILON
ElementRef:
        referencedElement::ANY
GroupRef:
        referencedGroup::ANY
All:
        contents::ANY+
Group:
        references::ANY+
Choice:
        contents::ANY+
Sequence:
        contents::ANY+
AbstractAttributeGroupContent:
        EPSILON
AttributeGroup:
        contents::ANY+ references::ANY+
AttributeGroupRef:
        referencedAttributeGroup::ANY
AtomicAttributeGroupContent:
        EPSILON
Attribute:
        use::ANY references::ANY+
AttributeRef:
        referencedAttribute::ANY
AbstractType:
        EPSILON
SimpleType:
        extensions::ANY+
ComplexType:
        extensions::ANY+ content::ANY attributes::ANY+
ComplexTypeSimpleContent:
        base::ANY
ComplexTypeComplexContent:
        base::ANY
