Node:
        EPSILON
ElementNode:
        nodes::ANY+
AttributeNode:
        name::ANY parentNode::ANY
RootNode:
        document::ANY
TextNode:
        value::ANY
XSLTNode:
        EPSILON
XSLTRootNode:
        EPSILON
Document:
        documentName::ANY document::ANY
ApplyTemplates:
        select::ANY
If:
        test::ANY
Template:
        match::ANY
ValueOf:
        select::ANY
When:
        test::ANY
Choose:
        when::ANY otherwise::ANY
Otherwise:
        
Sort:
        select::ANY
