UIModel:
        windows::Windows functions::Function+
Windows:
        id::String title::String orient::Orients style::String headers::HeaderCss+ headersJScript::HeaderJScript+
Button:
        tooltiptext::String image::String
Orients:
        horizontal::EPSILON
        vertical::EPSILON
Image:
        src::String
RadioGroup:
        radiobuttons::Radio+
Radio:
        id::String label::String selected::Boolean disabled::Boolean
ListBox:
        rows::Integer listitems::ListItem+
ListItem:
        label::String value::String
MenuList:
        menuitems::MenuItem+
MenuItem:
        label::String
vbox:
        EPSILON
hbox:
        EPSILON
Containement:
        Button
Containement:
        Image
Containement:
        RadioGroup
Containement:
        ListBox
Containement:
        MenuList
Containement:
        TabBox
Containement:
        TextBox
Containement:
        Spacer
Containement:
        Label
Containement:
        Grid
Containement:
        CheckBox
Containement:
        Caption
Containement:
        Description
Containement:
        style::String accesskey::String class::String maxlength::Integer label::String orient::Orients minlength::String onclick::String disabled::String
GroupBox:
        EPSILON
Container:
        Windows
Container:
        vbox
Container:
        hbox
Container:
        GroupBox
Container:
        row
Container:
        column
Container:
        TabPanel
Container:
        xulInteractors::Interactor+
Interactor:
        Radio
Interactor:
        ListItem
Interactor:
        MenuItem
Interactor:
        Containement
Interactor:
        Container
Interactor:
        flex::Integer id::String stat::String style::String events::Event+
TabBox:
        tabPanels::Interactor+
TextBox:
        multiline::Boolean value::String
Spacer:
        EPSILON
Label:
        value::String control::String
Grid:
        columns::column+ rows::row+
row:
        EPSILON
column:
        EPSILON
CheckBox:
        checked::Boolean
Caption:
        label::String
Description:
        value::String
HeaderCss:
        ref::String type::String
HeaderJScript:
        ref::String
TabPanel:
        id::String orient::Orients
Event:
        onClick
Event:
        functionCallParameters::Parameter+ functionCalledName::String name::String
Parameter:
        value::String name::String
onClick:
        EPSILON
Function:
        name::String functionUIModel::UIModel body::String
