LocatedElement:
        EPSILON
Model:
        classes::ANY+ elements::ANY+
Class:
        name::ANY
ModelElement:
        EPSILON
ColorableElement:
        EPSILON
ClassReference:
        class::ANY stereotype::ANY definition::ANY
AssociationType:
        simpleAssociation::EPSILON
        aggregation::EPSILON
        composition::EPSILON
Relationship:
        EPSILON
ClassDefinition:
        attributes::ANY+ methods::ANY+
Association:
        type::ANY sourceCardinality::ANY sourceLabel::ANY navigableSource::ANY sourceVisibility::ANY targetCardinality::ANY targetLabel::ANY navigableTarget::ANY targetVisibility::ANY
Inheritance:
        source::ANY target::ANY
Cardinality:
        lowerBound::ANY upperBound::ANY
Visibility:
        unspecified::EPSILON
        public::EPSILON
        private::EPSILON
        protected::EPSILON
        package::EPSILON
ClassMember:
        EPSILON
Attribute:
        type::ANY
Method:
        arguments::ANY+
Note:
        text::ANY+
NoteAssociation:
        note::ANY
