OperatorDeclaration:
        FEConstant
BuiltInSort:
        FiniteEnumeration
FiniteEnumeration.content:
        FEConstant*
FiniteEnumeration:
        finiteenumeration::FiniteEnumeration.content
FEConstant:
        feconstant::OperatorDeclaration.content
