BuiltInSort:
        String
BuiltInOperator:
        StringOperator
BuiltInConstant:
        StringConstant
String:
        string::EPSILON
StringConstant.content:
        value::STR
StringConstant:
        stringconstant::(StringConstant.content BuiltInConstant.content)
StringOperator.content:
        BuiltInOperator.content
StringOperator:
        StringLessThan
        StringLessThanOrEqual
        StringGreaterThan
        StringGreaterThanOrEqual
        StringConcatenation
        StringAppend
        StringLength
        Substring
StringLessThan:
        lts::StringOperator.content
StringLessThanOrEqual:
        leqs::StringOperator.content
StringGreaterThan:
        gts::StringOperator.content
StringGreaterThanOrEqual:
        geqs::StringOperator.content
StringConcatenation:
        stringconcatenation::StringOperator.content
StringLength:
        stringlength::StringOperator.content
StringAppend:
        stringappend::StringOperator.content
Substring:
        substring::(start::INT length::INT StringOperator.content)
