Operator:
        Equality
        Inequality
BuiltInSort:
        Bool
BuiltInOperator:
        BooleanOperator
BuiltInConstant:
        BooleanConstant
Bool:
        bool::EPSILON
BooleanOperator.content:
        BuiltInOperator.content
BooleanOperator:
        And
        Or
        Imply
        Not
And:
        and::BooleanOperator.content
Or:
        or::BooleanOperator.content
Not:
        not::BooleanOperator.content
Imply:
        imply::BooleanOperator.content
Equality:
        equality::Operator.content
Inequality:
        inequality::Operator.content
BooleanConstant:
        booleanconstant::(value::("true" | "false") BuiltInConstant.content)
