BuiltInOperator:
        Cardinality
        CardinalityOf
        Contains
MultisetOperator:
        Add
        All
        NumberOf
        Subtract
        ScalarProduct
        Empty
Add:
        add::MultisetOperator.content
Subtract:
        subtract::MultisetOperator.content
All:
        all::(MultisetOperator.content Sort)
Empty:
        empty::(MultisetOperator.content Sort)
ScalarProduct:
        scalarproduct::MultisetOperator.content
NumberOf:
        numberof::MultisetOperator.content
Cardinality:
        cardinality::BuiltInOperator.content
CardinalityOf:
        cardinalityof::BuiltInOperator.content
Contains:
        contains::BuiltInOperator.content
