nettype.uri:
        type::"http://www.pnml.org/version-2009/grammar/ptnet"
PTMarking:
        initialMarking::nonnegativeintegerlabel.content
PTArcAnnotation:
        inscription::positiveintegerlabel.content
place.labels:
        PTMarking?
arc.labels:
        PTArcAnnotation?
nonnegativeintegerlabel.content:
        text::INT annotationstandard.content
positiveintegerlabel.content:
        text::INT annotationstandard.content
pnml.element:
        pnml::(pnml.content+)
pnml.content:
        net.element
net.element:
        net::(identifier.content nettype.uri (Name? net.labels page.content+ toolspecific.element*))
identifier.content:
        id::STR
nettype.uri:
        type::"http://www.pnml.org/version-2009/grammar/pnmlcoremodel"
net.labels:
        EPSILON
basicobject.content:
        Name? toolspecific.element*
page.content:
        page::(identifier.content (basicobject.content page.labels netobject.content* (graphics::pagegraphics.content)?))
netobject.content:
        page.content
        place.content
        transition.content
        refplace.content
        reftrans.content
        arc.content
page.labels:
        EPSILON
place.content:
        place::(identifier.content (basicobject.content place.labels node.content))
place.labels:
        EPSILON
transition.content:
        transition::(identifier.content (basicobject.content transition.labels node.content))
transition.labels:
        EPSILON
node.content:
        (graphics::nodegraphics.content)?
reference:
        ref::STR
refplace.content:
        referencePlace::refnode.content
reftrans.content:
        referenceTransition::refnode.content
refnode.content:
        identifier.content reference basicobject.content node.content
arc.content:
        arc::(identifier.content source::STR target::STR (Name? arc.labels (graphics::edgegraphics.content)? toolspecific.element*))
arc.labels:
        EPSILON
pagegraphics.content:
        nodegraphics.content
nodegraphics.content:
        position.element dimension.element? fill.element? line.element?
edgegraphics.content:
        position.element* line.element?
simpletext.content:
        (text::STR)?
annotationstandard.content:
        (graphics::annotationgraphics.content)? toolspecific.element*
simpletextlabel.content:
        simpletext.content annotationstandard.content
Name:
        name::simpletextlabel.content
annotationgraphics.content:
        offset.element (fill.element? line.element? font.element?)
position.element:
        position::coordinate.attributes
offset.element:
        offset::coordinate.attributes
coordinate.attributes:
        x::INT y::INT
dimension.element:
        dimension::(x::positiveDecimal.content y::positiveDecimal.content)
positiveDecimal.content:
        INT
fill.element:
        fill::((color::color.type)? (gradient-color::color.type)? (gradient-rotation::("vertical" | "horizontal" | "diagonal"))? (image::STR)?)
line.element:
        line::((shape::("line" | "curve"))? (color::color.type)? (width::positiveDecimal.content)? (style::("solid" | "dash" | "dot"))?)
color.type:
        STR
font.element:
        font::((family::STR)? (style::STR)? (weight::STR)? (size::STR)? (decoration::("underline" | "overline" | "line-through"))? (align::("left" | "center" | "right"))? (rotation::INT)?)
toolspecific.element:
        toolspecific::(tool::STR version::STR anyElement*)
anyElement:
        (ANY | STR | anyElement)*
