Declarations:
        declarations::(Declaration*)
Declaration.content:
        id::STR name::STR
Declaration:
        SortDeclaration
        VariableDeclaration
        OperatorDeclaration
VariableDeclaration:
        variabledecl::(Declaration.content Sort)
SortDeclaration.content:
        Declaration.content
SortDeclaration:
        NamedSort
OperatorDeclaration.content:
        Declaration.content
OperatorDeclaration:
        NamedOperator
Variable:
        variable::refvariable::STR
NamedSort:
        namedsort::(SortDeclaration.content Sort)
NamedOperator:
        namedoperator::(OperatorDeclaration.content parameter::(VariableDeclaration*) def::Term)
Term.content:
        EPSILON
Term:
        Variable
        Operator
Sort.content:
        EPSILON
Sort:
        BuiltInSort
        MultisetSort
        ProductSort
        UserSort
BuiltInSort:
        EPSILON
MultisetSort:
        multisetsort::Sort
ProductSort:
        productsort::(Sort*)
UserSort:
        usersort::declaration::STR
Operator.content:
        subterm::Term*
Operator:
        BuiltInOperator
        BuiltInConstant
        MultisetOperator
        Tuple
        UserOperator
BuiltInOperator.content:
        Operator.content
BuiltInOperator:
        EPSILON
BuiltInConstant.content:
        Operator.content
BuiltInConstant:
        EPSILON
MultisetOperator.content:
        Operator.content
MultisetOperator:
        EPSILON
Tuple:
        tuple::Operator.content
UserOperator:
        useroperator::(declaration::STR Operator.content)
