program:
        function+
function:
        name name+ "=" expr newline+
expr:
        binary(atom (ops atom)*)
expr:
        apply(name atom+)
expr:
        ifThenElse("if" expr "then" expr "else" expr)
atom:
        literalint
atom:
        argumentname
atom:
        "(" expr ")"
ops:
        equal"=="
ops:
        plus"+"
ops:
        minus"-"
