OclExpression:
        EPSILON
SelfExp:
        queryArg::ANY+ querySrc::ANY+ resultType::ANY varDec::ANY+ varInit::ANY+
ResultExp:
        queryArg::ANY+ querySrc::ANY+ resultType::ANY varDec::ANY+ varInit::ANY+
VariableExp:
        var::ANY
OperationExp:
        EPSILON
QueryExp:
        EPSILON
Type:
        EPSILON
VariableDeclaration:
        var::ANY varType::ANY oclExpression::ANY+ queryExp::ANY+ varInit::ANY+
VariableInitialisation:
        initExpression::ANY varDec::ANY iterateExp::ANY
ForAllExp:
        EPSILON
ExistsExp:
        EPSILON
SelectExp:
        EPSILON
RejectExp:
        EPSILON
CollectExp:
        EPSILON
IterateExp:
        varInit::ANY
