Value:
        EPSILON
Type:
        EPSILON
BasicValue:
        EPSILON
IntegerValue:
        val::ANY
RealValue:
        val::ANY
StringValue:
        val::ANY
BooleanValue:
        val::ANY
ObjectValue:
        object::ANY
Object:
        objectValue::ANY
EnumValue:
        enumLiteral::ANY
EnumLiteral:
        enumValue::ANY
UndefinedValue:
        type::ANY bagValue::ANY+ sequenceValue::ANY+ setValue::ANY+
CollectionValue:
        EPSILON
BagValue:
        elements::ANY+
SequenceValue:
        elements::ANY+
SetValue:
        elements::ANY+
Count:
        num::ANY
