Fighter:
        fighter::(name::STR specs::(Spec*))
Spec:
        attribute::(name::STR strength::INT)
        behavior::(cond::Cond move::Action fight::Action)
Cond:
        const::name::STR
        and::(lhs::Cond rhs::Cond)
        or::(lhs::Cond rhs::Cond)
Action:
        action::name::STR
        choose::actions::(STR*)
