atomCommonAttributes:
        (xml:base::atomUri)? (xml:lang::atomLanguageTag)? undefinedAttribute*
atomPlainTextConstruct:
        atomCommonAttributes (type::("text" | "html"))? STR
atomXHTMLTextConstruct:
        atomCommonAttributes type::"xhtml" xhtmlDiv
atomTextConstruct:
        atomPlainTextConstruct
        atomXHTMLTextConstruct
atomPersonConstruct:
        atomCommonAttributes atom:name::STR (atom:uri::atomUri)? (atom:email::atomEmailAddress)? extensionElement*
atomDateConstruct:
        atomCommonAttributes STR
atomFeed:
        atom:feed::(atomCommonAttributes atomAuthor* atomCategory* atomContributor* atomGenerator? atomIcon? atomId atomLink* atomLogo? atomRights? atomSubtitle? atomTitle atomUpdated extensionElement* atomEntry*)
atomEntry:
        atom:entry::(atomCommonAttributes atomAuthor* atomCategory* atomContent? atomContributor* atomId atomLink* atomPublished? atomRights? atomSource? atomSummary? atomTitle atomUpdated extensionElement*)
atomInlineTextContent:
        atom:content::(atomCommonAttributes (type::("text" | "html"))? STR*)
atomInlineXHTMLContent:
        atom:content::(atomCommonAttributes type::"xhtml" xhtmlDiv)
atomInlineOtherContent:
        atom:content::(atomCommonAttributes (type::atomMediaType)? (STR | anyElement)*)
atomOutOfLineContent:
        atom:content::(atomCommonAttributes (type::atomMediaType)? src::atomUri)
atomContent:
        atomInlineTextContent
        atomInlineXHTMLContent
        atomInlineOtherContent
        atomOutOfLineContent
atomAuthor:
        atom:author::atomPersonConstruct
atomCategory:
        atom:category::(atomCommonAttributes term::STR (scheme::atomUri)? (label::STR)? undefinedContent)
atomContributor:
        atom:contributor::atomPersonConstruct
atomGenerator:
        atom:generator::(atomCommonAttributes (uri::atomUri)? (version::STR)? STR)
atomIcon:
        atom:icon::(atomCommonAttributes atomUri)
atomId:
        atom:id::(atomCommonAttributes atomUri)
atomLogo:
        atom:logo::(atomCommonAttributes atomUri)
atomLink:
        atom:link::(atomCommonAttributes href::atomUri (rel::(atomNCName | atomUri))? (type::atomMediaType)? (hreflang::atomLanguageTag)? (title::STR)? (length::STR)? undefinedContent)
atomPublished:
        atom:published::atomDateConstruct
atomRights:
        atom:rights::atomTextConstruct
atomSource:
        atom:source::(atomCommonAttributes atomAuthor* atomCategory* atomContributor* atomGenerator? atomIcon? atomId? atomLink* atomLogo? atomRights? atomSubtitle? atomTitle? atomUpdated? extensionElement*)
atomSubtitle:
        atom:subtitle::atomTextConstruct
atomSummary:
        atom:summary::atomTextConstruct
atomTitle:
        atom:title::atomTextConstruct
atomUpdated:
        atom:updated::atomDateConstruct
atomNCName:
        STR
atomMediaType:
        STR
atomLanguageTag:
        STR
atomUri:
        STR
atomEmailAddress:
        STR
simpleExtensionElement:
        STR
structuredExtensionElement:
        ANY+ (STR | anyElement)*
        ANY* STR? anyElement+ (STR | anyElement)*
extensionElement:
        simpleExtensionElement
        structuredExtensionElement
undefinedAttribute:
        ANY
undefinedContent:
        (STR | anyForeignElement)*
anyElement:
        (ANY | STR | anyElement)*
anyForeignElement:
        (ANY | STR | anyElement)*
anyXHTML:
        (ANY | STR | anyXHTML)*
xhtmlDiv:
        xhtml:div::((ANY | STR | anyXHTML)*)
