JSONText:
        Object
JSONText:
        Array
Value:
        NumericLiteral
Value:
        StringLiteral
Value:
        True"true"
Value:
        Object
Value:
        Array
Value:
        Null"null"
Value:
        False"false"
Object:
        Object("{" members::{Member ","}* "}")
Member:
        Member(memberName::StringLiteral ":" memberValue::Value)
Array:
        Array("[" values::{Value ","}* "]")
