net.labels:
        HLDeclaration*
page.labels:
        HLDeclaration*
place.labels:
        Type? HLMarking?
transition.labels:
        Condition?
arc.labels:
        HLAnnotation?
HLDeclaration:
        declaration::(simpletextlabel.content (structure::Declarations)?)
Type:
        type::(simpletextlabel.content (structure::Sort)?)
HLMarking:
        hlinitialMarking::(simpletextlabel.content (structure::Term)?)
Condition:
        condition::(simpletextlabel.content (structure::Term)?)
HLAnnotation:
        hlinscription::(simpletextlabel.content (structure::Term)?)
