BuiltInSort:
        FiniteIntRange
BuiltInOperator:
        FiniteIntRangeOperator
BuiltInConstant:
        FiniteIntRangeConstant
FiniteIntRange:
        finiteintrange::(start::INT end::INT)
FiniteIntRangeOperator.content:
        BuiltInOperator.content
FiniteIntRangeOperator:
        FIRLessThan
        FIRLessThanOrEqual
        FIRGreaterThan
        FIRGreaterThanOrEqual
FIRLessThan:
        lessthan::FiniteIntRangeOperator.content
FIRLessThanOrEqual:
        lessthanorequal::FiniteIntRangeOperator.content
FIRGreaterThan:
        greaterthan::FiniteIntRangeOperator.content
FIRGreaterThanOrEqual:
        greaterthanorequal::FiniteIntRangeOperator.content
FiniteIntRangeConstant:
        finiteintrangeconstant::(value::INT FiniteIntRange BuiltInConstant.content)
