WikiText:
        wssWikiSymbol*
WikiLink:
        barred("[[" destination::PageName "|" description::(MWWord+) "]]")
WikiLink:
        simple("[[" destination::PageName "]]")
WikiSymbol:
        wMWWord
WikiSymbol:
        wlWikiLink
