[wss] WikiText:
        WikiSymbol*
[barred] WikiLink:
        "[[" destination::PageName "|" description::(MWWord+) "]]"
[simple] WikiLink:
        "[[" destination::PageName "]]"
[w] WikiSymbol:
        MWWord
[wl] WikiSymbol:
        WikiLink
