WikiText:
        WikiSymbol*
WikiSymbol:
        w::MWWord
WikiSymbol:
        wl::WikiLink
[simple] WikiLink:
        "[[" destination::PageName "]]"
[barred] WikiLink:
        "[[" destination::PageName "|" description::(MWWord+) "]]"
