Architecture:
        describedBy::ArchitectureDescription
ArchitectureDescription:
        selects::ArchitectureView+ organizedBy::ArchitectureView+
ArchitectureView:
        selectedBy::ArchitectureDescription+ constituents::ModelElement+ conformsTo::ArchitectureViewPoint+
ArchitectureViewPoint:
        defines::MainView views::ArchitectureView+
MainView:
        isProjectedOnto::ArchitectureView+ consistsOf::ModelElement+
ModelElement:
        EPSILON
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
