Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
Book:
        title::String chapters::Chapter+
Chapter:
        title::String nbPages::Integer author::String book::Book
