IUmlType:
        ICdeComponentSpec
IUmlType:
        IUmlClass
IUmlType:
        members::IUmlMember+
ICdeComponentSpec:
        members::IUmlMember+
IUmlClass:
        IUmlComponent
IUmlComponent:
        ICdeServer
IUmlComponent:
        ICdeComponent
IUmlComponent:
        ICdeServer
        ICdeComponent
ICdeServer:
        implements::ICdeComponent+
ICdeComponent:
        EPSILON
IUmlMember:
        ICdeMember
ICdeMember:
        EPSILON
ICdeMemberExe:
        executionPerformance::String resourceNeeded::String executionDetails::String
Integer:
        INT
String:
        STR
Boolean:
        "true"
        "false"
