Company:
        corporateHQ::CorporateHQ Store::Store+
CorporateHQ:
        manages::Store+ corporateHQBackOffice::CorporateHQBackOffice
Store:
        storeBackOffice::StoreBackOffice employee::Employee+ cashRegister::CashRegister+
CorporateHQBackOffice:
        EPSILON
StoreBackOffice:
        EPSILON
Employee:
        EPSILON
CashRegister:
        EPSILON
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
