NamedElement:
        Namespace
NamedElement:
        Role
NamedElement:
        ValueProperty
NamedElement:
        EnumerationLiteral
LoadedElement:
        DomainModel
LoadedElement:
        Classifier
Namespace:
        LoadedElement
Namespace:
        Type
DomainModel:
        classifiers::Classifier+ types::Type+
Classifier:
        Class
Classifier:
        Relationship
Class:
        isSerializationRoot::PrimitiveTypes/Boolean
Relationship:
        isEmbedding::PrimitiveTypes/Boolean roles::Role
Role:
        min::PrimitiveTypes/Integer max::PrimitiveTypes/Integer isUnbounded::PrimitiveTypes/Boolean accepts::PrimitiveTypes/String isOrdered::PrimitiveTypes/Boolean isNavigableFrom::PrimitiveTypes/Boolean isPropertyGenerator::PrimitiveTypes/Boolean source::Classifier type::Classifier relation::Relationship
ValueProperty:
        owner::Classifier type::Type
Type:
        SimpleType
Type:
        Enumeration
SimpleType:
        EPSILON
EnumerationLiteral:
        value::PrimitiveTypes/Integer
Enumeration:
        literals::EnumerationLiteral+
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
