RootFolder:
        rootContainer::RootContainer+
RootContainer:
        name::String position::String rootFolder::RootFolder actor::Actor+ inputSignal::InputSignal+ outputSignal::OutputSignal+ queue::Queue+
Actor:
        memory::String script::String file::String WCET::String name::String position::String rootContainer::RootContainer transmitter::Transmitter+ receiver::Receiver+
Transmitter:
        name::String position::String actor::Actor associationQueueTransmitter::AssociationQueueTransmitter
Receiver:
        name::String position::String actor::Actor associationReceiverQueue::AssociationReceiverQueue
InputSignal:
        name::String position::String rootContainer::RootContainer associationReceiverQueue::AssociationReceiverQueue
OutputSignal:
        name::String position::String rootContainer::RootContainer associationQueueTransmitter::AssociationQueueTransmitter
Queue:
        name::String position::String rootContainer::RootContainer associationReceiverQueue::AssociationReceiverQueue associationQueueTransmitter::AssociationQueueTransmitter
AssociationReceiverQueue:
        srcqueue::Queue+ dstreceiver::Receiver+ inputSignal::InputSignal
AssociationQueueTransmitter:
        dstqueue::Queue+ srctransmitter::Transmitter+ outputSignal::OutputSignal
String:
        STR
Integer:
        INT
