Place:
        net::Net out::PTArc+ in::TPArc+
Transition:
        net::Net in::PTArc+ out::TPArc+
Net:
        place::Place+ transition::Transition+
PTArc:
        dst::Transition src::Place
TPArc:
        src::Transition dst::Place
