Place:
        net::ANY out::ANY+ in::ANY+
Transition:
        net::ANY in::ANY+ out::ANY+
Net:
        place::ANY+ transition::ANY+
Arc:
        PTArc
Arc:
        TPArc
PTArc:
        dst::ANY src::ANY
TPArc:
        src::ANY dst::ANY
Integer:
        INT
