Formula:
        true::EPSILON
        false::EPSILON
        not::arg::Formula
        and::(lhs::Formula rhs::Formula)
        and::args::(Formula*)
        or::(lhs::Formula rhs::Formula)
        or::args::(Formula*)
        if::(lhs::Formula rhs::Formula)
        fi::(lhs::Formula rhs::Formula)
        iff::(lhs::Formula rhs::Formula)
Formula:
        id::x::STR
