Formula:
        not("!" arg::Formula)
Formula:
        true"true"
Formula:
        false"false"
Formula:
        and(lhs::Formula "&" rhs::Formula)
Formula:
        or(lhs::Formula "|" rhs::Formula)
Formula:
        fi(lhs::Formula "<=" rhs::Formula)
Formula:
        if(lhs::Formula "=>" rhs::Formula)
Formula:
        iff(lhs::Formula "<=>" rhs::Formula)
Formula:
        idEPSILON
False:
        "false"
False:
        "not" t::True
False:
        "(" False ")"
False:
        lf::False "and" rt::True
False:
        lf::False "and" rf::False
False:
        lt::True "and" rf::False
False:
        lf::False "or" rf::False
True:
        "(" True ")"
True:
        "true"
True:
        "not" f::False
True:
        lt::True "and" rt::True
True:
        lt::True "or" rt::True
True:
        lt::True "or" rf::False
True:
        lf::False "or" rt::True
