Node:
        location::String manager::Nucleus capsules::Capsule+
Nucleus:
        otherEngObjects::EngineeringObject+ beos::BEO+
Capsule:
        otherEngObjects::EngineeringObject+ capsuleManager::CapsuleManager clusterManagers::ClusterManager+ clusters::Cluster+
EngineeringObject:
        Nucleus
EngineeringObject:
        CapsuleManager
EngineeringObject:
        ClusterManager
EngineeringObject:
        BEO
EngineeringObject:
        Stub
EngineeringObject:
        Binder
EngineeringObject:
        ProtocolObject
EngineeringObject:
        Interceptor
EngineeringObject:
        ControllingObject
EngineeringObject:
        ControlledObject
EngineeringObject:
        nodeManager::Nucleus
CapsuleManager:
        cmClusterManagers::ClusterManager+
Cluster:
        clusterManager::ClusterManager clusterBeos::BEO+
ClusterManager:
        clusters::Cluster+ clustermanagerBeos::BEO+ capsuleManager::CapsuleManager
BEO:
        beoNodeManager::Nucleus locallyBoundObjects::BEO+ localbinds::BEO+ beoManager::ClusterManager beoChannel::Channel+ beoStub::Stub+
Stub:
        stChannel::Channel stBinder::Binder stBeo::BEO
Binder:
        bdChannel::Channel chBinder::Stub bdProtocolObject::ProtocolObject+
ProtocolObject:
        type::String poChannel::Channel poBinder::Binder poInterceptor::Interceptor+ poBoundProtocolObject::ProtocolObject+
Interceptor:
        intChannel::Channel intProtocolObject::ProtocolObject
Channel:
        ClientServerChannel
Channel:
        chStub::Stub chBinder::Binder chPObject::ProtocolObject chInterceptor::Interceptor+ chEndPoint::BEO
ClientServerChannel:
        chStub::Stub chBinder::Binder chPObject::ProtocolObject chInterceptor::Interceptor+ chEndPoint::BEO
ControllingObject:
        SecurityAuthority
ControllingObject:
        ManagementAuthority
ControllingObject:
        AddressingAuthority
ControllingObject:
        NamingAuthority
ControllingObject:
        coDomain::Domain+
SecurityAuthority:
        coDomain::Domain+
ManagementAuthority:
        coDomain::Domain+
AddressingAuthority:
        coDomain::Domain+
NamingAuthority:
        coDomain::Domain+
ControlledObject:
        cdoDomain::Domain+
Domain:
        SecurityDomain
Domain:
        ManagementDomain
Domain:
        AddressingDomain
Domain:
        NamingDomain
Domain:
        parentDomain::Domain subDomain::Domain+ domControllingObject::ControllingObject domMember::ControlledObject+
SecurityDomain:
        parentDomain::Domain subDomain::Domain+ domControllingObject::ControllingObject domMember::ControlledObject+
ManagementDomain:
        parentDomain::Domain subDomain::Domain+ domControllingObject::ControllingObject domMember::ControlledObject+
AddressingDomain:
        parentDomain::Domain subDomain::Domain+ domControllingObject::ControllingObject domMember::ControlledObject+
NamingDomain:
        EngineeringInterfaceReferenceManagementDomain
EngineeringInterfaceReferenceManagementDomain:
        eirmdReference::EngineeringInterfaceReference+ eirmdManagementPolicy::EngineeringInterfaceReferenceManagementPolicy
EngineeringInterfaceReferenceManagementPolicy:
        eirmpManagementDomain::EngineeringInterfaceReferenceManagementDomain+
EngineeringInterfaceReference:
        eirManagementDomain::EngineeringInterfaceReferenceManagementDomain
String:
        STR
