Entity:
        Activity
Entity:
        Object
Entity:
        Timepoint
Entity:
        Relation
Entity:
        Activity
        Object
        Timepoint
        Relation
Activity:
        Decision
Object:
        Agent
Timepoint:
        EPSILON
Relation:
        Creates
Relation:
        Modifies
Relation:
        Before
Relation:
        Uses
Relation:
        Performs
Relation:
        ActivityStatus
Relation:
        Succesor
Relation:
        Creates
        Modifies
        Before
        Uses
        Performs
        ActivityStatus
        Succesor
Decision:
        EPSILON
Agent:
        EPSILON
Creates:
        EPSILON
Modifies:
        EPSILON
Before:
        EPSILON
Uses:
        EPSILON
Performs:
        EPSILON
ActivityStatus:
        EPSILON
Succesor:
        EPSILON
