QoSStatement:
        SingleQoSStatement
QoSStatement:
        CoumpoundQoSStatement
QoSStatement:
        relation::CoumpoundQoSStatement parameter::Parameter+
SingleQoSStatement:
        contraint::QoSContraint
CoumpoundQoSStatement:
        statement::QoSStatement
Parameter:
        EPSILON
QoSContraint:
        qualification::QualificationKind
QualificationKind:
        value::String
QoSCharacteristic:
        QualificationKind
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
