String:
        STR
Integer:
        INT
Man:
        language::String title::String type::String date::String name::String keyword::String exemple::String meta::Meta+
Meta:
        meta::String path::String category::String version_CSI::String version_DOC::String author::String man::Man
Short_Description:
        name::String verb::String+
Calling_Sequence:
        calling_Sequence_Item::Calling_Sequence_Item+
Calling_Sequence_Item:
        calling_Sequence_Item::String+ calling_Sequence::Calling_Sequence
Param:
        target::InOut param_Indent::Param_Indent+
Param_Indent:
        param::Param param_Description::Param_Description param_Item::Param_Item+
Param_Item:
        label::String param_Indent::Param_Indent param_Name::Param_Name param_Description::Param_Description
Param_Name:
        verb::String+ param_Item::Param_Item
Param_Description:
        param_Indent::Param_Indent+ param_Item::Param_Item
Description:
        itemize::Itemize+ description_Indent::Description_Indent+
Description_Indent:
        description::Description description_Item::Description_Item+
Description_Item:
        label::String description_Indent::Description_Indent
AIMG:
        A
AIMG:
        Img
AIMG:
        verb::String+
See_Also:
        see_Also_Item::See_Also_Item+
Exemple:
        exemple::String xml_space::PreDef
See_Also_Item:
        see_Also::See_Also link::Link+
A:
        href::String psppp::PSPPP authors_Item::Authors_Item
Img:
        src::String psppp::PSPPP
Biblio:
        Short_Description
Biblio:
        Used_Functions
Biblio:
        Authors_Item
Biblio:
        p::P+ sp::SP+ pp::PP+
Used_Functions:
        Param_Description
Used_Functions:
        Description
Used_Functions:
        Itemize
Used_Functions:
        Item
Used_Functions:
        Section
Used_Functions:
        verbatim::String+ table::Table+
PSPPP:
        P
PSPPP:
        SP
PSPPP:
        PP
PSPPP:
        verb::String+ em::String+ bd::String+ tt::String+ a::A+ link::Link+ img::Img+
P:
        biblio::Biblio
SP:
        biblio::Biblio
PP:
        biblio::Biblio
Itemize:
        Item
Itemize:
        Section
Itemize:
        label::String item::Item section::Section authors_Item::Authors_Item description::Description
Item:
        itemize::Itemize+
Table:
        table_New_Row::Table_New_Row+ used_Functions::Used_Functions
Table_New_Row:
        table_New_Column::Table_New_Column+ table::Table
Table_New_Column:
        Verb::String+ em::String+ bd::String+ tt::String+ table_New_Row::Table_New_Row
Link:
        link::String psppp::PSPPP see_Also_Item::See_Also_Item authors_Item::Authors_Item
Authors:
        authors_Item::Authors_Item+
Authors_Item:
        Verb::String+ em::String+ bd::String+ tt::String+ verbatim::String+ label::String a::A+ link::Link+ authors::Authors itemize::Itemize+
Section:
        itemize::Itemize+
InOut:
        in::EPSILON
        out::EPSILON
PreDef:
        Preserve::EPSILON
        Default::EPSILON
