SeminarSchedulingSystem:
        presenter::Presenter+ seminar::Seminar+
Presenter:
        name::String seminarSchedulingSystem::SeminarSchedulingSystem qualifiedFor::Seminar+ offering::Offering+
Seminar:
        title::String seminarSchedulingSystem::SeminarSchedulingSystem qualified::Presenter+ offering::Offering+
Offering:
        is_cancelled::Boolean date::Date attendee::Attendee+ presenter::Presenter seminar::Seminar
Date:
        year::Integer month::Integer day::Integer
Attendee:
        name::String offering::Offering+
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
