HyperLink:
        server::Server/ServerPage+
ClientPage:
        hyperlink::HyperLink
ClientPageModule:
        consistsOf::Client/ClientPage representsSMP::Server/ServerPageModule
LogicInterface:
        represents::Server/LogicModule generatedBy::Server/Renderer
DesignElement:
        represents::Server/DesignModule
ServerPage:
        link::HyperLink+ generates::Client/ClientPage+ module::Server/ServerPageModule+
ServerPageModule:
        contains::Server/ServerPage+ link::Server/Link containsModule::Server/DesignModule
DesignModule:
        EPSILON
LogicModule:
        useCase::Server/UseCase+ logicElement::Server/LogicElement+
Link:
        page::Server/ServerPage posts::Server/Data
BeginUseCase:
        useCase::Server/UseCase
UseCase:
        logicElem::Server/LogicElement+
LogicElement:
        uses::Server/UseCase+ generatedBy::Server/LogicElement next::Server/LogicElement
Alternative:
        EPSILON
UserDecision:
        allows::Server/Alternative+
ServerDecision:
        evaluatesResultOf::Server/Processor
Processor:
        persistentData::Server/Data+ inputData::Server/Data+ outputData::Server/Data+
Renderer:
        renders::Server/Data+
Data:
        renderer::Server/Renderer+ persist::Server/Processor+ uses::Server/Processor+ computes::Server/Processor+
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
