[prg] FLPrg:
        fs::(FLFun*)
[fun] FLFun:
        f::STR args::(str*) body::FLExpr
FLExpr:
        binary::(e1::FLExpr op::FLOp e2::FLExpr)
        apply::(f::STR vargs::(FLExpr*))
        ifThenElse::(c::FLExpr t::FLExpr e::FLExpr)
        argument::a::STR
        literal::i::INT
FLOp:
        minus::EPSILON
        plus::EPSILON
        equal::EPSILON
