BibTeXFile:
        entries::BibTeXEntry+
Author:
        author::String
BibTeXEntry:
        AuthoredEntry
BibTeXEntry:
        DatedEntry
BibTeXEntry:
        TitledEntry
BibTeXEntry:
        BookTitledEntry
BibTeXEntry:
        Misc
AuthoredEntry:
        Article
AuthoredEntry:
        TechReport
AuthoredEntry:
        Unpublished
AuthoredEntry:
        Book
AuthoredEntry:
        ThesisEntry
DatedEntry:
        Booklet
DatedEntry:
        Proceedings
TitledEntry:
        Manual
TitledEntry:
        Unpublished
TitledEntry:
        Proceedings
BookTitledEntry:
        InCollection
Article:
        journal::String
TechReport:
        authors::Author+
Unpublished:
        note::String
Manual:
        title::String
Proceedings:
        InProceedings
Proceedings:
        year::String title::String
InProceedings:
        
Booklet:
        year::String
Book:
        InBook
Book:
        InCollection
Book:
        publisher::String
InCollection:
        publisher::String booktitle::String
InBook:
        chapter::Integer
Misc:
        id::String
ThesisEntry:
        PhDThesis
ThesisEntry:
        MasterThesis
PhDThesis:
        school::String
MasterThesis:
        school::String
String:
        STR
Integer:
        INT
