LocatedElement:
        Entry
Query:
        entries::Entry+ predicates::Predicate+
Entry:
        name::String type::String allFields::Boolean fields::Field+ predicate::Predicate
Field:
        name::String entry::Entry
Predicate:
        entry::Entry expression::Expression+
Expression:
        field::String value::String
String:
        STR
Boolean:
        "true"
        "false"
