Id:
        STR
DotGraph:
        graph::(id::Id stmts::Stms)
        digraph::(id::Id stmts::Stms)
Stms:
        Stm*
NodeId:
        Id PortId
PortId:
        Id CompassPt
CompassPt:
        N::EPSILON
        NE::EPSILON
        E::EPSILON
        SE::EPSILON
        S::EPSILON
        SW::EPSILON
        W::EPSILON
        NW::EPSILON
        C::EPSILON
        _::EPSILON
Stm:
        N::(id::Id attrs::Attrs)
        N::id::Id
        N::(nid::NodeId attrs::Attrs)
        N::nid::NodeId
        E::(from::Id to::Id attrs::Attrs)
        E::(from::Id to::Id)
        E::(nfrom::NodeId to::Id attrs::Attrs)
        E::(nfrom::NodeId to::Id)
        E::(sfrom::Stm to::Id attrs::Attrs)
        E::(sfrom::Stm to::Id)
        E::(from::Id nto::NodeId attrs::Attrs)
        E::(from::Id nto::NodeId)
        E::(nfrom::NodeId nto::NodeId attrs::Attrs)
        E::(nfrom::NodeId nto::NodeId)
        E::(sfrom::Stm nto::NodeId attrs::Attrs)
        E::(sfrom::Stm nto::NodeId)
        E::(from::Id sto::Stm attrs::Attrs)
        E::(from::Id sto::Stm)
        E::(nfrom::NodeId sto::Stm attrs::Attrs)
        E::(nfrom::NodeId sto::Stm)
        E::(sfrom::Stm sto::Stm attrs::Attrs)
        E::(sfrom::Stm sto::Stm)
        S::(id::Id stms::Stms)
        S::stms::Stms
        A::(prop::Id val::Id)
        GRAPH::attrs::Attrs
        NODE::attrs::Attrs
        EDGE::attrs::Attrs
Attr:
        prop::STR val::Id
Attrs:
        Attr*
Outline:
        (key::INT args::(STR*))*
Dotline:
        graph::DotGraph outline::Outline
