ModelElement:
        AssociationEnd
ModelElement:
        Namespace
ModelElement:
        Key
ModelElement:
        Feature
ModelElement:
        name::Name
Name:
        EPSILON
AssociationEnd:
        isNavigable::Boolean isOrdered::Boolean aggregation::AggregationKind multiplicity::Multiplicity changeable::ChangeableKind TargetScope::ScopeKind rfIntegrety::RlIntegretyKind rlIntegrety::RlIntegretyKind
AggregationKind:
        EPSILON
Multiplicity:
        EPSILON
ChangeableKind:
        EPSILON
ScopeKind:
        EPSILON
RfIntegretyKind:
        EPSILON
RlIntegretyKind:
        EPSILON
Namespace:
        GeneralizableElement
GeneralizableElement:
        Classifier
Classifier:
        Class
Class:
        isActive::Boolean mutliplicity::Multiplicity key::Key+
Feature:
        StructureFeature
Feature:
        Constraint
Feature:
        StructureFeature
        Constraint
StructureFeature:
        Attribute
Attribute:
        initialValue::Expression isKey::Boolean isUnique::Boolean
Expression:
        EPSILON
