Class:
        parent::Generalization child::Generalization dependency::Dependency
Generalization:
        EPSILON
Dependency:
        supplier::StateMachine client::Class stereotype::Stereotype
Stereotype:
        baseClass::String extendedElement::Dependency
StateMachine:
        context::Class top::State
State:
        CompositeState
State:
        SimpleState
State:
        FinalState
State:
        stateMachine::StateMachine internal::Transition
CompositeState:
        subvertex::StateVertex
SimpleState:
        EPSILON
FinalState:
        EPSILON
StateVertex:
        State
StateVertex:
        PseudoState
StateVertex:
        compositeState::CompositeState
PseudoState:
        EPSILON
Transition:
        trigger::Event source::StateVertex target::StateVertex
Event:
        EPSILON
