UMLModelElement:
        Attribute
UMLModelElement:
        Package
UMLModelElement:
        PackageElement
Attribute:
        owner::Class type::Classifier
Package:
        elements::PackageElement+
PackageElement:
        Classifier
PackageElement:
        Association
Classifier:
        Class
Classifier:
        PrimitiveDataType
Class:
        attribute::Attribute+ general::Class+ generalOpposite::Class+ reverse::Association+ forward::Association+
PrimitiveDataType:
        typeOpposite::Attribute+
Association:
        source::Class destination::Class
String:
        STR
