Signal:
        Exception
Signal:
        Exception
Action:
        CreateAction
Action:
        DestroyAction
Action:
        UninterpretedAction
Action:
        CallAction
Action:
        SendAction
Action:
        ActionSequence
Action:
        ReturnAction
Action:
        TerminateAction
CreateAction:
        instantiation::Classifier
DestroyAction:
        actualArgument::Argument+ actionSequence::ActionSequence recurrence::IterationExpression target::ObjectSetExpression isAsynchronous::Boolean script::ActionExpression
UninterpretedAction:
        actualArgument::Argument+ actionSequence::ActionSequence recurrence::IterationExpression target::ObjectSetExpression isAsynchronous::Boolean script::ActionExpression
CallAction:
        operation::Operation
SendAction:
        signal::Signal
ActionSequence:
        action::Action+
Argument:
        action::Action value::Expression
ReturnAction:
        actualArgument::Argument+ actionSequence::ActionSequence recurrence::IterationExpression target::ObjectSetExpression isAsynchronous::Boolean script::ActionExpression
TerminateAction:
        actualArgument::Argument+ actionSequence::ActionSequence recurrence::IterationExpression target::ObjectSetExpression isAsynchronous::Boolean script::ActionExpression
Exception:
        
Element:
        ModelElement
ModelElement:
        Action
ModelElement:
        Argument
ModelElement:
        GeneralizableElement
ModelElement:
        Namespace
ModelElement:
        Feature
ModelElement:
        Relationship
ModelElement:
        Parameter
ModelElement:
        StateMachine
ModelElement:
        Event
ModelElement:
        StateVertex
ModelElement:
        Transition
ModelElement:
        Guard
ModelElement:
        Partition
GeneralizableElement:
        Classifier
Namespace:
        Classifier
Classifier:
        Signal
Classifier:
        ClassifierInState
Feature:
        BehavioralFeature
Relationship:
        Generalization
BehavioralFeature:
        Operation
Operation:
        concurrency::CallConcurrencyKind isRoot::Boolean isLeaf::Boolean isAbstract::Boolean specification::String
Parameter:
        type::Classifier behavioralFeature::BehavioralFeature defaultValue::Expression kind::ParameterDirectionKind
Generalization:
        parent::GeneralizableElement powertype::Classifier child::GeneralizableElement discriminator::String
AggregationKind:
        ak_none::EPSILON
        ak_aggregate::EPSILON
        ak_composite::EPSILON
ChangeableKind:
        ck_changeable::EPSILON
        ck_frozen::EPSILON
        ck_addOnly::EPSILON
OrderingKind:
        ok_unordered::EPSILON
        ok_ordered::EPSILON
CallConcurrencyKind:
        cck_sequential::EPSILON
        cck_guarded::EPSILON
        cck_concurrent::EPSILON
ParameterDirectionKind:
        pdk_in::EPSILON
        pdk_inout::EPSILON
        pdk_out::EPSILON
        pdk_return::EPSILON
PseudostateKind:
        pk_choice::EPSILON
        pk_deepHistory::EPSILON
        pk_fork::EPSILON
        pk_initial::EPSILON
        pk_join::EPSILON
        pk_junction::EPSILON
        pk_shallowHistory::EPSILON
ScopeKind:
        sk_instance::EPSILON
        sk_classifier::EPSILON
VisibilityKind:
        vk_public::EPSILON
        vk_protected::EPSILON
        vk_private::EPSILON
        vk_package::EPSILON
Multiplicity:
        range::MultiplicityRange+
MultiplicityRange:
        multiplicity::Multiplicity lower::Integer upper::Integer
Expression:
        BooleanExpression
Expression:
        ObjectSetExpression
Expression:
        ActionExpression
Expression:
        IterationExpression
Expression:
        TimeExpression
Expression:
        ArgListsExpression
Expression:
        language::String body::String
BooleanExpression:
        language::String body::String
ObjectSetExpression:
        language::String body::String
ActionExpression:
        language::String body::String
IterationExpression:
        language::String body::String
TimeExpression:
        language::String body::String
ArgListsExpression:
        language::String body::String
StateMachine:
        ActivityGraph
StateMachine:
        context::ModelElement submachineState::SubmachineState+ top::State transitions::Transition+
Event:
        TimeEvent
Event:
        CallEvent
Event:
        SignalEvent
Event:
        ChangeEvent
StateVertex:
        State
StateVertex:
        Pseudostate
StateVertex:
        SynchState
StateVertex:
        StubState
State:
        CompositeState
State:
        SimpleState
State:
        FinalState
TimeEvent:
        when::TimeExpression
CallEvent:
        operation::Operation
SignalEvent:
        signal::Signal
Transition:
        target::StateVertex trigger::Event stateMachine::StateMachine source::StateVertex effect::Action guard::Guard
CompositeState:
        SubmachineState
CompositeState:
        subvertex::StateVertex+ isConcurrent::Boolean
ChangeEvent:
        changeExpression::BooleanExpression
Guard:
        transition::Transition expression::BooleanExpression
Pseudostate:
        kind::PseudostateKind
SimpleState:
        ActionState
SimpleState:
        ObjectFlowState
SimpleState:
        ActionState
        ObjectFlowState
SubmachineState:
        SubactivityState
SubmachineState:
        submachine::StateMachine
SynchState:
        bound::Integer
StubState:
        referenceState::String
FinalState:
        deferrableEvent::Event+ internalTransition::Transition+ exit::Action doActivity::Action entry::Action stateMachine::StateMachine
ActivityGraph:
        partition::Partition+
Partition:
        contents::ModelElement+ activityGraph::ActivityGraph
SubactivityState:
        isDynamic::Boolean dynamicArguments::ArgListsExpression dynamicMultiplicity::Multiplicity
ActionState:
        CallState
ActionState:
        isDynamic::Boolean dynamicArguments::ArgListsExpression dynamicMultiplicity::Multiplicity
CallState:
        isDynamic::Boolean dynamicArguments::ArgListsExpression dynamicMultiplicity::Multiplicity
ObjectFlowState:
        type::Classifier parameter::Parameter+ isSynch::Boolean
ClassifierInState:
        inState::State+ type::Classifier
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
