Definition:
        context::STR+ defaultMetaclass::DefaultMetaclassSection mappings::Mapping+
DefaultMetaclassSection:
        metaclassName::STR attribute::STR
Mapping:
        metaclass::STR instanceClass::STR sections::Section+
Section:
        DefaultMetaclassSection
Section:
        PropertySection
Section:
        NewSection
Section:
        MultipleSection
Section:
        ValueSection
PropertySection:
        property::STR statements::Statement+
NewSection:
        constructors::Constructor+
MultipleSection:
        statements::Statement+
ValueSection:
        metaValue::STR instanceValue::STR
Statement:
        type::StatementType variables::STR+ calls::MethodCall+
StatementType:
        GET::EPSILON
        SET::EPSILON
        APPEND::EPSILON
        INSERT_AT::EPSILON
        REMOVE::EPSILON
        REMOVE_AT::EPSILON
        REMOVE_LAST::EPSILON
        REMOVE_ALL::EPSILON
        COUNT::EPSILON
        ACCESSORS::EPSILON
        DIRECT::EPSILON
NamedElement:
        MethodCall
NamedElement:
        Parameter
MethodCall:
        Constructor
MethodCall:
        params::Parameter+
Parameter:
        name::STR
Constructor:
        params::Parameter+
