JSONText:
        Object
JSONText:
        Array
Value:
        NumericLiteral
Value:
        StringLiteral
[True] Value:
        "true"
Value:
        Object
Value:
        Array
[Null] Value:
        "null"
[False] Value:
        "false"
[Object] Object:
        "{" members::EPSILON "}"
[Member] Member:
        memberName::StringLiteral ":" memberValue::Value
[Array] Array:
        "[" values::EPSILON "]"
