Value:
        null::EPSILON
        object::members::((memberName::STR memberValue::Value)*)
        array::values::(Value*)
        integer::n::INT
        float::r::INT
        string::s::STR
        boolean::b::("true" | "false")
