Value:
        null::EPSILON
        object::members::((memberName::STR memberValue::Value)*)
        array::values::(Value*)
        integer::n::INT
        float::r::real
        string::s::STR
        boolean::b::bool
