BibTeXFile:
        entries::BibTeXEntry+
Author:
        author::String
BibTeXEntry:
        AuthoredEntry
BibTeXEntry:
        DatedEntry
BibTeXEntry:
        TitledEntry
BibTeXEntry:
        BookTitledEntry
BibTeXEntry:
        Misc
DatedEntry:
        Booklet
TitledEntry:
        Manual
Article:
        journal::String
TechReport:
        EPSILON
Unpublished:
        note::String
Manual:
        title::String
Proceedings:
        EPSILON
InProceedings:
        EPSILON
Booklet:
        year::String
Book:
        InBook
Book:
        publisher::String
InCollection:
        EPSILON
InBook:
        chapter::Integer
Misc:
        id::String
ThesisEntry:
        PhDThesis
ThesisEntry:
        MasterThesis
PhDThesis:
        school::String
MasterThesis:
        school::String
