BibtexFile:
        entries::ANY+
Author:
        name::ANY
Entry:
        EPSILON
AuthoredEntry:
        EPSILON
BookTitledEntry:
        EPSILON
InstitutionEntry:
        EPSILON
EditoredEntry:
        EPSILON
DatedEntry:
        EPSILON
JournalEntry:
        EPSILON
TitledEntry:
        EPSILON
NotedEntry:
        EPSILON
PublisheredEntry:
        EPSILON
SchoolEntry:
        EPSILON
Article:
        volume::ANY number::ANY pages::ANY note::ANY
Book:
        volume::ANY number::ANY series::ANY address::ANY edition::ANY note::ANY
Booklet:
        authors::ANY+ howpublished::ANY address::ANY note::ANY
InBook:
        chapter::ANY type::ANY
InCollection:
        chapter::ANY type::ANY
Manual:
        organization::ANY address::ANY edition::ANY note::ANY
TechReport:
        type::ANY number::ANY address::ANY note::ANY
ThesisEntry:
        EPSILON
PhdThesis:
        type::ANY address::ANY note::ANY
MastersThesis:
        type::ANY address::ANY note::ANY
Proceedings:
        editor::ANY volume::ANY number::ANY series::ANY address::ANY organization::ANY publisher::ANY note::ANY
InProceedings:
        pages::ANY
Conference:
        EPSILON
Unpublished:
        EPSILON
Misc:
        authors::ANY+ title::ANY howpublished::ANY month::ANY year::ANY note::ANY
