BGFGrammar:
        grammar::(roots::(STR*) prods::(BGFProduction*))
BGFProduction:
        production::(label::STR lhs::STR rhs::BGFExpression)
BGFExpression:
        epsilon::EPSILON
        empty::EPSILON
        val::v::BGFValue
        anything::EPSILON
        terminal::t::STR
        nonterminal::t::STR
        selectable::(selector::STR expr::BGFExpression)
        sequence::exprs::(BGFExpression*)
        choice::exprs::(BGFExpression*)
        marked::expr::BGFExpression
        optional::expr::BGFExpression
        plus::expr::BGFExpression
        star::expr::BGFExpression
        starsepplus::(expr::BGFExpression sep::BGFExpression)
        starsepstar::(expr::BGFExpression sep::BGFExpression)
BGFValue:
        string::EPSILON
        integer::EPSILON
