reference:
        STR
sample:
        sampleType
runnable:
        runnableType
tail:
        mixedType
ListOfTerms:
        term::(name::STR definition::SimpleText)+
ListOfInternalLinks:
        link::(text::STR reference::STR)+
SimpleList:
        item::STR+
SimpleText:
        (p::STR | list::SimpleList)+
SimpleSection:
        (id::STR)? (title::STR)? author::STR+? content::SimpleText
TopSection:
        id::STR title::STR author::STR+? (placeholder::generated | normative | informative | production | relationship::ListOfInternalLinks | subtopic::TopSection)+
LexicalSection:
        id::STR type::lexical title::STR author::STR+? (placeholder::generated | normative | informative | production | relationship::ListOfInternalLinks | subtopic::TopSection)+
top-section:
        scope::SimpleSection
        conformance::SimpleSection
        compliance::SimpleSection
        compatibility::SimpleSection
        notation::SimpleSection
        clause::SimpleSection
        field::SimpleSection
        core::SimpleSection
normative:
        purpose::SimpleSection
        description::SimpleSection
        location::SimpleSection
        considerations::SimpleSection
        defaults::SimpleSection
        normative::SimpleSection
informative:
        note::SimpleSection
        example::SimpleSection
        informative::SimpleSection
status:
        draft::EPSILON
        committee draft::EPSILON
        recommendation::EPSILON
        international standard::EPSILON
generated:
        index::EPSILON
        fullgrammar::EPSILON
        listoftables::EPSILON
        listofauthors::EPSILON
        listofcontents::EPSILON
        listofreferences::EPSILON
lexical:
        lineContinuations::EPSILON
        whitespace::EPSILON
        tokens::EPSILON
        preprocessor::EPSILON
        literals::EPSILON
        other::EPSILON
body:
        ansi::EPSILON
        ecma::EPSILON
        ieee::EPSILON
        iso::EPSILON
        iso/iet::EPSILON
        itu::EPSILON
        ietf::EPSILON
        iec::EPSILON
        oasis::EPSILON
        wsa::EPSILON
        w3c::EPSILON
document:
        title::title placeholder::generated* frontMatter::frontMatter (languageOverview::ListOfTerms)? lexicalSection::LexicalSection+ top-section+ annex::TopSection*
title:
        ((body::body number::INT) | author::STR+) topic::STR (version::STR | edition::STR) status::status date::STR
frontMatter:
        foreword::SimpleText designGoals::SimpleList top-section+ normativeReferences::SimpleList (definitions::ListOfTerms)? (abbreviations::ListOfTerms)? documentStructure::TopSection whatsnew::SimpleList
runnableType:
        context::STR main::STR argument::STR* yields::STR language::STR (version::STR)? (id::STR)?
mixedType:
        (ANY | STR)*
