evolution:
        step*
step:
        rename
        introduce
        eliminate
rename:
        metasymbol::metasymbols from::STR to::STR
introduce:
        metasymbol::confixMetasymbols start::STR end::STR
eliminate:
        metasymbol::metasymbols
metasymbols:
        terminator::EPSILON
        defining::EPSILON
        definition-separator::EPSILON
        group::EPSILON
        seplist-plus::EPSILON
        seplist-star::EPSILON
confixMetasymbols:
        group::EPSILON
        seplist-plus::EPSILON
        seplist-star::EPSILON
