scenario:
        shortcut* tools source+ target+ testset*
tools:
        transformer::tool comparator::tool (validator::tool)? generator*
shortcut:
        name::STR expansion::xstring
generator:
        name::STR command::xstring
source:
        name::STR derived? source-grammar source-tree? test-set::(xstring*)
target:
        name::STR branch+
phase:
        step::(perform-transformation::STR | automated-transformation)+
testset:
        name::STR command::xstring
tool:
        grammar::xstring (tree::xstring)?
xstring:
        (expand::STR | STR)*
derived:
        from::STR using::STR
source-grammar:
        extraction::xstring (parsing::xstring)? (evaluation::xstring)?
source-tree:
        extraction::xstring (evaluation::xstring)?
branch:
        input::STR (preparation::phase)? (nominal-matching::phase)? (normalizing::phase)? (structural-matching::phase)? (extension::phase | correction::phase | relaxation::phase)*
automated-transformation:
        method::STR result::STR
