XBGFResult:
        r::XBGFOutcome g::BGFGrammar
XBGFOutcome:
        ok::EPSILON
        problem::msg::STR
        problemXBGF::(msg::STR xbgf::XBGFCommand)
        problemProd::(msg::STR p::BGFProduction)
        problemProd2::(msg::STR p1::BGFProduction p2::BGFProduction)
        problemPinProds::(msg::STR p::BGFProduction ps::(BGFProduction*))
        problemProds::(msg::STR ps::(BGFProduction*))
        problemProds2::(msg::STR ps1::(BGFProduction*) ps2::(BGFProduction*))
        problemExpr::(msg::STR e::BGFExpression)
        problemExpr2::(msg::STR e1::BGFExpression e2::BGFExpression)
        problemStr::(msg::STR x::STR)
        problemStr2::(msg::STR x::STR y::STR)
        problemStrs::(msg::STR xs::(STR*))
        problemScope::(msg::STR w::XBGFScope)
