Thing:
        Person
Thing:
        Event
Thing:
        Role
Thing:
        Document
Thing:
        Detail
Thing:
        Review_expertise
Thing:
        Organizer
Thing:
        Review_preference
Thing:
        date
Thing:
        conference
Thing:
        URL
Thing:
        conference_setup
Thing:
        Contribution
Thing:
        Conference
Thing:
        Person
        Event
        Role
        Document
        Detail
        Review_expertise
        Organizer
        Review_preference
        date
        conference
        URL
        conference_setup
        Contribution
Meta-Reviewer:
        invites_co-reviewers::Reviewer invited_by::Reviewer has_a_review_reference_or_expertise::Thing+ assignedByAdministrator::Administrator adjustBid::Bid readPaper::Paper hasBeenAssigned::Paper writeReview::Review assignExternalReviewer::ExternalReviewer
Reviewer:
        Meta-Reviewer
Reviewer:
        invites_co-reviewers::Reviewer invited_by::Reviewer has_a_review_reference_or_expertise::Thing+ assignedByAdministrator::Administrator adjustBid::Bid readPaper::Paper hasBeenAssigned::Paper writeReview::Review assignExternalReviewer::ExternalReviewer
Decision:
        Acceptance
Decision:
        Rejection
Decision:
        Acceptance
        Rejection
Person:
        ConferenceMember
Person:
        ExternalReviewer
Person:
        User
Person:
        Conference_participant
Person:
        Conference_contributor
Person:
        Committee_member
Person:
        Conference_applicant
Person:
        Track-workshop_chair
Person:
        Scholar
Person:
        Participant
Person:
        Member_PC
Person:
        Chair_PC
Person:
        Science_Worker
Person:
        Assistant
Person:
        Volunteer
Person:
        ProgramCommitteeMember
Person:
        Chairman
Person:
        Administrator
Person:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String employedBy::Organization hasHomePage::String hasSurname::String hasFax::String hasFirstName::String hasPhone::String hasEmail::String hasConflictOfInterest::Document email::String
Preference:
        EPSILON
ProgramCommittee:
        hasProgramCommitteeMember::ProgramCommitteeMember
Bid:
        adjustedBy::Reviewer
Conference:
        Conference_volume
Conference:
        hasConferenceMember::ConferenceMember paperAssignmentFinalizedBy::Administrator reviewCriteriaEnteredBy::Administrator paperAssignmentToolsRunBy::Administrator virtualMeetingEnabledBy::Administrator hardcopyMailingManifestsPrintedBy::Administrator detailsEnteredBy::Administrator reviewerBiddingStartedBy::Administrator date::date reviewsPerPaper::Integer logoURL::anyURI acceptsHardcopySubmissions::Boolean siteURL::anyURI
ConferenceChair:
        memberOfConference::Conference
ConferenceMember:
        Reviewer
ConferenceMember:
        ConferenceChair
ConferenceMember:
        AssociatedChair
ConferenceMember:
        Author
ConferenceMember:
        ProgramCommitteeMember
ConferenceMember:
        Chairman
ConferenceMember:
        memberOfConference::Conference
AssociatedChair:
        memberOfConference::Conference
ProgramCommitteeMember:
        ProgramCommitteeChair
ProgramCommitteeMember:
        memberOfProgramCommittee::ProgramCommittee maxPapers::Integer addedBy::Administrator
AuthorNotReviewer:
        writes::Contribution submitPaper::Paper writePaper::Paper
SubjectArea:
        EPSILON
ExternalReviewer:
        assignedByReviewer::Reviewer
Chairman:
        ConferenceChair
Chairman:
        AssociatedChair
Chairman:
        ProgramCommitteeChair
Chairman:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String employedBy::Organization hasHomePage::String hasSurname::String hasFax::String hasFirstName::String hasPhone::String hasEmail::String hasConflictOfInterest::Document email::String memberOfConference::Conference
ProgramCommitteeChair:
        endReview::Review
Acceptance:
        EPSILON
Rejection:
        EPSILON
Paper:
        PaperAbstract
Paper:
        PaperFullVersion
Paper:
        Abstract
Paper:
        Invited_Paper
Paper:
        Short_Paper
Paper:
        Full_Paper
Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Author:
        AuthorNotReviewer
Author:
        Co-author
Author:
        Corresponding_Author
Author:
        writes::Contribution submitPaper::Paper writePaper::Paper
Co-author:
        co-writePaper::Paper
PaperAbstract:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
PaperFullVersion:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Administrator:
        approve::Event assign::Role finalizePaperAssignment::Conference runPaperAssignmentTools::Conference enableVirtualMeeting::Conference startReviewerBidding::Conference assignReviewer::Reviewer rejectPaper::Paper enterConferenceDetails::Conference printHardcopyMailingManifests::Conference setMaxPapers::ProgramCommitteeMember enterReviewCriteria::Conference acceptPaper::Paper addProgramCommitteeMember::ProgramCommitteeMember
Meta-Review:
        writtenBy::Reviewer reviews::Reviewed_contribution
Event:
        Symposium
Event:
        Social_event
Event:
        Administrative_event
Event:
        Working_event
Event:
        conists_of::Event_Tracks confirmed_by::Approval_Email defined_by::Event_Setup approved_by::Administrator starts_on::String ends_on::String
Account:
        registred_by::Person
Inforamtion:
        EPSILON
User:
        Committee
User:
        Administrator
User:
        recieve::Document create::Thing+ submit::Document
Role:
        Admin_Role
Role:
        Author_Role
Role:
        Committe_Role
Role:
        Head_Role
Role:
        Reviewer_Role
Role:
        assigned_by::Administrator
Help_Request:
        Misc
Help_Request:
        Feature_Request
Help_Request:
        Assistance
Help_Request:
        Misc
        Feature_Request
        Assistance
Symposium:
        conists_of::Event_Tracks confirmed_by::Approval_Email defined_by::Event_Setup approved_by::Administrator starts_on::String ends_on::String
Abstract:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Abstract:
        is_the_1th_part_of::Thing+
Document:
        Email
Document:
        Submission
Document:
        Template
Document:
        Paper
Document:
        Review
Document:
        recieved_by::User used_by::Person submited__by::User
Invited_Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Admin_Role:
        assigned_by::Administrator
Paper_Typologies:
        define::Event
Event_Setup:
        Paper_Typologies
Event_Setup:
        Review_Form
Event_Setup:
        Submission_Template
Event_Setup:
        Event_Tracks
Event_Setup:
        Research_Topic
Event_Setup:
        Email_Template
Event_Setup:
        define::Event
Event_URL:
        concerned::Event
Notification_Email:
        EPSILON
Email:
        Notification_Email
Email:
        Group_Email
Email:
        Approval_Email
Email:
        Rejection_Email
Email:
        Notification_Email
        Group_Email
        Approval_Email
        Rejection_Email
Short_Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Author_Role:
        assigned_by::Administrator
Preview:
        EPSILON
Review_Form:
        Preview
Review_Form:
        Review_Form_Setup
Review_Form:
        Preview
        Review_Form_Setup
Committe_Role:
        assigned_by::Administrator
Group_Email:
        EPSILON
Submission_Template:
        define::Event
Review_Form_Setup:
        EPSILON
Misc:
        EPSILON
Event_Creation:
        has_result::Thing+ sent_by::Person
Approval_Email:
        confirm::Event
Rejection_Email:
        EPSILON
Submission:
        recieved_by::User used_by::Person submited__by::User
Template:
        recieved_by::User used_by::Person submited__by::User
Feature_Request:
        EPSILON
Event_Tracks:
        define::Event
Request:
        Help_Request
Activity:
        Event_Creation
Activity:
        Request
Activity:
        Event_Approval
Activity:
        Registration
Activity:
        has_result::Thing+ sent_by::Person
Head_Role:
        assigned_by::Administrator
Detail:
        EPSILON
Corresponding_Author:
        writes::Contribution submitPaper::Paper writePaper::Paper
Reviewer_Role:
        assigned_by::Administrator
Event_Approval:
        has_result::Thing+ sent_by::Person
Registration:
        has_result::Thing+ sent_by::Person
Full_Paper:
        hasCo-author::Co-author hasBid::Bid hasDecision::Decision assignedTo::Reviewer hasSubjectArea::SubjectArea readByReviewer::Reviewer paperID::unsignedLong title::String hasAuthor::Author acceptedBy::Administrator rejectedBy::Administrator readByMeta-Reviewer::Meta-Reviewer
Research_Topic:
        define::Event
Description:
        EPSILON
Assistance:
        EPSILON
Email_Template:
        define::Event
Conference_participant:
        Passive_conference_participant
Conference_participant:
        Active_conference_participant
Active_conference_participant:
        gives_presentations::Presentation
Passive_conference_participant:
        EPSILON
Review_expertise:
        has_a_submitted_contribution::Submitted_contribution has_an_expertise::EEnum
Submitted_contribution:
        Reviewed_contribution
Submitted_contribution:
        has_a_review_expertise::Review_expertise
Regular_author:
        Contribution_1th-author
Regular_author:
        Contribution_co-author
Regular_author:
        Contribution_1th-author
        Contribution_co-author
Conference_contributor:
        Regular_author
Conference_contributor:
        Invited_speaker
Conference_contributor:
        Active_conference_participant
Conference_contributor:
        Regular_author
        Invited_speaker
Contribution_1th-author:
        EPSILON
Contribution_co-author:
        EPSILON
Conference_contribution:
        Poster
Conference_contribution:
        Written_contribution
Conference_contribution:
        Presentation
Conference_contribution:
        is_submitted_at::Conference_volume
Co-chair:
        was_a_committe_co-chair_of::Committee
Committee:
        Program_committee
Committee:
        Organizing_committee
Committee:
        Steering_committee
Committee:
        has_members::Committee_member was_a_committee_of::Conference_volume has_a_committee_co-chair::Co-chair has_a_committee_chair::Chair
Committee_member:
        Co-chair
Committee_member:
        Chair
Committee_member:
        was_a_member_of::Committee
Extended_abstract:
        Abstract
Important_dates:
        is_an_abstract_submission_date::date is_a_full_paper_submission_date::date is_an_ending_date::date is_a_date_of_acceptance_announcement::date is_a_date_of_camera_ready_paper_submission::date is_a_starting_date::date belong_to_a_conference_volume::Conference_volume
Invited_speaker:
        EPSILON
Conference_proceedings:
        has_an_ISBN::String has_a_publisher::Publisher has_a_volume::Integer
Information_for_participants:
        has_authors::Person has_a_date_of_issue::date
Conference_document:
        Conference_contribution
Conference_document:
        Information_for_participants
Conference_document:
        Call_for_paper
Conference_document:
        Conference_announcement
Conference_document:
        Call_for_participation
Conference_document:
        Conference_www
Conference_document:
        Review
Conference_document:
        has_authors::Person has_a_date_of_issue::date
Regular_contribution:
        Extended_abstract
Poster:
        is_submitted_at::Conference_volume
Poster:
        writtenBy::Author dealsWith::Topic remark::String abstract::String contactEmail::String hasKeyword::String hasTitle::String
Written_contribution:
        Submitted_contribution
Written_contribution:
        Regular_contribution
Written_contribution:
        Submitted_contribution
        Regular_contribution
Conference_applicant:
        Registeered_applicant
Camera_ready_contribution:
        EPSILON
Accepted_contribution:
        Camera_ready_contribution
Program_committee:
        was_a_program_committee_of::Conference_volume
Organizing_committee:
        was_an_organizing_committee_of::Conference_volume
Steering_committee:
        was_a_steering_committee_of::Conference_volume
Conference_volume:
        has_parts::Conference_part has_workshops::Workshop has_tracks::Track has_tutorials::Tutorial has_a_commtitee::Committee has_a_steering_committee::Steering_committee has_an_organizing_committee::Organizing_committee has_important_dates::Important_dates has_contributions::Conference_contribution has_a_location::String has_a_program_committee::Program_committee
Call_for_paper:
        has_authors::Person has_a_date_of_issue::date
Conference_announcement:
        has_authors::Person has_a_date_of_issue::date
Invited_talk:
        is_given_by::Active_conference_participant
Conference_part:
        Track
Conference_part:
        Workshop
Conference_part:
        Tutorial
Conference_part:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair
Presentation:
        Invited_talk
Presentation:
        is_given_by::Active_conference_participant
Chair:
        was_a_committee_chair_of::Committee
Track:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair
Workshop:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair
Tutorial:
        has_a_track-workshop-tutorial_topic::Topic is_part_of_conference_volumes::Conference_volume has_a_track-workshop-tutorial_chair::Track-workshop_chair hasTopic::Topic hasAdministrativeEvent::Administrative_event
Rejected_contribution:
        has_a_review::Review
Reviewed_contribution:
        Accepted_contribution
Reviewed_contribution:
        Rejected_contribution
Reviewed_contribution:
        has_a_review::Review
Review:
        Meta-Review
Review:
        writtenBy::Reviewer reviews::Reviewed_contribution
Topic:
        belongs_to_a_review_reference::Review_preference is_a_topis_of_conference_parts::Conference_part
Late_paid_applicant:
        EPSILON
Paid_applicant:
        Late_paid_applicant
Paid_applicant:
        Early_paid_applicant
Paid_applicant:
        Late_paid_applicant
        Early_paid_applicant
Early_paid_applicant:
        EPSILON
Organizer:
        EPSILON
Call_for_participation:
        has_authors::Person has_a_date_of_issue::date
Publisher:
        issues::Conference_proceedings
Registeered_applicant:
        Paid_applicant
Track-workshop_chair:
        was_a_track-workshop_chair_of::Conference_part
Conference_www:
        has_a_URL::String
Conference_fees:
        EPSILON
Review_preference:
        has_a_topic_or_a_submission_contribution::Thing+ has_a_degree::Integer
EEnum:
        high::EPSILON
        medium::EPSILON
        low::EPSILON
        very high::EPSILON
        male::EPSILON
        female::EPSILON
Accepted_Paper:
        full_paper_size::Integer has_author::human
paper:
        Accepted_Paper
paper:
        Rejected_Paper
paper:
        Undecided_Paper
paper:
        full_paper_size::Integer has_author::human
Rejected_Paper:
        full_paper_size::Integer has_author::human
Undecided_Paper:
        full_paper_size::Integer has_author::human
Manual_Paper_Assignment:
        manually_assign_paper::Program_Committee_member+
Program_Committee_member:
        Senior_Program_Committee_member
Program_Committee_member:
        Regular_Program_Committee_member
Program_Committee_member:
        Senior_Program_Committee_member
        Regular_Program_Committee_member
paper_assignment:
        Manual_Paper_Assignment
paper_assignment:
        Automatic_Paper_Assignment
paper_assignment:
        assign_paper::Program_Committee_member is_performed_by::human
intensity:
        EPSILON
start_date_of_camera-ready_submission:
        EPSILON
camera-ready_submission_date:
        start_date_of_camera-ready_submission
camera-ready_submission_date:
        end_date_of_camera-ready_submission
camera-ready_submission_date:
        start_date_of_camera-ready_submission
        end_date_of_camera-ready_submission
date_of_notification:
        EPSILON
date:
        camera-ready_submission_date
date:
        date_of_notification
date:
        abstract_submission_date
date:
        date_of_conference
date:
        full_paper_submission_date
date:
        camera-ready_submission_date
        date_of_notification
        abstract_submission_date
        date_of_conference
        full_paper_submission_date
article:
        paper
article:
        group_email
article:
        notification_email
article:
        abstract_of_paper
article:
        review
article:
        review_form
article:
        summary_of_reviews
article:
        goes_through::activity is_sent_to::human is_created_in::activity structure_created_by::human has_author::human gives_classification::classification
Contact_Person:
        is_author_of::article performs_activity::activity is_employed_in::institute has_topic_of_interest::topic supervises::activity e-mail::String last_name::String first_name::String
conference:
        is_in_phase::phase_of_conference
bidding_of_reviewer:
        is_performed_by::human
activity:
        paper_assignment
activity:
        bidding_of_reviewer
activity:
        managing_of_conference_process
activity:
        reviewing_proces
activity:
        notification
activity:
        submission_process
activity:
        is_followed_by::activity is_monitored_by::human has_intensity::intensity has_result::article is_performed_by::human is_supervised_by::human
URL:
        Event_URL
URL:
        Senior_Reviewer_URL
URL:
        Chair_URL
URL:
        Contact_Person_URL
URL:
        Regular_Reviewer_URL
URL:
        Event_URL
        Senior_Reviewer_URL
        Chair_URL
        Contact_Person_URL
        Regular_Reviewer_URL
conference_setup:
        sets_member::human is_made_by::human includes_topic::topic sets_date::date sets_URL::URL
human:
        Program_Committee_member
human:
        Contact_Person
human:
        Program_Committee_Chair
human:
        is_author_of::article performs_activity::activity is_employed_in::institute has_topic_of_interest::topic supervises::activity e-mail::String last_name::String first_name::String
managing_of_conference_process:
        is_followed_by::activity is_monitored_by::human has_intensity::intensity has_result::article is_performed_by::human is_supervised_by::human
Program_Committee_Chair:
        is_author_of::article performs_activity::activity is_employed_in::institute has_topic_of_interest::topic supervises::activity e-mail::String last_name::String first_name::String
reviewing_proces:
        lower_tier_reviewing_process
reviewing_proces:
        upper_tier_reviewing_process
reviewing_proces:
        lower_tier_reviewing_process
        upper_tier_reviewing_process
end_date_of_camera-ready_submission:
        EPSILON
abstract_submission_date:
        end_date_of_abstract_submission
abstract_submission_date:
        start_date_of_abstract_submission
abstract_submission_date:
        end_date_of_abstract_submission
        start_date_of_abstract_submission
group_email:
        goes_through::activity is_sent_to::human is_created_in::activity structure_created_by::human has_author::human gives_classification::classification
Senior_Reviewer_URL:
        EPSILON
notification:
        has_result::article is_performed_by::human
notification_email:
        acceptance_notification_email
notification_email:
        rejection_notification_email
notification_email:
        acceptance_notification_email
        rejection_notification_email
Chair_URL:
        EPSILON
abstract_of_paper:
        goes_through::activity is_sent_to::human is_created_in::activity structure_created_by::human has_author::human gives_classification::classification
submission_process:
        is_performed_by::human
topic:
        EPSILON
lower_tier_reviewing_process:
        EPSILON
start_date_of_conference:
        EPSILON
date_of_conference:
        start_date_of_conference
date_of_conference:
        end_date_of_conference
date_of_conference:
        start_date_of_conference
        end_date_of_conference
Senior_Program_Committee_member:
        supervises::activity
end_date_of_abstract_submission:
        EPSILON
phase_of_conference:
        EPSILON
Regular_Program_Committee_member:
        EPSILON
review:
        gives_classification::classification is_created_in::activity
start_date_of_full_paper_submission:
        EPSILON
full_paper_submission_date:
        start_date_of_full_paper_submission
full_paper_submission_date:
        end_date_of_full_paper_submission
full_paper_submission_date:
        start_date_of_full_paper_submission
        end_date_of_full_paper_submission
start_date_of_abstract_submission:
        EPSILON
end_date_of_conference:
        EPSILON
review_form:
        is_created_in::activity
Automatic_Paper_Assignment:
        automatically_assign_paper::Program_Committee_member+
institute:
        EPSILON
classification:
        EPSILON
summary_of_reviews:
        is_created_in::activity
upper_tier_reviewing_process:
        is_performed_by::human
end_date_of_full_paper_submission:
        EPSILON
acceptance_notification_email:
        EPSILON
rejection_notification_email:
        EPSILON
Contact_Person_URL:
        EPSILON
Regular_Reviewer_URL:
        EPSILON
Trip:
        EPSILON
Banquet:
        EPSILON
Reception:
        EPSILON
Social_event:
        Trip
Social_event:
        Banquet
Social_event:
        Reception
Social_event:
        Trip
        Banquet
        Reception
Contribution:
        Poster
Contribution:
        Short_paper
Contribution:
        writtenBy::Author dealsWith::Topic remark::String abstract::String contactEmail::String hasKeyword::String hasTitle::String
City:
        EPSILON
Organization:
        Company
Organization:
        University
Organization:
        Company
        University
Country:
        EPSILON
Company:
        EPSILON
University:
        EPSILON
Scholar:
        studyAt::University
Short_paper:
        writtenBy::Author dealsWith::Topic remark::String abstract::String contactEmail::String hasKeyword::String hasTitle::String
Reviewing_results_event:
        follows::Administrative_event parallel_with::Administrative_event
Administrative_event:
        Reviewing_results_event
Administrative_event:
        Reviewing_event
Administrative_event:
        Registration_of_participants_event
Administrative_event:
        Submission_event
Administrative_event:
        Camera_Ready_event
Administrative_event:
        follows::Administrative_event parallel_with::Administrative_event
Reviewing_event:
        follows::Administrative_event parallel_with::Administrative_event
Registration_of_participants_event:
        follows::Administrative_event parallel_with::Administrative_event
Submission_event:
        follows::Administrative_event parallel_with::Administrative_event
Camera_Ready_event:
        follows::Administrative_event parallel_with::Administrative_event
Working_event:
        Tutorial
Working_event:
        hasTopic::Topic hasAdministrativeEvent::Administrative_event
Member:
        earlyRegistration::Boolean
Participant:
        Member
Participant:
        Student
Participant:
        Regular
Participant:
        earlyRegistration::Boolean
Member_PC:
        expertOn::Topic reviewes::Contribution
Chair_PC:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String employedBy::Organization hasHomePage::String hasSurname::String hasFax::String hasFirstName::String hasPhone::String hasEmail::String hasConflictOfInterest::Document email::String
Student:
        earlyRegistration::Boolean
Science_Worker:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String employedBy::Organization hasHomePage::String hasSurname::String hasFax::String hasFirstName::String hasPhone::String hasEmail::String hasConflictOfInterest::Document email::String
Assistant:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String employedBy::Organization hasHomePage::String hasSurname::String hasFax::String hasFirstName::String hasPhone::String hasEmail::String hasConflictOfInterest::Document email::String
Volunteer:
        inverse_of_add::Thing+ execute::Thing+ get::Inforamtion use::Document register::Account modify::Thing+ take_part_in::Event remove::Thing+ add::Person send::Activity added_by::Person contributes::Conference_document has_an_email::String has_the_first_name::String has_gender::EEnum has_the_last_name::String employedBy::Organization hasHomePage::String hasSurname::String hasFax::String hasFirstName::String hasPhone::String hasEmail::String hasConflictOfInterest::Document email::String
Regular:
        earlyRegistration::Boolean
Boolean:
        "true"
        "false"
Integer:
        INT
String:
        STR
